### ISSUE TITLE
Conditional `repeat` directive not removed from DOM

### ISSUE THREAD

**Issue by simonfuhrmann** [Polymer/lit-html#1007]
# Description

When using a `repeat` directive that is based on a condition, and if that condition changes such that the `repeat` directive will not be rendered anymore, the elements previously generated by `repeat` are not removed from the DOM.

# Steps to Reproduce

Put a `repeat` directive behind a condition.

## Live Reproduction Link
https://stackblitz.com/edit/u25pbw-jjbfqw (open console)

## Expected Results
Repeat DOM disappears when condition changes to false.

## Actual Results
Repeat DOM does not disappear.

**Comment by simonfuhrmann** [comment]
In this case, the work around is satisfactory. I was just worried that `repeat` is essentially useless once you have any conditionals higher up in the hierarchy. It would be nice the mention this limitation in the documentation though.

Feel free to close.

**Comment by blikblum** [comment]
Here's an simplified example of this behavior: https://codepen.io/blikblum/pen/BbeWXO?editors=1010

This was already [raised earlier](https://github.com/Polymer/lit-html/pull/874#discussion_r269361175 ) so better documenting is in order

**Comment by rictic** [comment]
Another repro: https://stackblitz.com/edit/lit-element-mhnapw

Workaround: https://stackblitz.com/edit/lit-element-7dfwvt?file=src/index.js

**Comment by justinfagnani** [comment]
This is fixed in 2.0: https://stackblitz.com/edit/lit-element-rau3qg?file=src%2Findex.js
