### ISSUE TITLE
how to pass parameter to listener?

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-html#1008]
![image](https://user-images.githubusercontent.com/1060733/65133559-64c0f580-da35-11e9-8a15-2f1b1494f9c2.png)

> `.bind` must not be used in templates, a method should be passed directly like `${this.myMethod}` as it will be bound automatically.eslint(lit/no-template-bind)

So, what is the best practice to pass parameters to an event listener?

**Comment by Westbrook** [comment]
The most immediate version of what you're attempting is to use fat arrow syntax in this context:
```
return html`
    <button @click=${() => this.cancelClick_cb(record)}></button>
`;
```

**Comment by web-padawan** [comment]
Isn't the arrow function also an anti-pattern per `lit/no-template-arrow` ? 🤔 

@justinfagnani what approach would you recommend? Could there be a directive handling that?

**Comment by Westbrook** [comment]
It's really a matter of how strongly you hold your feelings on method based GC, and on which side of the conversation they are held, IMO. The entire React community that is based around hooks has decided that they were wrong to say that this was _ever_ a problem. It's not a requirement, however. You can do something like the following to get around it:
```
const clickHandlers = new Map();

const getClickHandler = (key) => {
    if (!clickHandlers.has(key)) {
       clickHandlers.set(key, () => cancelClick_cb(key));
    }
    return clickHandlers.get(key);
}

const renderRecord = (record) => {
    const handler = getClickHandler(record.id); // some other identifying property or using a map is also cool...
    return html`
        <button @click=${handler}></button>
    `;
}
```

**Comment by qqiao** [comment]
I thought the simplest would just be:

`
// Pseudo code
<button record='${record}' @click="clickHandler">

clickHandler(e) {
    const target = e.target;
    if ('BUTTON' != target.tagName) return;
    const record = target.record;
    // do the rest
}
`

**Comment by justinfagnani** [comment]
@Westbrook is correct here. There's really only two options: create a new listener each render, or cache the listener somehow. The `lit/no-template-arrow` rule is definitely over-aggressive for these cases.

**Comment by justinfagnani** [comment]
Closing this as answered.

Maybe a thing for docs. cc @arthurevans
