### ISSUE TITLE
Lots of <!----> comments in generated code

### ISSUE THREAD

**Issue by jkleiser** [Polymer/lit-html#1009]
When I inspect the generated code in Chrome or Safari (both macOS) I see lots of `<!---->` comments. Why is that?
I use lit-html with this simple import in a single-file toy project:
```
<script type="module">
import {html, render} from "https://unpkg.com/lit-html?module";
...
</script>
```

**Comment by abraham** [comment]
See https://github.com/Polymer/lit-element/issues/249

**Comment by justinfagnani** [comment]
This is fundamental to how lit-html works, and cannot change. It should not cause any problems.

**Comment by AndreasGalster** [comment]
@justinfagnani Can you clarify if this may change when the new templating related spec is implemented in browsers? I agree it generally causes no problems, though no idea how it may impact e2e testing in any way. 

I guess it's more an unpleasant sight than a problem.
