### ISSUE TITLE
Allow optionally setting a property

### ISSUE THREAD

**Issue by ruphin** [Polymer/lit-html#1010]
Currently it is not possible to have a property optionally set by lit-html. If you declare a property in a lit-html template, the property setter is _always_ called, no matter what value is passed:

```js
class MyElement extends HTMLElement {
  set prop(value) {
    console.log("CALLING SETTER")
  }
}

// Both these statements will call the setter
html`<my-element .prop="${ nothing }"></my-element>`
html`<my-element .prop="${ undefined }"></my-element>`
```

It may be useful to have a way to _not_ call the property setter somehow

```js
html`<my-element .prop="${ condition ? value : doNotCallSetter }"></my-element>`
```

I'm not super convinced this is necessary, as you could easily solve this by adding an `if (value !== undefined)` at the start of the property setter, but I may not have control over the internal implementation of the component I'm using, and from a templating perspective, it could be nice to have a way to simply not call the setter at all.

We could use the `noChange` sentinel for this.

**Comment by CaptainCodeman** [comment]
Related: #982

**Comment by justinfagnani** [comment]
I think respecting `noChange` here is entirely reasonable.

**Comment by justinfagnani** [comment]
In 2.0 we do respect `noChange`. We need a test though: https://github.com/Polymer/lit-html/issues/1753
