### ISSUE TITLE
Events only fired once

### ISSUE THREAD

**Issue by ashubham** [Polymer/lit-html#1011]
I am creating WebComponents in `LitElement` for use in our AngularJS app. This is how I defined a component:

```js
import {LitElement, html, query} from 'lit-element';

export class InputComponent extends LitElement {
    @query('input') input;
    protected render() {
        return html`<input @click="${this.iOnlyGetFiredOnce}"/>`;
    }

    protected firstUpdated() {
        this.input.addEventListener('click', (e) => this.onClick(e));
    }

    onClick(e) {
        console.log(e);
    }

    iOnlyGetFiredOnce(e) {
        console.log('i got fired', e);
    }
}
customElements.define('wc-input-micro', InputComponent);
```

I just simply import and use this component in our _Angular 1_ app `<wc-input-micro></wc-input-micro>`.

### Expected behaviour

Whenever I click the `input` element I should see 2 console for each handler.

### Actual behaviour

The `iOnlyGetFiredOnce` handler is only fired once and then it magically gets removed and never gets fired on subsequent clicks. The other `onClick` handler continues to fire on each click.

### Debug steps taken

- Monkey patched `Element.prototype.removeEventListener` to check if something is calling that, but *NONE*.
- Tried `stopPropagation/preventDefault` on the `@click` handler.
- I see in dev-tools that the handler gets removed from element in the `Event Listeners` panel.

- lit-element: v2.2.1
- Browser: Chrome/Firefox

**Comment by justinfagnani** [comment]
SugarJS should not be adding properties to the Function prototype, that's incredibly and inherently dangerous, as this issue demonstrates.

I'm sorry this is causing trouble, but we can't change the behavior of event options now.
