### ISSUE TITLE
How to remove Any rendered templates? , removeAllNodes has a bug with sibling error

### ISSUE THREAD

**Issue by NickolasBenakis** [Polymer/lit-html#1014]
![image](https://user-images.githubusercontent.com/32495928/66478371-e7702a00-eaa2-11e9-9305-24ebc9cc7e88.png)

I am trying to delete some rendered nodes but I'm struggling with this error, Is there a valid way to remove rendered templates by Lit-html?? without hacking in to the DOM directly . Thank you a lot

**Comment by neuronetio** [comment]
just return `undefined` from your function instead of template result and render again
