### ISSUE TITLE
Using lit-html 1.1.2 with polymer bundler breaks page (1.1.1 works)

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/lit-html#1015]
# Description
I bundle our page with following command:

call node --max-old-space-size=6144 node_modules\polymer-cli\bin\polymer build --verbose --root ../../bin/Debug/HTML --entrypoint index.html

and following config:

	{
	  "sources": [
	   "dist/**",
	   "assets/resources/**",
	   "assets/images/**"
	  ],
	  "extraDependencies": [],
	  "builds": [
		{
		  "name": "HTML",
		  "browserCapabilities": ["es2015", "push", "serviceworker", "modules"],
		  "html": { "minify": true},
		  "css": { "minify": true},
		  "js": { "minify": true, "compile": false},
		  "bundle": {             
			"exclude": ["../libs/stimulsoft/" ], 
			"inlineCss": false,          
			"inlineScripts": true,       
			"rewriteUrlsInTemplates": false, 
			"sourcemaps": false,          
			"stripComments": true   
		  },
		  "addServiceWorker": false,
		  "addPushManifest": false
		}
	  ],
	  "moduleResolution": "node",
	  "npm": true,
	  "lint": {
		"rules": [
		  "polymer-3"
		]
	  }
	}

and I got the error that parameters wich I hand over from a lit-elemnt to a polymer component via a directive:

     <filter-data-grid id="datagrid" service="${ifDefined(this.service)}" service-name="${ifDefined(this.serviceName)}"

filter-data-grid is a polymer 3 component used inside a lit-element.

in my polymer component the "service" property has now the value :
(looks like as a part of the directive function)

    part=>{if(value===undefined&&part instanceof AttributePart$1){if(value!==part.value){const name=part.committer.name;part.committer.element.removeAttribute(name);}}else{part.setValue(value);}

If I switch back to lit-html 1.1.1 the minification works as excpected.

## Browsers Affected

- [x ] Chrome
- [x] Firefox

**Comment by justinfagnani** [comment]
I suspect this isn't the bundler, but that you now have multiple copies of lit-html interacting, with one doing the rendering and the other providing `ifDefined`.

Try `npm ls | grep lit-html` to see if there are multiple copies of lit-html, and `npm dedupe` to see if you can get down to one. If that doesn't work try updating dependencies that use lit-html. I also recommend using the lowest lower-bound for lit-html that you can to increase the chance of there being a single compatible version across your app.

**Comment by CaptainCodeman** [comment]
If you use rollup directly, instead of via the polymer CLI, you can use the deduping capabilities it provides (in the `@rollup/plugin-node-resolve` plugin):

```js
    resolve({
      dedupe: [
        'lit-element',
        'lit-html',
        // any lit-html directives etc...
      ]
    })
```

**Comment by jogibear9988** [comment]
I don't know how we fixed the error, need to look. (So long ago)
But I don't think we had multiple copies of LIT.
We use "yarn" with flat option, I thought this should prevent multiple copies or am I wrong?

**Comment by justinfagnani** [comment]
`yarn --flat` should prevent this, so I'm not sure what's up. Closing since it sounds fixed on your end.
