### ISSUE TITLE
How to create attributes on element from an array using map()?

### ISSUE THREAD

**Issue by benfrain** [Polymer/lit-html#1025]
# Description
I'm unable to create attributes dynamically on an element using a map().

I'm unsure if I'm fundamentally approaching this problem the wrong way with lit-html?

# Steps to Reproduce

1. Write this code

```ts
import {html, render} from 'lit-html';
let data = ["sausages","vegetables"]
render(html`<div ${data.map(item => html`data-attr="${item}"`)}>blah blah</div>`, document.body);
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-s7ajmj

## Expected Results

I would expect to see this rendered: `<div data-attr="sausages" data-attr="vegetables">blah blah</div>`
## Actual Results
In stackblitz this is rendered `<div {{lit-9771246086786735}}="">blah blah</div>`. In my own environment it breaks with this: "TypeError: Cannot read property '2' of null"

**Comment by web-padawan** [comment]
This is not currently supported. See also #923 for a similar request (using spread, not `map`).

**Comment by benfrain** [comment]
OK, thanks for clarification.

**Comment by motss** [comment]
Does setting as property instead of as attribute help here?

```ts
import {html, render} from 'lit-html';
let data = ["sausages","vegetables"]
render(html`<div .data=${data}>blah blah</div>`, document.body);
```

**Comment by frank-dspeed** [comment]
it can be supported easy via a additional renderer i am author of tag-html a lit-html replacement and can tell you if you do 

```js
import {html, render} from 'lit-html';
let data = ["sausages","vegetables"]
document.body.innerHTML = `<div ${data.map(item => `data-attr="${item}")`).join(' ')}>`
```
works like a charm thats why i use always string representation for my apps and then add interactivity via customElements no directives no magic just works

**Comment by justinfagnani** [comment]
Let's consolidate discussion in #923
