### ISSUE TITLE
Event listeners don't work when inside <template>?

### ISSUE THREAD

**Issue by newk5** [Polymer/lit-html#1030]
# Description
When rendering a template inside a < template> tag with lit-html, the event listeners are not fired and I can see in the HTML code that the onClick event is not rendered inside the < button> tag.
# Steps to Reproduce
Use this code
```ts
import { html, render } from 'lit-html';

let template =  document.createElement("template");

const clickHandler = {
    handleEvent(e) { 
      console.log('clicked!');
    },
    capture: true,
};
const myTemplate = () => html`<button @click=${clickHandler} >Click</button>`;
render(myTemplate(),  template.content);
document.querySelector("#container").appendChild(template.content.cloneNode(true)); 
```

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-nzksz7

## Expected Results
Click listener should be fired

## Actual Results
Click listener is not fired

## Browsers Affected
I only tested on chrome and firefox

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by jridgewell** [comment]
You’re cloning the template’s `content`, and we use `addEventListener` to add events which are not copied.

**Comment by newk5** [comment]
> You’re cloning the template’s `content`, and we use `addEventListener` to add events which are not copied.

I see. Is this a known/intended limitation or a bug to be fixed?

Is there any workaround I can do for the time being?

**Comment by jridgewell** [comment]
You can try rendering to a `DocumentFragment` instead, and inserting that? But why aren't you just rendering into the `#container` element to begin with?

**Comment by newk5** [comment]
Oh I was just hoping to take advantage of `<template>` features like the "lazy-loading" manner of how its contents are rendered and how everything inside it is "inert" until "activated". I've recently learned about it and thought it might be an interesting optimization. 

I don't really have much experience in this area since I'm mostly a backed developer. Do you recommend me to just ditch the `< template> `in most cases? Is it not considered a good practice? Or just for very specific scenarios?

**Comment by jridgewell** [comment]
Yes. lit-html already uses a template internally, there's no need for you to maintain one, too.

Note that rendering it into a `DocumentFragment` means you won't be able to update the DOM after you append the fragment. Just render it into a regular `<div>`, and let the library do the optimizations for you.

**Comment by newk5** [comment]
I understand, thanks will do.
