### ISSUE TITLE
[docs] typo in Creating Directives

### ISSUE THREAD

**Issue by innerop** [Polymer/lit-html#1037]
# Description

The [docs](https://lit-html.polymer-project.org/guide/creating-directives) for creating directives has a typo in it that took me an hour to recover from:

# Steps to Reproduce

Maintaining state between renders

```ts
import {directive} from 'lit-html';

// Define the map at module level
const stateMap = new WeakMap();

const statefulDirective = directive(() => {(part) => {
  let myState = stateMap.get(part);
  if (myState === undefined) {
    // Initialize state for this location
    myState = {};
    stateMap.set(part, myState);
  }
  // ... use the state somehow
});
```

The type is here " {(part)" The curly braces prevents returning the inner function (when balanced, where it's actually unbalanced, but some would assume a missing closing curly braces rather this being a typo, which leads to an error saying that the key for the WeakMap used by directives is invalid (because it would be undefined in this case)

One typo: 1 hour of debugging, for someone just getting started with lit.

**Comment by arthurevans** [comment]
Ugh. So sorry. Thanks for letting us know, I'll get that fixed.
