### ISSUE TITLE
Incorrect rendering of text values in-between slots on the web component polyfill

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#1046]
I'm running into quite a strange bug. I have a web component which, after minification, has two slots and a text binding in-between. On modern browsers this works fine, but on browsers which need the web component polyfill the first rendered value is never removed.

It's best observed in this jsbin: https://jsbin.com/caradirigo/2/edit?html,output there are two renders 'foo', and 'bar'. 'foo' should be removed when 'bar' is rendered.

I forced the polyfills, so it's observable on chrome as well.

When there is a whitespace character, it does work correctly: https://jsbin.com/govovaqicu/1/edit?html,output

**Comment by frank-dspeed** [comment]
To avoid a unneeded whitespace you can do 
```
<slot name="before"></slot>${this.title}<!-- --><slot name="after"></slot>
```

i added a comment node

**Comment by LarsDenBakker** [comment]
Absolutely, there are many ways to work around it. This is still a bug, though.

**Comment by justinfagnani** [comment]
This is likely because the polyfill is removing `<slot>` elements.

@sorvell and @dfreedm is there any way to leave the elements in, or replace them with a comment?

**Comment by frank-dspeed** [comment]
if is pollyfill wrap slot on parsing with makeComment ?

**Comment by justinfagnani** [comment]
This is being fixed in Shady DOM, but I think we should have a test here that it actually fixes this problem. cc @sorvell

**Comment by sorvell** [comment]
Closing based on #1077
