### ISSUE TITLE
<video .srcObject> not working

### ISSUE THREAD

**Issue by mantou132** [Polymer/lit-html#1048]
# Description
`<video .srcObject={stream}>`. 
The variable `stream` is never changed, and video does not play properly when repeating render

# Steps to Reproduce

1. open https://codesandbox.io/s/lit-html-props-test-1pite
2. allow permission request
3. click <video> play button

## Expected Results
can't play

## Actual Results
play

## Browsers Affected
- [x] Chrome 80
- [x] Firefox 73

**Comment by mantou132** [comment]
I think that native properties with side effects will have the same problem. Should lit-html implement these side effects correctly or mark them with a document for the user's attention?

**Comment by justinfagnani** [comment]
This is very odd. I'm surprised that `<video>` does anything if you set `srcObject` to the same object again.

I don't think there's much for lit-html to do here. You can already prevent re-rendering a template with the guard() directive, so you can do this:

import { render, html } from "lit-html";
import { guard } from "lit-html/directives/guard.js";

async function init() {
  const stream = await navigator.mediaDevices.getUserMedia({
    video: {
      facingMode: "user"
    }
  });
  const tick = () => {
    render(
      guard(stream, () => html`
        <video controls .srcObject=${stream}></video>
      `),
      document.getElementById("app")
    );
    window.requestAnimationFrame(tick);
  };

  window.requestAnimationFrame(tick);
}

init().catch(console.error);
```

I guess one thing that would be nice is for guard to work directly in property bindings so that you could have other values that change over time.

**Comment by justinfagnani** [comment]
Oops, `guard()` does work with properties:

```js
html`<video controls .srcObject=${guard(stream, () => stream)}></video>`
```

**Comment by mantou132** [comment]
thx.
lit-html is just setting properties.
it's up to developer to avoid this.

`HTMLMediaElement.prototype.srcObject` is setter, it looks like the video status is updated every time it is set

**Comment by justinfagnani** [comment]
Thanks for pointing this out. It's helpful to know about.
