### ISSUE TITLE
Long Build Time for Docs

### ISSUE THREAD

**Issue by AnthumChris** [Polymer/lit-html#1049]
# Description
I'm at the airport and cloned the repo so I could read the docs offline on the plane.  Installing, downloading, and compiling Ruby and the required Jekyll deps took a long time (> 5mins).  What do you think of converting the docs from Jekyll (Ruby) to 11ty (JavaScript) to keep the docs within the JS stack?  Happy to take this on if everyone would find it beneficial to remove the Ruby dependency and migrate to JavaScript/npm.

# Steps to Reproduce

```bash
$ time gem install bundler jekyll
```

**Comment by thepassle** [comment]
Another option would be to add a service worker

**Comment by AnthumChris** [comment]
Great idea.  A one-file solution is always nice.

**Comment by justinfagnani** [comment]
> What do you think of converting the docs from Jekyll (Ruby) to 11ty (JavaScript)

I would _love_ to do this. I've been using 11ty a lot recently and really like it. Not sure where this falls on our team priority list though. Contributions would be _very_ welcome!

cc @arthurevans

**Comment by hyperpress** [comment]
I'm totally onboard with using 11ty for docs. 👍

**Comment by justinfagnani** [comment]
This should be addressed by #1076

**Comment by justinfagnani** [comment]
Fixed by #1076

**Comment by AnthumChris** [comment]
Thanks so much for taking the time to look into this and resolving.  Apologies for the late reply and my unavailability to contribute.
