### ISSUE TITLE
Proposal: allow server side rendered templates

### ISSUE THREAD

**Issue by frank-dspeed** [Polymer/lit-html#1053]
To allow server side rendered templates we need to be able to create a template result from existing template tags.

**Comment by frank-dspeed** [comment]
Conclusion is that i will go with my own templating engine based on tagged template strings and maybe use lit-html if i want to use the live bindings it produces with customElements only if needed. 

Why i come to that conclusion?
- would need isomorphic directives while there is no need for directives at all in a string only case.
- Its much more clean and performant to render only strings and apply hooks via customElements that get registered for the rendered string template.

**Comment by justinfagnani** [comment]
Duplicate of #187
