### ISSUE TITLE
Handle npm formart in the merge pipeline not on developer side

### ISSUE THREAD

**Issue by frank-dspeed** [Polymer/lit-html#1065]
# Description
When some one wants to submit small changes its to much overhead to run npm install and npm formart the project should change its pipeline to apply formart changes on merge if needed not in the inital pull request.

# Steps to Reproduce

1. Edit a ts file Write this code

```ts
longCondition ? notSolong : thisWillbeLonger ? yesITisLongerThenTheAllowedLineLengthYaa : FinalyAFormartErrorYaaa : WeDidItaFormartErrorInOneLineOfCode;
```

2. See this output...
jenkins will fail with a formart suggestion if you submit a pr with that code while the code is maybe 100% valid legit and well tought and formed.

## Expected Results
All Tests do finish and can be merged into a extra branch to apply codestyles or additional stuff that the developer don't needs to be aware of.

## Actual Results
Jenkins will error with formart suggestions

## Browsers Affected

- [x ] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
We have the formatter plugged into git commits via Husky now. That should be enough to lower the friction. I don't think it's too much to ask for an `npm i` before contributing. You need that to get TypeScript anyway.

**Comment by frank-dspeed** [comment]
@justinfagnani in my case i have my own framework and also a extra fork of lit-html it self that is highly modifyed and is written in ESNext i don't use typescript for anything else then typechecking JSDOCs comments :D

**Comment by frank-dspeed** [comment]
i do typechecking on the run via asserts that the only runtime typechecking that exist typescript has no advantage :)

**Comment by justinfagnani** [comment]
That's fine, and I'm well aware that TypeScript doesn't do runtime type checks, but we expect contributors to this project to be able to run TypeScript and the formatter. That hasn't been too high of a barrier for contributors so far.

While we want to make contributing easy, I don't think we should spend too much time optimizing for the case where people don't want to run our tooling.

**Comment by frank-dspeed** [comment]
@justinfagnani ok if you think so its your project i would accept any value able contribution and would not make it depending on your choice of tooling. There are Tons of Online editors and dev environments that don't run the typescript version of lit-html and still they find bugs they even workaround them and could contribute if they don't would need to clone the whole project run install and all that they could use the github code editor to contribute.

they themself got the compiled version + source maps to find the right place in this ts code base.

**Comment by justinfagnani** [comment]
Discussed, and we're comfortable with the current setup. Thanks for the feedback.
