### ISSUE TITLE
Directives that operate on nodes

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#1069]
I often I run into use cases where I want to run a piece of code on a node, and express this declaratively in a lit-html template. For example to maintain an expanded/collapsed state of an element, it would be great to be able to do something like this:

```js
html`
  <my-element ${expandCollapse(expanded)}>

  </my-element>
`
```

This isn't possible, directives that operate on an element must be applied to an attribute even when it doesn't do anything with the attribute name. 

So we either need to make up a fake attribute:

```js
html`
  <my-element ~=${expandCollapse(expanded)}>

  </my-element>
`
```

Or make it a directive that must be used in a `NodePart` and query the first rendered element:

```js
html`
${expandCollapse(expanded, () => html`
  <my-element></my-element>
`)}
```

I'm wondering if it's possible to support directives that operate on a node like in the first example, without being associated with any attribute. 

I've seen something similar being proposed before, but then to be able to add arbitrary attributes/properties on a tag. This understandably isn't within the design goal of lit-html, but allowing this for directives will not cause any changes to the output HTML so it seems like something that should be feasible.

**Comment by justinfagnani** [comment]
I've been meaning to try out a few more ideas here. I think that the regex that detect the lexical position of bindings might be powerful enough to let us insert a special marker for these. It would indeed be really nice to allow.

**Comment by LarsDenBakker** [comment]
Great to hear it might be possible to add

**Comment by justinfagnani** [comment]
Please note this is mostly a hunch though. This code is in the critical path for first render of all templates, so it could even be possible but not desirable in the end...

**Comment by justinfagnani** [comment]
I have something almost working, but it fails one of the existing attribute binding tests and it does a bit more string scanning than I'd like. I'm thinking that it may be better to write a more explicit scanner here - this is like half a lexer - that would let use more accurately know the current lexical position of the expression. We should be able to definitely tell when we're in text, attribute, start tag and tag name position. The question is how much code it'll be. It should be a relative small state machine with some regexes to match the relevant character classes.

**Comment by LarsDenBakker** [comment]
For a feature like this a small code size increase could be ok.

**Comment by justinfagnani** [comment]
We have this in lit-html 2.0!
