### ISSUE TITLE
Allow setting template factory in shady renderer via options/make shady template factory public

### ISSUE THREAD

**Issue by mzeiher** [Polymer/lit-html#1082]
Hi,
we use some helpers for lit-html to be able to use scoped custom element registries, which are scoped to the render root (lit-htmls' render function). To do this we use or own template factory which creates scoped template instances. This works fine for the regular render function but to support older browsers we had to copy/reimplement most of the code of the shady renderer because it's not possible to inject a custom template factory into this renderer. Could it be possible to support setting custom template factories for the shady renderer without monkey patching/re-implementing the renderer?

**Comment by Westbrook** [comment]
Is this a limitation shared by the similar sounding project available at https://open-wc.org/scoped-elements/?

**Comment by LarsDenBakker** [comment]
Yes it is, we have a workaround but something proper would be great.

**Comment by mzeiher** [comment]
@LarsDenBakker your demo in the wc repo was also one of the reasons to create this feature request :) related to this issue is also defining `Template` as an interface instead of class.

**Comment by sorvell** [comment]
The `shady-render` implementation itself uses a custom template factory so it's not immediately obvious how to pass in a custom template factory here, but we'll take a look at doing some refactoring with this use case in mind.

**Comment by justinfagnani** [comment]
We've removed custom template factories in 2.0, but also added a ScopedRegistryHost mixin for LitElement. Hopefully this issue is covered now.
