### ISSUE TITLE
getting started with node

### ISSUE THREAD

**Issue by Conando025** [Polymer/lit-html#1095]
So **I know there is a getting started**, but I still need help.
I am new to node.js and wanted to use _lit-html_, so I used npm to install it in my project. But I don't get it to work, do I need a require? Ultimately I want to use _lit-html_ client-side, but how do I get there. When I writing html\`\<p>${foo}\</p>\` it throws the error html is not defined.

For the rest of the project all I'm doing is using _express_ to use a website which is just some basic html.

Server-side:
`const express = require('express');
const app = express();
app.listen(3000, () => console.log('listeing at 3000'));
app.use(express.static('public'));
`

**Comment by web-padawan** [comment]
Check out lit-html & lit-element basics here: https://open-wc.org/codelabs/basics/lit-html.html 

Regarding the development server, it is recommended to use `es-dev-server` which supports ES modules, and loads the polyfills / transpiles with Babel for older browsers if needed: 
https://open-wc.org/developing/es-dev-server.html

**Comment by Conando025** [comment]
Ok so right now I'm using `import {html, render} from 'https://unpkg.com/lit-html?module';` but surely there must be a better way with in a project.

**Comment by justinfagnani** [comment]
Does this section of the docs help? https://lit-html.polymer-project.org/guide/tools#dev-server

You need a static file server that resolves JS module specifiers. You can choose any one, `polymer-cli` and `es-dev-server` being the simplest to use, IMO.

cc @arthurevans

**Comment by CaptainCodeman** [comment]
You can also look at using a tool such as rollup which will transform your source code into more optimized code that will run in the browser. 

I prefer it as an approach because it's closer to what you'd actually deploy for a live site, esp. if you want it to be fast - you might just skip some steps while developing (such as minification).

**Comment by web-padawan** [comment]
BTW you can also use `express-transform-bare-module-specifiers`, that would allow to use

```js
import {html, render} from 'lit-html';
```

At the same time, you would have to configure Babel or polyfills for older browsers yourself.
