### ISSUE TITLE
Bundled size regression

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1096]
The bundled/minified/gzipped size as reported by the `checksize` script has increased since 1.1.2. I ran `checksize` against every commit since 1.1.2 with the following command (saved for posterity):

```
git rebase -ix 'git rev-parse HEAD && git log --oneline -1 | cat && npm ci && npm run build && npm run checksize && git reset --hard HEAD && git clean -f' v1.1.2
```

Cleaning up the output and computing deltas reveals the worst offending commits:

<img width="1402" alt="Screen Shot 2020-02-25 at 9 36 36 AM" src="https://user-images.githubusercontent.com/522948/75272266-68119780-57b2-11ea-8614-4bcac6ed6702.png">

The big increases are caused by three things:

1. The sanitization and trusted types work
2. A change in how Terser treats comments
3. Namespaced attribute support

(2) only affects how we track sizes internally for our own uses. We don't publish a bundled version, nor any reusable configs for bundling. It made it hard to compare historically, so we've addressed in #1094 by configuring Terser to remove all comments like it had been doing earlier.

(1) and (3) are cases where we need to balance utility and cost.

(1) is work that is used internally at Google, but has no external users yet as it's unreleased. We'd like to offer an even more secure version of lit-html, but we don't want to make all users pay for the added hooks. The Trusted Types support is likely to be the most used, but Trusted Types is not released in any stable browser yet.

(3) is useful for SVG templates that need to use `<use xlink:href="...">`, but on the other hand Safari now supports the non-namespaced version: `<use href="...">`. Given that current lit-html users have managed so far without namespaced attribute support, and the landscape seems to not require them any more for even the most common use, we should fine without it.

The plan is to revert the commits related to (1) and (3). We don't plan on re-adding namespaced attributes. Maybe there's a directive-based approach that will work without increased size. For (1) we are going to revert the commits, but then revert the revert in a branch. We might publish another package with the sanitization hooks that can be globally replaced in a build for those who want the extra security checks.

cc @rictic @kevinpschaaf @jridgewell

**Comment by hyperpress** [comment]
Thank you Justin. I think this is the plan. I think a company like mine would pay the price for additional security, but I like the idea of adding a branch for that version striking balance between what's currently available outside Google but being able to keep abreast of those features when they achieve release.

I think namespace attr would be better as a directive or maybe a helper plugin. I actually like the pwa-helper method of providing companion features kept separate for use just by those that need them keeping core lean. I know their are debt tradeoffs to that as well.

**Comment by justinfagnani** [comment]
Fixed by #1098 and #1097

**Comment by abdonrd** [comment]
@justinfagnani Why not add a GitHub Action to check size in each PR?

**Comment by CaptainCodeman** [comment]
This works well:
https://github.com/marketplace/actions/compressed-size-action

**Comment by justinfagnani** [comment]
We have a GitHub action that runs our benchmark and reports the size of the bundled benchmark app. We need to update this to report the result of our checksize script, and I'd like it to comment directly on the PR. One thing that happened here was a gradual increase due to features being spread out over many PRs, and a big increase in the reported number due to updating dependencies having an unexpected effect.
