### ISSUE TITLE
asyncAppend: Uncaught (in promise) TypeError: o[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by RickStanley** [Polymer/lit-html#1107]
# Description
Doesn't render asynchronous data into the template, using `asyncAppend`.

# Steps to Reproduce

1. Write this code

```ts
import {asyncAppend} from 'lit-html/directives/async-append.js';

// Endpoint that returns a billion digits of PI, streamed.
const url =
    'https://cors-anywhere.herokuapp.com/http://stuff.mit.edu/afs/sipb/contrib/pi/pi-billion.txt';

const streamingResponse = (async () => {
  const response = await fetch(url);
  return response.body.getReader();
})();
render(html`π is: ${asyncAppend(streamingResponse)}`, document.body);
```

2. See this output
```
Uncaught (in promise) TypeError: o[Symbol.iterator] is not a function
    at __asyncValues (async-append.ts:1)
    at async-append.ts:52
    at NodePart.commit (parts.ts:207)
    at TemplateInstance.update (template-instance.ts:53)
    at NodePart.__commitTemplateResult (parts.ts:277)
    at NodePart.commit (parts.ts:218)
    at Object.render (render.ts:55)
    at main.ts:82
    at fertig (commons.ts:26)
```

## Expected Results
Append digits of PI.

## Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [X] Edge Chromium
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

Using:

    "lit-html": "^1.1.2",
    "typescript": "^3.8.3"

tsconfig.json
```
{
    "compilerOptions": {
        "lib": ["es2017", "dom"]
    }
}
```

![image](https://user-images.githubusercontent.com/23178554/75597366-763e0d00-5a6b-11ea-813c-f2b3f46f343d.png)

**Comment by justinfagnani** [comment]
I don't think readable streams yet implement the async iteration protocol. To see how to use fetch with async iteration see the last example on this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of
