### ISSUE TITLE
What's the idiomatic way of focusing an input after render?

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [Polymer/lit-html#1114]
Not sure if there's an obvious way to do this, or it's outside the scope of lit-html.

**Comment by CaptainCodeman** [comment]
set the `autofocus` attribute and / or use the `.focus()` method on the element after first render

**Comment by motss** [comment]
@LewisAndrewCampbell When you say `after render` do you mean after first render or every render? IMHO, you can achieve that when the component finishes its render, at least that's when the component that needs to be focused should be rendered in the DOM:

```ts
class CustomElem {
  ...
  get  focusable() {
    this.shadowRoot.querySelector('.focusable');
  }

  firstUpdated() {
    this.focusable.focus();
  }

  // updated() {
  //   this.focusable.focus();
  // }
}
```

**Comment by justinfagnani** [comment]
In lit-html (not LitElement) the pattern would be to query and focus like @captaincodeman said (or use autofocus).

```js
render(template(), container);
const input = container.querySelector('input');
input.focus();
```
