### ISSUE TITLE
No style block in shadow root for StencilJS components

### ISSUE THREAD

**Issue by whoisryosuke** [Polymer/lit-html#1119]
# Description
StencilJS web components render properly, complete with styles -- but the styles are non-existent in the DOM (shadow or light/regular). If you inspect the component, you can see styles applied, but you can't go to where it's defined (unlike other styles, which will point you to `<style>` blocks or CSS files).

> Edit: After testing in React, I have the same issue. I'm assuming this means it's an issue with either StencilJS or my own code. [I created an issue in the StencilJS repo.](https://github.com/ionic-team/stencil/issues/2281) I'm leaving this here so someone else can verify if that's the case before I close (just in case someone else has had this issue in another similar form).

# Steps to Reproduce

1. Setup new vanilla JS project (index.html and index.js files)
2. Add my StencilJS web components to the index.html in a script tag:

```html
<script src="https://unpkg.com/sui-web-components@0.0.1/dist/sui-web-components.js"></script>
```

3. Add this to index.js

```ts
import { html, render } from "lit-html";

const myTemplate = name =>
  html`
    <sui-base>
      <sui-box display="flex">
        <sui-text as="h2" width="50%">Side by side</sui-text>
        <sui-text as="h2" width="50%">Side by side</sui-text>
      </sui-box>
    </sui-base>
  `;

render(myTemplate("World"), document.body);
```

4. See components side by side (complete with font styling). But if you inspect, no style block inside any of the web component's shadow root.

## Live Reproduction Link
https://codesandbox.io/s/jovial-mccarthy-qtckg

## Expected Results
Should see a `<style>` block inside the web component's shadow root that contains the components styles. 

- [Here you can see the style block (when I don't use lit-html to render the components)](https://i.imgur.com/1nq3kt6.png)
- [Here you can see the lack of a style block (when I use lit-html)](https://i.imgur.com/hw2ohLo.png)

lit-html seems capable of making `<style>` blocks. [If you run a test](https://codepen.io/justinfagnani/pen/mBQpqJ) where you place the style directly in lit's `html()`, you can see the `<style>` block in the shadow root. But for some reason the way StencilJS handles styles, it doesn't get picked up by lit to render in the DOM (but still gets applied?).

## Actual Results
Styles applied, but the CSS/styles is nowhere to be found in the DOM.

## Browsers Affected
- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by justinfagnani** [comment]
It seems like this isn't a lit-html issue. Stencil components are in control of their own shadow root.
