### ISSUE TITLE
Implement attribute/property/event part SSR & hydration

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-html#1123]
## Description
Currently only `NodePart`s are serialized/hydrated. This task is to add a serialization scheme for attribute, property, and event parts and the respective client-side hydration.

## Acceptance Criteria
* Tests demonstrating client-side hydration of serialized templates that include attributes, properties, and events are checked in and passing.

**Comment by justinfagnani** [comment]
Closing in favor of smaller issues in lit-ssr
