### ISSUE TITLE
Serialize built-in reflecting properties

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-html#1124]
## Description
`lit-ssr` needs to include a whitelist of built-in reflecting properties on built-in nodes (including those on `HTMLElement`) and automatically serialize property bindings to those properties to their corresponding attributes.

## Acceptance Criteria
* Tests that demonstrate correct serialization of built-in properties to attributes are checked in and passing.

**Comment by justinfagnani** [comment]
This is fixed now.
