### ISSUE TITLE
Export the shadyTemplateFactory function

### ISSUE THREAD

**Issue by manolakis** [Polymer/lit-html#1134]
## Initiative / goal
One to two sentences that describe:
-Who wants the functionality

Open-wc for scoped elements (https://github.com/open-wc/open-wc/pull/1464).

-What it is they want

We need the [`shadyTemplateFactory`](https://github.com/Polymer/lit-html/blob/master/src/lib/shady-render.ts#L58) exported to call it after preprocessing the `TemplateResult` scoping the elements.

-Why they want it

We don't want to loose the shady render functionality because the use of scoped elements and right now we have to copy the shadyTemplateFactory which is not ideal.

### Scope
Description of task/subtask

Just export the `shadyTemplateFactory`.

## Acceptance criteria and must have scope

`shadyTemplateFactory` should be available outside the `shady-render.ts` file.

**Comment by justinfagnani** [comment]
Ok, we can do this.
