### ISSUE TITLE
Broken link to "Part" interface on the guide page "Creating directives"

### ISSUE THREAD

**Issue by xPapay** [Polymer/lit-html#1137]
# Description
The page is not found when user clicks `Part` on the "Creating directives" page because the link has an incorrect path.

# Steps to Reproduce

1. Go to this page [Creating directives](https://lit-html.polymer-project.org/guide/creating-directives) and click `Part` interface link.

## Expected Results
The user should be directed to: https://lit-html.polymer-project.org/api/interfaces/lit_html.part.html

## Actual Results
But instead user is directed to: https://lit-html.polymer-project.org/api/classes/lit_html.part.html which yields 404.

**Comment by csvn** [comment]
I recently came across https://www.npmjs.com/package/hyperlink. It might be helpful to have as a Github Action/CI check to verify that there are no broken links.
