### ISSUE TITLE
Question: How does lit-html update different static parts without diff algo?

### ISSUE THREAD

**Issue by timonson** [Polymer/lit-html#1140]
I read through your amazing [wiki](https://github.com/Polymer/lit-html/wiki/How-it-Works) and I believe I understand how `lit-html` updates the dynamic parts so blazing fast now.
With the help of `tagged templates` lit-html takes the template, replaces all the expressions with generic placeholders, `Parts`, and makes a `<template>` element out of the result.
But unfortunately I am still wondering about one question: What does the process look like to figure out if the static parts are equal? I would appreciate even a short hint very much. Thank you!

Edit: Is the answer a hash table?

**Comment by hsablonniere** [comment]
I may be wrong but I think you're looking for this: https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L113

A part has a value, if you set a new value, there is a strict comparison.

**Comment by justinfagnani** [comment]
> What does the process look like to figure out if the static parts are equal?

That's just part of tagged template literals: the static strings array is equal across evaluations of the  template. You can check this yourself in a few lines:

```js
const tag = (strings, ...values) => strings;
const f = (x) = tag`hello ${x}`;
console.log(f(1) === f(2)); // prints true
```

**Comment by timonson** [comment]
@justinfagnani Thank you, this helped a lot!

**Comment by kevinpschaaf** [comment]
When replacing one template with a totally different template, lit-html will replace the DOM of the old template with a clone of a new template.  So the simple model is, if the TemplateResult came from the same `html` call site, then the static DOM remains unchanged and only the dynamic parts are updated; if the TemplateResult came from a different `html` call site, then the previous DOM is removed and new DOM is created.

Specialized directives like `repeat` actually perform key-based diffing to make the minimum updates to previously stamped DOM.   This split allows for an efficient application of diffing when it's likely to be beneficial (changing regularized data, i.e. `repeat`) and not where it is unlikely to help (swapping e.g. page 1 with page 2, i.e. a ternary on different templates).  Hope that helps.
