### ISSUE TITLE
Extend the repeat directive functionality so I can prevent unecessary triggering of connectedCallback and disconnectedCallback in my web components .

### ISSUE THREAD

**Issue by Spanoudakhs** [Polymer/lit-html#1142]
## Description
Repeat directive is triggering `connectedCallback` and `disconnectedCallback` of my web components . Here is an example that you can run and check the console :
```
window.customElements.define("c-e", class extends HTMLElement {
	connectedCallback() {
		console.log(`connectedCallback id=${this.id}`);
	}
	disconnectedCallback() {
		console.log(`disconnectedCallback id=${this.id}`);
	}
});

const renderComponents = (arr) => render(html`${repeat(arr,id => id,id => html`<c-e id=${id}></c-e>`)}`, document.body);
renderComponents([1,2]);
renderComponents([2,1]);
```
- Who wants the functionality
Me .
- What it is they want
I want the repeat directive to accept extra optional callbacks that run exactly before and after the reordering of a single element .
- Why they want it
Like that I can provide to the repeat directive functions that will prevent the unecessary triggering of the `connectedCallback` and `disconnectedCallback` of the web components I choose .

**Comment by kevinpschaaf** [comment]
It's possible to wrap `render` to add a callback that brackets the commit, but before we go there, could you explain a little more about your use case?

Depending on when you need to run your connected/disconnected callbacks and when you can skip them (e.g., if you're being reconnected into the same parent element, for example), you may be able to write more general code in your callbacks to catch the situation that happens in repeat in a more general way that doesn't require repeat-specific logic.

**Comment by Spanoudakhs** [comment]
@kevinpschaaf I am trying to create a "glue" between lit-html and mobx using web components. So far everything works fine . Even the problem I am mentioning here is solved by changing the repeat directive source code to do the things I have mentioned . The change is not something difficult to implement but then again I am not really experienced to understand if the problem should be solved the way I suggest .

The main is this : my `disconnectedCallback` can not understand if it is triggered because of deletion or because of changing DOM order among sibling elements . The only way I have found to bypass this issue is the extra callbacks that the repeat directive is receiving :

```
import { autorun, observable } from "mobx";
import { render, html } from "lit-html";
import { repeat } from "lit-html/directives/repeat";

let triggerConnectionCallbacks = true;
window.customElements.define("c-e", class extends HTMLElement {
	connectedCallback() {
		//triggerConnectionCallbacks value is changed from the two extra callbacks of the repeat directive
		if (!triggerConnectionCallbacks) return;
		console.log("connectedCallback");
		/*rest of code*/
		//autorun
	}

	disconnectedCallback() {
		if (!triggerConnectionCallbacks) return;
		console.log("disconnectedCallback");
		/*rest of code*/
		//dispose autorun
	}
});

//observable of mobx
let state = observable({
	arr: [1, 2]//then it changes to [3,2,1], notice that it needs not only reordering but also creation of new element
});

//the autorun of mobx
//in this case whenever I change the value of state.arr , the autorun runs the render
autorun(() => {
	render(html`${repeat(state.arr, id => id, id => html`
		<c-e id="${id}"><!--lot of stuff--></c-e>
	`,
	//the extra repeat directive callbacks
	() => triggerConnectionCallbacks = false ,
	() => triggerConnectionCallbacks = true)}`, document.body);
});

window.state = state;//change arr to [3,2,1]
```

**Comment by justinfagnani** [comment]
> The main problem is this : my disconnectedCallback can not understand if it is triggered because of deletion or because of changing DOM order among sibling elements

It's not really possible to detect this in general. Even if you patch this specifically for `repeat()` there are other ways of moving elements that will cause a disconnect+connect.

Are you sure that disconnecting and reconnecting from MobX is a performance issue? You might be interested in this project that adds MobX integration to LitElement, which doesn't do any special around clean up: https://github.com/adobe/lit-mobx/blob/master/src/lib/mixin.ts

If disconnecting and reconnected really is an issue, I would suggest trying to solve this outside of the single `repeat()` case, possibly by waiting a tick before cleaning up. Then if the element is immediately reconnected, you don't do the work:

```js
let triggerConnectionCallbacks = true;
class MyElement extends HTMLElement {

  _reaction;

  connectedCallback() {
    if (this._reaction !== undefined) {
      this._reaction = new Reaction(...);
    }
  }

  async disconnectedCallback() {
    // wait for a microtask in case we're immediately reconnected
    await 0;
    if (!this.isConnected && this._reaction !== undefined) {
      this._reaction.dispose();
      this_reaction = undefined;
    }
  }

}
```

**Comment by jridgewell** [comment]
We had a similar issue with Custom Elements firing `disconnected`/`conntectedCallback` during reparenting nodes in AMP. We found that just checking `node.isConnected` is sufficient to detect if this was a simple DOM reordering (it'll be `true`), or a removal (it'll be `false`).

**Comment by Spanoudakhs** [comment]
@jridgewell Funny thing is that I knew about `isConnected` but I am taken aback that it works likes this for such a case . Using this :
```javascript
import {render,html} from "lit-html";
import {repeat} from "lit-html/directives/repeat";

window.customElements.define("c-e", class extends HTMLElement {
	connectedCallback() {
		console.log(`connectedCallback id=${this.id} , isConnected=${this.isConnected}`);
	}
	disconnectedCallback() {
		console.log(`disconnectedCallback id=${this.id} , isConnected=${this.isConnected}`);
	}
});

const renderComponents = (arr) => render(html`${repeat(arr,id => id,id => html`<c-e id=${id}></c-e>`)}`, document.body);
renderComponents([1,2]);
renderComponents([2,1]);
document.body.innerHTML = "";
```
I tested what you claim and it works . Thx , I think that solves the issue .

**Comment by jridgewell** [comment]
Yup! This only works for if the function both removes and inserts the element in the same call. Eg, `insertBefore(alreadyInsertedInTree, before)`. It does not work for `insertBefore(removeChild(alreadyInsertedInTree), before)`, because the removal is a separate call than the insertion. The Custom Element spec is weird…

**Comment by Spanoudakhs** [comment]
@justinfagnani I think it would be wise mentioning in an example about the repeat directive in lit-html docs the `isConnected` solution . It will save time for some people .

**Comment by justinfagnani** [comment]
Maybe... though I reached out the the authors of lit-mobx, and I don't think they're concerned about rapid disconnection/reconnection because registering a listener is very cheap.

**Comment by justinfagnani** [comment]
> because the removal is a separate call than the insertion. The Custom Element spec is weird…

What's happening here is that the custom elements reaction queue is flushed before returning to script. If you have two calls that cause disconnect, then connect, the queue is flushed between them and this disconnectedCallback is run when the element is still disconnected.

That's why I have the await trick in my example above. I'd generally advice against tuning this just for `repeat()` or especially for `repeat()`s _current_ implementation. We should be able to change the DOM APIs we call to move elements without breaking use code.

**Comment by Spanoudakhs** [comment]
@justinfagnani I think now I understand what you are saying here :

> Are you sure that disconnecting and reconnecting from MobX is a performance issue? 

In my case I am using the `autorun` of mobx and not `reaction` of mobx . What is the difference ? `autorun` is triggered **on observing** the `observable` and on change of `observable` , while `reaction` only on change of `observable` . So one of the things that I was trying to avoid was the reconnect trigger of autorun (that by they way triggers the `render`) on the whole component subtree  . Going for `reaction` would produce possible repeating code (or at least ugly code) in my components so I am trying to avoid it .

**Comment by benjamind** [comment]
Ah yes using Autorun does mean that you will get side effects immediately when creating the autorun and hence if used without the isConnected guard fix you found above will cause more knock on effects than you want.

In `lit-mobx` we use Reaction so that we can control setup and track of the observable function, and since this is implemented into the base class / mixin, it keeps our component code pretty clean.
