### ISSUE TITLE
broken link to webpack info

### ISSUE THREAD

**Issue by wkeese** [Polymer/lit-html#1148]
# Description
https://lit-html.polymer-project.org/guide/tools#build-your-project-with-webpack links to https://open-wc.org/building/building-webpack.html#default-configuration but that page doesn't exist (anymore).

Would be great if you could fix that.

**Comment by thepassle** [comment]
We recently changed the docs and decided we want to focus support and our building recommendation on Rollup, and less on webpack, so we removed it from the main docs site. The webpack building docs are still available on github: https://github.com/open-wc/open-wc/tree/master/packages/building-webpack
