### ISSUE TITLE
Question regarding transitions

### ISSUE THREAD

**Issue by Hawmex** [Polymer/lit-html#1149]
Well, lit-element and lit-html are some of the best tools in web app developement.
And it could provide more opportunities if a solution on this matter was documented or a directive was provided. I looked at previous issues but they haven't progressed further for a while.
When will such a directive or doc come to lit-html? Are there any plans?

**Comment by justinfagnani** [comment]
What specifically are you referencing?

**Comment by Hawmex** [comment]
@justinfagnani I mean #1017 & #1018.

**Comment by justinfagnani** [comment]
Any updates would be in #1017. Let's keep the conversation there so we don't create too many open issues.

Our team road map is here: https://github.com/Polymer/project/blob/master/Roadmap.md and we're currently focusing on SSR. I've been experimenting with animation directives on the side though, and if I have updates I'll post them to #1017.
