### ISSUE TITLE
Problem with lit-html in IE11

### ISSUE THREAD

**Issue by niallcollins** [Polymer/lit-html#1150]
Hi all,

Working with lit-html and really like it. Works perfectly for me in all browsers except IE11 where the following error occurs:

Message: Syntax Error
File: directive.js
Line No: 68
Code: export const directive = <F extends DirectiveFactory>(f: F): F =>

Should I have any polyfills or specific setup to run on IE11? Please ask any questions and assistance would be appreciated as not working IE11 is a deal breaker for me. Thanks

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [X] IE 11

**Comment by justinfagnani** [comment]
lit-html is distributed as modern JavaScript. To run in very old browsers like IE11 you'll need to compile it to their particular level of JavaScript. Babel is well suited to this, as well as many bundlers which include it. See also: https://lit-html.polymer-project.org/guide/tools

**Comment by niallcollins** [comment]
Thanks for feedback. I already use Babel so will look to use this. An examples of projects available that may have this setup in place that I could review?

**Comment by kevinpschaaf** [comment]
The open-wc website has good docs on using rollup + babel to compile modern JS to work on older browsers: https://open-wc.org/building/building-rollup.html

**Comment by arthurevans** [comment]
For IE11, you'll need to load a template polyfill. There's one in the lit-html repo, but it's pretty sketchy. I'd recommend the one from the webcomponents polyfills (https://github.com/webcomponents/polyfills/tree/master/packages/template).

For a simple working example, here's what I came up with: https://github.com/PolymerLabs/lit-html-build
Deployed here: https://wizardly-davinci-e343a6.netlify.app/  ... Work on IE11 for me.

**Comment by sorvell** [comment]
Closing based on the comments above. If the problem persists after implementing the recommendations above, please fell free to re-open this issue or open a new issue with more info.
