### ISSUE TITLE
Release Notes documentation links point to wrong directory

### ISSUE THREAD

**Issue by PaulKinlan** [Polymer/lit-html#1163]
# Description
The documentation links in the [release notes](https://lit-html.polymer-project.org/guide/release-notes) point to the wrong directory. 

# Steps to Reproduce

1. Write this code

Visit the relese notes, then for `live` click the documentation link.

2. See this output...

## Live Reproduction Link
https://lit-html.polymer-project.org/guide/release-notes

## Expected Results
It should not 404

## Actual Results
It 404's

**Comment by arthurevans** [comment]
Fixed by #1164.
