### ISSUE TITLE
DOM nodes are not updating properly when removing values from an array

### ISSUE THREAD

**Issue by lastmjs** [Polymer/lit-html#1167]
# Description

lit-html does not seem to correctly update DOM nodes rendered based on mapping an array of values if items are deleted from the array without mutating the array, and if lit-html has no bindings to the DOM node.

For example, let's say you have an array of items and you map over them to create a list of input elements. If you do not bind to the value property of the inputs, but instead manually type into the inputs, and then remove one of the inputs, the corresponding values are incorrect.

# Steps to Reproduce

1. Write this code

```ts
import { html, render as litRender } from "https://unpkg.com/lit-html";

class TestElement extends HTMLElement {
  items = [1, 2, 3, 4, 5];

  remove(itemToRemove) {
    this.items = this.items.filter(item => {
      return item !== itemToRemove;
    });

    this.render();
  }

  connectedCallback() {
    this.render();
  }

  render() {
    litRender(
      html`
        ${this.items.map(item => {
          return html`
            <div>
              Input ${item}: <input type="text" />
              <button @click=${() => this.remove(item)}>Remove</button>
            </div>
          `;
        })}
      `,
      this
    );
  }
}

window.customElements.define("test-element", TestElement);
```

2. See this output...

Type into the inputs, and then click remove on any but the last input. You'll notice that the value of the input that you removed is still present in the input that replaced it. This is not right.

## Live Reproduction Link

https://codesandbox.io/s/damp-firefly-iehkd?file=/test-element.js

## Expected Results

Removing a DOM node should remove it entirely, and its properties and state should be entirely gone.

## Actual Results

It seems that lit-html is somehow keeping the state of previous DOM nodes around, and incorrectly assigning that state to other elements when mapping over arrays and removing items.

**Comment by justinfagnani** [comment]
If you have stateful DOM, you need to use a keyed `repeat()` instead of `array.map()`.

See the change here: https://codesandbox.io/s/vigilant-pasteur-9ptp7?file=/test-element.js

Hopefully the docs describe the differences: https://lit-html.polymer-project.org/guide/writing-templates#repeating-templates
