### ISSUE TITLE
Support import into Node.js

### ISSUE THREAD

**Issue by rhythnic** [Polymer/lit-html#1184]
## Description
lit-html code is written in ESM syntax, but the package.json doesn't use `type: module`, so Node.js sees it as `type: commonjs`.  The result is that lit-html cannot be imported into a JS module running in Node.js.  This might be intentional, because certain functionality requires the DOM, but that might be limited to `render`.

The biggest use case enabled by supporting import to Node.js is unit testing.  There may be ways of doing SSR that would be enabled too.

## Acceptance criteria
Add `type: module` to package.json

**Comment by sorvell** [comment]
Good suggestion. This should already be fixed via https://github.com/Polymer/lit-html/pull/1146.
