### ISSUE TITLE
make headers in documentation clickable to generate sharing links

### ISSUE THREAD

**Issue by samccone** [Polymer/lit-html#1185]
All documentation headers on https://lit-html.polymer-project.org/guide/* should be clickable to enable people to share direct links to the documentation sections.

For example clicking this header
![image](https://user-images.githubusercontent.com/883126/87804839-48364b00-c809-11ea-9fcb-b3d591d3f519.png)

should update the URL to: 
https://lit-html.polymer-project.org/guide/writing-templates#bind-to-attributes

or potentially copy the link to my clipboard.

**Comment by arthurevans** [comment]
Good news: we can generate a trailing symbol with a permalink just by setting `permalink: true` here:

https://github.com/Polymer/lit-html/blob/master/docs/.eleventy.js#L29

Bad news: the e11y TOC plugin we're using doesn't know any better than to include the permalink symbol in the TOC, which looks terrible.

Ideal might be to make the whole heading a link, but I don't see an option for that in markdown-it-anchor.

Reassigning to @justinfagnani to see if he has any ideas.

**Comment by justinfagnani** [comment]
Fixed in 2.0 docs.
