### ISSUE TITLE
lit-html 1.3.0 Release Plan

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1191]
# 1.3.0 Release Plan

Release Plan that outlines the focused tasks for lit-html 1.3.0.

[Milestone](https://github.com/Polymer/lit-html/milestone/15)

## Notable Changes
- Enhancements
  - [x] [Restore Trusted Types support](https://github.com/Polymer/lit-html/pull/1153)
  - [x] [Set type in package.json to "module"](https://github.com/Polymer/lit-html/pull/1146)
  - [ ] ~~[Add a generic for directive factories to type check against](https://github.com/Polymer/lit-html/pull/1151)~~
  - [x] [Export shadyTemplateFactory](https://github.com/Polymer/lit-html/pull/1135)

- Infrastructure
  - [x] [Upgrade TypeDoc and fix API docs](https://github.com/Polymer/lit-html/pull/1178)

## Documentation
N/A

## Release Process
- [x] [1.3.0 Release: Run Google Internal Tests](https://github.com/Polymer/lit-html/issues/1187)
- [x] [1.3.0 Release Notes](https://github.com/Polymer/lit-html/issues/1188)
- [x] [Verify 1.3.0 CHANGELOG](https://github.com/Polymer/lit-html/issues/1189)
- [x] [1.3.0 Prelease](https://github.com/Polymer/lit-html/issues/1190)

**Comment by rictic** [comment]
internal tests are :+1:

**Comment by justinfagnani** [comment]
Generics for directives aren't really critical, and it seems like there's only two built-ins that would use it, so I'm doing to bump it to another release.
