### ISSUE TITLE
Implications of a dumb template function

### ISSUE THREAD

**Issue by grimly** [Polymer/lit-html#1197]
I have given some thoughts to #1182 and an idea I didn't put in there was to have a really dumb `html` function. In fact so dumb its implementation would be as  such :

```typescript
export function html(tsa, ...values) {
  return {tsa, values, type: 'html'};
}
```

The `type` added was just to solve the issue with html vs svg vs mathml but that is just a detail. We could even say it is `html` by default.

I am not taking into consideration directives, just that they exist. This idea would be a breaking change anyway and directives can change to many things meanwhile. 

This idea could have the following implications:

* PRO: You would not suffer from using `html` and `render` functions from different instances of `lit-html`
* You change the responsability of template creation to the `render` function.
  * CON : If you use multiple part factories this would hurt.
  * PRO : You do not rely on the DOM anymore to create the template. Therefore you may have a `render` function that does not rely on the DOM either for servers and an other that draw the content in the DOM for browsers.
* `lit-html` would still be able to cache its compiled template from the template string array since the reference does not change.
* SSR implementation could be as dumb as `String.raw` (well, not as dumb because of directives but pretty close)

I am not foreseeing edge cases that does not imply directives accessing the part committer (which IMHO is a problem), therefore maybe you have something in mind to invalidate this idea. Do you see any ? I'm looking for your experience. 

Grimly

**Comment by justinfagnani** [comment]
The prototype implementation of lit-html 2.0 already includes such a simplified `html` tag, with responsibility for building the HTML string moved to `render()`. This doesn't change SSR much.

**Comment by justinfagnani** [comment]
Closing this, since we are pursuing this approach.
