### ISSUE TITLE
Pushing new item in the array replace the last item in lit html

### ISSUE THREAD

**Issue by parasharrajat** [Polymer/lit-html#1198]
I am trying to create dynamic listing in lit-html but I am not able to understand while pushing new item into the array old item is being replaced somehow and DOM updates to the that item instead of adding a new list item.

I have tried several times with many different implementations but always result is same.
```
import { html, render } from 'lit-html';


const dataMain = {
  running: false,
  status: '',
  tags: [],
};




const chipsFunc = (tags) => {
  return tags.map((t, i) => html`
  <li class="">
    <div class="chip">${t}
      <span class="close" @click="${tags.splice(i, 1)}">&times;</span>
     </div>
  </li>`);
}

function card(data) {
  console.log(data.tags);
  const chips = chipsFunc(data.tags);
  return html`
  <div class="card">
  <div class="card-header d-flex align-items-center header">
<div class="image">
  ${data.running !== 'loading' ?
      html` <img src="../images/logo-38.png" class="mr-2 icon">` :
      html`<img src="../images/loader.svg" class="mr-2 icon">`
    }
  </div>
    ${!data.running ?
      `Extension` :
      html`${status}`
    }
 <div class="actions d-flex">
 <button type="button" class="btn">
   <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
</svg></button>
  </div>
  </div>
  <div class="card-body" >
  <ul class="d-flex form-control list-inline">
  ${chips}
<li>
  <input type="text" class="form-control" id="add-tag" placeholder="Add Tag" @keyup="${e => addTag(e)}">
  </li>
  </ul >
  </div >
  `;
}
function addTag(e){
  if (e.key === 'Enter') {
    dataMain.tags.push(e.target.value);
    // e.target.value = "";
    render(card(dataMain), document.body);
  }
}

render(card(dataMain), document.body);
```

Please help me understand How can I make it work?

**Comment by grimly** [comment]
You used `@click="${tags.splice(i, 1)}"` which is not an action done on click but instead executed immediately. It produces the side effects you see. 

Replace it with `@click="${() => tags.splice(i, 1)}"` and it should already have a better behavior.

You have to render again your cards somehow on deletion but that is something you can solve later

**Comment by parasharrajat** [comment]
> You used `@click="${tags.splice(i, 1)}"` which is not an action done on click but instead executed immediately. It produces the side effects you see.
> 
> Replace it with `@click="${() => tags.splice(i, 1)}"` and it should already have a better behavior.
> 
> You have to render again your cards somehow on deletion but that is something you can solve later

Thanks, I moved to hyperHtml. So I come to know the things work in **tagged template literal** based rendering.
