### ISSUE TITLE
Stricter types for nothing and noChange

### ISSUE THREAD

**Issue by asyncLiz** [Polymer/lit-html#1235]
## Description
[`nothing` and `noChange`](https://github.com/Polymer/lit-html/blob/e66eb66d9244d019a5d5b17a692a6269b806b552/src/lib/part.ts#L45) sentinels have a type of `{}` (empty object). This can be confusing and misleading in TypeScript when mixing with other valid lit-html types such as `TemplateResult`.

```ts
function render(value?: string): TemplateResult | {} {
  if (!value) {
    return nothing;
  }

  return html`Value: ${value}`;
}
```
The return type is not entirely accurate, since any new empty object is not a valid return value for this function. It should only expect a template result or the nothing sentinel.

## Acceptance criteria
lit-html can provide a stricter unique type alias for `nothing` and `noChange` that ensures the types for those sentinel values are unique and do not conflict with the empty object type.

Example:

```ts
export type NothingSentinel = {
  _nothingBrand: never;
};
export const nothing = {} as any as NothingSentinel;
```

**Comment by justinfagnani** [comment]
This should be fixed in lit-next by #1470
