### ISSUE TITLE
How to call DOM element's method following lit-html render?

### ISSUE THREAD

**Issue by hokiedsp** [Polymer/lit-html#1248]
Hi, this is a how-to question; if this has been answered before I'd appreciate if someone could let me know where to look.

I need to call `focus()` & `scrollIntoView()` of a DOM element immediately after lit-html renders it (and surrounding DOM tree structure). What is the best, most elegant way to go about doing this?

I guess this process can be broken down into 3 steps (my ideas in parentheses): 

1. Wait till DOM is rendered (zero-delay `setTimeout()` call? possibly use `MutationObserver` but attribute change is not guaranteed)
2. Find the target DOM element (just call `querySelector()` from a known ancestor?)
3. Run the DOM methods

Mucho thanks for any insights towards resolving this

**Comment by justinfagnani** [comment]
`render()` is synchronous, so you can just call `render()`, then query for the element and call methods on it.

```
render(html`<div id="a"></div>`, document.body);
const el = document.querySelector('#a');
el.scrollIntoView();
```

**Comment by hokiedsp** [comment]
@justinfagnani Thanks for the clarification! 

But [facepalm]... I don't know where I got this async idea from. Maybe I'm confused between lit-html render and lit-element render method?

**Comment by justinfagnani** [comment]
Glad that helped!
