### ISSUE TITLE
[lit-next] Local workflow for testing IE11

### ISSUE THREAD

**Issue by aomarks** [Polymer/lit-html#1306]
E.g. manual sauce tunnel and wtr in manual mode. Maybe karma.

**Comment by LarsDenBakker** [comment]
For local testing you could also consider using the selenium launcher: https://modern-web.dev/docs/test-runner/browsers/selenium/

Right now it does require setting up a selenium server yourself, later on I'd like to move that logic inside the launcher as well. You can see an example here https://github.com/modernweb-dev/web/blob/master/packages/test-runner-selenium/test/seleniumLauncher.test.ts#L11

**Comment by justinfagnani** [comment]
@LarsDenBakker note that for "local" IE11 testing we mean running the test server locally and IE11 on Sauce in an interactive session.
