### ISSUE TITLE
More descriptive/useful message for html template errors

### ISSUE THREAD

**Issue by bmsmg** [Polymer/lit-html#1312]
# Description
As a new user of lit-html and lit-element, I hit a snag working on a simple demo of lit-element.  The error was my fault; I simply forgot a closing " on a data-attr.  However, the error message suggested something more catastrophic from the depths of lit-html: `TypeError: Failed to set the 'currentNode' property on 'TreeWalker': The provided value is not of type 'Node'.`
![image (2)](https://user-images.githubusercontent.com/3442539/93951147-5d908f80-fcfa-11ea-9834-b087242045af.png)

NOTE: the helpful crew on the Polymer Slack #general channel pointed me to the VSCode `lit-plugin` which would have helped me see my error much easier.  

# Steps to Reproduce
1. Create a template with invalid html.  In this case, a missing " after a data-attr.
`render() {
      // ERROR here!  Missing closing " after data-someid
        return html`
            <li data-someid="${this.value}>${this.name}</li>
        `;
    }`

## Live Reproduction Link
https://stackblitz.com/edit/js-3msbzx?file=mymenuitem.js

## Expected Results
It would be nice to have a SyntaxError or something as a result of parsing the template up-front rather than allowing a runaway string to wreak havoc.

## Actual Results
 `TypeError: Failed to set the 'currentNode' property on 'TreeWalker': The provided value is not of type 'Node'.`
![image (2)](https://user-images.githubusercontent.com/3442539/93951147-5d908f80-fcfa-11ea-9834-b087242045af.png)

## Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [x ] Edge
- [x ] Safari 11
- [x ] Safari 10
- [x ] IE 11

**Comment by justinfagnani** [comment]
We have a lot more dev mode errors added to 2.0, plus we now handle the case that was problematic here. We can open more issues for other cases as needed.
