### ISSUE TITLE
[lit-ssr] Port lit-ssr and hydrate to lit-next

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-html#1329]
## Description
* Move [`lit-ssr`](https://github.com/PolymerLabs/lit-ssr) to `lit-next` monorepo
* Port `lit-ssr` to work with lit-next client code
* Port [`lit-html#hydrate`](https://github.com/PolymerLabs/lit-html/tree/hydrate) `hydrate()` to work with lit-next client code
* Confirm lit-ssr integration tests pass

## Acceptance criteria
`lit-ssr` integration tests pass

**Comment by lanyusan** [comment]
Can I ask if you have a target release date for this? Thanks.
