### ISSUE TITLE
Pass eventContext to PropertyCommitter

### ISSUE THREAD

**Issue by Artur-** [Polymer/lit-html#1335]
# Description
Right now, `options` are passed to NodeParts https://github.com/Polymer/lit-html/blob/master/src/lib/default-template-processor.ts#L55 and the `eventContext` part of `options` is passed to `EventPart`: https://github.com/Polymer/lit-html/blob/master/src/lib/default-template-processor.ts#L42

Is there a reason that `options` or `options.eventContext` are not passed to `PropertyCommitter`?

Use case: 
Declaratively define a renderer for a vaadin-grid-column, something like
```
<vaadin-grid-column .renderer=${renderer((data:MyData) => html`<span @click="${this.nameClick}">{$data.name}</span>`)}>
```

This works fine except that when rendering the inner template you have no access to `eventContext` so `this` points to something else.

The fix would be quite trivial, something like
```
-      const committer = new PropertyCommitter(element, name.slice(1), strings);
+      const committer = new PropertyCommitter(element, name.slice(1), strings, options.eventContext);
```

```
-
-  constructor(element: Element, name: string, strings: ReadonlyArray<string>) {
+  readonly eventContext?: EventTarget;
+  
+  constructor(element: Element, name: string, strings: ReadonlyArray<string>, eventContext?: EventTarget) {
     super(element, name, strings);
+    this.eventContext = eventContext;
```

**Comment by Artur-** [comment]
Any comments @justinfagnani? Seems simple and non-breaking but I might be wrong

**Comment by zandaqo** [comment]
I have the same issue, and I believe this #1143 would solve our problems, `eventContext` is passed with RenderOptions and access to it from directives would do the trick.

**Comment by sorvell** [comment]
We're considering adding this in the next major version. See #1441.

**Comment by justinfagnani** [comment]
This has been added for 2.0
