### ISSUE TITLE
lit-html may reuse existing input DOM nodes and keep the `.value` property.

### ISSUE THREAD

**Issue by jeffmcmahan** [Polymer/lit-html#1337]
# Description
The user types "Jim" into `<input id="name" value=${props.name}>`. The user clicks a button to advance to the next view, replacing much of the DOM, which then contains `<input id="age" value=${props.age}>`. This new, freshly rendered `<input>` *somehow* contains the text "Jim".

# Steps to Reproduce

I could not reproduce with a smallish example; the problem seems to depend on triggering some fancy optimizations for sharing nodes across renders (which could be done by the browser or by lit-html; I know not which). But I'll tell you what *did* work in my own code, which I think gives a hint as to what might be going on. Assume that the problem exists between the two `<input>` elements shown below:

```js
import {...} from '...'

export const myView1 = props => {
  return html`<div class=${css.container1}>
    <input id="the-input" value=${somethingA()}>
  </div>`
}

export const myView2 = () => {
  return html`<div class=${css.container2}>
    <input id="the-input" value=${somethingB()}>
  </div>`
}
```

Next, I simply altered one of them by adding a comment:

```js
export const myView2 = () => {
  return html`<div class=${css.container2}>
    <!-- comment -->
    <input id="the-input" value=${somethingB()}>
  </div>`
}
```

*Voila.* The problem disappears. Moreover, if I add that same comment to both, the problem reappears. Whitespace has the same effect. So then: the problem can occur when the raw string passed to `html` is *identical* in two templates - even if the `${...}` bindings are different. I think this is because `<template>` is doing the work, and it's seeing identical templates and so treats the DOM update as if the new bound values came from the same place. If that's correct, I'm not really looking for a solution per se, but it may be useful to note somewhere (if not already done) that if the string literal portions of two templates are identical, it can cause node-reuse optimizations that may result in errant behavior - particularly with `<input>`.

## Live Reproduction Link
I spent more than an hour trying to get lit-html to do the same thing it does in my project.

## Expected Results
A freshly rendered `<input>` should never carry a value from an input that originated in some other template.

## Actual Results
In some cases, the input value property sticks around.

## Browsers Affected

- [x] Chrome
- [x] Firefox (Dev Edition)
- [ ] Edge - NOT TESTED
- [x] Safari 12
- [ ] Safari 11 - NOT TESTED
- [ ] Safari 10 - NOT TESTED
- [ ] IE 11 - NOT TESTED

**Comment by justinfagnani** [comment]
This sounds like a non-spec-compliant template literals implementation. Template literal strings are supposed to be referentially identical and _unique_ per call-site. An old version of the spec had them globally shared by _contents_.

All current browsers implement the spec correctly. Edge 17 and prior didn't. If you're seeing this behavior in multiple browsers, and not able to reproduce it separately, I think it's likely that you're using a non-spec-compliant compiler in your project. Please add your compiler, version, and relevant plugins and settings so we can see if that's the case.

**Comment by jeffmcmahan** [comment]
I'm executing my source JS directly in the latest versions of the three browsers I indicated. No transpilation of any kind.

**Comment by justinfagnani** [comment]
Interesting. We definitely need to see a reproduction then. lit-html 1.3.0 includes a workaround for a Safari bug that could be being triggered here.

**Comment by jeffmcmahan** [comment]
I will see if I can strip the project down and retain the misbehavior, and get back to you. Thank you for the quick response.

**Comment by justinfagnani** [comment]
Thanks for the report. I'm quite sure this is triggering our Safari workaround, and I don't think there's much we can do about it in 1.x. In 2.0 we've removed the workaround completely, so this should be fine.

**Comment by jeffmcmahan** [comment]
Hey if you're sure, I'm sure. :) For now, I'll just insert a comment when this comes up. Thanks again.
