### ISSUE TITLE
[lit-html] Allow a directive to get the parentNode of the associated NodePart

### ISSUE THREAD

**Issue by graynorton** [Polymer/lit-html#1346]
`lit-virtualizer`'s directive implementation needs to know the `parentNode` of the `NodePart` associated with the directive.

In lit-html 1.x, it used `part._startNode.parentNode`, but with the new directive API it's no longer possible to access `_startNode` or `_endNode`.

I don't know of any other specific use cases, but it seems like it might be generally useful for a directive for a `NodePart` directive to be able to access the `parentNode`.

**Comment by web-padawan** [comment]
We are also interested in this API, it is needed to implement `renderer` directive which works like this:


```js
<vaadin-select label="Select status">
  ${renderer(
    this.statuses,
    () => html`
      <vaadin-list-box @selected-changed="${this._onSelected}">
        ${this.statuses.map(status => {
          return html`
            <vaadin-item name="${status.name}">${status.name}</vaadin-item>
          `;
        })}
      </vaadin-list-box>
    `
  )}
</vaadin-select>
```

The [current prototype](https://glitch.com/edit/#!/vaadin-lit-renderer-experiment?path=renderer.js%3A40%3A0) gets reference to a parent as described above and then sets property on it.

**Comment by kevinpschaaf** [comment]
This now exists in lit-next: https://github.com/Polymer/lit-html/blob/lit-next/packages/lit-html/src/lit-html.ts#L850-L852

Added in https://github.com/Polymer/lit-html/pull/1347/files#diff-bead45bb43cda474d916704550a1b26322667aa42b814c48300b05be79b9a7ebR847-R850
