### ISSUE TITLE
[lit-html] Use Element#getAttributeNames() instead of Element#attributes

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1353]
It should be a bit faster.

**Comment by sorvell** [comment]
FWIW, we may want to also check `hasAttributes` first as my recollection is that this is a fast lookup and doesn't need to make the array. Might be worth some benchmarking.

**Comment by justinfagnani** [comment]
We are using `hasAttributes` here: https://github.com/Polymer/lit-html/blob/lit-next/packages/lit-html/src/lit-html.ts#L493

It looks like we aren't even using the attribute value here, so this should be an easy change to make.
