### ISSUE TITLE
[reactive-element] Update @lit/reactive-element readme

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#1359]
## Description
When updating-element is its own package, the README should be updated to include examples that show UpdatingElement rather than LitElement.

## Acceptance criteria
Readme updated.

**Comment by justinfagnani** [comment]
We should discuss. I think it's quite ok to show samples for UpdatingElement in context of a subclass.

We can add a few "vanilla" samples for UpdatingElement, but IMO we shouldn't feel required to double-up every example for Updating/Lit, nor suffer a clarity problem on the other side with many LitElement samples using only UpdatingElement.
