### ISSUE TITLE
User should be able to define what is "undefined" in `ifDefined`

### ISSUE THREAD

**Issue by e111077** [Polymer/lit-html#1364]
## Description

- Who wants the functionality: Users of `ifDefined`
- What it is they want: To customize what "undefined" is other than `undefined`
- Why they want it: Clears up lots of boilerplate
- Functional description of task/subtask: Implement another agrument(s) on `ifDefined` to allow the user to customize what is "undefined"

It'd be great if ifDefined had something like:

`aria-label=${ifDefined(this.label, '', null, undefined)}`

or simply just:

`aria-label=${ifDefined(this.label, '')}`

The current solution is:

`aria-label=${ifDefined(this.label ? this.label : undefined)}`

## Acceptance criteria

If defined can prevent the display of an attribute based on an arbitrary set of "undefined" values

**Comment by justinfagnani** [comment]
Honestly, `aria-label=${ifDefined(this.label ? this.label : undefined)}` is the most readable of the three snippets. I don't know what al the options would do in the first, and I'm not sure what the `''` is for in the second. If you're checking for truthiness, you can simplify to using a logical or as well: `aria-label=${ifDefined(this.label || undefined)}`. That flexibility is why `ifDefined` is so simple - we can't know all the conditions you might want to check against, so we let you transform values into `undefined` for customization.

One great alternative here is to define your own helper using `ifDefined` as a building block. If you want to remove the attribute when a value is falsey, you can write:

```ts
const ifTruthy = (v: unknown) => ifDefined(v || undefined);
```

**Comment by e111077** [comment]
We cannot use the truthyness suggestion due to lit-to-wiz changing `this.label || undefined` into `label OR undefined` in soy which always returns a boolean thus `aria-label="false"`

Also, this gets worse when we have to do the following:

`aria-label=${ifDefined(this.label ? this.label : this.icon ? this.icon : undefined)}`

as opposed to:

`aria-label=${ifDefined(this.label ? this.label : this.icon, '')}`

the first one would be equivalent to `ifDefined(value: unknown, ...undefinedVal = [undefined])` Also I agree that the `ifDefined` name likely wouldn't fit anymore.

**Comment by bathos** [comment]
> Also, this gets worse when we have to do the following:
>
> aria-label=${ifDefined(this.label ? this.label : this.icon ? this.icon : undefined)}

```
aria-label=${ifDefined(this.label || this.icon || undefined)}
```

You can also define accessors or methods for deriving values you want to use during templating, which for more complex cases has the added benefit of giving those things names.

I don’t have an opinion on whether it’d be a good idea to include `isTruthy` or a factory for other variants in lit, but I do think `isDefined` is the wrong place for it. Configuring “what is undefined” is like configuring “what is the number 3”.

**Comment by e111077** [comment]
Unfortunately under the parameters in which we are working with, as of now, we cannot use `||` assignments as they end up evaluating to a boolean before assigning, and we cannot use methods that return anything other than another template result.

Yeah perhaps a ifNotEqual and ifDefined can be composed on top of that.

Though I'd still argue `ifDefined(this.prop || undefined)` is a smell of a leaky implementation since the term `defined` is somewhat vague in JS.

**Comment by bathos** [comment]
> the term defined is somewhat vague in JS

The title of the issue described this as a request to “define what is "undefined"”, and `undefined` is ... [well-defined](https://tc39.es/ecma262/#sec-ecmascript-language-types-undefined-type) in JS :) But it’s true that using the term “defined” to refer to “the set of values which are not `undefined`” follows from typical English language patterns, not ECMA-262.

**Comment by e111077** [comment]
Sure, I guess I meant English: I attempted to differentiate between "undefined" and `undefined` in the issue. I somewhat think I'd prefer the term `isNotUndefined` since it affords `!== undefined`, but that naming convention is against Google style guide.

**Comment by justinfagnani** [comment]
I think `nothing` support in 2.0 supersedes this. You can now write a function that translates any value to `nothing` if you wish.
