### ISSUE TITLE
Doesn't render in Edge or IE

### ISSUE THREAD

**Issue by simsketch** [Polymer/lit-html#1366]
here is the most basic example provided by the docs, which is not working in Edge or IE. I've tried on multiple machines.

https://codesandbox.io/s/wq2wm73o28

works fine in firefox, chrome and safari

**Comment by csvn** [comment]
`lit-html` is delivered as a set of ES-modules, with modern es2015+ syntax. So while the code is designed to work with IE11, it does not do so out of the box in v1. To run in legacy browsers such as IE and Edge you need build tooling, to bundle all the modules into a single file, as well as to transform es2015+ to es5. You will also need polyfills for IE 11 (see below).

* https://lit-html.polymer-project.org/guide/tools goes through useful build and dev-tools, and mentions requirements for IE 11
* https://github.com/PolymerLabs/lit-html-build shows an example of how to build `lit-html` with Rollup

Also worth mentioning, is that team is [currently working on v2.0, which contains a few nuggets of information](https://github.com/Polymer/lit-html/issues/1182) related to this:

> ### Prod and dev builds
> ### Move IE11 support out of the core library

**Comment by justinfagnani** [comment]
Thanks for the answer @csvn!

@simsketch does this help you? I hope the docs are clear on what needs to be done for IE.

**Comment by simsketch** [comment]
Thanks! Yeah this makes it clear enough...I was hoping there was a way to support it out of the box...also was hoping that if there is a hello world example in code sandbox referenced from the docs that the example would support all of the browsers listed.
