### ISSUE TITLE
unsafeHTML not working well outside of render()

### ISSUE THREAD

**Issue by fylux** [Polymer/lit-html#1374]
Calling unsafeHTML in a plain string does not return the plain string unescaped.

```
console.log((html`Foo`).getHTML()); //  'Foo'
console.log((html`${unsafeHTML("Foo")}`).getHTML()); // '<!--{{lit-8186002727240103}}-->'
```
From what I could find out, unsafeHTML rather than returning a template with the HTML content in .values, it returns a function that takes a Part.

How can I get the "final" input when using unsafeHTML?

**Comment by justinfagnani** [comment]
`unsafeHTML()` is a lit-html directive, you have to use it inside `render()`. If you want HTML outside of lit-html, just use the standard `.innerHTML` setter on an element.

**Comment by fylux** [comment]
Then if I want to test unsafeHTML without rendering, what would be the way to go? In that example, how can I test that unsafeHTML is returning a plain string Foo?

```
console.log((html`${unsafeHTML("Foo")}`).getHTML())
```

**Comment by csvn** [comment]
Why without rendering? You can use a simple utility to get the resulting HTML of using the directive.

```ts
function getHtml(template: TemplateResult) {
  const div = document.createElement('div');
  render(template, div);
  return div.innerHTML;
}

console.log(getHtml(html`${unsafeHTML("Foo")}`));
```

**Comment by justinfagnani** [comment]
`unsafeHTML` is a directive and doesn't "return" anything. It creates some DOM from the HTML and appends it into the DOM where the template is. Directives only run on render.

You can check the rendered DOM instead.

**Comment by fylux** [comment]
Thank you for the clarification!
