### ISSUE TITLE
[lit-html] nothing & noChange are currently version-dependent

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-html#1377]
# Description
One of the goals in `lit-next` is to allow for interoperability between multiple `lit-html` versions loaded on the same page. However, currently `nothing` and `noChange` are version-dependent: since they're objects checked for identity, they will not be respected correctly between versions.  

Practically, this can happen when a directive loaded from a different `lit-html` package returns `noChange`.

# lit-html version
2.0.0-pre.3

# Steps to Reproduce

With non-deduped installs of e.g. `lit-html` and `lit-element/node_modules/lit-html`:

```ts
import {html, render} from 'lit-html';
import {nothing} from 'lit-element/node_modules/lit-html';
render(html`${nothing}`, document.body);
```
renders:

```
[object Object]
```

## Expected Results
Nothing is rendered

## Actual Results
The `nothing` sentinel value from the other `lit-html` package is rendered to `[object Object]`.

**Comment by kevinpschaaf** [comment]
Two options:
1. Use a gloabally-registered Symbol instead of `{}`, e.g. `Symbol.for('$litNoChange$')`
   * Pros: Keeps current identity checks simple
   * Cons:
      - Symbol is a primitive, so it makes the commit cascade slightly tricky (although I think we could change `isPrimitive` to exclude Symbol now that we don't accept Symbol in text position?, and then it's trivial)
      - Need to check polyfill support fo `Symbol.for`

2. Add a branding to the objects and check for that: e.g. `{$litNoChange$: true}`
   * Pros: Avoids any polyfill stress
   * Cons: Sites that need to check for `nothing`/`noChange` are wordier/more code: need to check for truthyness then dereference the branding field; would likely need `isNothing` / `isNoChange` helpers

**Comment by straversi** [comment]
Using a Symbol rather than `{}` can help tooling as well. `{}` clobbers other types in expressions. The TS inferencer evaluates `foo ? html`` : nothing` as returning type `{}`, due to the existence of `nothing` in the expression. If `nothing` were a symbol,  the type would be inferenced as `TemplateResult | typeof nothing`, which retains more information that useable to tooling.

**Comment by justinfagnani** [comment]
Fixed by https://github.com/Polymer/lit-html/pull/1470
