### ISSUE TITLE
Consider avoiding political advocacy as a policy

### ISSUE THREAD

**Issue by claytongulick** [Polymer/lit-html#1386]
# Description
Currently on the official lit-html home page, there is a banner supporting BLM as well as a couple of other political advocacy groups. The purpose of this issue report isn't to discuss the merits or value of those organizations, the purpose of this issue is to consider, as a policy, avoiding political commentary as part of the project.

Different people have different views, a community thrives from an inclusive, diverse group of participants.

Advocating for specific political policies that are unrelated to the project risks alienating potential contributors and users, and distracting from the core goals of the project.

Can we have a discussion about the merits of adopting a policy of political neutrality in a technical library? There are many venues available to us to discuss and communicate our political ideas. Can we have an objective discussion about whether a technical library is an appropriate venue for this discussion / advocacy?

I think the last thing we want to see as an open-source community is additional fracturing / forking / infighting due to unrelated political affiliation.

**Comment by mgilcrease** [comment]
I agree. There is no benefit to the project by injecting unrelated political agendas into the endeavour. It is detrimental to comity and adds unnecessary risk

**Comment by kevinpschaaf** [comment]
Google is committed to advancing racial equity for Black communities, and the banners on many of our project websites are one small way that we're helping raise awareness. Please see [our blog post on this topic](https://blog.google/inside-google/company-announcements/commitments-racial-equity/) to learn more.

**Comment by claytongulick** [comment]
Ah, so no discussion then. Just shut down with zero conversation. Ok.

Probably time to consider creating a place to fork projects like this to remove politics from them.

Some of us just want to code.

**Comment by blargism** [comment]
I agree. There are many forums where such advocacy is legitimate and much needed. I question the necessity of it's inclusion here. My reasons are as follows:

1) It provides no technical value.
2) Issues that seem clear cut can still be very divisive and interrupt technical progress.
3) What is and is not overly divisive is difficult to determine.
4) Politics, like religion, tends to induce emotional responses. These responses can result in interactions that are not respectful. These sorts of interactions are counter-productive.
6) Social-political issues are massively complex and require nuanced debate. This is not the forum for those debates. Advocacy of an issue invites debate of the issue, thus diverting from the project's purpose of building useful technology.

Personal Note:
I have chosen to participate in initiatives within my company that support diversity and inclusion initiatives. I am writing code and volunteering time. I encourage the community members who feel passionate about these issues to do the same. It is much more valuable than a web banner.

**Comment by blargism** [comment]
> Google is committed to advancing racial equity for Black communities, and the banners on many of our project websites are one small way that we're helping raise awareness. Please see [our blog post on this topic](https://blog.google/inside-google/company-announcements/commitments-racial-equity/) to learn more.

Thank you for your response and I appreciate your company's stance on the issue. It is an important issue for our time.

However you did not address the issue raised by the author. That such advocacy may not be in the best long term interests of an open source project such as this. We do not wish to discuss the validity of that issue, but rather how we might keep politics out of a technical effort such as this.
