### ISSUE TITLE
lit-next doesn't build on Node 15 and npm 7

### ISSUE THREAD

**Issue by bicknellr** [Polymer/lit-html#1403]
## Description
The `lit-next` branch doesn't bootstrap successfully when using Node 15 and npm 7. It looks like the template-shadowroot dependency of lit-ssr fails to build because it can't find types from `@types/jasmine`.

## Acceptance criteria
Running `npm i && npm run bootstrap && npm run build` on a clean checkout of the `lit-next` branch using Node 15 and npm 7 should succeed.

**Comment by kevinpschaaf** [comment]
Best path is probably to publish a pre-release of `@webcomponents/template-shadowroot` and remove the package.json hacks in lit-ssr, which are probably causing the problem.

**Comment by bicknellr** [comment]
I'm not seeing this anymore; closing.
