### ISSUE TITLE
[localize] Factor lit-localize CLI out of @lit/localize package

### ISSUE THREAD

**Issue by aomarks** [Polymer/lit-html#1429]
Currently `@lit/localize` includes both the client library, and the CLI. This isn't good, since typically users would want the former in `dependencies`, and the latter in `devDependencies`.

Maybe the first command in a lit CLI?

**Comment by justinfagnani** [comment]
A good start would be to make a new package for the transform, so any CLI wouldn't include the client library.

**Comment by aomarks** [comment]
> A good start would be to make a new package for the transform, so any CLI wouldn't include the client library.

There are a bunch of CLI pieces:

1. The analyzer that finds `msg` calls and generates XML files for localization.
2. The code generator that creates modules for each locale for runtime mode.
3. The transformer that emits the entire TypeScript program in a particular locale for transform mode.
4. The bit of code that runs the transformer for each locale (note that a TypeScript transformer can't emit a new file [at least as far as I could tell], so you can't just execute the transformer using e.g. https://github.com/cevek/ttypescript).

So I agree, but I think the package would include all of these pieces, not just the transformer.
