### ISSUE TITLE
[localize] Message IDs should be optional

### ISSUE THREAD

**Issue by aomarks** [Polymer/lit-html#1437]
It should not be required to manually provide an ID for every localized message, since we can generate an ID from the message contents instead.

**Scheme**

Use a hex digest of the hash of the concatenation of all string components of a template as the ID.

We need a delimiter between each string component, to distinguish between `foobar` and `foo${baz}bar`. Maybe a backtick, or `${`, since those can never appear in a template string literal unless escaped.

We can use SHA-1, or maybe something faster. Note we can detect collisions during analysis.

**API**

We need a new signature for the `msg` function, because currently the ID is the first parameter, and it needs to become optional. There is also now ambiguity between the message ID and parameters for a function-form template, so I think an optional arguments object is the clearest solution, which also gives us a place to add more per-message configuration in the future.

Before: 
```ts
msg(id: string, template: TemplateResult|string|Function, ...args: any[])
```

After:
```ts
msg(template: TemplateResult|string|Function, options?: {id?: string, args?: any[]})
```

(Note the actual signatures are much stricter than shown here -- e.g. `args` must match the parameters of the function).

**Implementation**

In static analysis, we have access to the string components and options object, so generating the ID is straightforward.

In transform mode, we fully substitute all `msg` calls with their localized result, so there is no difference.

Runtime mode is the trickiest area. We can access the string components of a template from `TemplateResult.strings`, so we can generate an identical ID to the one picked in static analysis from a `TemplateResult`.

If the template is a function, we need to do a throwaway call to the function (with arbitrary placeholder values) to access the `TemplateResult`.

If the template is a function that returns a _string_ instead of a `TemplateResult`, then we can't directly access the `TemplateStringsArray`. Instead, we would need to check `fn.length` to find the number of parameters, pass in unique placeholder values, and then split the resulting string on the unique placeholder. We could also change the API to require that template functions return `html` tagged strings, even if they don't contain HTML.

The built-in crypto API is asynchronous, so we can't use it within the `msg` call without changing the API to be asynchronous, which is unacceptable. This suggests we would need to use a pure-JS implementation of the hash function. We can maintain a map from `TemplateStringsArray` object identity to digest, so that each unique message only needs to be hashed once. This should also inform the decision of which hash function to use, since its speed will affect application performance.

This may also suggest that a third output style could be useful: runtime mode, but transformed so that all `msg` calls have hard-coded IDs, to eliminate all runtime hashing overhead. As a side benefit, we could emit minimized message IDs here instead of the full hash, since we're generating the message maps at the same time.

**Comment by JosefJezek** [comment]
Angular i18n assigns each translation unit a unique ID.

https://angular.io/guide/i18n#manage-marked-text-with-custom-ids
