### ISSUE TITLE
html tags inside bindings

### ISSUE THREAD

**Issue by nicolasr75** [Polymer/lit-html#1438]
Sorry, most likely not a bug. I was wondering whether it is possible to have html tags inside my bindings. A simple example:
I have an object with values for all cells in a table, including the header row because even the header row may be dynamic.
After playing around this for a while I found that it would be great if I could have html tags inside my values.

For example, in a header cell I would like to include a line break like this: "System`<br/>`requirements".
In a data cell I would like to show a boolean value with an LED image like this: "`<img src="led-on.png"/>`".

The problem is that the templates don't seem to handle this but only print the tags out as strings.

My template code looks something like this:

    render() {

		return html`

        <table>
			<tr>${this.tableContent.header.map(h => html`<th>${h}</th>`)}</tr>
			${this.tableContent.data.map(d => html`
				<tr>${d.map(cellSpec => html`<td>${this.getTextForDataCell(cellSpec)}</td>`)}</tr>				
			`)}
		</table>
        `;
    }

`this.tableContent` contains the specification of what to show in the table.
`this.getTextForDataCell` builds the output that is to be shown in the cells and that may include html tags, as described above.

Am I missing something or is this a general limitation?

**Comment by justinfagnani** [comment]
You can use [`unsafeHTML`](https://lit-html.polymer-project.org/guide/template-reference#unsafehtml) for this. Beware that this is a potential XSS security vulnerability. You should sanitize any user input that might pass through `unsafeHTML`.

**Comment by nicolasr75** [comment]
Yes, that solves it, thanks so much. I should have read the docs more carefully. This is an Intranet application with a limited known user group but I will sanitize the input nevertheless.
