### ISSUE TITLE
[lit-next] input does not work with null/undefined values like it did on version 1

### ISSUE THREAD

**Issue by vegarringdal** [Polymer/lit-html#1446]
# Description

Just tried version 2.0
Dont know if Im doing something wrong, but version 2.0 does not handle null/undefined with .valueAsDate.

# lit-html version

2.0.0-pre3

# Steps to Reproduce

Use this and set to version 2.0.0-pre3
https://codesandbox.io/s/lit-html-forked-njyi8?file=/index.html

![image](https://user-images.githubusercontent.com/2901416/100135118-7bf54180-2e89-11eb-808a-6543538ec76d.png)

## Live Reproduction Link

https://codesandbox.io/s/lit-html-forked-njyi8?file=/index.html

## Expected Results

Work as normal like version 1

## Actual Results

Try sample...

TypeError
Failed to set the 'valueAsDate' property on 'HTMLInputElement': Failed to convert value to 'object'.

## Browsers Affected
- [x] Chrome
- [ ] Firefox  (I have not tried)
- [ ] Edge   (I have not tried)
- [ ] Safari   (I have not tried)

**Comment by kevinpschaaf** [comment]
Thank you for the issue report!  This was indeed a bug in the pre-release, and has already been fixed on the `lit-next` branch in this PR: https://github.com/Polymer/lit-html/pull/1347/files#r508116058

We are going to get a new pre-release out soon, hopefully early next week. Thanks for the help in testing!
