### ISSUE TITLE
Support options for declarative event listeners in lit-extended

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#145]
Passive event listeners are particularly important:  https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by richardanaya** [comment]
Just for my own curiosity, why do you think this is something lit-extended should enforce?

**Comment by justinfagnani** [comment]
This isn't about enforcing, just exposing options. Passive event listeners are important on scroll and wheel events for reducing jank, so it'd be nice if declarative event listeners could use the passive option.

**Comment by richardanaya** [comment]
Neat!

**Comment by bennypowers** [comment]
certain events should be passive by default e.g. touch and pointer events

**Comment by justinfagnani** [comment]
I can think of a few syntactic options for passing options to lit:

1. Pass an object with `handleEvent` and `options` properties:

    ```ts
    html`<div on-scroll=${{handleEvent: (e) => doSomething(e), options: {passive: true}}}></div>`;
    ```
  
    **Pros:** Nicely explicit. Familiar by reusing an object with a `handleEvent` as accepted by `addEventListener`
    **Cons:** Verbose. Slight chance of a breaking change if objects with `handleEvent` and `options` properties are already passed to lit.

2. Pass an array:

    ```ts
    html`<div on-scroll=${[(e) => doSomething(e),  {passive: true}]}></div>`;
    ```

    **Pros:** Concise. Kind of like the argument list to `addEventListener`.
    **Cons:** Not obvious? Why is an array passed when a function is expected?

cc @sorvell @kevinpschaaf @azakus

**Comment by justinfagnani** [comment]
And while those are both ok syntaxes, they both those suffer from a problem a creating fresh objects each render and forcing lit-extended to deep compare the options object.

We'll probably have to recommend a pattern of storing the configuration outside of the template, like:

```ts
class MyElement extends LitElement {
  _scrollListener = {
    handleEvent: (e) => this.scroll(e),
    options: {passive: true},
  };

  _render() {
    return html`<div on-scroll=${this._scrollListener}></div>`;
  }
}
```

In this case I think the object form is much easier to read.

**Comment by bgotink** [comment]
Another option would be to pass these options in the attribute name. Possible syntaxes:

```js
html`<div on-scroll:passive=${(e) . => doSomething(e)}></div>`;
html`<div on-scroll.passive=${(e) . => doSomething(e)}></div>`;

// These throw errors when adding them using setAttribute, but they parse fine ¯\_(ツ)_/¯
html`<div on-scroll|passive=${(e) . => doSomething(e)}></div>`;
html`<div on-scroll(passive)=${(e) . => doSomething(e)}></div>`;
```

__Pros__:

- declarative
- no issues with object/array
- options cannot change, which is a good thing: if the options change we need to remove the listener with the old options and add it with the new options

__Cons__: 

- it limits the event names consumers can use (e.g. if we go for `on-scroll:passive` a consumer can never use a custom event called `<whatever>:passive`)
- only works for boolean flags, so will this work forever?
- complicates parsing of event listener attributes

**Comment by zeroliu** [comment]
Ping! Any updates?
