### ISSUE TITLE
[lit-next] Distinguish `property` and `internalProperty` better

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#1451]
## Description
Other popular frameworks have a concept of `props` which are passed in from the outside and should be treated as immutable and `state` which is set internally and is mutable. 

In Lit, we have `property` which is passed in and `internalProperty` which is managed internally. It probably makes sense to change `internalProperty` to `state` to leverage user knowledge of other frameworks.

When marked as a `property` a value may be both a "prop" and "state." This should be clearly indicated in some way.

Users have also reported issues with setting up default values that mutate inside the element. In DOM there are analogs with input.value which is set via an attribute (which does not change) and a property which does.

## Acceptance criteria
Decide on the right design, implement, and document changes.

**Comment by lithtml-dev** [comment]
Hello,

I reccomend you to check out the code more better. This code isn't to our standards. Please include code. We are not responsible for this. You can increase the input value working range by improving your code

Kind regards,

Sebastiaan

**Comment by sorvell** [comment]
Some possible ideas in addition to renaming `@internalProperty` to `@state`, we may also want to consider the following. Most of this would be for documentation and linting behavior only.

* In addition to `@state`, adding `state: true|false` to property options for JS users. (This sets `attribute` to `false`)
* Adding `input: true|false` and `@input` to indicate a property that should only set by users of the element and not mutated by it. LitPlugin would warn if you set this property in your element.
* Adding `output: true|false` and `@output` which creates a readonly property only with a getter and no setter (and `attribute` to `false`) and generates a `set<name>` function which (optionally?) generates an event with the property's changed value. Alternatively, `readonly` and `notifier` could be explicitly separate options perhaps in addition to the `output` shorthand.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/lit-html/pull/1485.
