### ISSUE TITLE
[docs] Document how to use bound functions in declarative event handlers

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#146]
Context: https://github.com/PolymerLabs/lit-html/issues/76

**Comment by richardanaya** [comment]
Agreed, I only found out by digging in the polymer meetup video

**Comment by QuinntyneBrown** [comment]
Are you able to use bound functions outside of Polymer? Doesn't seem to work for me.

**Comment by silenceisgolden** [comment]
I believe this discussion is relevant https://github.com/tc39/proposal-class-fields/issues/80

**Comment by QuinntyneBrown** [comment]
Thanks! Am I correct in assuming that it's not suppose work at the moment without another poly fill for the future spec coming in the future?

**Comment by silenceisgolden** [comment]
@QuinntyneBrown I do not believe any browsers have native support for this feature, but I would love to be wrong about that sooner rather than later.

**Comment by justinfagnani** [comment]
lit-extended and classes support this now:

```js
import {html} from 'lit-html/lib/lit-extended.js';

class MyElement extends LitElement {
  constructor() {
    super();
    this._handleClick = (e) => { console.log('click'); };
  }

  render() {
    return html`<button on-click=${this._handleClick}>Click Me</button>`;
  }
}
```

It's only just slightly nicer with class fields:

```js
import {html} from 'lit-html/lib/lit-extended.js';

class MyElement extends LitElement {
  _handleClick = (e) => { console.log('click'); };

  render() {
    return html`<button on-click=${this._handleClick}>Click Me</button>`;
  }
}
```

**Comment by LarsDenBakker** [comment]
I personally always use this:

```
import {html} from 'lit-html/lib/lit-extended.js';

class MyElement extends LitElement {
  constructor() {
    super();

    this._handleClick = this._handleClick.bind(this);
  }

  render() {
    return html`<button on-click=${this._handleClick}>Click Me</button>`;
  }

  _handleClick(e) {
    console.log('click');
  }
}
```

I like it, because it keeps the idiomatic method syntax and you declare explicitly what you want. Are there any downsides I'm overlooking?

**Comment by justinfagnani** [comment]
Arrow functions, because they _can't_ be bound can be a little faster than regular functions. Also you have to pay for the `bind()` cost, even though that's been reduced lately.

**Comment by QuinntyneBrown** [comment]
@justinfagnani, is what you described suppose to work with just  lit-html, lit-extended with the native latest version of Chrome? No other libs or dependencies?

**Comment by QuinntyneBrown** [comment]
@justinfagnani Trying it out in this repo and it doesn't seem to work?  https://github.com/QuinntyneBrown/simple-custom-element/blob/master/src/simple.component.ts

**Comment by justinfagnani** [comment]
@QuinntyneBrown you need lit-extended for property and event bindings.

What's happening in your sample?

**Comment by justinfagnani** [comment]
We document this in LitElement docs now.
