### ISSUE TITLE
Optimize for NodeParts that are the only child

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#147]
They don't need start and end nodes.

**Comment by richardanaya** [comment]
Great idea

**Comment by richardanaya** [comment]
Just was researching this issue and noticed @justinfagnani 

https://github.com/PolymerLabs/lit-html/blob/master/src/lit-html.ts#L270

**Comment by justinfagnani** [comment]
We can elide the end node in lit-html 2.0
