### ISSUE TITLE
[lit-html] Directive imports not working with lit-html@2.0.0-pre.5

### ISSUE THREAD

**Issue by heikkilamarko** [Polymer/lit-html#1508]
I installed `lit-html@2.0.0-pre.5`. 

When I run `npm start`, I get the following error:

```
[snowpack] Package "lit-html" exists but package.json "exports" does not include entry for "./directives/class-map".
```

I am using Snowpack as the build tool.

Everything works okay with `lit-html@2.0.0-pre.3`.

**Comment by vegarringdal** [comment]
maybe the entire build of 4 & 5 is broken

When I set it to 4 or 5 it wont event try to run the code.
Sample
https://codesandbox.io/s/lit-html-forked-r7cf9

**Comment by heikkilamarko** [comment]
I found the cause of the problem. Adding `.js` fixes the problem.

This throws the error:
```js
import { classMap } from 'lit-html/directives/class-map';
```

This works:
```js
import { classMap } from 'lit-html/directives/class-map.js';
```
