### ISSUE TITLE
Docs: Add directives to API page (cache, repeat, etc)

### ISSUE THREAD

**Issue by matthias-ccri** [Polymer/lit-html#1515]
The built-in directives have no presence on the [API section](https://lit-html.polymer-project.org/api/index.html) of the web site.

A few directives are mentioned in the [Writing templates](https://lit-html.polymer-project.org/guide/writing-templates#caching-template-results:-the-cache-directive) page of the Guide: `repeat`, `cache`. In various talks, others are mentioned.

To see the directives, I have to browse the repo source:
https://github.com/Polymer/lit-html/tree/bd2a3ef3dfa6f65149d218f6c7f4a3c1fc6f8743/src/directives

The directives should be listed in a single convenient place.

Thanks

**Comment by arthurevans** [comment]
I think what you're looking for is https://lit-html.polymer-project.org/guide/template-reference#built-in-directives

We're working on making that higher-profile in the next major release, making it a separate doc in the left nav.

They _should_ be in the API reference. That's been blocked by issues with getting Typedoc to recognize directives.

**Comment by justinfagnani** [comment]
We've done this for the upcoming 2.0 site, and for 1.x the TypeDoc output was too bad to publish.
