### ISSUE TITLE
[lit-next] Refine controller/directive API

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#1516]
## Description
- rename `connnected/disconnectedCallback` to `connected/disconnected` for both controllers and directives.
- add interface for a `ControllerHost` so that Controllers can accept a host argument that is typed to `ControllerHost`. This interface implements `addController` and `requestUpdate`.
- consider making a hooks example for React that uses controllers to validate the design

## Acceptance criteria
PR landed with changes.

**Comment by kevinpschaaf** [comment]
@justinfagnani Can you confirm that https://github.com/Polymer/lit-html/pull/1522 resolves this issue and close it if so? Thanks!

**Comment by justinfagnani** [comment]
#1522 addresses everything except a React Hooks adapter. That should be in a separate issue.
