### ISSUE TITLE
Release 0.8.0 Discussion

### ISSUE THREAD

**Issue by richardanaya** [Polymer/lit-html#154]
I know there's some pretty major bugfixes in 0.8.0 and wanted to start an issue related to it's release. A suggestion is perhaps some sort of Medium article per major release might be a nice thing to start doing? I'd be very interested in understanding what the whole async streaming stuff is. Also interested in performance increases, and any sort of breaking changes.

**Comment by QuinntyneBrown** [comment]
When is the next release? @justinfagnani

**Comment by QuinntyneBrown** [comment]
ping @justinfagnani

**Comment by justinfagnani** [comment]
Update: 0.8.0 is shaping up with IE11 support, async iterables, and a change in directive behavior. I want to run through some tests and benchmarks and get IE11 setup on Travis before releasing.
