### ISSUE TITLE
How to automatically redraw input values after user intervention?

### ISSUE THREAD

**Issue by masaoliou** [Polymer/lit-html#1560]
# Description
_Input_ element ignores model changes and always displays the value entered by user.

# Steps to Reproduce
1. Use keyboard or mouse to change the values of the two _input_ elements.
2. Click button to change model.
3. Notice that these _input_ elements do not redraw model's new values. They keep displaying the values you entered although their _value_ attributes do reflect model's new values.

On the other hand, these _input_ elements redraw model's new values if you **never manually enter data** for them.

## code

```ts
import {html,LitElement} from 'lit-element';

class MyElement extends LitElement {
	render() {
		return html`
			<input type="checkbox" ?checked="${this.checkBox}">${this.checkBox}
			<br>
			<input type="text" value="${this.myString}">${this.myString}
			<br>
			<button @click="${this.changeModel}">Change Model</button>
		`;
	}
	static get properties(){
		return {
			checkBox:{Boolean}
			,myString:{String}
		};
	}
	constructor(){
		super();
		this.checkBox=false;
		this.myString='A';
		this.counter=1;
	}
	changeModel(){
		this.checkBox=!this.checkBox;
		this.myString=++this.counter;
	}
}
```

## Browsers Affected

- [ X] Opera
- [ X] Firefox

**Comment by yorrd** [comment]
check out the `live` directive. Also, I believe that value is a property, try `.value=...`

**Comment by masaoliou** [comment]
> check out the `live` directive. Also, I believe that value is a property, try `.value=...`

Binding values with properties in stead of attributes as you suggested appears to have automated the update to _input_ without resorting to _live_ directive.

I need to test more.

**Comment by masaoliou** [comment]
Below are my findings:

1. element _input_
  
  - Use notation `.value="${this.myValue}"` instead of `value="${this.myValue}"`
  - Use notation `.checked="${this.myValue}"` instead of `?checked="${this.myValue}"`

2. element _mwc-switch_

  - Use notation `.checked="${live(this.myValue)}"`
  - Do not use notations `?checked="${this.myValue}"` or `.checked="${this.myValue}"`
