### ISSUE TITLE
[lit-html] Regression: event bindings right before self-closing tag ends are broken

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1594]
Example

```ts
html`<input @click=${listener}/>`
```

We don't support this well for attribute/property bindings - they will include the `"/"` in the value - but this does work for events in 1.x. If we fix this binding position in general it would be a nice improvement.

**Comment by csvn** [comment]
#1595 has been merged. Can this issue be closed @justinfagnani?
