### ISSUE TITLE
Best way to pass asnyc function property in html

### ISSUE THREAD

**Issue by MichaelPeter** [Polymer/lit-html#1606]
I wanted to create my own autocomplete component and it has a function parameter where the items can be searched

Now I wanted to do the following:

`<my-autocomplete optionsasnyc='${async function(e) { await new Promise(xxx); return e.searchtext; } } '><mw-autocomplete>`

Now I defined the optionsasnyc parameter as type object and attribute=false, but the property always stays null

What is the best way to do this? Or is it not possible to define a (asnyc) function parameter in html? Do I need to do it in Javascript?

**Comment by justinfagnani** [comment]
@MichaelPeter to set properties in lit-html you need to prefx the "attribute" name with a `.`: https://lit-html.polymer-project.org/guide/writing-templates#bind-to-properties

Property names are case-sensitive, so make sure that the property is really `optionsasync`, not `optionsAsync`. (you also had a mispelling in the name above, so check that).

```ts
html`<my-autocomplete .optionsasync='${async function(e) { await new Promise(xxx); return e.searchtext; } } '><mw-autocomplete>`
```

**Comment by MichaelPeter** [comment]
@justinfagnani: thank you very much for your answer, the missing `'.'` was what cost me half a day, now it works :) The uppercase was because I typed it on the phone after it kept me awake after work ;).

**Comment by justinfagnani** [comment]
@MichaelPeter I'm glad that helped, but sorry you lost half a day.

I'd recommend using the `lit-plugin` extension if you use VS Code: https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin or the `lit-analyzer` tool: https://www.npmjs.com/package/lit-analyzer

They can help catch invalid bindings.

**Comment by MichaelPeter** [comment]
Will try lit analyzer since I use normal visual studio, thanks!
