### ISSUE TITLE
Add exports to package.json for lit-html & lit-element

### ISSUE THREAD

**Issue by daKmoR** [Polymer/lit-html#1620]
## Description

Generate an import map can be automated by combining all exports map in your dependency tree... however, this means that each dependent will need to define an export map.

lit-html and lit-element currently do not have an "export" property in their package.json.

Would you be willing to add it? or accept a merge request which adds them?

## Acceptance criteria
- lit-html & lit-element have an "export" property in their `package.json`

**Comment by justinfagnani** [comment]
We have exports define in 2.0 now.
