### ISSUE TITLE
[lit-next] cache directive breaks when there are nested cache directives 

### ISSUE THREAD

**Issue by Avocher** [Polymer/lit-html#1632]
# Description
I noticed after upgrading to lit `^2.0.0-pre.1` that the cache directive breaks if there are nested cache directives. This worked fine in lit-html `1.3.0`.

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-next-ic1xz1?file=src/index.js

## Actual Results
`Uncaught (in promise) TypeError: Cannot read property 'setConnected' of undefined`

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

**Comment by kevinpschaaf** [comment]
Thank you for the bug report! Confirmed the issue, [fix](https://github.com/Polymer/lit-html/pull/1651) should be included in the next pre-release.

**Comment by kevinpschaaf** [comment]
Closing, fixed in https://github.com/Polymer/lit-html/pull/1651, will be included in next release.
