### ISSUE TITLE
[lit-element] [lit-next] createRenderRoot() in inheritance chain

### ISSUE THREAD

**Issue by dflorey** [Polymer/lit-html#1645]
I have a bunch of components inheriting from a base class that extends LitElement, but overrides createRenderRoot() to return this (no shadow dom).
Some of the components should have a shadow dom, so I'm then copy/pasting the original createRenderRoot() method to get back shadow dom+adopt the styles.
For this usecase it would be nice to be able to have a way to set this behaviour via static property similar to shadowRootOptions (or set shadowRootOptions to null to return "this" instead of shadow dom)

**Comment by sorvell** [comment]
We're not inclined to promote not using Shadow DOM, but you can feel free to make your own base class that does something like this:

```
createRenderRoot() {
  return this.constructor.shadowRootOptions === null ? this : super.createRenderRoot();
}
```

Can you explain why you need to avoid using Shadow DOM for some elements? Is it related to styling?

**Comment by dflorey** [comment]
Yes, I'm using something along those lines in my base class now and it works nicely.
I've started using shadow dom for all of my components (design system with focus on form fields), but I've been running into so many issues (autofill not working properly, tab key to go to next form field not working on mobile, validation issues, chrome vox not working etc.) that I had to revert everything and start from scratch without using shadow dom.
I'm very happy that everything just works without workarounds and to have all the great css selectors back to target nested tags across component boundaries. The only feature I'm really missing is slots :-(

**Comment by sorvell** [comment]
Ok, seems like this issue is resolved then. If you have any additional concerns, feel free to re-open with more information.

The issues you're having with using Shadow DOM are unfortunate and areas in which the platform needs to evolve and make better. I encourage you to file browser bugs on Chrome and especially on Safari (which does not implement `delegatesFocus`).
