### ISSUE TITLE
[lit-html] `PartInfo`s are not assigned properties from getters in their respective `Part`.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/lit-html#1697]
# Description
`AttributePartInfo`'s `tagName` property is always `undefined`.

`PartInfo` objects are created here, by spreading the `Part`:

https://github.com/Polymer/lit-html/blob/be81dc75c23bf40604d175ea0420487d40061ce7/packages/lit-html/src/lit-html.ts#L694-L699

This prevents properties of the `Part` that are retrieved through getters in the prototype chain from being assigned because the spread operator only copies an object's enumerable own properties.

# lit-html version

`2.0.0-pre.5`

# Steps to Reproduce

1. Write this code

```ts
import { html, render } from 'lit-html';
import { Directive, directive, PartType } from 'lit-html/directive.js';

class ExampleDirective extends Directive {
  constructor(partInfo) {
    super(partInfo);

    if (partInfo.type !== PartType.ATTRIBUTE) throw new Error();

    if (typeof partInfo.tagName !== 'string') {
      throw new Error(`partInfo.tagName: ${partInfo.tagName}`);
    }
  }
}

const example = directive(ExampleDirective);

const myTemplate = name =>
  html`
    <h1 some-attr="${example()}">Hello ${name}!</h1>
  `;

render(myTemplate('lit-html'), document.body);
```

2. See this output...

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-next-8x5yle?file=src%2Findex.js

## Expected Results
`AttributePartInfo`'s `tagName` property should be a string.

## Actual Results
`AttributePartInfo`'s `tagName` is `undefined`.

**Comment by justinfagnani** [comment]
Fixed in #1703
