### ISSUE TITLE
[lit-element] Styles in `styles` getter not transformed by ShadyCSS apply shim before insertion into `adoptedStyleSheets`

### ISSUE THREAD

**Issue by bicknellr** [Polymer/lit-html#1740]
Related: #1739

# Description
Styles added to a component using the static `styles` property are not transformed by the Shady CSS apply shim before being inserted into `adoptedStyleSheets`.

# Lit versions

lit-element: 3.0.0-pre.4 lit-html: 2.0.0-pre.7

# Steps to Reproduce

1. Write this code...

```html
<!DOCTYPE html>
<body>
<outer-element></outer-element>

<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.5.0/webcomponents-bundle.js"></script>
<script src="https://unpkg.com/@webcomponents/shadycss@1.10.2/apply-shim.min.js"></script>
<script type="module">
import 'https://unpkg.com/lit@2.0.0-pre.2/polyfill-support.js?module';
import {LitElement, css, html, render} from 'https://unpkg.com/lit@2.0.0-pre.2?module';

customElements.define('outer-element', class extends LitElement {
  static get styles() {
    return css`
      inner-element {
        --some-mixin: {
          color: blue;
        };
      }
    `;
  }

  render() {
    return html`
      outer element
      <inner-element></inner-element>
    `;
  }
});

customElements.define('inner-element', class extends LitElement {
  static get styles() {
    return css`
      div {
        @apply --some-mixin;
      }
    `;
  }

  render() {
    return html`
      <div>inner element</div>
    `;
  }
});

</script>
</body>
```

2. See this output...

## Live Reproduction Link
https://jsbin.com/kidutigeva/edit?html,output

## Expected Results
The CSS mixin definition and application (not natively supported syntax) should be flattened to custom properties before being inserted into `adoptedStyleSheets`.

## Actual Results
The CSS mixin definition is inserted into `adoptedStyleSheets` before being edited by the Shady CSS apply shim.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

**Comment by sorvell** [comment]
This is by design. The `@apply` behavior is not supported in `static styles`. This is also not supported in LitElement 2.x.
