### ISSUE TITLE
Update GitHub description

### ISSUE THREAD

**Issue by abdonrd** [Polymer/lit-html#1751]
Right now the GitHub description is:

>An efficient, expressive, extensible HTML templating library for JavaScript.

We can update it as the new Readme.

<img width="528" alt="Screenshot 2021-04-15 at 09 06 55" src="https://user-images.githubusercontent.com/1007051/114828240-f63b4980-9dc9-11eb-866b-e17b5b5ed3d2.png">

**Comment by kevinpschaaf** [comment]
Thanks for pointing out, I updated it.

**Comment by abdonrd** [comment]
@kevinpschaaf another minor thing... To get cleaner GitHub sidebar UI:

| From      | To |
| -------- | -- |
| <img width="1389" alt="Screenshot 2021-04-15 at 10 24 59" src="https://user-images.githubusercontent.com/1007051/114838351-eb39e680-9dd4-11eb-91f0-48b58f1d74ed.png"> | <img width="1389" alt="Screenshot 2021-04-15 at 10 25 28" src="https://user-images.githubusercontent.com/1007051/114838361-ed9c4080-9dd4-11eb-8714-cc263333c9aa.png"> |

As you are not using it, you can also uncheck the `Packages` and `Environments`:

<img width="462" alt="Screenshot 2021-04-15 at 10 18 45" src="https://user-images.githubusercontent.com/1007051/114838077-a2822d80-9dd4-11eb-892c-c7b92158c80e.png">
