### ISSUE TITLE
Render to a stream

### ISSUE THREAD

**Issue by ithinkihaveacat** [Polymer/lit-html#187]
For demos, prototyping and SSR use-cases, it would be useful if `lit-html` supported rendering to a string. For example:

```ts
import {html, render} from 'lit-html';

const helloTemplate = (name) => html`<div>Hello ${name}!</div>`;

// This returns <div>Hello Steve!</div>
render(helloTemplate('Steve'));
```

**Comment by jmas** [comment]
I guess,  for SSR we need DOM API support on server side. It can be done with [JSDOM](https://github.com/tmpvar/jsdom), but I do not sure.

**Comment by jridgewell** [comment]
@justinfagnani and I spoke a bit about this. To summarize (I hope I'm remembering correctly):

- SSR will probably be handled by another implementation of `html` and `render`.
  - (my thoughts): Requiring DOM access on the server is just dumb. We have a abstract templating system, there's no reason to require it.
  - This would probably hamper re-rendering on the server, but I'm not sure how many would actually do that.
- As for rehydrating on the client, we'll probably need to leave Comment nodes so we know where Parts start and end. (Mainly because of the multi-node support)
  - Might even need a `hydrate` function, that'll attached the cached values that were used to render on the server to the DOM nodes on the client.
    - This wouldn't validate or render, just setup the cached logic so `render` doesn't blow away the nodes.

In all, SSR doesn't seem super difficult. They're _just_ tagged template literals, we might even just let it stringify like a normal template literal.

**Comment by justinfagnani** [comment]
@jridgewell good summary. It's ever-slightly more complicated than using a no-op template tag on the server though, because we want to offer the same XSS protection. I think we'd want to do the same HTML-string generation, then run through parse5, then do value substitution. It's a perf cost, but ensures parsing behavior and escaping.

**Comment by ithinkihaveacat** [comment]
The `repeat()` and `until()` directives would also need to made available too, right?

It would also be neat if the goal of "Efficient updates of previously rendered DOM" was achieved if the initial rendering occurred server-side. (This may require embedding some of the data structures needed into the server-side rendered string--perhaps something similar to what glimmer [describes as rehydration](https://www.emberjs.com/blog/2017/10/10/glimmer-progress-report.html#toc_rehydration)--or generating client-side JS at template compilation time.)

**Comment by js-choi** [comment]
What also would be nice is if lit-html’s server-side rendering someday also supported asynchronous/streaming rendering, like how [Marko](https://github.com/raptorjs/marko) already does. Not only would you be able to render templates into single, concatenated, contiguous-memory strings. You would also be able to render them into an [async iterable](https://github.com/tc39/proposal-async-iteration) (or, eventually, perhaps a [WHATWG readable stream](https://streams.spec.whatwg.org)) that yields strings of HTML chunks. This is not urgently needed, but it's something to keep in mind from the beginning while designing lit-html’s SSR.

See also:

* [The Lost Art of HTML Rendering](http://blog.codinghorror.com/the-lost-art-of-progressive-html-rendering/)
* [Async Fragments: Rediscovering Progressive HTML Rendering with Marko](http://www.ebaytechblog.com/2014/12/08/async-fragments-rediscovering-progressive-html-rendering-with-marko/)
* [Best Practices for Speeding Up Your Web Site: Flush](https://developer.yahoo.com/performance/rules.html#flush)
* [Progressive rendering via multiple flushes](http://www.phpied.com/progressive-rendering-via-multiple-flushes/)
* [FaceBook BigPipe](https://www.facebook.com/notes/facebook-engineering/bigpipe-pipelining-web-pages-for-high-performance/389414033919)

**Comment by trygve-lie** [comment]
I might be interested in pitching in on developing SSR if possible. What would an appropiate starting approach be in terms of where I put the code etc?

**Comment by kirill3333** [comment]
also we need renderToString for unit testing

**Comment by gfortaine** [comment]
[shuhei/pelo: ⚡️ Lightning fast server-side rendering with tagged template literals](https://github.com/shuhei/pelo)

**Comment by gfortaine** [comment]
[motss/lit-ntml: Inspired by lit-html but for Node.js](https://github.com/motss/lit-ntml)

**Comment by popeindustries** [comment]
There is now an (unofficial) `lit-html-server` project being worked on and discussed in #461

**Comment by justinfagnani** [comment]
Working on this now, but I'm doing it as rendering to a stream, rather than a string.

**Comment by Robula** [comment]
We use Puppeteer for rendering HTML out as PNGs, most libraries support SSR but add markers for rehydration on the client which doesn't work for us because we don't want to load any clientside code or have any reactivity which makes `renderToString` is essential.

**Comment by majo44** [comment]
Any progress, plans ?

**Comment by justinfagnani** [comment]
I have some rather rough experimental code I can into a repo today.

**Comment by frank-dspeed** [comment]
hmmm when i read render to stream i get headache we got already the stream implamentation with lit-html server in reallife tests that is not enought. 

And the Stream Implamentation does add a lot of unneeded code.. but ok go for it but i think we could then simply copy paste the relevant parts from lit-html-server

**Comment by tstewart-klaudhaus** [comment]
@justinfagnani @popeindustries Hi to both the `lit-html` team and the creator of `lit-html-server`. Thank you both for these wonderful projects, they are great accomplishments

I wanted to chime in to say I've been working on a means of making isomorphic apps that can use either implementation, as well as including a state management pattern for interactive front end apps and a few other features, called `lit-app`. It's published now on NPM, I'd appreciate any feedback.

https://github.com/klaudhaus/lit-app

IMHO it would make sense to keep the implementations (DOM / static) separate - that way you avoid unnecessary code inclusion or complication. It keeps to the Unix principal of small tools that do one thing well (which I try to follow too, the state management is a separate package called `lit-up` that can be used independently of `lit-app`).

**Comment by justinfagnani** [comment]
This is implemented in labs/ssr. It's still experimental, but we'll have docs soon and should track smaller issues now.

**Comment by tstewart-klaudhaus** [comment]
Hi Justin, do you have a link to labs/ssr for those of us working in this space to get an idea of approach / roadmap / direction? Thanks.

**Comment by justinfagnani** [comment]
@tstewart-klaudhaus https://github.com/Polymer/lit-html/tree/main/packages/labs/ssr
