### ISSUE TITLE
AttributePart and PropertyPart need previous value optimizations

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#199]
The dirty checking that NodePart does for primitive values should be ported to AttributePart and PropertyPart.

**Comment by QuinntyneBrown** [comment]
@justinfagnani When do you think you will be releasing a new version? 0.7.2? or 8?

**Comment by justinfagnani** [comment]
@QuinntyneBrown please do not ask the same question on several, unrelated issues.

**Comment by kenchris** [comment]
Something along these lines? https://gist.github.com/kenchris/745f22b7451d3fe56e986965f2cc6d9b

I removed my previous dirty check in lit-html-element and used this instead and it results in a similar speed up:

![screenshot from 2017-12-08 15-09-08](https://user-images.githubusercontent.com/1101339/33769260-c4782cc0-dc29-11e7-937f-eecfacd8ba43.png)

If the approach is correct and I understood the code correctly, then I can turn this into a patch
