### ISSUE TITLE
Incorrect template-literal parsing when interpolation is followed by element with event handler

### ISSUE THREAD

**Issue by js-choi** [Polymer/lit-html#206]
The following script, when executed in a document with an element whose ID is `app`, demonstrates what is probably a bug. It should result in a `div` element, containing `<p>A</p>` followed by `<button>Button</button>`. The `button` element, when clicked, should log a click event to the console.

Instead, the `button` element is `<button on-click="<!--_-lit-html-_--">>Button</button>`. Its text is “>Button” instead of “Button”, its `onclick` property has not been set, and an `on-click` attribute has instead been set to `<!--_-lit-html-_--`.

    import { html, render } from 'https://unpkg.com/lit-html@0.7.1/lib/lit-extended.js'

    const renderingTarget =
      document.getElementById('app')

    render(f(), renderingTarget)

    function f () {
      return html`
        <div>
          ${ g() }
          <button on-click=${ event => console.log(event) }>Button</button>
        </div>
      `
    }

    function g () {
      return html`
        <p>A</p>
      `
    }

This bug still occurs when core `lit-html.js` is used instead of `lit-extended`.

This bug does not occur if the wrapping `div` in `f`’s template literal is flattened such that `f` returns a fragment ``html ` ${ g() } <button …>…</button> ` `` instead.

The bug also does not occur if `${ g() }` is inlined such that `f` returns ``html ` <p>A</p> <button …>…</button> ` `` instead.

The bug has been reproduced with lit-html 0.7.1, in Safari Technology Preview Release 44, Firefox 57.0.1, and Chrome 62.0.3202.94.

**Comment by bgotink** [comment]
I can reproduce this in Chrome for version 0.7.1. Everything works fine when using the code on master though, so it looks like this is already fixed.

**Comment by js-choi** [comment]
Confirmed that this issue is fixed in master. I’ll close this when the next version is published.

**Comment by js-choi** [comment]
lit-html 0.8.0 has been released. This bug is fixed.
