### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#210]
I'd really like to start using lit-html. I don't mind it being rough around the edges, and breaking changes coming in the future, but IE11 support is unfortunately a deal breaker for my company. 

I'd like to contribute, but I see there have already been a few attempts at becoming IE11 compatible. Are we close to a solution? Is there an overview of the remaining issues?

**Comment by bgotink** [comment]
I'm not sure the list is complete, but:

- There's an issue with the cloning process (see #201 and proposed fix #202)
- There's an issue with `<tr>`, `<th>` or `<td>` elements as root element in the template because of an issue in the template polyfill (see webcomponents/template#3)
- The tests for lit-extended and some directives don't import the necessary polyfills for IE yet, so the tests fail
- A couple of tests fail because IE sorts attributes differently from other browsers. This is a bug in the tests, not the library.

**Comment by justinfagnani** [comment]
With #202 and #211 we're really close.

I think we might be able to fix the table problem because we're in control of generating the template contents - unlike the template polyfill we get to do things before the parser.

Before that I would be ok with skipping the table tests on IE and making sure we get tests passing to lock in our progress and make sure we don't regress.

**Comment by LarsDenBakker** [comment]
Is there anything that can be done here to help put?

**Comment by toddoh** [comment]
Any updates on this?

**Comment by smalluban** [comment]
There is yet another bug - it is not possible to set `style` attribute. IE11 prevents setting style attribute, which is not proper CSS text (list of CSS properties) and clears attribute placeholder, so template does not know that there was any expression.

```javascript
const template = value => html`<div style="{value}">Sample text</div>`;
render(template('color: red'), ...);
```

Above example in IE11 produces black text.

The second thing is npm package. It is not properly distributed. The compiled version of the project contains code, which is not supported in IE11, for example, arrow functions.

**Comment by seaneking** [comment]
@smalluban just re npm package, pretty sure it's only shipped as an ES module, the assumption being that you'd bundle and transpile it youself for legacy browsers

**Comment by smalluban** [comment]
@seaneking I think it is not a good idea. `module` or `jsnext:main` should be used for esm version of the library. Parcel and common Webpack configuration of babel usually omits `node_modules` and does not transpile external packages. With current solution, users have to change this only for one dependency.

**Comment by seaneking** [comment]
Yep agree, but remember lit-html is still pre-release. Imagine the team will include UMD bundles alongside ES modules for 1.0. Because yeah as you say, it's almost universal to exclude node_modules from transpilation.

**Comment by motss** [comment]
Is this resolved?

**Comment by MartinsThiago** [comment]
I am using it on IE11 with no problems

**Comment by smalluban** [comment]
The problem with `style` attribute can be solved only in one and unfortunately also dirty way. Attribute has to prefixed (or changed in another way) before template element is initialised, and after that the prefix should be removed and expression should be set to style attribute. 

Few days ago I released 1.0 version of my library for creating web components in functional way. It's template engine is inspired by `lit-html`, but implementation is different. However, I could solve all IE11 problems, and library's tests pass in IE11. 

Here you have place where the problem with style attribute is solved: https://github.com/hybridsjs/hybrids/blob/9a2b5c2b98d1978bda5f15dedf3d860765f4710a/src/html/template.js#L221

**Comment by justinfagnani** [comment]
Aside from some specific issues like `style` attribute, this issue is fixed and we're running all tests on IE11.

**Comment by bashmish** [comment]
@justinfagnani shall we remove this from this know issues https://github.com/Polymer/lit-element#known-issues ?

**Comment by jpierson** [comment]
I think I may be running into what @smalluban described [above](https://github.com/Polymer/lit-html/issues/210#issuecomment-387360499) as I'm seeing lambda expressions in bundled .js file in IE11 which appear to be related to `lit-html`. Normally things are running through webpack but perhaps there is something we've overlooked with regard to how this library is either transpiled or not in our bundling process.

**Comment by LarsDenBakker** [comment]
Lit html is shipped uncompiled, as it should not make assumptions about the app's runtime environment. Webpack does not transpile node_modules by default so probably thats where it goes wrong.

**Comment by jpierson** [comment]
Oh this looks related to #339.

**Comment by jpierson** [comment]
Importing `@webcomponents/template` seems to have gotten me further but now I'm seeing an issue with this section of code. I'm unsure if this is related to the imported template definition or something else yet but the line `throw _iteratorError;` in the snippet below where it's failing for me right now when my template is rendered.

```javascript
        try {
            if (!_iteratorNormalCompletion && _iterator.return) {
                _iterator.return();
            }
        } finally {
            if (_didIteratorError) {
                throw _iteratorError;
            }
        }
```

**Comment by jpierson** [comment]
This last error I'm getting appears related to https://github.com/Polymer/lit-html/pull/229#issuecomment-356448243.
