### ISSUE TITLE
Interpolation not working

### ISSUE THREAD

**Issue by sjruby22** [Polymer/lit-html#221]
When I try to render an array of objects from an API call I am seeing some odd results in the interpolation.  The JSON resulting from the API call looks like:

```
   {
      "character":"A",
      "soundName":"clap",
      "idForClickEvent":"65",
      "audioSrc":"sounds/clap.wav"
   },
   {
      "character":"S",
      "soundName":"hihat",
      "idForClickEvent":"83",
      "audioSrc":"sounds/hihat.wav"
   }
```

The code called to render each object is:
```
const renderKeys = (keys) => html` 
        ${repeat(keys, 
            (k) => k.idForClickEvent,  
            (k) => html` ${key(k.character, k.soundName, k.idForClickEvent)} `
        )}`
```

The key template used in the repeat above:
```
function key(character, soundName, idForClickEvent, audioSrc) {
  return html`
    <div data-key=${idForClickEvent} class=key>
      <kbd>${character}</kbd>
      <span class=sound>${soundName}</span>
      <audio data-key=${idForClickEvent} src=${audioSrc}></audio>
    </div>
  `
```

The resulting HTML when I run the app is wrong, inspecting it in chrome shows:
![screen shot 2017-12-08 at 2 53 00 pm](https://user-images.githubusercontent.com/30550807/33782654-87efb4b4-dc27-11e7-84f4-e21fb394c7e7.png)

Splitting the audio tag into a separate template and composing that template and key template resolved the issue but I shouldn't need to split the template.

**Comment by justinfagnani** [comment]
Closing as stale. We've had a number of fixes to expression <-> part association, so this may not be a problem anymore. Please re-open if it's still a problem.
