### ISSUE TITLE
Type errors in `repeat.ts`

### ISSUE THREAD

**Issue by kaste** [Polymer/lit-html#224]
Don't know, I'm not really a TypeScripter, but Code squiggles

![image](https://user-images.githubusercontent.com/8558/33840909-8b28631c-de96-11e7-9349-18e635ffdd02.png)

**Comment by justinfagnani** [comment]
I'm not seeing these error, so may be a TS version problem.

**Comment by kaste** [comment]
I'm not seeing this on current master.  But you also did https://github.com/Polymer/lit-html/commit/1daaea774b9d9cf11f6dcd97bb63fab8e4f0422d

Anyway, closing.
