### ISSUE TITLE
Error in shady DOM when rendering a template with shadow root and slotted content

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#231]
On browsers that don't support native shadow dom (ex. firefox) there is an error when rendering a template that contains a shadow root with slotted content which is followed by a sub template.

I couldn't easily get a proper demo set up for firefox as it doesn't support native es modules. However forcing the shady dom polyfill on chrome also throws an error:

See: http://plnkr.co/edit/ofiGJR5T0ewsvPNrQluG?p=preview for a live example.

I created three template, two of which work and one that fails. It demonstrates that the template works fine if there is no slotted content:
```
    render(html`      
      <custom-element-with-shadowroot>
      </custom-element-with-shadowroot> 
      
      ${html`<h3>sub template</h3>`}
    `, document.body);
```

Or if the sub template precedes the shadow root:

```
    render(html`      
      ${html`<h3>sub template</h3>`}

      <custom-element-with-shadowroot>
        <h1>Slotted content</h1>
      </custom-element-with-shadowroot> 
    `, document.body);
```

But breaks when the sub template follows the shadow root:

```
    render(html`      
      <custom-element-with-shadowroot>
        <h1>Slotted content</h1>
      </custom-element-with-shadowroot> 
      
      ${html`<h3>sub template</h3>`}
    `, document.body);
```

**Comment by justinfagnani** [comment]
@sorvell I suspect that ShadyDOM is interfering with the post-instance-creation part finding, which requires the instance have the exact same structure as the template. Is there a way we can defer ShadyDOM's work, or ignore the nodes it adds?

**Comment by bgotink** [comment]
A possible fix would be doing

```ts
const fragment = this.template.element.content.cloneNode(true);
```

instead of 

```ts
const fragment = document.importNode(this.template.element.content, true);
```

in `TemplateInstance#_clone`.

This keeps the fragment inside the template's Document (without browsing context -> inert) until after the treewalker has done its job.

This works with or without ShadyDOM, with or without template polyfill. This requires no changes to the ShadyDOM library and no "are we using shady?" checks in lit-html.

Plunker with the change: http://plnkr.co/edit/vvFpugG92pItexqoN7Y0?p=preview.  
I've added an explicit `document.adoptNode(fragment)` in the return value of the `_clone` function in this plunker, but that's strictly speaking not needed as nodes are implicitly adopted when appending them to another node.

**Comment by daKmoR** [comment]
if that works... that would be awesome :) all the test are still green?

**Comment by justinfagnani** [comment]
Yeah, I hadn't realized that until recently clonedNodes are adopted and upgraded when they hit the new document, meaning that we don't have to use importNode. I wonder if that impacts performance at all.

@sorvell has also been working on specific ShadyDOM integration. Steve, is this relevant?

**Comment by bgotink** [comment]
@daKmoR Tests are green :)

@justinfagnani I'm unsure what the impact is ([jsperf](https://jsperf.com/template-importnode-vs-clonenode)). On Chrome cloneNode looks faster, on Firefox importNode seems faster and on Safari everything suddenly slows down after a couple of runs of the importNode test (hit re-run on safari and you'll see it's not that cloneNode is 97% slower than importNode, it's Safari that slows down 97%)

**Comment by justinfagnani** [comment]
Only marking low because there will be official ShadyDOM/CSS support, but I'm still interested in @bgotink's fix.

**Comment by sebs** [comment]
Awesome to stumble about exactly this problem and see a proposal open in a pull request. I wish I could be surprised.

**Comment by justinfagnani** [comment]
@sebs I hadn't revisited this since integrating ShadyCSS support a while back. @sorvell is working on even better support now, but we should make sure to have a test for this and I'll look at @bgotink 's #241 again.
