### ISSUE TITLE
Boolean attributes are rendered incorrectly

### ISSUE THREAD

**Issue by depeele** [Polymer/lit-html#236]
When using boolean attributes, [the spec](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes) states:
> [2.4.2. Boolean attributes](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes)
> A number of attributes are boolean attributes. The presence of a boolean attribute on an element 
> represents the true value, and the absence of the attribute represents the false value.
>
> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-
> insensitive match for the attribute’s canonical name, with no leading or trailing white space.

`lit-html` currently renders boolean attributes as `enabled="true"` or `enabled="false"` instead of using `enabled` when `true` and removing the attribute when `false`.

This could be resolved by updating `Attribute.setValue()` to something like:
```javascript
async setValue(values, startIndex) {
  const text = await this._interpolate(values, startIndex);
  if (text === 'false') {
    this.element.removeAttribute( this.name );

  } else if (text === 'true') {
    this.element.setAttribute(this.name, '');

  } else {
    this.element.setAttribute(this.name, text);

  }
```

**Comment by justinfagnani** [comment]
Deduping all boolean/conditional attribute issues to #56
