### ISSUE TITLE
Declarative property binding with kebab-case and camelCase

### ISSUE THREAD

**Issue by klebba** [Polymer/lit-html#240]
If I understand correctly, when using `lit-html`, a template with a binding like:

```
html`<my-element attr-foo="${bar}"></my-element>`
```

Will correspondingly call `myElement.setAttribute('attr-foo', bar);` when rendered.

If I use `lit-extended` the rendering behavior changes to `myElement['attr-foo'] = bar;` which uses the kebab-cased attribute name to set the property value. Because this probably isn't what you want with hyphenated attributes, you have two options:

```
html`<my-element attr-foo$="${bar}"></my-element>`
```

By using the `$=` notation I can inform `lit-extended` that I want it to use the standard `lit-html` behavior and call `myElement.setAttribute(...)` otherwise I must use the camelCased property name in my template:

```
html`<my-element attrFoo="${bar}"></my-element>`
```

Which will in turn call `myElement.attrFoo = bar;` when rendered. In Polymer, I can author my templates using kebab-cased attributes and they will be correspondingly mapped to the camelCased property names and rendering time (thus calling my property accessors). In my opinion this is more natural than what is currently supported by `lit-extended`. In other words, outside of the `lit-html` template context, I would import my custom element and author plain HTML like:

`<my-element attr-foo="bar value"></my-element>`

Then I would configure the `my-element` definition to observe changes to `attr-foo` and route them to the `attrFoo` property accessor. However I would never author:

`<my-element attrFoo="bar value"></my-element>`

Because this would not trigger the `attributeChanged` callback for `attr-foo`.

So my question is -- how can I go about extending `lit-extended` to behave the way Polymer does, and map `attr-foo` bindings to `attrFoo` property updates?

Thanks in advance!

**Comment by kenchris** [comment]
My lit-html-element allows attr-foo to map to whatever you define (as that is faster than doing auto mapping between case systems). In that case it works as an attribute which is backed by a property.

If you really don't want to use attributes and just properties, like mostly for internal use of custom elements within other custom elements, then I think staying with attrFoo casing makes the most sense.

**Comment by justinfagnani** [comment]
@klebba the kebab-case to camelCase mapping is cumbersome in my option, and leads to cases where you have to alternate letters and hyphens for runs of capital letters, or start a name with a hyphen, or use double hyphens to represent a single one in the property name. Having case-sensitive property names is just much easier. lit-extended templates are a little Polymer-like, in that if some syntax is needed it'll likely borrow from Polymer, but in this case syntax isn't needed.
