### ISSUE TITLE
Repeat slow when removing elements

### ISSUE THREAD

**Issue by NeoLegends** [Polymer/lit-html#242]
Hey!

We're using the repeat directive (from master) for fast list renderings, but we noticed it's quite slow when elements are removed in the middle of the list. This is likely because a the removal of an item in the middle changes the index of the following elements which triggers their reparenting while in reality, the repeat directive would only need to remove the dom node corresponding to the removed element.

https://github.com/PolymerLabs/lit-html/blob/5742a9e5e6ae74ee91b0421bca92d90f3e2b0601/src/lib/repeat.ts#L78-L86

Reorderings work extremely well though, so I wonder if this behavior can be improved.

**Comment by NeoLegends** [comment]
Seems like changing item indices from bottom to top (like moving a bottom item up) can be done very quickly, while moving items from top to bottom, or removing items (which unfortunately falls into this category as the removed item is moved to the end of the list before its removal) takes lots of iterations.

**Comment by justinfagnani** [comment]
Thanks for the diagnosis. This indeed fits the relatively naive in-order processing that `repeat()` does. We can port over the array-splice algorithm from Polymer, or one of a number of

**Comment by justinfagnani** [comment]
Opps, accidentally closed with some key combo.

**Comment by kenchris** [comment]
Something like this maybe: https://github.com/WebReflection/majinbuu

**Comment by kenchris** [comment]
So checking out the Polymer array-splice algorithm, then that is basically doing the same (also levenshtein) with the difference that it calculates substitutions as costing 2 operations

> The one change is that "updates" are treated as two edits - not one. With Array splices, an update is really a delete followed by an add. By retaining this, we optimize for "keeping" the maximum array items in the original array.

Which makes a lot of sense.

**Comment by justinfagnani** [comment]
I'd rather not have links into that user's code from here. I don't need the drama, whining, and accusations of stealing. Lots and lots of people have been doing Levenshtein edit-distance array mutation calculators for a long time.

**Comment by kenchris** [comment]
I did a tab at this in https://github.com/Polymer/lit-html/pull/260 but using the array splice algorithm makes it hard / impossible to make it work with iterables (at least in the sense of streams) as we need to compare the keys up front using Levenshtein.

**Comment by NeoLegends** [comment]
Something I forgot to mention: using naïve Array.map inside the interpolation instead of the repeat directive yields kinda better results for us. Removals in the middle of large lists work better, but the overall performance seems worse (as expected).

**Comment by vogloblinsky** [comment]
I can confirm with numbers that it is very slow ;)

![benchmark_delete](https://user-images.githubusercontent.com/2841805/36701418-9e5e6720-1b53-11e8-872f-34adc546aa44.png)

Extracted from this recent benchmark : https://github.com/vogloblinsky/web-components-benchmark

**Comment by kenchris** [comment]
BTW are you deleting one by one (doesn't need to be fast) or multiple at the same time?

**Comment by vogloblinsky** [comment]
I delete 50 items one by one. I start the telemetry before starting the delete sequence, and stop it after.
Same stuff for all the implementations.

**Comment by kenchris** [comment]
If you delete one by one, then performance might depend on how the UI is updated, like whether it is batched or not... Like if you delete all 50 elements in one iteration of requestAnimationFrame or just one per iteration

**Comment by kenchris** [comment]
That is actually a bad benchmark, because if the user deleted manually one by one, that would render super fast so the user never saw any lag. But if the user selected every second element and click remove, that should be just as fast and would be a much better benchmark

**Comment by kenchris** [comment]
Your test just tests how the rendering is batched. If you schedule 50 items for deleting within an animation frame that should just result in one update, but if scheduling takes longer it will not.

Like with vanilla lit-html you would delete all 50 and then render and not before.

**Comment by vogloblinsky** [comment]
> That is actually a bad benchmark
Ok so did you think better to just measure the deletion of one element inside the 50 elements list ? number 25 for example.

**Comment by kenchris** [comment]
Well, you could make separate benchmarks. I think it would be interesting if you deleted say the middle 25 items in one go. Or every second items in one go. Just make sure that each delete call doesn't result in a direct rendering updatw

**Comment by kenchris** [comment]
That way you test the rendering and diffing algorithms and not the rendering batching/update system. Of course testing both is valid, just need to make sure you use the framework right

**Comment by vogloblinsky** [comment]
Ok i will update the 'delete benchmark' with just deletion of item 25. Will post results soon.

**Comment by justinfagnani** [comment]
Is it possible to not benchmark pre-release unoptimized code? :)

**Comment by kenchris** [comment]
If you use vanilla lit-html you control when you call render, with LitElement you don't control it so directly. Which can mean that each change calls a property change which results in multiple renders for no apparent reason

**Comment by kenchris** [comment]
At least it is good knowing what you are benchmarking :-)

**Comment by vogloblinsky** [comment]
> Is it possible to not benchmark pre-release unoptimized code? :)

Ok, if you want, i can explain like for Angular Elements implementation i create in the repository that it is too early to bench them.
