### ISSUE TITLE
Online-hosted API documentation

### ISSUE THREAD

**Issue by js-choi** [Polymer/lit-html#252]
Currently, the only documentation readable on the web that I can find consists of the readme on GitHub and YouTube videos. In particular, the [TypeDoc-generated API reference](https://github.com/Polymer/lit-html/tree/master/docs) does not seem to be accessible online. GitHub won’t render a repository’s HTML unless it’s in a Markdown file or it’s on github.io. As far as I can tell, people seeking to look up things must download/clone the repository and view the reference from their filesystem.

It would be nice if this documentation were hosted somewhere, such as [polymer.github.io](https://polymer.github.io). If this is already the case, then the readme should link to it.

**Comment by justinfagnani** [comment]
The API docs are viewable here: https://polymer.github.io/lit-html/api/

Though we need scripts to update them on publishing.
