### ISSUE TITLE
Cannot bind properties

### ISSUE THREAD

**Issue by arodic** [Polymer/lit-html#254]
It appears that lit-html in its current form only supports attribute binding. This is a problem for applications where property types need to be preserved. I found [lit-html-brackets](https://github.com/bgotink/lit-html-brackets) which fixes this issue. Consider implementing some of its features in lit-html.

**Comment by daKmoR** [comment]
`lit-html` on purpose only supports HTML e.g. only attributes 
`lib/lit-extended.js` supports properties and attributes and events...

**Comment by justinfagnani** [comment]
@daKmoR is right. I'm considering whether the default library shouldn't actually be lit-extended, and lit-html be renamed something like `lit-core.js` for dialect authors.

I'll close this for now, but will open an issue for documentation or renaming libraries.
