### ISSUE TITLE
Possible to make render more flexible?

### ISSUE THREAD

**Issue by gauntface** [Polymer/lit-html#256]
Feel free to close this as it's just an ergonomics / preference thing, but thought I'd raise an issue in case you were open to the idea.

I have a set of JS Objects, I pass that through lit to get an array of "templates".

```javascript
const templates = dataPoints.map((data) => {
    return lit`<div>${name}</div>`;
});
```

Then what I'd like to do is just tell lit to render the array of templates into the the DOM at the point specified.

```javascript
render(templates, document.body);
```

**Comment by justinfagnani** [comment]
I'll have to think about this one. It's equivalent to:

```js
render(html`${templates}`, document.body);
```

And I think we'd have to essentially do exactly what that does under the hood to make it work with lists. My first instinct is that it's an edge case with a simple workaround, and not to add any more complexity to the core for it. On the other hand, support may just be wrapping the first argument in an empty template if it's not already a template result.

**Comment by kevinpschaaf** [comment]
I believe the code now supports rendering any supported type via `render`, but the types have not been updated to reflect this -- is that right @justinfagnani?

**Comment by justinfagnani** [comment]
The types have been updated now. `render()` accepts an `unknown` value.
