### ISSUE TITLE
shady-render breaks style conditions

### ISSUE THREAD

**Issue by daKmoR** [Polymer/lit-html#265]
```js
import { render, html, svg } from 'https://unpkg.com/lit-html/lib/lit-extended.js';
import { render as renderShady } from 'https://unpkg.com/lit-html/lib/shady-render.js';

render(html`
  <style>
    h3 { color: green; }
    ${true ? `h3 { color: red; }` : ``}
  </style>
  <h3>hello</h3>
`, document.querySelector('#render'));
```
works just fine
https://codepen.io/daKmoR/pen/LQNPyz

```js
import { render, html, svg } from 'https://unpkg.com/lit-html/lib/lit-extended.js';
import { render as renderShady } from 'https://unpkg.com/lit-html/lib/shady-render.js';

renderShady(html`
  <style>
    h3 { color: green; }
    ${true ? `h3 { color: red; }` : ``}
  </style>
  <h3>hello</h3>
`, shady, 'scope-1');
```
using renderShady already breaks
https://codepen.io/daKmoR/pen/qxZWmX

and combining both also breaks render
https://codepen.io/daKmoR/pen/qxZWER

tested in Chrome 61

**Comment by justinfagnani** [comment]
ShadyCSS is just incompatible with style bindings. It has to remove the style tags from templates before they're stamped out, and there's only one style tag per scope name, shared across all instances.

I'll document this better.
