### ISSUE TITLE
declaring a template and export it

### ISSUE THREAD

**Issue by fopsdev** [Polymer/lit-html#270]
hi
i'm trying to declare my components in separate files and export them.
but the following fails:
app.js
```
import { html } from './lit-html'
export const app = values => {
  console.log(values)
  return html`<div>Hello ${values.counter}!</div>`
}
```
index.js
```
import { render } from './lit-html'
import { app } from './app'
render(app({ counter: 0 }, document.body))
```
using everything directly in the index-file works.
the error msg is:
TypeError: Cannot read property '__templateInstance' of undefined
render

**Comment by Lodin** [comment]
If this code is one you are working with, you made an error:
```js
import { render } from './lit-html'
import { app } from './app'
render(app({ counter: 0 }, document.body)) // <<-- here
```
Here you are sending `document.body` to `app` function instead of `render` function.

**Comment by fopsdev** [comment]
woa, thanks that solved it :)
