### ISSUE TITLE
wiring  up event handlers 

### ISSUE THREAD

**Issue by fopsdev** [Polymer/lit-html#273]
the following doesn't work
```js
import { html } from './lit-extended'
import { cvf } from './CerebralViewProps'
function handleClick(event) {
  console.log('lalala')
  cvf.RunSignal('toggleChartVisibility')({})
  event.stopPropagation()
}
export default function MyComponent(props) {
  return html`
    <div>
      <input
        type="checkbox"
        on-click=${e => {
          console.log('hurray')
          return handleClick(e)
        }}
        checked=${props.values.showChart}
      />
    </div>
  `
}
MyComponent.Dependencies = props => {
  return { showChart: `${props.showChart}` }
}
```
I have no output in the console when clicking. (other comps without events work as expected)
(i'm using fresh compiled lit-html and extended.)

**Comment by daKmoR** [comment]
any reason you want to have 2 functions for one event?
```
on-click="${handleClick}"
```
should work fine

**Comment by fopsdev** [comment]
yeah doesn't make sense...
but does not work either.
```
* Example:
 *
 *     html`<button on-click=${(e)=> this.onClickHandler(e)}>Buy Now</button>`
 *
 */
```
thats what i have found inside lib-extended...
maybe its just broken in current master...

**Comment by daKmoR** [comment]
here it works...
https://codepen.io/daKmoR/pen/BYpBrd?editors=1010

**Comment by fopsdev** [comment]
hey thanks for helping me out.
i've found the issue. i was importing { html } still from "lit-html" (not extended) in the parent component.
Looks like once you switch to extended  you should use html from there only (makes sense anyway) :)
