### ISSUE TITLE
Facing problems with `viewBox` attribute on `svg`

### ISSUE THREAD

**Issue by itssumitrai** [Polymer/lit-html#275]
Hi, when I use `lit-html` to use `viewBox` attribute on a svg, I get an error from lit-html. I found that lit-html was searching for `viewbox` instead of `viewBox`.

**Comment by bgotink** [comment]
Could you provide us with some code to reproduce the error?

In [this plunker](https://plnkr.co/edit/dyJw2XmU5iZsbsjWlVqe?p=preview) everything seems to work fine, but without a code sample it's hard to investigate any issue you're running into.

**Comment by itssumitrai** [comment]
Hi @bgotink , 
Thanks. I see that this is not an issue with version 0.9. I am closing this.

**Comment by intcreator** [comment]
This is still an issue for me on 0.9.0.  Here is an [updated Plunker](https://plnkr.co/edit/KOPWWZjMBsmdYPB0Rjqk?p=preview) that shows the problem.  For me it occurs when I use lit-extended (which is the case with `LitElement`).

**Comment by justinfagnani** [comment]
One problem is the use of the `svg` template tag. The `<svg>` element itself is an HTML element, so it needs to be an `html` lit-html template tag. Only SVG elements, like `<line>` or `<rect>`, need to use the `svg` template tag to create them in the correct namespace.

**Comment by intcreator** [comment]
There still seems to be an issue if I use the tags as you suggest.  See [another updated Plunker](https://plnkr.co/edit/artZm8nQyKyegQsyb9WG?p=preview).

**Comment by intcreator** [comment]
@bgotink or @justinfagnani can you double check that my Plunker contains an actual bug in lit-html?  If it does, should we reopen this issue or should I create a separate issue?

**Comment by lamplightdev** [comment]
I'm also seeing this on 0.10.2

`viewBox="0 0 ${size} ${size}"` gives:

```
lit-html.ts:372 Uncaught TypeError: Cannot read property 'value' of null
    at new Template (lit-html.ts:372)
    at result (shady-render.ts:59)
    at render (shady-render.ts:154)
    at HTMLElement._applyRender (lit-element.ts:286)
    at HTMLElement._propertiesChanged (lit-element.ts:218)
    at HTMLElement._flushProperties (properties-changed.js:370)
    at HTMLElement._flushProperties (lit-element.ts:232)
    at HTMLElement.ready (properties-changed.js:193)
    at HTMLElement.ready (lit-element.ts:119)
    at HTMLElement._enableProperties (properties-changed.js:347)
```

`viewbox="0 0 ${size} ${size}"` works as expected.

**Comment by intcreator** [comment]
@lamplightdev hmm...are you sure?  [MDN says the attribute should be `viewBox` not `viewbox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox).

I've opened a new issue to follow up on this (#374).

**Comment by justinfagnani** [comment]
In lit-extended `viewbox=` will set the property, which is likely why it works. I'll move the rest of the conversation to #374
