### ISSUE TITLE
Confused about README.md render() function usage

### ISSUE THREAD

**Issue by kkpoon** [Polymer/lit-html#277]
In [README.md](https://github.com/Polymer/lit-html/blob/ea3e8bfc321d30e132afa49d9452d7e48c3d5b13/README.md), there are multiple usages of "`render()`" function.

I am confused by the imported `render` in [Overview](https://github.com/Polymer/lit-html/blob/ea3e8bfc321d30e132afa49d9452d7e48c3d5b13/README.md#overview):

```js
import {html, render} from 'lit-html';
// ...
render(helloTemplate('Steve'), document.body);
// ...
```

and the render returned by `html` in [Features](https://github.com/Polymer/lit-html/blob/ea3e8bfc321d30e132afa49d9452d7e48c3d5b13/README.md#features)

```js
const render = () => html`foo is ${foo}`;
```

Are they the same?
or the second one should be

```js
const renderFoo = () => html`foo is ${foo}`;
```

Thanks

**Comment by oskarrough** [comment]
I agree the naming is confusing. There are many examples in the readme where the template is stored as `render` variable. This is how I understand it.

```js
import {html, render} from 'lit-html'

// First we create a template.
const exampleTemplate = (name) => html`hello ${name}`

// Then we render it.
render(exampleTemplate('Steve'), document.body)
```

So I propose not to name the variables `render` when they actually hold a templates. That being said, I don't know lit-html internals and if there is a reason for it :]

```js
// "render" is confusing
const render = () => html`foo is ${foo}`;

// alternative examples
html`foo is ${foo}`;
const renderTemplate = () => html`foo is ${foo}`;
const helloTemplate = (name) => html`foo is ${name}`;
```
