### ISSUE TITLE
Changing slot content

### ISSUE THREAD

**Issue by yuri-karadzhov** [Polymer/lit-html#279]
# The issue
Changing interpolation value inside a slot content does not expose any elements in light DOM and force entire element to rerender (no wonder, because we are changing default slot value) e.g.
```js
const template = html`<slot>${items}</slot>`;
```
So lit should handle interpolation inside slot as a special case.

# Why put interpolation to a slot
Something that looks like a list and works like a list should also have a list structure. An example of a list
```html
<my-awesome-list></my-awesome-list>
```
that renders to a list that have a content does not feel that awesome, but
```html
<my-awesome-list>
  <my-awesome-item>1</my-awesome-item>
  <my-awesome-item>2</my-awesome-item>
  <my-awesome-item>3</my-awesome-item>
</my-awesome-list>
```
does, because it has proper structure.

**Comment by justinfagnani** [comment]
Interpolating values into a `<slot>` would only ever set the default content. For distributing content into a slot you need to use the browsers native distribution mechanism, by adding light-DOM children. In general, lit-html has very little knowledge of the structure of the DOM inside your template. It knows nothing about shadow DOM.

I don't think there's much we can do here.

**Comment by yuri-karadzhov** [comment]
Sure, but at least for the first level of slot element it might be worse to create a special slotted content that will execute append/removeChild inside it. Otherwise there will be no declarative way to create structured components like lists e.g.
```js
html`
<slot>
${utems.map(item => html`<my-awesome-item>${item}</my-awesome-item>`)}
</slot>
```

**Comment by justinfagnani** [comment]
Shouldn't that expression be in the element _using_ `<my-awesome-list>`? Otherwise it's just setting the default content.

**Comment by yuri-karadzhov** [comment]
Ah, yes, you are exactly right!
