### ISSUE TITLE
A simple link to the new website can be helpful

### ISSUE THREAD

**Issue by motss** [Polymer/lit-html#280]
No one remembers the URL all the time. Please add one.

**Comment by MatxBerg** [comment]
What website?

**Comment by daKmoR** [comment]
https://polymer.github.io/lit-html/

However I'm not sure if it's ready for prime time... I guess if it would be there would be a link...

**Comment by motss** [comment]
@MatxBerg 

Thanks @daKmoR. That's I'm talking about. The link should be shown somewhere in the documentation.

**Comment by justinfagnani** [comment]
The link is in the readme now.
