### ISSUE TITLE
[QUESTION] Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [Polymer/lit-html#282]
I have created a benchmark of major Web Components librairies here : 
https://github.com/vogloblinsky/web-components-benchmark

My results for lit-html are a bit strange.

Here is the screenshot for creating 50 items :

![benchmark_create](https://user-images.githubusercontent.com/2841805/36642335-635bf55e-1a3e-11e8-845e-fb3b101974bc.png)

May be my implementation of lit-html version is wrong, but i don't understand why the lit-html version is slower than native one.

Thanks by advance for your feedbacks.

**Comment by bgotink** [comment]
At first glance I have but one remark on your native + lit-html code: instead of binding in the template getter it's best to create one bound function and use that throughout. Right now every render is creating multiple bound functions and changing the event listeners. By binding once you're cutting that cost.  
The effect of this change is small though: average time decreases from ±375ms to ±358ms but the standard deviation increases from ±5ms to ±15ms.

I must say that the numbers I get are totally different from the ones in the README. I'm reading that native takes nearly double the time native + lit needs to perform the benchmark. Perhaps I'm running the wrong command, or with outdated code, or&hellip;?

```
$ npm run benchmark-create-todos

> web-components-benchmark@1.0.0 benchmark-create-todos /private/tmp/web-components-benchmark
> node benchmarks/benchmark_create-todos.js

Top down tree total time 0: 792
Top down tree total time 1: 849
Top down tree total time 2: 723
Top down tree total time 3: 761
Top down tree total time 4: 808
Top down tree total time 5: 744
Top down tree total time 6: 731
Top down tree total time 7: 730
Top down tree total time 8: 745
Top down tree total time 9: 657

Average time for native : 754 ms

Top down tree total time 0: 391
Top down tree total time 1: 379
Top down tree total time 2: 373
Top down tree total time 3: 366
Top down tree total time 4: 386
Top down tree total time 5: 382
Top down tree total time 6: 390
Top down tree total time 7: 389
Top down tree total time 8: 377
Top down tree total time 9: 383

Average time for native + lit-html : 382 ms
```

Hardware: 2017 MacBook Pro with a bunch of open applications, the heaviest of which are IntelliJ IDEA, Sophos (on-access scan enabled), VS Code and Chrome streaming video.

**Comment by vogloblinsky** [comment]
> instead of binding in the template getter it's best to create one bound function and use that throughout

Thanks.

Did you mean that ?

```
get template() {
        const template = html`

to

render() {
        return html`
```

**Comment by bgotink** [comment]
I mean that the template getter uses

```js
const template = html`
  <!-- bunch of CSS -->
  <li class="item">
    <input type="checkbox" checked=${this.checked} on-change=${this.handleOnChecked.bind(this)}>
    <label>${this.text}</label>
    <button class="destroy" on-click=${this.handleOnRemoved.bind(this)}>x</button>
</li>`
return template
```

while it is advised to have

```js
this._handleOnChecked = e => this.handleOnChecked(e);
this._handleOnRemoved = e => this.handleOnRemoved(e);
```

in the constructor with

```js
const template = html`
  <!-- bunch of CSS -->
  <li class="item">
    <input type="checkbox" checked=${this.checked} on-change=${this._handleOnChecked}>
    <label>${this.text}</label>
    <button class="destroy" on-click=${this._handleOnRemoved}>x</button>
</li>`
return template
```

in the template getter. That way you only create a bound function once (per instance) and only install the listeners once, instead of replacing the listeners on every render

**Comment by vogloblinsky** [comment]
Ok thanks, it is more clear.
I have re-run the bench, lit-html decrease to around 240ms, but i don't have the situation where lit-html is twice faster than native implementation.

**Comment by vogloblinsky** [comment]
Here is an updated graph with last fixes

![localhost_tmp_web-components-benchmark_benchmarks_benchmark_results_graph html 11](https://user-images.githubusercontent.com/2841805/36700085-fc7a65b6-1b4e-11e8-9ca0-a472ea284926.png)

**Comment by justinfagnani** [comment]
I'll look at the benchmark soon. If you're using the `repeat()` directive, it's know to be slow.

**Comment by vogloblinsky** [comment]
Ok. I will update the benchmark to be more closed to what lit-html compute and not the UI. For now, the create benchmark bench the creation of 50 items, not just one.
Same stuff for delete.
I will update the benchmark to monitor only one creation, and for example, one random delete inside a big list.
I will also publish an initial version of the results without WIP projects : lit-html, lit-element & Polymer 3.
When they will come in RC i will add them in the results graphs.

**Comment by justinfagnani** [comment]
I'll fork your repo too and see what we need to lock down for it to be a reflection of wat 1.0 will be. I hope to have a release relatively soon, but I'm working on benchmarks on this side first as well.

**Comment by vogloblinsky** [comment]
For information, this JavaScript frameworks benchmark seems to use for lit-html `.map` instead of `repeact()` directive.
https://github.com/krausest/js-framework-benchmark/blob/master/lit-html-v0.9.0-non-keyed/src/app.js

Like discussed here, https://github.com/Polymer/lit-html/issues/242, i don't know if it is better to just benchmarking the creation/deletion of one element, or a loop of for example 50 elements.

**Comment by CaptainCodeman** [comment]
There are two benchmarks in there - the regular one uses map and the keyed one uses the `repeat` directive.

These results include both:
https://rawgit.com/krausest/js-framework-benchmark/d38c5b386fb3825ed9c7f019a2c1c5e4421936ba/webdriver-ts-results/table.html

**Comment by justinfagnani** [comment]
I think this can be closed now.
