### ISSUE TITLE
Syntax Highlighting for vim

### ISSUE THREAD

**Issue by ccutch** [Polymer/lit-html#285]
Hello i found syntax highlighters for visual studio code and atom but non for vim does anyone know of any projects?

**Comment by justinfagnani** [comment]
I'm not really sure, since I'm not a regular vim user. @cdata or @aomarks?

**Comment by cdata** [comment]
Not that I am aware of. As a long-time Vim user, I have found mixed-mode syntax highlighting to be one of Vim's weak spots. Let us know if you learn anything on this topic!

**Comment by justinfagnani** [comment]
I'll close this for now as I don't think there's much we can do from this end right now.

**Comment by jonsmithers** [comment]
I copied [mxw/vim-jsx](https://github.com/mxw/vim-jsx/blob/52ee8bb9f4b53e9bcb38c95f9839ec983bcf7f9d/after/syntax/jsx.vim#L48) and got xml syntax highlighting inside ``html`...` ``. It's a start. See [jonsmithers/experimental-vim-javascript-with-lit-html](https://github.com/jonsmithers/experimental-vim-javascript-with-lit-html). 

Maybe it'd be cool to see this implemented in [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript).

**Comment by cdata** [comment]
Update that may be relevant to anyone paying attention to this thread. I forked another plugin and created one that can support arbitrary syntaxes inside of tagged template strings. Check it out here: https://github.com/cdata/vim-tagged-template

Demo of what it can achieve:

![taggedtemplates](https://user-images.githubusercontent.com/240083/38775055-5117aeac-4035-11e8-8b85-2a4adda3d969.gif)

**Comment by dman777** [comment]
I tried it and for Polymer 3 it is not highlighting. I will post a bug on there with a screen shot. **Please keep Polymer decoupled from Microsoft. After Angular and typescript and now this, there a legitimate concern. **. After years of using Polymer, I will switch to React if it goes down this road.
