### ISSUE TITLE
lit-extended treats class names differently

### ISSUE THREAD

**Issue by gauntface** [Polymer/lit-html#286]
In project-health we had the following in a lit-html template which worked when using `node_modules/lit-html/lit-html.js`:

```javascript
<span class="pr-status__msg ${status.actionable ? 'actionable' : ''}">${status.text}</span>
```

I switched to lit-extended (`node_modules/lit-html/lib/lit-extended.js`) to use click listeners and this broke the above snippet - all classes were removed. The final output was essentially `<span>${status.text}</span>`

In case it's important, this was on Firefox stable.

**Comment by LarsDenBakker** [comment]
I think you need to use class$, lit extended sets properties by default

**Comment by justinfagnani** [comment]
Yep, in lit-extended you must use the `$` suffix for attributes. I think this can be clearer in the docs though. I'll put some more work in there.
