### ISSUE TITLE
Idea: Support continues separated Javascript expressions

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/lit-html#291]
Allow to use related JS code in embedded expressions, where the expressions are separated  throughout the string literal. 

e.g. Just like in server-side templating where: ({% - marks the server-side rendered code)
```
{% if(x) { %} 
     <h1>title</h1> 
{% } %}
```
will include the inner html is affected by the JS code that wraps it.
Or 
```
<div>
      {% for(let item of items) { %}
         <span>{% print(item) %}</span>
      {% } %}
</div>
```

(Sorry for the terminology, didn't take the time to write it better.

**Comment by justinfagnani** [comment]
lit-html doesn't parse the expressions, the JavaScript VM does when it parses and evaluates template literals. lit-html just receives an array of literal parts and values form already evaluated expressions, so there's really no way for lit to do this.

Your examples are translatable into lit-html template literals however:

```js
html`
  ${(() => {
    if(x) {
     return html`<h1>title</h1>`;
    }
  })()}
`
```

```js
html`
  ${(() => {
    for(let item of items) {
      return html`<span>${print(item)}</span>`;
    }
  })()}
`
```

The extra noise comes from creating an IIFE to execute statements within. If JavaScript gets [do-expressions](https://github.com/tc39/proposal-do-expressions) it'll be cleaner:

```js
html`
  ${do {
    for(let item of items) {
      return html`<span>${print(item)}</span>`;
    }
  }}
`
```

Clasing this as there's nothing we can do now.

**Comment by myuseringithub** [comment]
@justinfagnani Thanks, just the second example the templates in the loop should be merged, cause the function can return only once. Is there a merge functionality for templates built in ? How to combine templates ? 
```
html`
  ${(() => {
    let aggregation = []
    for(let item of items) {
      aggregation.push(html`<span>${print(item)}</span>`)
    }
    return mergeHtmlTemplate(...aggregation) // is there a merge function for multiple templates ?
  })()}
`
```

**Comment by myuseringithub** [comment]
Probably creating a container template and then appending the templates into it.

**Comment by fafcrumb** [comment]
You can use `map` for this, like so:

```javascript
html`
  ${items.map((item) => { html`
      <span>${print(item)}</span>
  `)}
`
```

Note that this solution is best suited for rendering static data.
For dynamic data, use the `repeat` directive:

```javascript
html`
  ${repeat(items, (item) => item.id, (item) => { html`
      <span>${print(item)}</span>
  `)}
`
```
