### ISSUE TITLE
IE: Can't bind inner contents of <style> tag

### ISSUE THREAD

**Issue by keanulee** [Polymer/lit-html#296]
On IE, this doesn't work as expected in the babel-compiled version of LitElement:

```js
html`<style>${sharedStyles}</style>`
```

Instead, the contents are rendered as a text node after an empty style tag:

```html
<style></style>
.shared-style {
  foo: bar;
}
```

**Comment by bgotink** [comment]
That's a known issue. Lit-html uses empty text nodes as marker nodes for the interpolations and IE skips empty text nodes when walking or cloning a DOM element.

#267 will fix this

**Comment by justinfagnani** [comment]
If #267  fixed this, then we can close. @keanulee can you confirm?
