### ISSUE TITLE
[Question] How can I re-render the content whether a event is fired?

### ISSUE THREAD

**Issue by zaclummys** [Polymer/lit-html#297]

**Comment by fafcrumb** [comment]
I'm assuming you mean "when an" event is fired right?
Just call `render` again with the same template in your event handler.

**Comment by zaclummys** [comment]
@fafcrumb,

 I have modular components, so I can't reference it externally. How can I do it internally, like React's `setState`?


For example,

```js
// incrementor
export default = () => {
    let i = 0;

    const handleClick = () => {
        i++;
        // re-render me, please!
    };

    return html`
        <div>
            <span>${i}</span>
            <button on-click="${handleClick}">CLICK ME</button>
        </div>
    `;
}
```

**Comment by justinfagnani** [comment]
That example isn't a component, just a template. Are you using something for a component model?

In [LitElement](https://github.com/PolymerLabs/lit-element) for example you'd call `this.invalidate()`.

**Comment by zaclummys** [comment]
Got it! Thanks, @justinfagnani @fafcrumb!

**Comment by KeithHenry** [comment]
The answer to this question has changed, for `LitElement` this now appears to be `this._invalidate()`
