### ISSUE TITLE
AttributePart.setValue() should also update properties in some case

### ISSUE THREAD

**Issue by cognitom** [Polymer/lit-html#298]
## Minimal reproduction
Could you hava a look at this example on jsbin? The `<input>` field doesn't update after editing.
http://jsbin.com/jicuhel/edit?html,output

## Background
According to MDN, `value` attribute of `<input>` represents **the initial value**. It's **not the current one**. So, even if `lit-html` changes this attribute, it has no effect after any editing.

> `value`: The initial value of the control.
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-value

Unfortunately, there's no attribute for **the current value**, so changing **the property** seems the only reasonable way for me.

## Possible solution
We can change this behavior at [this line](https://github.com/Polymer/lit-html/blob/54afddcfa7de802181e502f3b69599aa0507efb8/src/lit-html.ts#L510):

```javascript
// inside AttributePart.setValue()
this.element.setAttribute(this.name, value);
if (this.name === 'value') this.element.value = value; // add this line
```

I know that `lit-html` is designed to handle *only* attributes, and  `lib/lit-extended` solves this issue. But this issue could make `lit-html` a little bit inpractical, I think. cf. #71

If there're positive feedbacks, I'd like to send PR about it. Thanks!

**Comment by justinfagnani** [comment]
I think this falls squarely in the realm on lit-extended. There's no standard syntax for setting properties, so lit-core shouldn't take an opinion there. Closing as "use lit-extended".

**Comment by cognitom** [comment]
@justinfagnani thank you for your response!

> There's no standard syntax for setting properties

Exactly that's the point. Pls let me ask one more question: what is the use case of `lit-html`? Still unclear for me.
