### ISSUE TITLE
[Suggestion] Supports inline styles

### ISSUE THREAD

**Issue by zaclummys** [Polymer/lit-html#299]
For example, 
```js
const Button = ({ color, text }) => {
    return html`
        <button style=${{ color }}>${text}</button>
    `;
};
```

As well as it's in [React's docs](https://reactjs.org/docs/dom-elements.html#style), inline styles can be useful sometimes.

**Comment by justinfagnani** [comment]
Inline styles are already supported if you list them explicitly:

```js
const Button = ({ color, text }) => {
    return html`
        <button style="color: ${color}">${text}</button>
    `;
};
```

If you want to auto-convert from an object or Map to inline styles, that's perfect for a directive:

```js
const Button = ({ color, text }) => {
    return html`
        <button style=${styles({color})}>${text}</button>
    `;
};
```
