### ISSUE TITLE
nested TemplateResult not being transformed

### ISSUE THREAD

**Issue by argyleink** [Polymer/lit-html#300]
https://stackblitz.com/edit/recursive-lit-html?file=index.js

Above demo renders the result to the dom. Notice the [object Object]. If you open the console, you'll see the TemplateResult is logged and is the proper interface.

**Comment by bgotink** [comment]
You're missing a `html` string literal tag, passing the HTML as a string instead of a TemplateResult.

See: https://stackblitz.com/edit/recursive-lit-html-wjhqhd?file=index.js

**Comment by argyleink** [comment]
i love programming, even when i do dumb things. thanks!
