### ISSUE TITLE
[labs/task] Investigate task ergonomics

### ISSUE THREAD

**Issue by taylor-vann** [Polymer/lit-html#3005]
## Description

Tasks are a way to execute and visualize asynchronous operations inside a LitElement.

The dx behind chaining tasks and canceling tasks isn't well defined. Create examples that cover different use cases:
- initial values
- placeholder render
- cancelling tasks

## Acceptance criteria

This issue can be closed when examples can help decide whether a use case can be expressed through a composition pattern or if an update to the Task API is necessary.

**Comment by rictic** [comment]
Dupe of https://github.com/lit/lit/issues/1499
