### ISSUE TITLE
Insert another raw string to svg

### ISSUE THREAD

**Issue by romanlex** [Polymer/lit-html#304]
I have this code, but it is not work
```js
import { svg } from 'lit-html'
import sealImage from '!!raw-loader!static/assets/signes/seal.svg'

const certificateSealTemplate = svg`<g id="certificateSeal" transform="matrix(0.24731808,0,0,0.24787261,50,30)">
  ${sealImage}
</g>`
```
I can't insert another svg file to svg as string
In the DOM tree I see this

![image](https://user-images.githubusercontent.com/3369304/38433983-86258f4e-39d5-11e8-86f1-0e276469c13e.png)

How I can fix it?

**Comment by justinfagnani** [comment]
I'm not familiar with this: `import sealImage from '!!raw-loader!static/assets/signes/seal.svg'`, what type is `sealImage`?

**Comment by romanlex** [comment]
@justinfagnani type is string
![image](https://user-images.githubusercontent.com/3369304/38434338-a2972f7e-39d6-11e8-87b7-c2f363eb6053.png)

**Comment by justinfagnani** [comment]
Ah, ok. That's definitely a non-standard use of import. It won't work with native modules.

So, we're going to need an SVG version of the `unsafeHTML()` directive: https://github.com/Polymer/lit-html/blob/master/src/lib/unsafe-html.ts

The only difference is that it has to insert a `<svg>` tag in the template:

```ts
export const unsafeSVG = (value: any) => directive((part: NodePart) => {
  const tmp = document.createElement('template');
  tmp.innerHTML = `<svg>${value}</svg>`;
  const clone = document.importNode(tmp.content, true);
  part.setValue(clone.firstChild!.firstChild!);
});
```

**Comment by LarsDenBakker** [comment]
I think the regular version of unsafeHTML will work fine here, since it's already inside in a svg tagged literal it does not need to be wrapped again.

You're using webpack to compile that import syntax to a string variable. lit-html renders regular variables as textContent provide XSS safety.

**Comment by ernsheong** [comment]
Perhaps a directive can be provided to render the content as SVG directly, instead of as textContent?

**Comment by justinfagnani** [comment]
If `unsafeHTML` already works, I think we can close this.

**Comment by Artur-** [comment]
Did something change regarding this during the last year? 

If I do e.g.
```
  constructor() {
    super();
    this.rect = '<rect fill="red" x=10 y=10 width=100 height=100></rect>';
  }
  
  render() {
    return svg`<svg width=100px height=100px viewport="0 0 200 200">${unsafeHTML(this.rect)}</svg>`;
  }
```

Then the resulting DOM sure looks correct
```
<svg width="100px" height="100px" viewport="0 0 200 200"><!----><rect fill="red" x="10" y="10" width="100" height="100"></rect><!----></svg>
```

But no rectangle is drawn because
```
> this.shadowRoot.querySelector("svg").namespaceURI
< "http://www.w3.org/2000/svg"
> this.shadowRoot.querySelector("rect").namespaceURI
"http://www.w3.org/1999/xhtml"
```

Using the proposed `unsafeSVG` instead correctly renders a red rectangle

Example at https://2tt1wn.run.stackblitz.io

There are also other cases where you cannot use the HTML parser e.g.
```
const tpl = document.createElement("template"); 
tpl.innerHTML="<image></image>"; 
tpl.innerHTML
```

prints
`<img>` where it should be `<image>` for SVGs

**Comment by justinfagnani** [comment]
@Artur- indeed, you're right. Reopening this and thanks for the PR!
