### ISSUE TITLE
Consider adding the marker* properties to the TemplateResult class for easier snapshot testing

### ISSUE THREAD

**Issue by ryanvanoss** [Polymer/lit-html#308]
I threw together a quick Jest snapshot test today and realized that it would be great to be able to easily mock / force a static value for [marker and nodeMarker](https://github.com/Polymer/lit-html/blob/master/src/lit-html.ts#L187-L195) to make string output deterministic in tests. For the Jest fans, a snapshot test would look something like:

```javascript
import {
    html
} from "lit-html/lit-html.js";

const render = (props) => html`<div>${props.foo}</div>`;

it('renders correctly', () => {
    const asString = render({ foo: ""}).getHTML();
    expect(asString).toMatchSnapshot();
}
```

However, since the marker changes for each test run, the snapshot would very rarely (essentially never) match. There are ways to work around this as-is (for example `asString = asString.replace(/lit\-[0-9]+/, "SNAPSHOT_TOKEN");`), but something a little more supported would be great, and adding `marker` to the prototype or as an instance property should make it cleaner.

Unless I missed something and there's a simple way to get the string output of a `TemplateResult` :)

**Comment by justinfagnani** [comment]
To get the string output of a TemplateResult, you can just render it:

```js
const container = document.createElement('container');
const renderTemplate = (data) => html`<div>${data.foo}</div>`;

render(renderTemplate({foo: ''}, container);

// innerText respects styling, so comments and hidden elements are not included
const text = container.innerText;
assert.equals(text, whatever);
```

**Comment by ryanvanoss** [comment]
Yeah, the idea here was to get it without rendering, since Jest by default doesn't run in a DOM environment, and even when run in jsdom there's no custom element support. There's some decent work going into a Jest and Puppeteer environment, but so far it's not as user friendly as I'd like.

For now the workaround I mentioned works well enough that this isn't a big concern.

**Comment by justinfagnani** [comment]
Seems like what you want is `TemplateResult#strings`, which is equal to the template literal strings form the source. You can join them with your own consistent marker like so:

```js
const renderTemplate = (data) => html`<div>${data.foo}</div>`;
const result = renderTemplate({foo: ''});
assert.equal(result.strings.join('MARKER'), '<div>MARKER</div>');
assert.deepEquals(result.values, ['']);
```

**Comment by ryanvanoss** [comment]
Aha, precisely that. Thanks!
