### ISSUE TITLE
PWA and Dynamic Templates

### ISSUE THREAD

**Issue by MVSICA-FICTA** [Polymer/lit-html#315]
Are there any special considerations (or examples) when it comes to using lit-html templates in the context of a PWA using Workbox? When using a index.html with only a root node that is populated dynamically at runtime with injected templates the typical SPA pattern no longer applies. 

I suppose template functions in JS modules can just be cached by Workbox and used. Seems the only thing different is that now we use lit-html template functions instead of HTML pages or bloated framework components.

https://developers.google.com/web/tools/workbox

**Comment by justinfagnani** [comment]
There should be no problem with templates and workbox. Workbox doesn't cache individual functions, it caches files.
