### ISSUE TITLE
Templating of html attributes is incorrect

### ISSUE THREAD

**Issue by kjlubick** [Polymer/lit-html#321]
```
const buggytemplate = (ele) => html`
<div data-alpha=${ele.alpha} ${ele.not_exist ? "BETA" : "beta"}>

gamma: ${ele.gamma}
delta: ${ele.delta}
</div>`

let output = document.createElement('span');

render(buggytemplate({alpha: 'alpha', gamma: 'gamma', delta:'delta'}), output);
console.log(output.innerHTML);
```

Expected HTML:
```
<div data-alpha=alpha beta>

gamma: gamma
delta: delta
</div>
```

Actual HTML:
```
<div {{lit-520176040559966}}="">

gamma: beta
delta: gamma
</div>
```

Notice especially that the gamma and delta are wrong, almost as if the templates get shifted down.

This seems to be specific to if there are properties on html.  If I get rid of all <div> in the template, it handles it just fine.

This is on Chrome Version 66.0.3359.139 (Official Build) (64-bit), on Linux

**Comment by LarsDenBakker** [comment]
Try adding quotes " " around the atrribute value. I think lit gets confused by that syntax.

**Comment by justinfagnani** [comment]
The problem is that you can't use an expression for element or attribute names. You'll have to do that imperatively.

**Comment by jridgewell** [comment]
Or use https://github.com/Polymer/lit-html/pull/213?

**Comment by kjlubick** [comment]
Thanks for the advice - I switched to using lit-extended and tweaked my template to be:
```
`<div data-alpha$=${ele.alpha} data-beta$=${ele.not_exist ? "BETA" : ""} >

gamma: ${ele.gamma}
delta: ${ele.delta}
</div>`
```

and that gave the expected result (or at least a result I can work with):

```
<div data-alpha="alpha" data-beta="">

gamma: gamma
delta: delta
</div>
```
