### ISSUE TITLE
Why TS?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/lit-html#325]
Thank you for releasing this great library.
I have one question: why Typescript?

You say "Use the platform"... shouldn't that apply to use ES6 in its pure state, rather than writing code in something effectively outside the platform?

With ES6 we have proper classes, quasi-proper mixins, and a lot of nice features -- I think most of the ones you get with TS, except the typing.

Polymer (at least for now, and in the future I HOPE) targets ES6, which is the centrepiece of the "platform". The fact that polymer-cli will transpile and node-prpl will redirect to the right version is _incredibly_ fantastic.

But... why TS? Would you even consider compiling it to ES6 and maintain that instead?

**Comment by justinfagnani** [comment]
The choice of TypeScript is for the benefit of mainters only, and doesn't effect users of the library, other than making it easy to produce typings for other TypeScript users.

**Comment by mercmobily** [comment]
Hi,

Well yes... And no. It does make it harder for non-ts developers to read
its code, extend it if needed, and understand what  goes on during
debugging. Plus, it's not using the platform as such...

Still awesome that you wrote it, and will use it!

Merc.
