### ISSUE TITLE
Add regression test for #231 - via an element that modify its children.

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#331]
A misbehaved element that modifies its children should not disturb the part finding on instances. This was originally reported in #231 as a problem with ShadyDOM.

**Comment by daKmoR** [comment]
not sure if it's the same but also related to ShadyDom.

A dom node with shadow dom will prevent lit-html from setting properties of any light-dom element in polyfilled browsers like FireFox

something like this should work right?
```js
class FooOne extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open'});
    this.fooOne = 'fooOne';
  }
  connectedCallback() {
    this.shadowRoot.innerHTML = '<span>shadow-dom</span><br /><slot></slot>';
  }
}
customElements.define('foo-one', FooOne);

render(html`
  <foo-one>
    <span id="nodeA" foo="${'fromLit'}">light-dom</span>
  </foo-one>
`, document.querySelector('#target'));
```

if not it would be a pretty HUGE deal right? I mean you could use it for only one level deep? even though you are only light-dom elements... => however could also be a "bug" in shadyDom? (maybe not moving properties along?)

So here is the full example which runs fine in Chrome but fails in Firefox.
https://codepen.io/daKmoR/pen/jKPReb

I sure hope this can be "fixed" - and it may need a higher priority then "low" :see_no_evil:

**Comment by daKmoR** [comment]
@bgotink oh yeah that did the trick :)

@justinfagnani any chance for a bugfix release?

**Comment by justinfagnani** [comment]
This isn't going to be very practical to test, since elements are barred from modifying their light children or attributes in the constructor. Going to close this now.
