### ISSUE TITLE
Cannot get :host to function

### ISSUE THREAD

**Issue by dburles** [Polymer/lit-html#338]
Not sure exactly if I am doing something wrong or if it's a bug, but the text in this example is not red 😣

```js
import {
  render,
  html,
} from 'https://unpkg.com/lit-html/lib/lit-extended.js?module';

render(
  html`
  <style>
    :host {
      color: red;
    }
  </style>

  hello
`,
  document.body,
);
```

**Comment by LarsDenBakker** [comment]
:host is meant for the shadow root's host element. https://developer.mozilla.org/en-US/docs/Web/CSS/:host() in this case you're looking for :root or html since you're rendering to the body.

**Comment by jsilvermist** [comment]
Here's a working example while using a shadow root: https://glitch.com/edit/#!/hollow-shift-1

**Comment by dburles** [comment]
Thanks @LarsDenBakker @jsilvermist maybe not the best example as it wasn't an explicit requirement to attach the style to the body/root element but rather I was having trouble attaching it to any parent like:

```js
render(
  html`
  <div>
    <style>
      :host {
        color: red;
      }
    </style>

    hello
  </div>
`,
  document.body,
);
```

@LarsDenBakker thanks for the example, does it mean that in order to use the `:host` selector I must render to a shadowRoot?  Please excuse my ignorance on shadow-dom!

**Comment by LarsDenBakker** [comment]
@dburles Lit-html does not provide any css scoping, it just provides template rendering. So you're just writing that <div> with <style> to the document.body literally.

If you want to create scoped CSS, I suggest creating a web component with a shadow root so that the styles inside it are scoped. Look into https://github.com/Polymer/lit-element which is a web component implementation with lit-html rendering.

**Comment by dburles** [comment]
Right yes, that makes sense. I have a much better idea of what’s going on now, thanks!

**Comment by dburles** [comment]
One further question, it seems that having to use the `customElements.define` API negates a lot of the benefits we are now afforded with native es browser modules. Is it possible to do something like the following with a `LitElement`? 

Contrived example:

```js
import { render, html } from 'https://unpkg.com/lit-html/lib/lit-extended.js?module';
import MyLitElement from './MyLitElement.js';

render(html`
  <p>${MyLitElement}</p>
`, ...);
```

**Comment by Lodin** [comment]
@dburles Until #274 is not merged, you can do the following:
```javascript
// MyElement.js
import {LitElement} from '@polymer/lit-element';

export class MyElement extends LitElement {
  static get is() {
    return 'my-element';
  }
  // component implementation
}

customElements.define(MyElement.is, MyElement);

// index.js
import { render, html } from 'lit-html';
import './MyElement.js'

render(html`
    <my-element/>
`, document.body);
```
When it is merged, you'll be able to do something like this:
```javascript
// MyElement.js will be the same
// index.js
import { render, html } from 'lit-html';
import { unsafeStatic } from 'lit-html/lib/unsafeStatic';
import {MyElement} from './MyElement.js'

const myElement = unsafeStatic(MyElement.is);

render(html`
    <${myElement}/>
`, document.body);
```
