### ISSUE TITLE
IE 11 not working

### ISSUE THREAD

**Issue by ajainvivek** [Polymer/lit-html#339]
`lit-html` seems to be not working on IE11. The template content returns `undefined`. Therefore we get the error `SCRIPT5022: NotSupportedError`.

I tried out the example `clock.js` using version `0.10.0`.

```
this.element = element; // returns the template
let content = this.element.content; // returns undefined, web components is not supported in IE11

// throws the exception in the line
let walker = document.createTreeWalker(content, 133 /* NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT |
                                                          NodeFilter.SHOW_TEXT */, null, false);
```

**Comment by bgotink** [comment]
Are you loading [the polyfill for the `<template>` element](https://github.com/webcomponents/template)? The `element` variable in the bit of code you posted is a HTMLTemplateElement, which IE11 doesn't support. Without the polyfill, templates won't have a `content` property.

**Comment by smalluban** [comment]
It is related to `shadydom` bug, which causes `template.content` to be `undefined`. I am sure I read about it in some issue or PR, but I can't find it now.

**Comment by ajainvivek** [comment]
@bgotink @smalluban I need to add polyfill `shadydom` to resolve the issue for IE11?

**Comment by smalluban** [comment]
What I see, current codebase is using `<template>` element directly, so it should work. IE11 has problem with using something like this:
```javascript
div.innerHTML = `<template>${...}</template`;
```

This kind of code is going to be introduced to support Firefox in https://github.com/Polymer/lit-html/issues/327 and this *will* break IE11, but currently it should work. I suppose you did not include [`webcomponents/template`](https://github.com/webcomponents/template) polyfill. The best idea is to use [`webcomponents/webcomponentsjs`](https://github.com/webcomponents/webcomponentsjs) package, which has all required polyfills included.

**Comment by bgotink** [comment]
ShadyDOM is not provided by `lit-html` (it is not included in the shady renderer either). The consumer of the library is responsible for brining the polyfills. 

Note that the template polyfill isn't the same as the ShadyDOM polyfill. Those are separate polyfills, shimming different parts of the webcomponents specifications.

**Comment by ajainvivek** [comment]
@bgotink Ah I get it, all the dependencies are added as `devDependencies` for `lit-html`. I didn't realize that anyways I have preferred going with plain template literal string injection. 

```
let template = `<style>.header { color: "red"; }</style><div class="header">Hello<div>` ;
document.body.innerHTML = template;
```
The above code serves me the purpose.
