### ISSUE TITLE
Please provide a browser-friendly version of lit-html, or a babel config/command to make one

### ISSUE THREAD

**Issue by erichiggins** [Polymer/lit-html#346]
I have a project where I'd like to use VanillaJS as much as possible.  Templates are the one piece that's missing and I'd really like to use `lit-html` (especially instead of React/JSX).  I would strongly prefer to avoid the need for a `package.json` or any type of build system to keep the project as minimal as possible. 

When I was looking into using `lit-html`, I noticed that I cannot use it directly in the browser (the use of `<script type=module>` is a non-starter).  The [README refers to using `babili`](https://github.com/Polymer/lit-html/blame/master/README.md#L336) (now deprecated/renamed to `babel-minify`0 and there are several closed Issues from other folks asking for something similar -- all were hand-waved away to figure it out on their own. 

Here's the problem: I don't want to have to also learn how to use Babel just to use `lit-html`.  Believe me, I've tried.  The docs are a mess, the developers assume you've already been using it for years in order to understand the terminology, it requires crazy configs, lots of dependencies (plugins) -- it's a mess and a rabbit hole.

All I and others are requesting is a browser-compatible version of `lit-html` that we can just start using.  I don't want to shave yaks,  I just want templating.

Similar requests:
* #60 
* #70 
* #141  
* #216

**Comment by justinfagnani** [comment]
modules work in the current version of all major browsers. There's no other format that loads in browsers and doesn't involve unsafe writing to globals to emulate exports.

You don't have to use Babel to use lit-html. Babili s just what we used for minification for that measurement.

**Comment by pwFoo** [comment]
I'm new with script type="module and unpkg.com. How could I use a local version of lit-html?
Is it a single file (https://unpkg.com/lit-html) to download or a package / directory (src)?

**Comment by web-padawan** [comment]
See https://github.com/npm-clones-for-bower/lit-html
