### ISSUE TITLE
HTML template result linting / validation

### ISSUE THREAD

**Issue by thescientist13** [Polymer/lit-html#350]
A nice feature of JSX / React / ESLint was that if an HTML tag was missing it's closing tag (for example) a linting error could be raised, ex.
```shell
 @ ./.cache/sync-requires.js 30:67-185

 WAIT  Compiling...                                                                                                                 10:17:16

 ERROR  Failed to compile with 1 errors                                                                                             10:17:17

 error  in ./src/pages/blog/2018/06/01/index.jsx

Syntax Error: Expected corresponding JSX closing tag for <p> (24:8)

  22 |             we would be happy to have you join the convesation<p>
  23 |
> 24 |         </div>
     |         ^
  25 |       </BlogPost>
  26 |     );
  27 |   }



 @ ./.cache/sync-requires.js 30:67-185
```

I notice that unclosed tags seem to "fail" silently when using **lit**.  

That said, I'm not sure (or assuming) that this in scope for **lit-html** but I think it makes for a nicer developer experience.  

I guess this is just to raise the issue here to see if this is something that would possible, or is maybe already a solved somewhere I didn't find?  (maybe it could be built on top of **lit**, or maybe it should be an ESLint preset or something like that?)

All thoughts / feedback welcome + appreciated.  Totally digging **lit-html** so far!  ✌️

**Comment by justinfagnani** [comment]
It's definitely possible, and tools like VS Code already offer intellisense on HTML in tagged literals.

The Polymer Analyzer already analyzes HTML, we likely just need some new rules for the Polymer Linter to offer this. Could you file a bug on http://github.com/Polymer/tools?

**Comment by thescientist13** [comment]
will do, thanks @justinfagnani !

**Comment by pshihn** [comment]
I've been using lit-html VS Code extension (https://github.com/mjbvz/vscode-lit-html) which has its bugs, but can be useful for basic sanity checks and code highlighting within the template string.

**Comment by thescientist13** [comment]
thanks @pshihn !  I just installed that recently and it is helpful indeed.  👍

**Comment by hyperpress** [comment]
I use it right now, but it breaks intellisense and color picker, which for
some reason is making me rage inside.
