### ISSUE TITLE
Use of render in docs

### ISSUE THREAD

**Issue by jakearchibald** [Polymer/lit-html#352]
https://polymer.github.io/lit-html/guide/index.html demonstrates using lit's render function.

https://polymer.github.io/lit-html/guide/writing-templates.html includes multiple examples of writing your own render function.

This feels confusing given the naming. Is one supposed to be instead of the other? Are they supposed to do similar things?

Feels like the `render` functions in the "writing templates" doc should be called something else.

**Comment by therocco** [comment]
Duplicate of #277

**Comment by jakearchibald** [comment]
Ah, yes
