### ISSUE TITLE
Spreading attributes

### ISSUE THREAD

**Issue by chabb** [Polymer/lit-html#354]
Hi

Is there a way to pass an arbitrary object whose keys will be rendered as attributes name, and values as attributes values ?

`<circle  ${..attributesToSpread} /> ` would render like
`<circle transform='...' style=' ' x='...'  some_other_attributes=some_other_values ..../>`

Thanks

**Comment by pshihn** [comment]
Here's one way:
You could write a util method that spreads the object as attribute strings
```javascript
function spread(x) {
  return Object.entries(x).reduce((prev, current) => {
    return `${prev} ${current.reduce((a, b) => `${a}="${b}"`)}`;
  }, '');
}
```

then when rendering you could call this method `${spread(attributes)}` which will return a string

**Comment by chabb** [comment]
@pshihn 
 I've thought about it
The issue is that lit-html see values in template as either an attribute value, or some text content.
If i use this approach, lit-html will try to link the value of `${spread(attr)}` to an attribute that does not exists ( which results as an error at the end )... one trick would be to add a special marker `...${spread(atttributes}}` that can be used to tell lit-html that there is a special case there, and then recreate a TemplateResultArray

**Comment by chabb** [comment]
and i just noticed that there was already a PR for that feature..
