### ISSUE TITLE
Relative path for CSS URL within <style> tag

### ISSUE THREAD

**Issue by manustays** [Polymer/lit-html#356]
Hi,

I am trying to load a background image which is stored relative to my module using the CSS background:url(...) syntax.

`background-image: url('./static/bg.svg');`

But the path is interpreted relative to main URL instead of the current module.

Is there any way to do so in lit-html?

Thanks.

**Comment by Lodin** [comment]
I think you could use `import.meta.url` in combination with CSS Variables here:
```js
const bgSvgUrl = new Url('./static/bg.svg', import.meta.url).toString();
html`<my-element style="--background-svg: url(${bgSvgUrl})"/>`;
```
However, be careful, AFAIK `import.meta` works only in Chrome for now.

**Comment by justinfagnani** [comment]
@Lodin is correct that `import.meta.url` is the correct solution here.

Our tools support import.meta.url for all browsers. We consider "full" modules support to include static import, dynamic import and `import.meta.url`. Without all three we compile to an AMD format that handles `import.meta.url` correctly.

**Comment by manustays** [comment]
Thanks, @Lodin. your approach of using inline CSS in the element with data binding worked. It should work for direct element styling.

As for the `import.meta` compatibility issue, I am currently using the module https://github.com/yairopro/resolveUrl

Although, I have only tested it myself with Chrome yet.

**Comment by manustays** [comment]
Thanks a lot, @Lodin and @justinfagnani!

But, it would require data binding and therefore support inline style attribute only (as shown in @Lodin's example). Is there a way to data-bind within the style tag block? I tried but didn't work.

Example:

`<style>
    .elem:hover {
        background-image: url(${bgSvgUrl})
    }
</style>
`

**Comment by jsilvermist** [comment]
AFAIK binding in `style` works where polyfills aren't needed, but is not recommended due to the entire stylesheet being recalculated after each change.

You would probably be best to set the value from Javascript.

**Comment by manustays** [comment]
Thanks, @jsilvermist.
