### ISSUE TITLE
Align NodePart and AttributePart interfaces

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#360]
Currently NodePart and AttributePart have slightly different interfaces, NodePart implementing the SinglePart interface and AttributePart implementing the MultiPart interface. This was done so that attributes and properties with multiple bound expressions would only be set once.

This ends up being a complication for directives, and most of the directives written work with NodeParts, but not AttributeParts. It also adds a small additional complexity to part handlings.

I'd like to simplify the part API to make directives easier to write, and as part of this unify the part interfaces.

This is an issue that's come up in the Template Instantiation proposal as well, and has inspired two ideas around dealing with attributes: 1) an "AttributeValueSetter" object, or 2) An explicit commit phase. I'm not sure we need to align perfectly with what Template Instantiation - if we keep the choice an implementation detail from both the lit-html user and the directive writer, we should be able to change in the future. We also might be able to give a sort of implementor feedback to the spec.

At the least I'd like to eliminate the `MultiPart` and `SinglePart` interfaces and turn `Part` into an abstract base class with a an abstract `setValue(v)` method. This would mean removing the interpolation functionality from `AttributePart` and moving it to an `AttributeValueSetter`-like object. This probably also means that `TemplateInstance` will need some new functionality to know when to commit an update, and some mechanism for committing parts with new values.

As part of this work it might also make sense to standardize how `_previousValue` is used, which will also make writing directives easier.

**Comment by depeele** [comment]
Will this also resolve #272?

**Comment by justinfagnani** [comment]
@depeele it'll make it possible for `until` to work against both, but attributes will need promise support added.

**Comment by justinfagnani** [comment]
Fixed in #400
