### ISSUE TITLE
How to implement routing in lit-html?

### ISSUE THREAD

**Issue by rahulbhondave** [Polymer/lit-html#378]
As a single page app, how can i implement url routing in lit-html?

**Comment by web-padawan** [comment]
You can use any router, as the lit-html is totally framework agnostic.

If you are looking for a router which works with Web Components, take a look at the `vaadin-router`: https://github.com/vaadin/vaadin-router

**Comment by justinfagnani** [comment]
lit-html is just a templating library. Use whatever routing library you wish. Loss of people seem to use page.js

**Comment by ernsheong** [comment]
There are some sample apps using LitElement, take a look at how they do it: https://polymer.github.io/pwa-starter-kit/sample-apps/

**Comment by fernandopasik** [comment]
PWA Starter kit routing approach is great! I manage to put all this in a route element here: https://github.com/fernandopasik/lit-redux-router

Feedback and contributions are very much welcomed!!

**Comment by hyperpress** [comment]
Very nice. I'm sure that a lot of incoming users will appreciate this.

<https://themesurgeons.com>

<https://themesurgeons.com>

**Comment by gfortaine** [comment]
[@lit-labs/router](https://github.com/lit/lit/tree/main/packages/labs/router#readme) https://github.com/lit/lit/discussions/3354
