### ISSUE TITLE
Enable/document extension by composition

### ISSUE THREAD

**Issue by jrunning** [Polymer/lit-html#380]
I'm eager to play with writing extensions for lit-html. The only example of an extension that the docs mention or link to is lit-extended. lit-extended imports `defaultPartCallback` from lit-html to extend the standard ``html`...` `` behavior. That works fine for lit-extended, but for third-party extension authors it doesn't.

If I write an extension, I don't know if the person using it wants to use it with lit-html or lit-extended. I could export two extensions, but that doesn't scale. Inevitably a user will want to use more than one third-party extension together. I think ideally they would be able to do this with composition:

```js
import { html as htmlExtended } from 'lit-extended';
import myLitExtension from 'my-lit-extension';
import anotherLitExtension from 'another-lit-extension';

const html = myLitExtension(anotherLitExtension(htmlExtended));
```

...or something like that.

I _think_ this may already be possible because a TemplateResult [has a `partCallback` property](https://github.com/Polymer/lit-html/blob/1a993e74411981e623c6d66cc2fb81ff279932f5/src/lit-html.ts#L51), but it's not clear to me what the "right" way to use it would be, if there is one.

So I'm not sure if what's needed here is some documentation around how to make extensions that can be composed, or code changes to that end, but it would be great to see it discussed.

**Comment by bgotink** [comment]
Composing extensions is indeed already possible at the level of the part callbacks. You'd need something similar to below (pseudo)code to create the composition you want:

```js
import {TemplateResult, defaultPartCallback} from 'lit-html';
import {extendedPartCallback} from 'lit-html/lib/lit-extended';

export const wrapPartCallback = (partCallbackFallback) =>
  (instance, templatePart, node) => {
    if (myPluginCanHandleThis(templatePart)) {
      return handleStuff(instance, templatePart, node);
    }
    return partCallbackFallback(instance, templatePart, node);
  };

export const createHtml = (partCallback) => (strings, ...values) =>
  new TemplateResult(strings, values, 'html', partCallback);

const html = createHtml(wrapPartCallback(defaultPartCallback));
const htmlExtended = createHtml(wrapPartCallback(extendedPartCallback));

// more composition:
import {wrapPartCallback as wrapSomeExtensionPartCallback} from 'some-other-lit-extension';
const htmlWithSomeOtherExtension = createHtml(
  wrapPartCallback(wrapSomeExtensionPartCallback(defaultPartCallback))
);
```

I like the idea of exposing a `createHtml` and `createSvg` from lit-html, because it gives extension authors / custom template syntax authors an API to use instead of having to basically copy the `html` and `svg` functions from lit-html and making the necessary changes.

Related question: How good are treeshakers at removing statements like these if the `html` variable is never used?

```js
const html = createHtml(defaultPartCallback);
```

If we need to do

```js
const html = /*#__PURE__*/createHtml(defaultPartCallback);
```

to get uglify to pick this up, it suddenly becomes a lot less interesting imo.

**Comment by justinfagnani** [comment]
@jrunning this is an interesting feature request, but it can be done currently with manual delegation, or a helper function. After merging mering lit-extended into core, and making TemplateProcessor a class that can be extended, I think I'd rather see a real world example before adding features to the library.

I'm going to close this for now in an effort to prune issues.
