### ISSUE TITLE
How do we access the DOM content or parent of a part?

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-html#388]
I want to access the DOM content of a part, so that I can add/remove events/observers.

For instance, something like this to only render the content part once it is visible:

```ts
import { directive, SinglePart, html } from '../../lib/lit-html/lit-html.js';

/** Custom event that fires when visible */
const visibleEvent = new Event('litvisible');

/** observer watching for intersection with visible area */
const obs = new IntersectionObserver(items => {
    for (const i of items)
        if (i.isIntersecting)
            i.target.dispatchEvent(visibleEvent);
});

/** Don't render content until it becomes visible.
 * @param content The content/part to render once visible. */
export const visible = (content: any) => directive((part: SinglePart) => {
    // Create a placeholder
    const placeHolder = document.createElement('span');

    // Fired when the intersectonal observer sees any part
    const onVisible = () => {
        // Remove the placeholder
        placeHolder.removeEventListener(visibleEvent.type, onVisible);
        obs.unobserve(placeHolder);
        placeHolder.remove();

        // Render the part
        part.setValue(content);
    }

    // Set up the observer to fire the custom event
    placeHolder.addEventListener(visibleEvent.type, onVisible, { once: true });
    obs.observe(placeHolder);

    // Set the content to be the DOM element?
    part.setValue(placeHolder);
});
```

Then I could do something like:
```ts
html`...
lots of content...
<div>
    ${visible(html`<slow-to-load></slow-to-load>`)}
</div>`
```

Working demo at https://stackblitz.com/edit/lit-html-visible

However, the events should really apply to the immediate parent or a fallback part (similar to `until`) - how should I access that DOM?

**Comment by justinfagnani** [comment]
A better Part API, which would include methods for accessing the DOM associated with a Part - it's parent Node, current content, and possibly its anchor Nodes, is definitely something I want for 1.0. You can get to those things now, but it requires using essentially the internal API of Parts.

If you want something like `until()`, 

```js
html`${visible(html`<slow-to-load></slow-to-load>`, 'Loading...')}`
```

```js
export const visible = (content: any, placeholder: any) => directive((part: SinglePart) => {
  part.setValue(placeholder);
  
  let sentinelNode;
  if (part.startNode.nextSibling === part.endNode) {
    // part is empty
    sentinelNode = document.createElement('span');
    part.setValue(sentinelNode);
  } else {
    sentinelNode = part.startNode.nextSibling;
  }
  // now observe with IntersectionObserver
});
```

As you can see, the `part.startNode.nextSibling === part.endNode` bit requires pretty inside knowledge of a Part. The only problem with giving a nice API to access the content is that the DOM doesn't make it easy. We can't return a DocumentFragment, or a NodeList that I know of. We could return a Range, but it has a similar API to Part. One thing we could do is make the API even closer to Range and add a `.collapsed` (or maybe `.empty`) getter.

**Comment by KeithHenry** [comment]
Cheers @justinfagnani!

How final are those inside details?

Would something like this be worth adding as a directive to lit-extended?

**Comment by justinfagnani** [comment]
lit-html 2.0 adds an `element` property to non-ChildParts (AttributePart, etc.), which should address this pretty well. We still have `startNode` and `endNode` on ChildPart (nee NodePart).
