### ISSUE TITLE
__templateInstance vs WeakMap?

### ISSUE THREAD

**Issue by sgentle** [Polymer/lit-html#394]
Hi! Really digging this project's approach.

I notice you're setting `__templateInstance` on DOM nodes/document fragments to map them to template instances. Would a `WeakMap<Element|DocumentFragment, TemplateInstance>` work just as well?

Seems like it'd be a bit nicer, and as I understand it the polyfills for `WeakMap` do basically the same thing anyway...

**Comment by justinfagnani** [comment]
I didn't realize WeakMap was supported by IE11 and Chrome 41. I think we can use it.
