### ISSUE TITLE
Nested asyncAppend loaded controls re-render with undefined properties

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-html#397]
I have a control that uses `until` and then `asyncAppend` to lazy load entities.

Each entity is set into a control which has further sub controls.

This causes a lot of errors: `Cannot read property 'whatever' of undefined`, but `undefined` is never passed in - every instance should have a value set.

It also gets lots of `Setting properties in response to other properties changing considered harmful. Setting 'whatever' from 'undefined' to '[object Object]'` but the property is only ever set by the loop and is read-only in the child controls.

Here is the error: https://asyncappend-bug.stackblitz.io/

Here is the source: https://stackblitz.com/edit/asyncappend-bug?file=grand-child.js

Examples may only work in Chrome because I've used an `async *` function for the demo.

**Comment by ruphin** [comment]
I can't reproduce the error in the page you linked. Can you confirm this is still happening?

**Comment by KeithHenry** [comment]
It appears to be fixed by 0.11 in my stackblitz simple reproduction - I'll double check in the (more complicated) source where I originally observed the issue and see if it's fixed there too.

**Comment by justinfagnani** [comment]
If this is still a problem, please reopen :)
