### ISSUE TITLE
asyncReplace and asyncAppend cannot map to template

### ISSUE THREAD

**Issue by lucaelin** [Polymer/lit-html#406]
I was trying to give async generators a go to stream some data, when I noticed that i could not use the mapper argument to create a template from the value, like so:
```
render(html`${asyncReplace(asyncIterable, i=>'v: ' + i)}`,      working); // -> v: 0 ... v: 1 ...
render(html`${asyncReplace(asyncIterable, i=>html`v: ${i}`)}`,  notworking); // -> [object Object] ... [object Object]
```
I have a reproduction of this issue here: https://codepen.io/anon/pen/yqgVZa

**Comment by lucaelin** [comment]
And for completeness: https://codepen.io/anon/pen/WKRRXR?editors=1011
Using the generator to return a template directly into these functions (without the need for a mapper) has the same issue.

**Comment by justinfagnani** [comment]
I can't reproduce with 0.13.0: https://codepen.io/justinfagnani/pen/RqQZKj
