### ISSUE TITLE
Docs are ahead of npm

### ISSUE THREAD

**Issue by claytongulick** [Polymer/lit-html#410]
I think maybe the trigger got pulled on the docs at https://polymer.github.io/lit-html/guide/ a bit early, the version that's in npm - 0.10.2 doesn't support the new syntax. If a developer new to lit comes into it today, they'd be pretty confused.

I get this is a short term issue until the next npm release, but we should probably at least indicate in the docs that they are for the next version and not compatible with 0.10.2.

I'll do a quick PR with some text to that effect to try to help reduce confusion.

**Comment by aaronshaf** [comment]
Yes, please revert the docs until the new version is released :)

**Comment by jpierson** [comment]
Agreed, this bit me and it took me two hours to figure out what was going on.

Example: https://github.com/Polymer/lit-html/issues/432
