### ISSUE TITLE
Part type detection breaks with '>' in attribute content

### ISSUE THREAD

**Issue by ruphin** [Polymer/lit-html#418]
Lit fails to correctly parse the type of the following part:

```javascript
html`<div a=">" b=${0}></div>`
```

This is because to detect the part type, lit checks the last occurrence of a `<` character, and tests if it is proceeded by a `>` character to check if the last HTML tag has been closed. This does not work in the above case, because the string `<div a=">" b=` has a `>` character after the last `<` character. In this example the `${0}` part is incorrectly identified as a NodePart.

More generally, if any `>` character occurs inside an attribute before an AttributePart on the same Node, lit incorrectly identifies that part as a NodePart.

Here is a [reproduction](https://codepen.io/ruphin/pen/mjmRWQ?editors=1010)

I have not found an easy solution to this problem yet.

**Comment by ruphin** [comment]
The solution I am pursuing is changing the node marker tag to something like this:

```
`<!--${nodeMarker} " ${brokenMarker} -->`
```

When a node contains the value of `brokenMarker` as a boolean attribute, I know that the above issue has occurred, and I can raise an error. The above tag works both if the attribute that is escaped is and is not surrounded with `"`, so it works in both of the following cases:

```
<div a=">" attr=${0}>
```

```
<div a=">" attr="${0}">
```

I haven't found a way to gracefully fix the situation, but at least this reliably detects it without any overhead.

**Comment by justinfagnani** [comment]
There are lots of ways to write broken templates. While it'd be great to catch all of these at runtime, it's a tradeoff on difficult and cost. I'm pretty comfortable saying that users need to use `&gt;` in place of `>` in attribute value literals. I think a static linter can catch these errors more reliably.

**Comment by ruphin** [comment]
I have done some research on this problem specifically and I think there is no good solution. The best we can do is detect it at runtime _if_ you accept some limitations to attributes (no surrounding `"`), but without a full HTML parser it is not possible to fix at runtime.

Fixing it through linter is a good idea.

**Comment by justinfagnani** [comment]
With a rule in eslint-plugin-lit, I think we'll be good here, or as good as we can be for now. I'm going to close this to track for the upcoming releases. Thanks for the report!
