### ISSUE TITLE
how to check if a lit-html component got unmounted

### ISSUE THREAD

**Issue by fopsdev** [Polymer/lit-html#419]
hi there

i'm using straight forward lit components like:
A.js
```
import { html } from "lit-html/lib/lit-extended.js"
import { repeat } from "lit-html/lib/repeat.js"
import {    Data
} from "../library/index.js"
import { B } from "./B.js"


export const A = props => html`
<h2>${Data.A} </h2>
  <ul>
      ${repeat(
          Data.B,
          i => i.id,
          i => {
             return B(i)
          }
      )}
    </ul>`
```
How can i detect now if A or B got unmounted? (B is a nested lit-html element)

**Comment by justinfagnani** [comment]
If **A** and **B** are custom elements, then just implement `disconnectedCallback`.

**Comment by fopsdev** [comment]
thanks!
...and if they are just lit-templates which i render using lit render function?

**Comment by fopsdev** [comment]
... i'm thinking of using mutationObserver on every parent and make sure that a parent only gets observed once...

**Comment by justinfagnani** [comment]
> ... i'm thinking of using mutationObserver on every parent and make sure that a parent only gets observed once...

Sounds like you'd be starting to reimplement the Custom Elements polyfill. Why not just use custom elements? They exist exactly to participate in the DOM tree and receive the lifecycle callbacks like `disconnectedCallback`.

**Comment by fopsdev** [comment]
the only thing i'm concerned a bit is that in this case i'm after the banana... and by using another module-x i maybe get the gorilla holding the banana, if you know what i mean :)
reading up on custom-elements now, thanks for the advice :)

**Comment by aadamsx** [comment]
I'm just starting out with lit-html, and share @fopsdev's attitude... if I can get things done with lit-html, even if I have to jump a few more hoops, I'd rather stay as minimal as possible and not introduce more libs/dependencies.

Having said this, where do you find Custom Elements polyfill?  Also, @fopsdev, is there some place I can reference to start making use of lit-html for my templates?  What are you using for client side state?  How are you communicating with the server and what are you using server side (I was thinking of using Apollo Server)?

Thanks!

**Comment by web-padawan** [comment]
@aadamsx you might be interested in this list: https://github.com/web-padawan/awesome-lit-html

**Comment by aadamsx** [comment]
@web-padawan wow, this is much more thank I expected, thank you for this!

**Comment by fopsdev** [comment]
@aadamsx 
i'm using https://github.com/cerebral/overmind for my client side state management. overmind is still fairly new but its supposed to be a successor to cerebraljs which i've also used in a few production sites and was quite happy with.
i'm still using good old rest api's to communicate with my servers which i'm doing in ms sql and sort of web api.
i'm a bit on hold with my tries to make lit-html even more resource friendly because i have other work to do. but i9 can't wait to give it another spin soon. because my components solely depend on overmind-state (=> so each component knows exactly when it needs to be reevaluated) and some parent-child params i'm fairly positive to create a caching layer which could improve lits performance (no measures yet). 
hope that helps you!

**Comment by aadamsx** [comment]
@fopsdev , thanks for the advice.  How would you compare overmind to redux (which is the state lib I was planning on using)?

**Comment by justinfagnani** [comment]
I'm going to close this one for now. The component case is handled in the platform with disconnectedCallback(). Directives possibly needing to know when they're unmounted is discussed in #283.

**Comment by Legioth** [comment]
I encountered something that looks like a workaround when looking at how `lit-translate` works: https://github.com/andreasbm/lit-translate/blob/9ccd057dde2c12972d9b7c9b63e61d467d7e6c50/src/lib/cleanup.ts#L16-L26
