### ISSUE TITLE
optimizing start render dom position

### ISSUE THREAD

**Issue by fopsdev** [Polymer/lit-html#420]
hi there

lets say i have a tree structure like:
```
A
|__B
    |__C1
    |__C2
   ...
```
whereas A,B and C are nested templates.
now C1 changes (my component detects that). So i would like to start the rerender at dome node id from B.
now the point is when i inspect a rendered lit-tree i cannot find some useful dom id's which i could use.
or i could also rephrase this question to:
how can i access B directly with document.getElementById(..) when it was rendered starting from A using nested templates?

**Comment by justinfagnani** [comment]
Re-rendering from **A** should not be a problem. lit-html is designed to do minimal work when re-rendering DOM when data hasn't changed.

If for some reason you are seeing a performance problem with that, first I'd like to hear about it :)

Then, you should be able to call `render()` with **B** and **B**'s template, as long as you have a reference to **B**. How you get that reference is up to you, but `A.querySelector(somethingAboutB)` should be fine. I'd just put an id attribute on **B**.

**Comment by fopsdev** [comment]
ok, yeah i know, performance is not an issue currently. just wanna make sure that least amount of processing is done without using vanilla and a lot of imperative code :)

> I'd just put an id attribute on B.

thats what i basically did :) do you know how this could be abstracted so i don't have to put the id manually everytime?

**Comment by justinfagnani** [comment]
> do you know how this could be abstracted so i don't have to put the id manually everytime?

Like I said, jus re-render A. Doing the least processing is what lit-html is for.
