### ISSUE TITLE
Boolean attributes not rendering

### ISSUE THREAD

**Issue by positlabs** [Polymer/lit-html#433]
[Demo of the issue](https://codepen.io/positlabs/pen/YjMPBZ)

[In the docs](https://polymer.github.io/lit-html/guide/writing-templates.html), there is an example of how to set boolean attributes.

```
html`<input type="checkbox" ?checked=${checked}>`
```

However, it doesn't render the attribute when I try it.

```
html`<input type='checkbox' ?checked=${true}></input>`
// yields <input type='checkbox'></input>

html`<div foo=${true} ?fizz=${true} buzz$=${true}></div>`
// yields <div buzz="true"></div>
```

**Comment by ruphin** [comment]
This is because the docs are ahead of the latest release, and this syntax does not work yet.

To install lit-html with the new syntax, install the development release: `npm install --save lit-html@dev`

**Comment by positlabs** [comment]
That did the trick, thanks!

**Comment by pitus** [comment]
I do, however have a problem with checkbox attribute / state rendering.
It works correctly when using ?checked="${state}" ... until I click on the checkbox.
Once clicked, it no longer reacts to state change but remains unchecked (or checked, whatever the last click produced).
This is similar to how input value="${val}" only renders it until we manually change the input value via UI, then it no longer reloads new val, however .value="${val}" will correctly refresh new val (which was a painful process to figure out we should use the property not attribute syntax).
Is there a working equivalent solution for checkboxes (or boolean properties in general) ?
For now I'm forced to find the checkbox by ID and set its .checked property via javascript rather than declaratively, which is a major pain :(

**Comment by pitus** [comment]
Here's an example of how `?checked` is ignored completely **once the checkbox was manually clicked**, while `.checked` seems to be behaving correctly (no timeouts actually, just correct behavior).
Declare a `test: { type: Boolean }` property & then render the following and try clicking various checkboxes:
```
	TEST 1: <input type="checkbox" ?checked="${this.test}" @click="${e => this.test = e.target.checked}"/>
		<input type="checkbox" ?checked="${this.test}" @click="${e => this.test = e.target.checked}"/>
		<b>${this.test}</b> using ?checked<br>
	TEST 2: <input type="checkbox" .checked="${this.test}" @click="${e => this.test = e.target.checked}"/>
		<input type="checkbox" .checked="${this.test}" @click="${e => this.test = e.target.checked}"/>
		<b>${this.test}</b> using .checked<br>

```

**Comment by justinfagnani** [comment]
The solution for `checked` is the same as for `value` - bind to the property.

We should make sure that we don't have `?checked=${}` in the docs because of that. `?hidden=${}` is a better example.

**Comment by pitus** [comment]
Well, ?disabled is not a problem because we can't disable the control manually from UI so it works fine. The problem is only with attributes that the user can change from the UI such as value= or ?checked=

**Comment by ruphin** [comment]
Well, lit-html is just a rendering engine. It's up to the developer to respond to user interaction and change the state of the application accordingly. Lit-html can't do this for you, but you can use it to attach event listeners.

**Comment by pitus** [comment]
Well, I suppose, this should have been a lit-element issue not lit-html ;)

**Comment by nboisteault** [comment]
In my case neither
`<input type='checkbox' ?checked=${true} />`
nor 
`<input type='checkbox' .checked=${true} />`

Are able to force checked state when rendered.

**Comment by KatWorkGit** [comment]
For anyone else stumbling on this issue via google, I was able to find a solution using Lit 3.0.0 using the following (in a typescript based project):

```typescript
type ToggleSwitchDisabled = 'true' | 'false' ;

@property({type: String, attribute: 'disabled'})
disabled: ToggleSwitchDisabled = 'false';

@property({type: Boolean})
toggled : boolean = false;

activated() {
    this.toggled = !this.toggled;
}

render() {
  return html`
    <label class='toggle-switch'>
        <input 
                type='checkbox' 
                ?disabled=${this.disabled === 'true'} 
                ?checked="${this.toggled}" 
                @change="${this.activated}"
        />
        <span class='slider'>d=${this.disabled} c=${this.toggled}</span>
    </label>
    `;
}
```
