### ISSUE TITLE
Update CSS <style> tags dynamically

### ISSUE THREAD

**Issue by yorrd** [Polymer/lit-html#435]
I'm not sure if this is by design or whether I'm not doing something correctly or whether this is a bug:

```
      <style>
        :host {
          --feedback-height: ${this.expanded ? '70vh' : '60px'};
        }
      </style>
```

I update `expanded` to be true or false, but the style doesn't change. In the inspector, the value doesn't change either. This does not only happen with css variables, it also doesn't work with the usual properties (`background-color: ${condition}`).

I'd appreciate a clarification :)

**Comment by justinfagnani** [comment]
Are you using ShadyCSS? Style bindings are not supported with ShadyCSS because styles are globalized and you can't have pre-element variations.

**Comment by justinfagnani** [comment]
Closing as a bit out of scope for lit-html. Whether or not styles can be updated is environment dependant, but lit-html supports it if the environment does.

**Comment by AnisTss** [comment]
Is there any way to have a similar syntax to this `--feedback-height: ${this.expanded ? '70vh' : '60px'}` working with lit-html ?

**Comment by CaptainCodeman** [comment]
Set the css property from JS, apply it in CSS, no need to try and make it part of the template:

### CSS
```css
:host {
  height: var(--feedback-height);
}
```

### JS
```js
this.style.setProperty('--feedback-height', this.expanded ? '70vh' : '60px')
```

**Comment by AnisTss** [comment]
I was able to achieve this using the [styleMap] (https://lit-html.polymer-project.org/guide/template-reference#stylemap) directive. Thank you for your help.
