### ISSUE TITLE
undefined/null attribute gets rendered as 'undefined'

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#437]
When rendering attributes, switching from a value to undefined causes 'undefined' to be set literally in the DOM.

This seems unexpected, how else do we let the renderer know that an attribute should no longer be set? See: http://jsbin.com/qigigavaqu/edit?html,output for a reproduction.

If you inspect the dom, you will first see `<div foo="bar"></div>`. After clicking the button, you wil see `<div foo="undefined"></div>` 

The same behavior is observed when rendering a null attribute

**Comment by LarsDenBakker** [comment]
I was going to make a PR for this, but I see that this behavior is somewhat captured in a test: https://github.com/Polymer/lit-html/blob/master/src/test/core_test.ts#L193 so I'm wondering what the intended behavior is.

**Comment by ruphin** [comment]
For attributes, the default behaviour is to simply `String()` whatever you return, and returning an empty string is the closest you can get to rendering nothing.

You could use a directive to get the behaviour you describe, should be fairly straightforward.

**Comment by LarsDenBakker** [comment]
Then it's unexpected that html`<div foo="${undefined}"></div>` renders as `<div></div>`. I'm running into this while rendering aria attributes, I'm not sure how picky screen readers about empty attributes.

**Comment by ruphin** [comment]
That does seem like inconsistent behaviour.

Lite-html renders `<div foo=${ undefined }></div>` as `<div
foo=”undefined”></div>`, which is what I assumed was also the behaviour of
lit.

I'll do some compatability research on it

**Comment by ruphin** [comment]
`NodePart` has an undefined check that sets the value to emptystring if it is undefined or null:

`value = value == null ? '' : value;`

Currently `AttributePart` does not have this check. I think for consistency, either both `NodePart` and `AttributePart` should have this behaviour, or none of them should.

**Comment by justinfagnani** [comment]
The reason that `undefined` pass though in attributes is from a desire to stay close to the behavior of `setAttribute`, which renders both null and undefined as the strings "null" and "undefined".

a Text node however doesn't render `undefined` - that becomes an empty text node. The check we have in NodePart#_commitText is for `null`, which is rendered as "null". I agree that's a bit inconsistent, but NodePart will never render "undefined" because we'd have to specially make it do that.

**Comment by justinfagnani** [comment]
Marking "low" only for now because it's basically working as intended.

@LarsDenBakker points out that this is arguably solved by #440, though that requires opting in.

**Comment by ruphin** [comment]
I was just looking into this, and I agree that the current behaviour is desirable.

What I don't understand is why this happens:

```javascript
html`<div attr=${undefined}></div>` // => <div></div>
```

I went through the code but I can't find why the initial `undefined` leads to an empty attribute. If we want to be consistent here, it should render `<div attr="undefined"></div>`

**Comment by justinfagnani** [comment]
That sounds like a bug, and I thought we had a test for this and that @bgotink fixed it.

**Comment by justinfagnani** [comment]
Ah, the test was for undefined in an interpolation: https://github.com/Polymer/lit-html/blob/master/src/test/lib/render_test.ts#L425

**Comment by ruphin** [comment]
I just submitted a PR that fixes another bug in AttributeParts, maybe it's somehow related (although I doubt it).

**Comment by ernsheong** [comment]
My 2 cents is that this is a bug because... name an occasion where a developer really wants `"undefined"` to be rendered as the attribute value. Hardly any.

**Comment by justinfagnani** [comment]
@ernsheong `setAttribute(undefined)` renders "undefined". If `name=${value}` is syntax for `setAttribute`, then it should too.

> With lit-element's refactor and the removal of object argument in render, there is no longer a last frontier default value check before hitting lit-html.

I don't quite parse this. What object argument in render?

**Comment by ernsheong** [comment]
Hi @justinfagnani I was referring to https://github.com/Polymer/lit-element/tree/refactor where `render` no longer takes a properties argument (which was useful to quickly set default values).

Anyways I don't think setting to "undefined" causes any malfunctioning browser behavior, for now. More like something died in the developer.

**Comment by jsilvermist** [comment]
@ernsheong you can still do the same thing as before like:
```js
const { propA, propB = true } = this;
```

**Comment by justinfagnani** [comment]
I think we have sufficient ability to control how attributes are rendered with boolean attribute syntax, `ifDefined()` and ternaries to convert `undefined` -> String. Given that we don't know whether we should remove or set to an empty string for `undefined`, I'm more comfortable sticking with the same behavior as `setAttribute`.
