### ISSUE TITLE
Error when using property binding notation

### ISSUE THREAD

**Issue by SnareChops** [Polymer/lit-html#444]
> lit-html@0.10.2

In your example you state that property binding follows the syntax
```html
<some-element .prop=${someValue}></some-element>
```
However when running with
```javascript
html`<grid-row row="${r}" .map=${this.map}></grid-row>`
```
The application errors with
```
lit-html.js:436 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '.map' is not a valid attribute name.
```
Looking into the library a bit I see that there is a class `AtributePart` that uses the `AttributeCommitter`. Then not too far below it there is a `PropertyCommitter` and a `PropertyPart extends AttributePart` which seems great, but the committer is not being overwritten with the `PropertyCommitter`... Could this be what is going on here? Or is the documentation wrong / property binding is not supported?

A more detailed example of the use case for clarification

```typescript
class GridArea extends HTMLElement{
  map: GameMap = someGameMapObject;

  connectedCallback(){
    let rows: TemplateResult[] = [];
    for (let r = 0; r < this.map.rows; r++) {
      rows.push(html`<grid-row row="${r}" .map=${this.map}></grid-row>`);
    }
    const template = html`${rows}`;
    render(template, this);
  }
}
customElements.define('grid-area', GridArea);

class GridRow extends HTMLElement{
  map: GameMap;
}
customElements.define('grid-row', GridRow);
```

The potentially and possibly misguided expectation is that setting `.map` on the `grid-row` would not create an attribute `.map` with a value of `[object Object]` but instead set the property `map` on the `GridRow` instance.

**Comment by ruphin** [comment]
The `.`-prefixed syntax is new and is not yet available in the latest release. You need the `0.11.0-dev.2
` release to try out the new syntax.

What version of `lit-html` are you on?

**Comment by SnareChops** [comment]
@ruphin Ah I see. thanks. I'm on `0.10.2` so I'll try the new version.
