### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by russellbeattie** [Polymer/lit-html#449]
I used Rollup to bundle the lit-html.js output into a single file, and it warned of a circular dependency: 

`$ rollup lit-html.js --file lit-html-bundle.js --format esm`

`(!) Circular dependency: lib/template-result.js -> lib/template-processor.js -> lib/parts.js -> lib/template-result.js`

**Comment by ruphin** [comment]
This is a consequence of splitting up the codebase into multiple files. It's not a problem, everything still works as intended. The way to get rid of this warning is to have the whole library defined in a single file which is not beneficial for maintenance.

**Comment by justinfagnani** [comment]
Circular dependencies are fine in JS modules. I'm not sure why Rollup warns by default, but it's fairly easy to turn off. See the Rollup config in this repo.
