### ISSUE TITLE
bindings in <template> not working

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/lit-html#45]
```js
const who = 'world';
render(html`<template id="res">hello ${who}</template>`, document.body);

// `hello {{}}` instead of `hello world` :(
console.log(document.getElementById('res').innerHTML);
```

**Comment by justinfagnani** [comment]
Oh, interesting...

I suppose we have to walk into nested template contents when preparing a template.

**Comment by justinfagnani** [comment]
@valdrinkoshi #50 starts us on the path to being able to fix this. Because it does a recursive walk on the template, rather than using a TreeWalker, we can choose to special-case <template>s and recurse into them.

How critical is this?

**Comment by valdrinkoshi** [comment]
The fact that we're using a template literal with a template element within it it's a bit strange, I know, but nevertheless I think it's important we support it for inter-op.

I've been updating [iron-overlay](https://github.com/PolymerLabs/iron-overlay) to use lit-html.
`<iron-overlay>` gets a template via distribution, stamps it and hosts it in a stacking-context-safe node (e.g. `<body>`). It relies on `<template>` so that the overlay content gets created and appended only when needed.
Another similar example is `<iron-list>`, which gets the item template via distribution.
If I want to use `<iron-list>`, I have to pass a template:
```js
const templateResult = html`
<iron-list items=${props.items}>
  <template>
    <div> lit-html binding: ${props.userName}, polymer binding: [[item]] </div>
  </template>
</iron-list>`;

**Comment by justinfagnani** [comment]
Well, with #50 I think we can do this, but it might be a bit confusing to deal with two separate data-binding systems. The lit-html bindings are going to change the `<template>`'s content. You have that right above, but I wonder how many would get that distinction immediately.

It's be nice to have an iron-list that took something even a bit more abstract than template elements, maybe a function that produces DOM (something like `(item, index) => Node`).

**Comment by mkorenko** [comment]
What about event binding?
```html
<iron-list items="${items}">
  <template>
    <div on-click="${(e) => this.onItemClick(e)}">
      [[item]]
    </div>
  </template>
</iron-list>
```
Does not work in #50
