### ISSUE TITLE
Custom elements should be connected after being updated

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#453]
There's currently a difference between `TemplateResult`'s processed via `render` and those handled by `NodePart` in a "nested" `TemplateResult`. The former updates prior to being attached to the DOM, but the latter does not. 

This can cause an issue if a custom element processes state in the `connectedCallback`. Elements made with `Polymer` and `LitElement` (prior to version `0.6`) do this, and when used in a nested `TemplateResult` these elements render with default state and then update with the state set by `lit-html`. This is inconsistent with non-nested `TemplateResult`'s and less efficient. 

The fix is simple, just update the instance before https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L267.

**Comment by ruphin** [comment]
I need to fix this in `lite-html` too. I'll see if I can make a PR that fixes this too.

**Comment by justinfagnani** [comment]
@ruphin I'm about to do a release and wanted to get this fix in, so I'm making a PR right now.

**Comment by justinfagnani** [comment]
@ruphin actually, scratch that. the 0.11.0 release is more important right now and we realized that this actually _isn't_ different from `render()` so that needs to be changed too.

**Comment by ruphin** [comment]
My PR is already in

**Comment by ruphin** [comment]
My PR is failing tests that explicitly check that setters are called _after_ upgrading. Which is the desired behaviour? Setting properties before or after elements are upgraded?

**Comment by ruphin** [comment]
The more I look at this issue the more confused I get. The 0.11.0 release contains some changes that specifically made sure properties were set after upgrading elements. :/

**Comment by justinfagnani** [comment]
This issue isn't about _update_, but _update_ lit's phase where it sets properties.

This is for custom elements that might do synchronous rendering work on being connected. If we connect then update, we'll cause more work. If we update then connect, the initial render will contain the correct values.

**Comment by justinfagnani** [comment]
> I'm not exactly sure what you mean with that first comment.

Sorry, I had a typo there, it should have been:

> This issue isn't about _upgrade_, but _update_: lit's phase where it sets properties.

The order we want is:

1. Clone
2. If polyfill: Upgrade
3. Update
4. Connect

You PR fixes that by moving update() before _commitNode()
