### ISSUE TITLE
Support device with no native template implementation

### ISSUE THREAD

**Issue by zeroliu** [Polymer/lit-html#464]
We are currently looking into experiment lit-html on the browsers that do not have native template element support. The webcomponents template polyfill seems overkill for the template use cases in lit. It would be nice if we can provide a lightweight fallback solution in lit-html core.

**Comment by justinfagnani** [comment]
Babel, TypeScript and Closure all support template literals. Template Literals are syntax, so they can't be polyfilled.

**Comment by justinfagnani** [comment]
We'll add this to the docs. Closing now as there's nothing to do on this end.

**Comment by justinfagnani** [comment]
Ah! Sorry, I was reading too quickly!

We indeed have plans to support browsers without `<template>` without the polyfill, and I was indeed talking to you about this on Monday. oops 😬

**Comment by zeroliu** [comment]
Here's a very rough idea: https://github.com/Polymer/lit-html/pull/466/files
Probably not covering all use cases though...

**Comment by LarsDenBakker** [comment]
Should we expect to see a large performance difference on browsers like IE11 with this? The template polyfill seems quite slow on IE.

**Comment by justinfagnani** [comment]
This is basically what the template polyfill does, so I'm not sure we'll see any gains in rendering, but you won't have to load the polyfill, so there's a relatively easy size win.

**Comment by justinfagnani** [comment]
THis was fixed by #466
