### ISSUE TITLE
CSS styles bug - different results crossbrowser

### ISSUE THREAD

**Issue by xkotj** [Polymer/lit-html#471]
Hello, I've been testing Polymer/lit-element and Polymer/lit-html a lot for few months.
I' am not sure if I do somethinng wrong, but when I create basic element and use code below in render method I get different results in chrome and firefox.:

`      <style>
        .tenant-card {
          display: flex;
          flex-direction: column;
          text-align: center;
          border: 1px solid black;
        }
      </style>
      <div class="tenant-card">
        <div>NAME</div>
        <div>DESCRIPTION</div>
        <div>0</div>
      </div>
`

Tested on:
Lit-Element 0.5.2 and latest dev (6.)
Lit-html 0.11.0

Expected result - chrome:
![image](https://user-images.githubusercontent.com/42933817/44984144-0507c180-af7c-11e8-89f8-69c152a2c5b9.png)

Bad result - FF
![image](https://user-images.githubusercontent.com/42933817/44984192-2b2d6180-af7c-11e8-914d-469dff1ef6f7.png)

When I use code above in simple index.html file it renders as expected in both browsers.

FF - 61.0.2
Chrome -  68.0.3440.106

Is it a bug of lit-html?

**Comment by ruphin** [comment]
This looks like a problem with the webcomponents polyfill. Which version of webcomponentsjs are you using?

**Comment by xkotj** [comment]
In package.json I' ve got "@webcomponents/webcomponentsjs": "^2.1.1"

**Comment by xkotj** [comment]
Found the issue. It is connected to components name. You named it 'my-element', but when I name it 'tenant-card'. It gets badly rendered in FF. 

<tenant-card></tenant-card>
customElements.define('tenant-card', MyElement);

**Comment by xkotj** [comment]
Here is the code.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Lit-element example</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Polyfills only needed for Firefox and Edge. -->
    <script src="./node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
  </head>  
<body>
  <tenant-card></tenant-card>
  <script>void(0);</script>
  <script type="module">
  import {LitElement, html} from '@polymer/lit-element';

      class TenantCard extends LitElement {

        _render() {
        return html`
          <style> 
            .tenant-card { display: flex; flex-direction: column; text-align: center; border: 1px solid black; }
          </style>
          <div class="tenant-card">
            <div>NAME</div>
            <div>DESCRIPTION</div>
            <div>0</div>
          </div>
        `;
      }
      }

      customElements.define('tenant-card', TenantCard);
  </script>
</body>
</html>
```

**Comment by web-padawan** [comment]
@xkotj you shouldn't use CSS class name same as element name, as it is used for scoping.

See wencomponents/shadycss#113 and webcomponents/shadycss#134

**Comment by ruphin** [comment]
If you think your problem is resolved, you can close this issue. :)
