### ISSUE TITLE
The link in README.md to CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by MarkJamesHoward** [Polymer/lit-html#474]
At the bottom of the README.md file the link to the CONTRIBUTING.md file is broken as the url is not provided. So currently it is as below:

## Contributing
Please see [CONTRIBUTING.md]()

It should be:

## Contributing
Please see [CONTRIBUTING.md](https://github.com/Polymer/lit-html/blob/master/CONTRIBUTING.md)

**Comment by justinfagnani** [comment]
Thanks for letting me know, it's fixed now.
