### ISSUE TITLE
[0.11.0/0.11.1] Render value doesn't update in markup

### ISSUE THREAD

**Issue by aadamsx** [Polymer/lit-html#478]
I'm using lit-element 0.6.0-dev.6/webcomponentsjs 2.1.1, and lit-element uses lit-html 0.11.0 at the moment.  I ran into an issue that might be a bug with lit-html.

Basically the value in the LitElement class increments/decrements (you can see from the console logging), but after lit-html renders the this.value initially, the property on the class doesn't display the changes in markup.

To make things easier, I built a repo to reproduce the issue:  https://github.com/aadamsx/meteor-lithtml

Just a note, even though I'm using lit-element's version of lit-html, I have lit-html version 0.11.1 installed in this project as well.  I tried using the lit-html 0.11.1 on it's own, but got the same results.

Also, I opened the same issue in lit-element as I'm not sure where the problem is: https://github.com/Polymer/lit-element/issues/174

**Comment by justinfagnani** [comment]
@aadamsx any chance you can make a cliet-side only reproduction, ideally on something like Stackblitz, jsbin, Glitch, etc., so I can directly look at it?

**Comment by aadamsx** [comment]
Is there any way you could clone the repo to check it out, that way you can tell if the client side code is correct and has all the deps it needs?  I can help if you run into issue with the repo?

In this case Meteor is just the build tool.

**Comment by aadamsx** [comment]
I tried to pull something together on stackblitz, but it throws for some reason: https://stackblitz.com/edit/js-1uf5w3?file=index.html

**Comment by aadamsx** [comment]
I think I found the issue.  I believe it's with the decorators.  When I remove the decorator property and instead add it as a static get, the increment/decrement works as it should.  

You can see it here, https://jsfiddle.net/aadamsx/9ny1axdr/15/.

If you look at the code in my original repo: https://github.com/aadamsx/meteor-lithtml, I have decorators set up correctly using babel.

Added the following dependencies:

``` 
// package.json
@babel/plugin-proposal-class-properties: 7.0.0
@babel/plugin-proposal-decorators: 7.0.0
```

and the .babelrc config:

```
// .babelrc
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```

After added this into the project, it complies correctly and displays the inital value.  But it will not increment or decrement with the decorator.  

```
// x-counter.js
class XCounter extends LitElement {
  @property({type: Number})
  value = 0;

  ...

```

Replacing the above with a static allows the increment and decrement values to DISPLAY.  I say that in caps, only to say if you console log, the value is actually changing, just not being displayed.

```
// x-counter.js

// THIS_WORKS
class XCounter extends LitElement {
  // @property({type: Number})
  // value = 0;

  static get properties() {
    return {
      value: 0
    }
  }

  ...

```

Here is the original repo with the static property added that now works: https://github.com/aadamsx/meteor-lithtml

**Comment by justinfagnani** [comment]
Babel 7 implements the newer decorators spec. The LitElement decorators are still written to the older spec. We have an issue open to make them work: https://github.com/Polymer/lit-element/issues/156

Until then you can try to `legacy: true` option: http://babeljs.io/docs/en/babel-plugin-proposal-decorators#legacy

**Comment by aadamsx** [comment]
I do have legacy: true set on the babelrc config as you can see from my post just above. Is there something else I need in order to use this lib with Babel7?
