### ISSUE TITLE
accessing resulting dom after  lit render(...) not working anymore

### ISSUE THREAD

**Issue by fopsdev** [Polymer/lit-html#481]
Hi there

I had a custom element running which was using:
```js
const template = html`<hello-world id="myID${this.obj.id}"></hello-world>`
render(this, template)
const ref = document.getElementById("myID" + this.obj.id)
```
it was working with latest release 0.11.1 but not anymore with current master
ref is now null so it looks like render changed somehow (maybe render is now async?, just wild guessing)

**Comment by fopsdev** [comment]
so i'm doing now a ```this.getElementByTag("xyz")``` to get the ref.
This works because i'm still in the custom element context.
still strange though that it worked before

**Comment by justinfagnani** [comment]
Huh, nothing like this should have broken recently. Can you get a repro up an running online I can look at?

Separately, for your use case you might want to create the node ahead of time and pass it to lit-html:

```js
const chartNode = document.createElement('div');
chartJs.doThing(chartNode);
html`${chartNode}`
```

**Comment by fopsdev** [comment]
Ok, thanks for the tip.  I'll try to get a repro out

**Comment by fopsdev** [comment]
oh, ok its becaue this awesomplete lib requires the input to be inside a parent.
so now i'm doing:
```js
 let div = document.createElement("div")
    let input = document.createElement("input")
    div.appendChild(input)
...
...
```
and now its working :)

**Comment by aadamsx** [comment]
@fopsdev do you mind putting something out on codepen or jsbin or anything in order to help the others in the community see how do interact with chartsjs?

**Comment by fopsdev** [comment]
Yeah @aadamsx thats a good idea. Currently in discovery mode. As soon as i have some work finished i can post a sample here
