### ISSUE TITLE
async-replace - Not working correctly when the directive is called with the same iterator

### ISSUE THREAD

**Issue by ManRueda** [Polymer/lit-html#484]
The `async-replace` directive has a issue when its called multiple times with the same iterator at the same time that the iterator emits a new value. It's not keeping track of the iterator correctly and it restart on each call.

Like `async-append` it has some logic to handle this case but it not working correctly (it works on `async-append`).

Example of the issue: https://jsfiddle.net/ManRueda/ra5sb91j/8/

I think a found a solution to the problem and create a test for the case.

**Comment by justinfagnani** [comment]
Fixed by #485
