### ISSUE TITLE
rendering html`${noChange}` results in empty result

### ISSUE THREAD

**Issue by fopsdev** [Polymer/lit-html#498]
...whereas it should just leave the dom alone.

https://codepen.io/fopsdev/pen/qMKWEp?editors=1111

**Comment by justinfagnani** [comment]
You're rendering two different templates to the same container here:

```ts
let getUI = (flag) => {
    return html`${flag?html`<h1>hello</h1>`:html`${noChange}`}`
}
```

That's always going to clear the container. If you want to preserve the previous rendering, you have to use the same template.

You can do:

```ts
let getUI = (flag) => {
    return html`${flag ? html`<h1>hello</h1>` : noChange}`;
}
```

As of 0.11.3, render() reuses the NodPart logic, so you can pass `noChange` directly to it, and it will work as you want:

```ts
let getUI = (flag) => {
    return flag ? html`<h1>hello</h1>` : noChange;
}
```
