### ISSUE TITLE
`when` directive: false value should be optional

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#511]
This would be more convenient if the false argument could be omitted. It's currently r[equired](https://github.com/Polymer/lit-html/blob/master/src/directives/when.ts#L49).

**Comment by ruphin** [comment]
What value should it default to? Emptystring and undefined are both reasonable here. Emptystring will probably produce the expected outcome for users.

**Comment by justinfagnani** [comment]
Rather than specifying a value, it can simply clear the container part

**Comment by justinfagnani** [comment]
I'm removing myself as assignee, until I actually start working on it. So anyone else can pick this up too :)

**Comment by ruphin** [comment]
Seems easy enough. I'll get it fixed.
