### ISSUE TITLE
copy of shop-product element gives error when trying to print button below show-item

### ISSUE THREAD

**Issue by mfons** [Polymer/lit-html#512]
[Sorta like this problem](https://github.com/Polymer/lit-html/issues/156)

In a derivation from pwa-starter-kit, I am getting the following error from [trying to open the bean-counter nutrients of interest page](https://github.com/mfons/bean-counter) :

VM4530 async.js:44 Uncaught TypeError: Cannot read property 'value' of null
    at new Template (VM4510 lit-html.js:292)
    at TemplateInstance.result [as _getTemplate] (VM4489 shady-render.js:43)
    at NodePart._setTemplateResult (VM4510 lit-html.js:545)
    at NodePart.setValue (VM4510 lit-html.js:498)
    at NodePart._setIterable (VM4510 lit-html.js:603)
    at NodePart.setValue (VM4510 lit-html.js:500)
    at TemplateInstance.update (VM4510 lit-html.js:662)
    at render (VM4489 shady-render.js:126)
    at HTMLElement._applyRender (VM4470 lit-element.js:230)
    at HTMLElement._propertiesChanged (VM4470 lit-element.js:168)

Now I saw in the pwa-starter-kit README.md that in node 10 I might get some issue like this, but I am using version 9.5...so?

**Comment by mfons** [comment]
Now I basically I am trying to initially create a clone of the "shop" page (page 3, my-view3.js) called bc-nutrientsofinterest.js.  Where my-view3.js calls shop-products I call nutrientsofinterest-nutrients.  Where these elements call shop-item, I call nutrientsofinterest-item.

All this works fine but when I try to put the <button> element below nutrientsofinterest-item like there is in shop-products element for the button below shop-item, I get this error.  

I am trying to cobble a presentation for Denver Google Development Group meetup in early November...I am running out of time to get done what I wanna get done by the time I gotta get in front of all those people and say I know all about Polymer 3...so if you could help me I would really appreciate it!!

**Comment by aadamsx** [comment]
Always helps to put out a CodePen or jsbin.

**Comment by mfons** [comment]
apologies...github source is not good enough I guess.

**Comment by mfons** [comment]
Sorry:  how about [my site itself](https://bean-counter-9ac63.firebaseapp.com/nutrientsofinterest)
the error occurs when the page renders.  I have turned off minification and bundling.

This page is simply trying to clone my-view3.js only with different names.

**Comment by mfons** [comment]
The error occurs in nutrientsofinterest-nutrients.js in _render() when I try to add in the button using the same js values that just worked.  If you remove the <button> element it works...

(If this example is not good enough, I will work on getting a code pen for you...never done that...so it will be a good learning experience for me.)

**Comment by justinfagnani** [comment]
It looks like you have an old version of lit-html, and this has been fixed.

**Comment by mfons** [comment]
yayy!!!   sorry to bug you  !!

**Comment by mfons** [comment]
hm...I changed package.json to ^0.6.1 for lit-element, ran npm i, and on local and in deployed firebase hosted version the issue seems to persist.

**Comment by mfons** [comment]
how do I tell if anybody is looking at my problem or not?

**Comment by CaptainCodeman** [comment]
You'll have more chance of someone looking if you create a clear cut-down example of the issue. Right now you're effectively just asking people to debug your project for you. The shop codebase shows a working example and you're the person most familiar with what has been changed from that.

**Comment by mfons** [comment]
ok, fair enough!  I will do that.  Thank you @CaptainCodeman

**Comment by mfons** [comment]
well I figured out I had commented out some markup in render() which gives lit-element heartburn.
