### ISSUE TITLE
<slot> fallback content never shown when using empty string|undefined as value

### ISSUE THREAD

**Issue by purtuga** [Polymer/lit-html#513]
I have some components that provide slots to the consumer, but also include fallback content - thus making them optional at times.  When using one of these components where lit-html is used to conditionally control the content of them, the fallback content is never displayed. Example:

```
render() {
        return html`
<style>:host { display: block; }</style>
<box-content>${this.msg || ""}</box-content>
`;
```
Working example: https://codepen.io/purtuga/pen/zJyMjK 

I have tried (in the template) to return empty string as well as `undefined` - neither worked. I see that internally, the `<slot>` is really not empty - looks like some marker elements are there. I can imagine (but have not tested) that this would also impact css rules - specifically the ones that might attempt to use `:empty` pseudo selector.

Is this expected behavior? Or should the template parser perhaps detect that it is the only "child" of the parent element and suppress the markers?

The only way I have found to do it is to introduce a conditional statement that returns a different templates. Something like:
```
render() {
    return this.msg 
        ? html`<box-content>${this.msg}</box-content>`
        : html`<box-content></box-content>`;
}
```
 Thanks in advance for your help.

**Comment by ruphin** [comment]
This is interesting. Effectively, a custom element considers a `slot` to be filled whenever it has any non-`CommentNode` children. This includes a `TextNode` with emptystring value:

https://codepen.io/ruphin/pen/gdZJKW?editors=1010

This seems like an awkward problem. One possible solution is to render a CommentNode instead of a TextNode:

```javascript
const commentNode = document.createComment('');
html`<box-content>${this.msg || commentNode}</box-content>`
```

Ofcourse this generates some overhead, and it would be nice if lit-html had the capability to render "nothing". Fortunately it is very easy to create a directive that effectively does just that:

```javascript
const nothing = directive((nodePart) => { nodePart.clear() });
html`<box-content>${this.msg || nothing}</box-content>`
```

I haven't tested it, but it should work. Maybe lit-html should provide that directive. This is a compelling case for why it can be necessary.

**Comment by justinfagnani** [comment]
Interesting indeed.

The `when()` directive without a false case should fix this, but I also like the `nothing` special value, which has an analog to `noChange`, and would put a Part back to its initial state without having to call `clear()`.

**Comment by ruphin** [comment]
Do you think `nothing` should be a builtin sentinel like `noChange`, or a
directive that calls `clear()`? I can make a PR to implement either.

**Comment by ruphin** [comment]
You can implement `nothing` yourself right now if you want to. You can do the following anywhere in your application:

```javascript
import { directive } from 'lit-html/lit-html.js';
const nothing = directive((nodePart) => { nodePart.clear(); delete nodePart.value; });
```

And then you can use `nothing` like I posted in the example above. 

If we add a builtin `nothing` it will probably be identical to this.

**Comment by purtuga** [comment]
Thanks @ruphin ... Yes, I realized that... I just implemented that in our base class that exposes lit-html :+1: 
Thanks again.

**Comment by ruphin** [comment]
Nice catch! I updated my comment for future reference.

**Comment by purtuga** [comment]
FYI (to others): The solution above shows to be working (the text node is not in DOM), but needs a current version of lit-html... In my case, we are still working with v0.9.0 which seems to use textNodes for start/end markers (`startNode`, `endNode`), thus it does not work as intended.

I do plan to upgrade :) - but just wanted to mention that.

**Comment by justinfagnani** [comment]
Closing as basically resolved, though adding a `nothing` value seems useful.
