### ISSUE TITLE
The requested module 'xyz.js' does not provide an export named 'directive'` in 0.11.1+

### ISSUE THREAD

**Issue by Artur-** [Polymer/lit-html#515]
### Description
The project at https://github.com/Artur-/lit-directive-not-found built using `polymer build` throws 
```
Uncaught (in promise) SyntaxError: The requested module '../my-app.js' does not provide an export named 'directive'
```

#### Live Demo
https://artur.app.fi/directive-not-found/

#### Steps to Reproduce
https://github.com/Artur-/lit-directive-not-found/blob/master/README.md

The test case works fine with lit-html 0.11.0 and lit-element 0.6.0-dev.5 but breaks with lit-html 0.11.1 and newer. This issue potentially belongs in https://github.com/Polymer/tools if the problem is with the bundler

**Comment by justinfagnani** [comment]
Should I be seeing the error in the live demo? I don't think I am.

**Comment by Artur-** [comment]
It is logged in the console once you press the button (Chrome 69.0.3497.81)

**Comment by ruphin** [comment]
Your `other-view.js` imports `repeat.js` which imports `directive` from lit-html. Lit-html exports `directive`, so that should not be a problem.

It looks to me like it's either a bundler problem, or some version mismatching between lit-element and lit-html somehow. Have you tried serving the app without bundling? That makes it a lot easier to see which files get loaded so you can see where it breaks. If it doesn't break when you're not bundling, it's clearly a bundling problem.

**Comment by Artur-** [comment]
It is indeed a problem only with the bundled version created with `polymer build`. 
Works with lit-html 0.11.0, fails with 0.11.1 and newer. Works without bundling, fails with bundling. 

The bundled my-app.js contains (when 0.11.1 is used)
```
export{..., directive$1 as $directive,... ,directive as directive$1,isDirective,...};
```

when 0.11.0 is used
```
export{..., directive$1 as $directive,... ,directive as directive$1,isDirective,...,directive,isDirective as isDirective$1,... };
```
which explains the error message but not the reason

**Comment by LarsDenBakker** [comment]
We have this issue as well. I spent some time debugging it, but could not find a good explanation.

**Comment by LarsDenBakker** [comment]
Definitely something is going on here. In your example, the error goes away when you also import the `repeat` directive in the main module.

**Comment by ruphin** [comment]
Looks like an issue with the bundling tool, not with lit-html. I'd post this issue there

**Comment by LarsDenBakker** [comment]
See https://github.com/Polymer/tools/issues/721#issuecomment-424212312

**Comment by keanulee** [comment]
Fixed (workaround really) by https://github.com/Polymer/lit-html/pull/556
