### ISSUE TITLE
Improve website mobile view

### ISSUE THREAD

**Issue by nwarwick** [Polymer/lit-html#529]
There is currently no padding on the main element which doesn't look good on mobile views.

<img width="406" alt="screen shot 2018-10-02 at 7 20 24 am" src="https://user-images.githubusercontent.com/7636254/46345844-0fb58500-c614-11e8-8555-02b1b1c3d6ec.png">

Proposed solution: add `padding-right: 20px; `to match with the side nav padding.

<img width="385" alt="screen shot 2018-10-02 at 7 20 50 am" src="https://user-images.githubusercontent.com/7636254/46345899-44294100-c614-11e8-82c7-5909a30c6231.png">

**Comment by keanulee** [comment]
We've already made some updates to the documentation site to address this, and we're planning to make more changes soon. Stay tuned.
