### ISSUE TITLE
Question: How lit-html resolves consecutive renders?

### ISSUE THREAD

**Issue by aletorrado** [Polymer/lit-html#532]
Hi, I couldn't find information about how lit-html does smart updates when the results from consecutive render calls differs significantly. I think it would be nice to have this documented for user optimizations as well.

Can you give me some insights?

**Comment by justinfagnani** [comment]
It's described in the docs here: https://polymer.github.io/lit-html/guide/how-it-works.html

**Comment by aletorrado** [comment]
I'm sorry I should have posted this on lit-element. Thanks

**Comment by justinfagnani** [comment]
The answer for LitElement will be the same though.

**Comment by ruphin** [comment]
There's no diffing. If you render a different template, lit-html will rebuild a new DOM tree. Fortunately, with component model based development, you generally render the same templates on consecutive renders. You should read the link posted above in this thread, it explains exactly how lit-html takes advantage of this, and why it performs well.
