### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by mantou132** [Polymer/lit-html#542]
Especially useful when used

**Comment by hastebrot** [comment]
Hey. lit-html is written in TypeScript and the `tsc` compiler is instructed to generate `.d.ts` declaration files.

When you install lit-html via npm (e.g. `npm install lit-html`) you can find all declaration files within directories `node_modules/lit-html/` and `node_modules/lit-html/lib/`.

~~~
> ls -1R node_modules/lit-html | grep "\.d\.ts\$"
lit-html.d.ts
async-append.d.ts
async-replace.d.ts
classMap.d.ts
guard.d.ts
if-defined.d.ts
repeat.d.ts
styleMap.d.ts
unsafe-html.d.ts
until.d.ts
when.d.ts
default-template-processor.d.ts
directive.d.ts
dom.d.ts
modify-template.d.ts
part.d.ts
parts.d.ts
render-options.d.ts
render.d.ts
shady-render.d.ts
template-factory.d.ts
template-instance.d.ts
template-processor.d.ts
template-result.d.ts
template.d.ts
~~~

**Comment by mantou132** [comment]
I use `import { html } from 'https://dev.jspm.io/lit-html';`;

result, I forgot that lit-html was written in TypeScript.
