### ISSUE TITLE
AsyncAppend and AsyncReplace can clear the part even if they are not the current value 

### ISSUE THREAD

**Issue by mariusGundersen** [Polymer/lit-html#543]
In the following code, if the part had changed before the first item in the async iterable, then the part would still be cleared. If these two ifs are swapped it will work better 

        // When we get the first value, clear the part. This lets the previous
        // value display until we can replace it.
        if (i === 0) {
          part.clear();
        }

        // Check to make sure that value is the still the current value of
        // the part, and if not bail because a new value owns this part
        if (part.value !== value) {
          break;
        }

**Comment by justinfagnani** [comment]
Fixed by #548
