### ISSUE TITLE
Optional indexes in a new implementation of `repeat`

### ISSUE THREAD

**Issue by merlinnot** [Polymer/lit-html#547]
Hi, I've noticed that an index provided to [`ItemTemplate`](https://github.com/Polymer/lit-html/blob/ddfd13a4487f2d42056e5a2aa2ab6a629ed07bda/src/directives/repeat.ts#L18) is now optional, but I can't find any documentation on this nor I can figure out when is it possibly undefined looking at the source code. Is it marked as optional by accident? Does the same apply to [`KeyFn`](https://github.com/Polymer/lit-html/blob/ddfd13a4487f2d42056e5a2aa2ab6a629ed07bda/src/directives/repeat.ts#L17)?

**Comment by justinfagnani** [comment]
The types are wrong there. The index is always passed to the function.

**Comment by csvn** [comment]
Thanks for fixing this @justinfagnani! I have quite a few errors in the code due to this. Do you know roughly when next release of `lit-html` will be?
