### ISSUE TITLE
Body text is hardly readable in docs

### ISSUE THREAD

**Issue by andersforsell** [Polymer/lit-html#549]
I am trying to read the good doc on https://polymer.github.io/lit-html/, but on Windows 10/Chrome the body text is hardly readable.

Please increase the font-weight from 300 to at least 400.

Thanks!
Anders

**Comment by justinfagnani** [comment]
cc @keanulee

**Comment by keanulee** [comment]
I made some CSS changes and staged them at https://keanulee.github.io/lit-html/. Can't really tell the difference on my Windows 10 VM, but it does look more readable on my MacBook.

**Comment by jsilvermist** [comment]
MUCH more readable on Windows 10 / Chrome 69 for me.

**Comment by andersforsell** [comment]
Before
![image](https://user-images.githubusercontent.com/1157421/46696486-83f2b880-cc12-11e8-8786-af93365c5b72.png)

**Comment by hyperpress** [comment]
Looks much better across browsers. I'd also recommend a responsive template for mobile. Not a high priority, but, you know. . . . 😁

**Comment by stramel** [comment]
Does this have something to do with antialiasing?
