### ISSUE TITLE
Add commit hook to RenderOptions

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#551]
As requested in #271, we need sanitization hooks. We recently introduced `RenderOptions` to `render()` that can flow to all Parts when they're instantiated by a `TemplateProcessor`. Via `RenderOptions` we can pass in a "commit" hook that all Parts will call too in the commit phase.

For reference, @mikesamuel's requirements for the hooks:

1. The value prior to any coercion to a string
2. The attribute and/or property name if any
3. The element if any -- <input type> != <script type>
4. If being substituted into a text node, the parent context -- Is it being substituted into a <script type=text/javascript>?

Some questions to answer about the hooks:

- Should it be in the `setValue()` or `commit()` phase, or both? Since directives run in the commit phase, a hook would need to go after directives run to see the final value.
- Should the attribute/property hook be in `AttributePart#commit()` or `AttributeComitter#commit()`? `AttributeComitter#commit()` is where we know all of the literal string and expression values.
- Directives can convert the types of values.
  - They could stringify them, which violates (1), _but_ lit-html sets `textContent` in text-bindings, so those are generally safe. I think that attribute sanitization generally needs the string value too, expect when allowing `SafeHTML` values to pass through. Directives should just not convert those to strings.
  - They can convert _from_ strings, and generally do unsafe things. `unsafeHTML` does this by converting strings to nodes. In a security sensitive environment, such directives need to be disallowed.

If the hook is in `AttributePart#commit()`, the change will look like this:

```ts
export class AttributePart implements Part {

  // ...

  commit() {
    while (isDirective(this.value)) {
      const directive = this.value;
      this.value = noChange;
      directive(this);
    }
    if (this.value === noChange) {
      return;
    }
    // Here's the hook:
    if (typeof this.options.commitCallback === 'function') {
      this.options.commitCallback(this);
    }
    this.committer.commit();
  }
}
```

The hook will have access to the value via `part.value`, and the element and attribute name via `part.committer.name`, `part.committer.element`.

If the hook is in `AttributeComitter#commit()`, the change will look like:

```ts
export class AttributeCommitter {

  // ...

  commit(): void {
    if (this.dirty) {
      // Here's the hook:
      if (typeof this.options.commitCallback === 'function') {
        this.options.commitCallback(this);
      }
      this.dirty = false;
      this.element.setAttribute(this.name, this._getValue());
    }
  }
}
```

The hook will have access to the element and attribute name via `commiter.name` and `commiter.element`, and the strings and values via `commiter.strings`, and `commiter.values`.

The problem here is a commit hook doesn't always receive a Part - it might receive a NodePart, BooleanAttributePart, EventPart, or AttributeCommiter or PropertyCommiter. That inconsistency might not be so bad though?

cc @mikesamuel for feedback.

**Comment by justinfagnani** [comment]
> Are there other things that are likely to hook in and which might prematurely coerce values to strings?

Not within the lit API, but of course values can be fed to functions before they hit a template.

> If a commit hook sees an {Attribute,Property}Committer can it assume that that committers commits will eventually return to it?

Not sure I understand the question, but what I was getting at is that in the 2-phase system, Parts have `setValue()` and `commit()`, but for Parts that could make up a multi-part value, there's an additional Committer object that determines the final value, and so a hook might have to be fairly polymorphic, or better we pull out a consistent interface for the hook.

> What's an EventPart?

```ts
html`<button @click=${this._handleClick}>Click Me</button>`
```

EventParts only work with function values.

**Comment by mikesamuel** [comment]
> Not within the lit API, but of course values can be fed to functions before they hit a template.

Ok.  In that case order of operations doesn't dictate the AttributePart vs AttributeCommitter design decision.

> but for Parts that could make up a multi-part value, there's an additional Committer object that determines the final value, and so a hook might have to be fairly polymorphic, or better we pull out a consistent interface for the hook.

If an attribute has multiple parts like

```js
html`<a href="/foo?bar=${ bar }#${ frag }">`
```

do we get more context by operating at the AttributeCommitter level?
If so, I'd prefer to operate at the beginning of commit of the attribute as a whole, and after the values of the parts have been set, but before the parts have been combined into a single string.

> EventParts only work with function values.

Thanks for explaining.  Since EventParts don't involve coercion from strings, I think the hook just needs to recognize and ignore them.  It's possible bad things could happen if an attacker caused the value of the function to be `Function` or `eval`, but that's not a lit-html specific risk.

**Comment by rictic** [comment]
Fixed in https://github.com/Polymer/lit-html/pull/1031, will be in the next release.
