### ISSUE TITLE
Improve code snippet legibility on lit-html site

### ISSUE THREAD

**Issue by marcushellberg** [Polymer/lit-html#554]
I think that the code snippets on  https://polymer.github.io/lit-html could benefit from a heavier font weight and/or bigger font size. Currently, I find them a bit hard to read even with good eyesight on a good monitor. 

<img width="602" alt="screen shot 2018-10-09 at 5 05 16 pm" src="https://user-images.githubusercontent.com/883698/46705717-a6baa800-cbe5-11e8-9a71-df7a165078f9.png">

**Comment by justinfagnani** [comment]
Wow, how is the font rendering so different? This is on my Mac:

<img width="882" alt="screen shot 2018-10-09 at 5 17 00 pm" src="https://user-images.githubusercontent.com/522948/46706027-36148b00-cbe7-11e8-8c78-6ebb893faa93.png">

**Comment by justinfagnani** [comment]
@keanulee

**Comment by marcushellberg** [comment]
Yes, that URL is better. Forgot to say I'm on Chrome 69, macOS 10.14

**Comment by keanulee** [comment]
Fixed by #553
