### ISSUE TITLE
Attribute parts with value `undefined` set attribute to string "undefined"

### ISSUE THREAD

**Issue by cdata** [Polymer/lit-html#56]
Please refer to the following reduced repro case and read the console output: https://enshrined-noise.glitch.me/

### What I wanted

```
Element.outerHTML: <div foo></div>
```

### What I got

```
Element.outerHTML: <div foo="undefined"></div>
```

**Comment by justinfagnani** [comment]
After talking, I'm unsure whether or not this is a bug. Calling setAttribute() with a value of `undefined` results in the attribute having the string value `"undefined"`.

The question to answer is how much an attribute binding should behave like setAttribute(). Should attribute bindings be _just_ setAttribute(), or should the try to fix the DOM API somewhat?

@sorvell @kevinpschaaf for opinions

**Comment by cdata** [comment]
Definitely think this was a matter of ergonomics and not correctness for me. Consider this food for thought and not a bug report, because I'm also on the fence about what is the best way.

**Comment by justinfagnani** [comment]
@sorvell @kevinpschaaf interested in your opinion here. Should `undefined` as an attribute value act like `setAttribute(undefined)` (set the attribute to the string `"undefined"`), or should it do something different, like remove attribute, or remove its value?

**Comment by gdi2290** [comment]
`setAttribute` should only accept a string so anything else is type coercion (which should be avoided). If someone wanted undefined they can return a string value of `"undefined"`. If the value returned is `false || undefined || NaN || null` then the attribute should most likely be removed as you're most likely doing this for boolean values. So this usually boils down to an API like 
```html
<div foo="${ check ? '' : undefined }"></div>
```
returning `''` should output
```html
<div foo></div>
```
and not
```html
<div foo=''></div>
```
In some template engines most falsey values are converted to null otherwise you have to deal with  `false || undefined || NaN || null` (`''` is an exception)

Even though we would like to live in a world with an API decoupled from the DOM at the end of the day it's still the browser DOM API.

-from experience working with Angular's templating engine

**Comment by justinfagnani** [comment]
The question for me, especially in lit-html core as opposed to lit-extended, is how much should an attribute binding behave like `setAttribute()`, and how does a full-binding relate to an interpolation. Would it be surprising that `<div foo=${undefined}>` behaves different than `setAttribute('foo', undefined)`, or different than `<div foo=" ${undefined} ">` (note the spaces).

**Comment by gdi2290** [comment]
I think the the spaces is a gotcha and can't be avoided unless you detect it's an attribute binding. You can provide console warnings but then you need a way to remove the warning code from production. I think all this should be in core to avoid anyone else, who plans of making their own lit-extended, to recreate these rules

another question is being able to set a property vs the attribute (I think for polymer 3 it was `<div foo$="{{ yo }}"` for prop vs attr `<div foo="{{ yo }}"`). If you set a property the polymer way you still run into the spaces problem but a property doesn't need to be a string
`foo=" ${undefined} "` -> `setAttribute('foo', ' ' + undefined)`
vs property
`foo$=" ${undefined} "` -> `el['foo'] = ' ' + undefined`

**Comment by shutdown256** [comment]
My PR #204  has a possible solution

**Comment by justinfagnani** [comment]
Since lit-extended has added support for the `?` suffix, and I think we've pretty well determined there's no nice way to encode boolean semantics in plain HTML syntax, I think we can close this.

**Comment by pitus** [comment]
Well, I'm getting `'Uncaught Error: boolean attributes can only contain a single expression'` at `BooleanAttributePart.setValue` for a very simple test `<input type="checkbox" checked?=${true}/>` - why is that?

**Comment by bgotink** [comment]
That's due to HTML including the `/` in the attribute value in your example:

```js
d = document.createElement('div')
d.innerHTML = `<input type="checkbox" checked?=${true}/>`

console.log(JSON.stringify(d.firstElementChild.getAttribute('checked?')))
// logs: "true/"
```
