### ISSUE TITLE
Do event handlers always ensure that `this` refers to the current component?

### ISSUE THREAD

**Issue by mbrowne** [Polymer/lit-html#564]
I am following a conversation in the [proposal-class-fields](https://github.com/tc39/proposal-decorators) about a `@bound` decorator to create bound methods in an object (i.e. the equivalent of `this.myMethod = this.myMethod.bind(this)`). @csvn mentioned lit-html as an example of a library where this would be useful. As it happens, I just started playing around with lit-html and lit-element but so far I haven't seen this issue; for example in this [test component](https://github.com/mbrowne/lit-element-webpack-boilerplate/blob/4fadf0362ffee7c9e6d0a51cbad9a3cd779de783/src/MyCounter.js) the `increment()` and `decrement()` methods already have access to `this`. I consider this a nice feature of the library and wish React did the same thing (and BTW I don't see any technical reason why they don't).

My question is this: is this a deliberate design decision, and is it reliable behavior that can be counted on regardless of what event handler is being used? If not, I would suggest that such a design be maintained, because it improves usability and eliminates a bunch of needless issues as React users have seen.

And to be honest, I'm party just creating this issue to ask @csvn: what exactly were you referring to? (The decorators repo didn't seem like the right place to discuss that.)

**Comment by LarsDenBakker** [comment]
Actually since 0.12.0, lit-html adds a hook for components to pass their event context which is then used at the `this` value for event handlers. Before 0.12.0 an `@bound` decorator would have been very useful :)

**Comment by mbrowne** [comment]
@LarsDenBakker cool, this is a nice feature :) And it seems like it defaults to the current component so it just works out of the box.

**Comment by csvn** [comment]
@mbrowne I was referring to the fact that if you don't want a new method to be created every new re-render, it would be helpful to have a single bound function. I assumed that `this.click === oldClick` every time `render()` is called. This could be a helpful ergonomic and performance improvement.

```ts
class Foo extends HTMLElement {
  render() {
    return html`<button @click=${ (e) => console.log('clicked') }>Click Me</button>`;
  }
}
```
```ts
class Foo extends HTMLElement {
  @bound
  click() {
    console.log('clicked');
  }
  render() {
    return html`<button @click=${ this.click }>Click Me</button>`;
  }
}
```

**Comment by csvn** [comment]
I did not know 0.12.0 was released. Cool 😄

**Comment by mbrowne** [comment]
@csvn Thanks for clarifying. Fortunately I see that version 0.12.0 has resolved this in what I consider to be the most user-friendly and efficient way (and also what I wish React had done) - simply calling the method with the correct context: https://github.com/Polymer/lit-html/pull/523/files#diff-63a9df26ecde05415a902b5b5dc5e266R450. That way there's not even a need to create a new bound function.

**Comment by csvn** [comment]
Yeah, I read that earlier. It’s a nice solution, which is also the most performing due to re-using the same prototype method 🎉

**Comment by mbrowne** [comment]
As an aside, in general of course I'm still a big proponent of a `@bound` decorator for cases where it applies (which is already possible to implement yourself with both the legacy and current decorators proposals). That's why I wrote this article: https://github.com/tc39/proposal-decorators/blob/master/bound-decorator-rationale.md. 

(FYI to anyone finding this thread in the future, the `@bound` decorator is not part of any proposed JS standard at this time, but it doesn't necessarily need to be since you can implement it yourself or use an open-source implementation...perhaps I'll publish my implementation as a library. In the meantime there are existing libraries for similar decorators using the legacy decorators proposal for both JS and TypeScript.)
