### ISSUE TITLE
when Directive puts its node in the wrong place when taken from the cache.

### ISSUE THREAD

**Issue by akc42** [Polymer/lit-html#565]
I have an app with various icons in the toolbar.  I only render any icons when the user is logged on and I only render a "reply" icon (used to return up a level) with the top level is not there.  These are both controlled using the `when` directive.
The first time I logon,  and then go below the top level the icons appear on the correct order, but the second time I activate the reply icon it has moved to the end of the list of icons.

I created a demo at home and proved it fails the same way in a cut down version.  Tried to load to stackblitz and it seems to have got stuck with dependencies. It should be here https://stackblitz.com/edit/js-zt2cnc

However the core of the problem is demonstrated in a single file - which is replicated below
```
import { LitElement, html } from '@polymer/lit-element/lit-element.js';
import {when} from 'lit-html/directives/when.js';

import '@material/mwc-icon/mwc-icon.js';

const appTitle = 'Test System';

class PasApp extends LitElement {
  static get properties() {
    return  {
      pageTitle: {type: String},
      isLoggedOn: {type: Boolean}
    };
  }
  constructor() {
    super();
    this.pageTitle = appTitle;
    this.isLoggedOn = false;
  }
  connectedCallback() {
    super.connectedCallback();
    this.removeAttribute('unresolved');
  }
  disconnectedCallback() {
    super.disconnectedCallback();
  }
  render() {
    return html`
      <style>
        :host {
          display: block;
        }
        .flexcontainer {
          display: flex;
          flex-direction: row;
        }
        .filler {
          flex: 1;
          text-align: center;
          align-self: flex-start;
        }
        mwc-icon {
          cursor: pointer;
        }

      </style>
      <div class="flexcontainer">
      <div class="filler">${this.pageTitle}</div>
        ${when(this.isLoggedOn, () => html`
          <mwc-icon @click="${this._resetTitle}">today</mwc-icon>
          <mwc-icon @click="${this._changeTitle}">date_range</mwc-icon>
          ${when(this.pageTitle !== appTitle, () => html`
            <mwc-icon @click="${this._logoff}">reply</mwc-icon>
          `, () => html``)}
          <mwc-icon id="home" @click="${this._gotoHome}">home</mwc-icon>
        `, () => html``)}
        <mwc-icon @click="${this._logon}">menu</mwc-icon>
      </div>
    `;
  }
  _changeTitle(e) {
    e.stopPropagation();
    this.pageTitle = 'Some Different Text'
  }
  _logoff(e) {
    e.stopPropagation();
    this.isLoggedOn = false;
  }
  _logon(e) {
    e.stopPropagation();
    this.isLoggedOn = true;
  }
  _resetTitle(e) {
    e.stopPropagation();
    this.pageTitle = appTitle;
  }
}
customElements.define('test-app',PasApp);
```

**Comment by akc42** [comment]
I have been through the above sample step by step with a debugger.  The cause of the problem is the following lines (lines 65 - 68 in version 0.12.0)
```
        // If the next part was rendered, take it from the cache
        if (nextPart.value) {
            parentPart.startNode.parentNode.appendChild(cache.cacheContainer);
        }
```
This adds the part that is a result of the condition as the last element in the parents container, even though the when directive maybe somewhere in the middle.

**Comment by akc42** [comment]
I think the fix is to replace
```
parentPart.startNode.parentNode.appendChild(cache.cacheContainer);
```
with
```
parentPart.startNode.parentNode.insertBefore(cache.cacheContainer, parentPart.endNode);
```
but I have no idea how to add a test for this, so I can't really make a pull request

**Comment by LarsDenBakker** [comment]
Thanks for the investigation. Ill add a test case in the when refactor PR.

**Comment by aadamsx** [comment]
FYI, your StackBlitz project doesn't have any of this code (just in case you meant to save it there).

**Comment by akc42** [comment]
@aadamsx yes I know - I set it up, bit it just would not save.  No idea why.

**Comment by aadamsx** [comment]
After you add the code, there's a save button on top, just click that.

![image](https://user-images.githubusercontent.com/5341158/46911147-dab10880-cf18-11e8-9548-efd75c1e4cac.png)

**Comment by akc42** [comment]
I did, and a blue box saying "Installing Dependencies" came up and stayed there for over an hour - at which time I had written the above post.  Eventually I had no choice but the close the browser and it seemed when I looked again to have lost every thing.

**Comment by mariusGundersen** [comment]
There is a second bug in this code, in [when.js line 87](https://github.com/Polymer/lit-html/blob/master/src/directives/when.ts#L87) and [line 92](https://github.com/Polymer/lit-html/blob/master/src/directives/when.ts#L92):

```ts
 // If the next part was rendered, take it from the cache
if (nextPart.value) {
  parentPart.startNode.parentNode!.appendChild(cache.cacheContainer);
}

// If the prev part was rendered, move it to the cache
if (prevPart.value) {
```

Both of these lines assume that `nextPart.value` and `prevPart.value` are truthy, but that might not be the case. Here is a basic way to reproduce the issue:

```js
const app = value => when(value, () => true, () => false);

render(app(false), document.body);
render(app(true), document.body);
// the output will now be `truefalse`
```

This is also reproducible when either part returns an empty string (`''`) which is also a falsy value. In that case the startNode, an empty text and the endNode will still be in the DOM, as can be seen in the inspector

```js
> $0.childNodes
< NodeList(8) [comment, comment, text, comment, comment, text, comment, comment]
```

**Comment by akc42** [comment]
@mariusGundersen This looks very much the same as the bug I just reported as #606

**Comment by mariusGundersen** [comment]
I can make a pull request to fix both these issues, they are fairly straight forward to solve. But, as noted in the linked and related issues, the directives will be redesigned very soon, so the greatest value in the pull requests might not be in the code but the unit tests.
