### ISSUE TITLE
Event binding (EventPart) changes context of callback when using EventListener Interface

### ISSUE THREAD

**Issue by purtuga** [Polymer/lit-html#571]
Hello all. 
Just switched over to the latest version of lit-html and noticed a change in behavior (from v0.6.0) with event binding when using an EventListener interface.  Example:

```javascript
const eventCallSummary = document.getElementById("eventCallSummary");
const myEventListener = {
    events: {},
    handleEvent(event) {
        if (!this.events.hasOwnProperty(event.type)) {
            this.events[event.type] = 0;
        }
        this.events[event.type]++;
        eventCallSummary.textContent = Object
          .entries(this.events)
          .map(([key, value]) => `    ${ key }: ${ value }`)
          .join("\n");
    }
};

document.getElementById("one").addEventListener("click", myEventListener);
document.getElementById("two").addEventListener("click", myEventListener);

document.getElementById("three").addEventListener("mouseover", myEventListener);
document.getElementById("three").addEventListener("mouseenter", myEventListener);
document.getElementById("three").addEventListener("mouseleave", myEventListener);

document.getElementById("four").addEventListener("mouseover", myEventListener);
document.getElementById("four").addEventListener("mouseenter", myEventListener);
document.getElementById("four").addEventListener("mouseleave", myEventListener);
```

In the above, when `myEventListener.handleEvent()` is called, the context should always be `myEventListener` object. This is true when using the above with Native DOM Events - check out quick prototype:

https://codepen.io/purtuga/pen/ReMwyv?editors=1010

However, what is happening is that lit-html EventPart is actually changing the context to be the Element to where the Event was bound: 
https://github.com/Polymer/lit-html/blob/f7bdfca23162d366a75ecb6e0b434d3a51d64c19/src/lib/parts.ts#L482-L488

In my mind, `EventPart.handleEvent` should use the original `Object` as the `eventContext` when the `EventListener` interface is used.

**Comment by daKmoR** [comment]
that was changed in the latest release.
https://github.com/Polymer/lit-html/blob/master/CHANGELOG.md#0120---2018-10-05

you can now set the event context with the render function.

it unclear to me what are you trying to archive? what is your lit-html template that causes you trouble? or are you doubting the change made in the last release?

**Comment by justinfagnani** [comment]
Oops, this indeed a bug. Event listener objects should indeed be called with the object as the `this`, and I did change that line of code when I added `eventContext`. I guess the question is, with an `eventContext` specified, should that override the default behavior for event listener objects?

**Comment by purtuga** [comment]
Thomas,
I did not realize `render()` had introduced a context variable (I did see it as an input param in the EventPart).  My apologies. But even with that in place, it still breaks the expectation behind EventListener DOM Interface. And what if I want to use different EventListener interfaces to handle different events?

Justin,
I agree with your suggestion.  If `eventContext` was explicitly used, then override (docs should indicate that).  But by default (IMO) the DOM EventListener interface should be met with the expected behavior if no context was defined.

Thank you both for the quick response.

Paul

-- sent from mobile

**Comment by purtuga** [comment]
Hi Justin.
Actually, I’m not so sure about applying the render eventSource to the EventListener interface anymore. Perhaps it should only be aplicable to callbacks.

If someone explicitly defined an EventListener object then they are clearly aware of the behavior that is expected. Also, applying the context to these feels limiting in that you have to choose one (render context) or the other.

For callbacks, I do see value in having the context from render applied - as it avoids us having to .bind() our Component’s callbacks (memory efficiency) an essentially (in a way) provide similar behaviors as EventListener objects.

-- sent from mobile

**Comment by purtuga** [comment]
For others that might find this and would like to "path" up lit-html (temporary) utnil this is fixed - I changed the EventPart `handleEvent` method to the following (note: this is ES5 code, since I'm working with a transpiled version of lit-html):

```javascript
var listener,
    context = this.eventContext || this.element;

if ('function' === typeof this.value ) {
    listener = this.value;
} else if (this.value && 'function' === typeof this.value.handleEvent) {
    listener = this.value.handleEvent;
    context = this.value;
} else {
    listener = function () {
        return null;
    };
}

listener.call(context, event);
```

This will honor the EventListener interface regardless if `eventContext` was set on `render()`.
