### ISSUE TITLE
Consider an approach for assigning change events to avoid boiler plate code.

### ISSUE THREAD

**Issue by akc42** [Polymer/lit-html#573]
A pattern that is seemingly coming up a lot as I move over from Polymer 3 is
```
<my-sub-element .property=${this.myInterpretation} @property-changed=${this._myInterpretationChanged}></my-sub-element>
....
_myInterpretationChanged(e) {
this.myInterpretation = e.currentTarget.property;
}
```
This is all boiler plate that could be done away with if I could do something like this
```
<my-sub-element @property=${'myInterpretation'}></my-sub-element>
```
The key difference is that the '@' marker either takes a function (for the old way) or a string - which becomes the name of a local property that is two way databound. (Obviously a different character than @ could be used - it just seemed a way of not adding a whole new type - I have no opinion one way or the other)

**Comment by ruphin** [comment]
lit-html doesn't really do "data binding" in the same sense that polymer does, and the syntax you suggest is not possible to implement in lit-html itself, without using `eval`-like constructions. Two-way data binding is somewhat out of scope for what lit-html is designed to do, and I don't think there will be builtin support for it.

I personally think two-way data binding is not a good pattern, and I avoid using it in general. However, there is nothing stopping you from creating a `bind` directive that does more or less what you want, with the following signature:

```js
html`<my-element @property=${ bind(this, 'myInterpretation') }><my-element>`
```

**Comment by justinfagnani** [comment]
A directive is fine, but it's not something we'd include in the lit-html package. We want to avoid string-based meta-programming as much as possible. lit-html already has it's share due to property bindings, but we have specific syntax for it and can process it if need be to work correctly with renaming compilers and minifiers.

**Comment by justinfagnani** [comment]
Going to close this now. We don't have plans for such a directive, but third parties could vend one.
