### ISSUE TITLE
?hidden not working on element with display:grid

### ISSUE THREAD

**Issue by lastmjs** [Polymer/lit-html#574]
I've got an element that has a class applied to it. The class has the `display` property set to grid. the `?hidden` directive or whatever you call it is applying the hidden attribute to the element, but it isn't hiding the element. If I inspect the CSS in Chrome the `display: grid` property seems to have more specificity than the hidden attribute's application of `display: none`...not sure if this is a lit-html problem. If it isn't, does anyone know of an elegant solution to this?

**Comment by amitmerin** [comment]
I dont think the `hidden` attribute has anything to do with `lit-html`.
You can take a look here - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

If you want, you could do something like
```
.myClass[hidden] {
    display: none;
}
```

**Comment by lastmjs** [comment]
Yep, that makes sense, doesn't seem to be an issue with lit-html

**Comment by jsilvermist** [comment]
As best practise, any element which adds a `display` property to `:host` should always implement:
```css
:host([hidden]) {
  display: none;
}
```
