### ISSUE TITLE
Sorry to open it as an issue. I made a tooling for lit-html.

### ISSUE THREAD

**Issue by pushqrdx** [Polymer/lit-html#586]
I made a vscode plugin for lit-html that enables Syntax Highlighting, Intellisense, and Emmet for `html/css` inside the `html` tag in both typescript and javascript files. I thought it would be nice if i shared it with people working with lit.

link at [marketplace](https://marketplace.visualstudio.com/items?itemName=pushqrdx.inline-html) called Inline HTML.

Anyway, I want to thank the team and contributors behind lit. I'll be really happy if i managed to help someone with this little contribution of mine.

**Comment by justinfagnani** [comment]
Thanks for the tool and letting us know!
