### ISSUE TITLE
lit-html rerender weird phenomenon

### ISSUE THREAD

**Issue by mantou132** [Polymer/lit-html#588]
https://codepen.io/mantou132/pen/YJdQxb?editors=1000

When using method 1, custom-element will rerender;

but using method 2, custom-element no rerender;

<img width="688" alt="screen shot 2018-10-25 at 23 03 21" src="https://user-images.githubusercontent.com/3841872/47510216-40eb4300-d8aa-11e8-9095-e44a2a1bdc51.png">
<img width="698" alt="screen shot 2018-10-25 at 23 03 41" src="https://user-images.githubusercontent.com/3841872/47510217-40eb4300-d8aa-11e8-809b-7649337c0ec3.png">

**Comment by mantou132** [comment]
lit-html detected the location where it was called?

**Comment by mariusGundersen** [comment]
It kind of remembers where it's called from, because of how tagge string literals work. In the first example it will make two different templates while in the second case it will only make one template. This means that in the first case it will switch out the custom element and make a new one, while in the second case it will reuse the custom element it made the first time and only update the property. Note that it's changing the property, not the attribute, since it starts with a `.`. Is your custom element set up to handle the property changing?

**Comment by mantou132** [comment]
should I handle property changes through setter?

> remembers where it's called from
How is this implemented? I searched the source code for "try", "throw" and didn't find useful information.

**Comment by ruphin** [comment]
This is a feature of [JavaScript tagged template string literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

When you tag a template string with a function, that function is called with an array of the static string components of the template, and arguments that represent the dynamic values of the template. Each time the tag function is invoked for the same template literal, the string array will be the same object. Lit-html uses this identity to uniquely identify different templates.

```js
const tag = (strings, ...values) => { return {strings, values}};
const template = (value) => tag`hello ${value}`;
const identicalTemplate = (value) => tag`hello ${value}`;

console.log(template('world').strings === template('bob').strings) // true
console.log(template('world').strings === identicalTemplate('world').strings) // false
```

**Comment by mantou132** [comment]
thanks.

**Comment by csvn** [comment]
> should I handle property changes through setter?

@mantou132 There are a couple of different ways to do this. Using `get/set` manually every time is straightforward, but may add boilerplate if used often.

```js
class MyElement extends LitElement {
  get foo() {
    return this._foo;
  }
  set foo(value) {
    this._foo = value;
    this.invalidate(); // schedule a re-render
  }
}
```

If you want to use decorators and class properties (via babel/Typescript), it can help make your code a bit more concise. It basically does the same as above, but it becomes a re-usable pattern.

```js
class MyElement extends LitElement {
  @prop() // automatically calls re-render on changes
  foo;
}
```

We took inspiration from [Polymer/lit-element](https://github.com/Polymer/lit-element), and made a base class that can use `@prop()` and `@attr()` decorators, for regular properties and values read/written to/from attributes. I suggest taking a look at `LitElement`, it's pretty popular.

**Comment by mantou132** [comment]
@ruphin The situation seems to have changed now.
@csvn This method is very useful to me because of the change in lit-html.
