### ISSUE TITLE
Consider `templateContent` directive that stamps an HTMLTemplateElement

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-html#605]
Consider adding a directive that takes an `HTMLTemplateElement` as a value and stamps its content once (and is a no-op for subsequent renders).

See discussion on [Polymer#5417](https://github.com/Polymer/polymer/issues/5417#issuecomment-435225445).  While perhaps being generally useful, it specifically provides a nice transition path for Polymer users who are migrating an app element-by-element, since they could share static "shared styles" (e.g. chunks of ``export html`<style>/*shared css*/</style>` ``) between `PolymerElement`s and `LitElement`s by defining the shared styles with Polymer's `html` tag function (which simply returns a standard `HTMLTemplateElement`), which could then be interpolated into Polymer or lit templates.

**Comment by ruphin** [comment]
I like this. I think it's a better solution than having a special case for `HTMLTemplateElement` in the Node rendering subroutine.

See #582 for additional discussion on this subject.

**Comment by justinfagnani** [comment]
Fixed by #1058
