### ISSUE TITLE
Documentation for lit-html features

### ISSUE THREAD

**Issue by nickcolley** [Polymer/lit-html#610]
Hey, is there any documentation how to do anything more than just rendering HTML?

I noticed you can do event handling with the @ symbol but can't find anywhere that explains it.

**Comment by daKmoR** [comment]
Readme at the top?

Full documentation is available at polymer.github.io/lit-html.

for the @ symbol it's here
https://polymer.github.io/lit-html/guide/writing-templates
"Event Listeners"

**Comment by nickcolley** [comment]
Think I got lost since getting started doesnt link through to writing templates?

**Comment by nickcolley** [comment]
Maybe worth doing some user research on the docs, will close for now
