### ISSUE TITLE
Formatting code

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-html#618]
Hello,

This is more a question rather than an issue. I was wondering how you format your source code? I have tried Webstorm, but it does not support formatting inside of template strings as of now. There seems to be a VS Code plugin, but it does not work for me either. So, simple question: Which tool do you use formatting your code?

Thanks a lot.

**Comment by ruphin** [comment]
VS Code has several plugins for lit-html. The `lit-html` plugin does syntax highlighting in html template strings, and the latest [prettier](https://github.com/prettier/prettier) release supports formatting html templates. 

The integration with Prettier is brand new, and was only released a few days ago, but I can confirm that it properly does formatting for `html` tagged templates.

**Comment by Christian24** [comment]
Thank you very much. Prettier does work really well. I am going to close this now.
