### ISSUE TITLE
why `when`, `repeat`, `IfDefined` and all the extras?

### ISSUE THREAD

**Issue by prasannavl** [Polymer/lit-html#619]
What's the point of all above extra functions and the likes? I don't understand the need for the extra API surface and the cognitive overhead.  I love that `lit-html` is extremely simple (aside from this). 

All of these methods can just be used like how it is in `jsx`, with javascript's own arrays, maps, filter, etc.  If someone *really* needs this for ergonomic needs, they can always just curry them functionally, or accomplish the same in combination with `lodasd`, `rambda`, or any of the well known functional libraries. This seems excessive to provide it a part of the public API surface. Am I missing something? 

Wouldn't it be a much better design to keep it out of lit-html core, like having a separate package with `lit-html-helpers`, or utils, etc.

**Edit**: After looking at the code,  my initial guess is it's seems since the fundamental difference is them being implemented as `directives`, they likely could end up more efficient being able to change parts directly rather than doing a complete render, which will have to re-evaluate the whole template. But I'm still a little confused -- since they are tagged template literals anyway (meaning each part is passed into the `html` fn separately), can this not be efficiently optimized internally without having most of these APIs at all?
 
For places where the above doesn't apply -- `ifDefined` for instance, when they are only applicable to attributes, I think they are better off being named, `ifAttributeDefined/definedAttr` so that it's intent is clear?

**Comment by prasannavl** [comment]
Okay, after rethinking this a little more, 

`when` - I don't see a valid use case that can't be optimized away in the html fn itself. 
`guard` - I'm not sure if it really needed. 
`ifDefined` - naming isn't obvious since only works with attributes so much so that its goes in and calls remove attribute when not defined.  
`repeat` and promises api - definitely useful.

**Comment by mariusGundersen** [comment]
Have a look at #523 where the `when` directive is discussed vs a proposed `cache` directive. It also brings up the `repeat` directive and how it is different. In general thought these directives can improve performance when used in the correct situations. If you are making something simple then you maybe don't need them.

IMO `guard` is a bit weirdly named, since it's not clear what it guards against. I think `memo` might be a better name.

**Comment by prasannavl** [comment]
Thanks @mariusGundersen. I spent a little more time with the source, and I think I'll close this for now. Since a lot of directive implementations are tiny and `lit-html` not having hit 1.0, I think it's probably just isn't worth the head ache to separate them into a different package, until some more real life analysis can be performed on what patterns needs internal optimizing, and how.

**Comment by mkay581** [comment]
Yes, I do however think @prasannavl's point below is valid.

> `ifDefined` - naming isn't obvious since only works with attributes so much so that its goes in and calls remove attribute when not defined.

It can be a little confusing on the outset.
