### ISSUE TITLE
How do I handle selected option?

### ISSUE THREAD

**Issue by jnylund** [Polymer/lit-html#620]
I was thinking I should do something like this:

```
 <label for="direction">Direction:</label>
                  <select id="lat-direction">
                    <option value="north" ${this.latDirection === "N" ? 'selected' : ''} >North</option>
                    <option value="south">South</option>
                    <option value="east">East</option>
                    <option value="west">West</option>
                  </select>
   </div>
```

But this breaks, with error:
TypeError: Cannot read property '2' of null

thx
Joel

**Comment by Lodin** [comment]
Just set your attribute like it has a `boolean` type
```javascript
html`
<label for="direction">Direction:</label>
<select id="lat-direction">
  <option value="north" selected=${this.latDirection === "N"}>North</option>
  <option value="south">South</option>
  <option value="east">East</option>
  <option value="west">West</option>
</select>
`;
```

**Comment by LarsDenBakker** [comment]
@Lodin  That will print `selected="false"` or `selected="true"` which is not how HTML boolean attributes work it should be either `<option selected>` or `<option>`.

@jnylund you can't dynamically set attribute that way, as lit-html doesn't know that you might set an attribute there. 

There is a special modifier for boolean attributes, if you prefix the attribute with a `?` it will be set or removed based on what value passd:

```
html`
<label for="direction">Direction:</label>
<select id="lat-direction">
  <option value="north" ?selected=${this.latDirection === "N"}>North</option>
  <option value="south">South</option>
  <option value="east">East</option>
  <option value="west">West</option>
</select>
`;
```

Check out https://github.com/thepassle/create-lit-app and https://github.com/LarsDenBakker/lit-html-examples for examples.

**Comment by jnylund** [comment]
Awesome, thanks that works perfectly!
