### ISSUE TITLE
Directive functions stopped working after rm package-lock.json and npm install

### ISSUE THREAD

**Issue by RyanAfrish7** [Polymer/lit-html#621]
I had a dependency conflict somewhere between paper-input and gold-phone-input. I read in stackoverflow about it and cleared the node_modules directory as well as package-lock.json and reinstalled using npm install later. This fixed the dependency issue between paper-input and gold-phone-input. 

And since then, none of the directives are seeming to work. And instead of applying a directive, it prints the javascript code of the directive I'm using into the html. There were no errors logged in console.

![](https://user-images.githubusercontent.com/9781909/48315187-0b0fc380-e5f9-11e8-9c77-9b454e184012.png)

Here is the link to the [package-lock.json](https://github.com/Polymer/lit-html/files/2569551/package-lock.json.txt)

I'm using `polymer-cli` to serve up the files.

**Comment by mariusGundersen** [comment]
In version 0.13 of lit-html the way directives are defined has changed, and it sounds like this could have caused the issue you see. Make sure you don't have two different versions of lit-html, through some other dependencies, installed.

**Comment by hyperpress** [comment]
Try running `npm dedupe`

**Comment by RyanAfrish7** [comment]
Hey! I found that there has been two versions of lit-html being used so I tried using a older version of lit-html installed at my root node_modules so that all are in sync. But didn't help. Also tried running `npm dedupe`. Same as before.

**Comment by mariusGundersen** [comment]
`dedupe` probably doesn't work because `@material/mwc-base` and `@material/mwc-ripple` require `^0.12.0` while `@polymer/lit-element` requires `^0.13.0`. Downgrade `@polymer/lit-element` to version 0.6.2 (exactly) and it should work, since [v0.6.3 upgraded to lit-html v0.13.0](https://github.com/Polymer/lit-element/releases/tag/v0.6.3).
