### ISSUE TITLE
Conditional attributes

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-html#625]
Hi,

I think this is not really related to #56. I have a custom element which defines a `placeholder` attribute. It works like this: 
```html
<rhm-combo-box
            id="group"
            @select="${this.onSelectDepartment.bind(this)}"
            .value="${this.selectedDepartmentItem}"
            .items="${this.departmentComboBoxItems}"
            placeholder="Group"
          ></rhm-combo-box>
```
However, I only want to set `placeholder`if a certain condition is met. So I came up with something like this:
```html
<rhm-combo-box
            id="group"
            @select="${this.onSelectDepartment.bind(this)}"
            .value="${this.selectedDepartmentItem}"
            .items="${this.departmentComboBoxItems}"
           ${this.departmentComboBoxItems.length > 1 ? html`placeholder="Group"` : ``} 
          ></rhm-combo-box>
```
However, this ends with `TypeError: Cannot read property '2' of null` in template.ts line 88. Same if I return null instead of an empty string. Returning html`` does not do the trick either. I have also tried this with the `when` directive, but that also does not work. 

Is this even possible? 

Thanks a lot in advance.

**Comment by jsilvermist** [comment]
Not 💯 sure on this and on phone atm so I can't really check it out easily but, would something like this work?

```js
import { ifDefined } from './directives/if-defined.js';
```
...
```html
<rhm-combo-box
    id="group"
    @select="${this.onSelectDepartment.bind(this)}"
    .value="${this.selectedDepartmentItem}"
    .items="${this.departmentComboBoxItems}"
    placeholder="${ifDefined(this.departmentComboBoxItems.length > 1 ? 'Group' : undefined)}"
></rhm-combo-box>
```

**Comment by mariusGundersen** [comment]
You can use the [if Defined](https://github.com/Polymer/lit-html/blob/master/src/directives/if-defined.ts) directive to do that.

**Comment by Christian24** [comment]
Thanks a lot I went with @jsilvermist's solution. That works perfectly.
