### ISSUE TITLE
Best practice for a two-way binding with the latest permutation of parts and directives?

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-html#626]
I've been working with `lit-html` and I end up with a _lot_ of code that looks like this:

```ts
...
html`
...
<input value=${this.foo} @change=${e => this.updateFoo(e)} />...`; }

updateFoo(e) {
    this.foo = e.target.value; // or e.detail.value, etc
}
```

In particular we end up with either explicit updates (so `@change=${e => this.foo = e.target.value}`) or an update method for each input (so lots of boilerplate code, and I have hundreds of inputs to bind).

So I was thinking that we need something like this:

```ts
function bind<O extends object, K extends keyof O>(
    obj: O,
    prop: K,
    source?: string | ((evt: Event) => O[K])) {

    if (!obj)
        return; // No object to bind

    const handler = (e: Event) => {
        if (!source)
            source = 'value'; // default to value?

        // Get the target property, or use the getter function
        let val;
        if (typeof source === 'string')
            val = e.target[source];
        else
            val = source(e);

        obj[prop] = val;
    };

    // We don't need to be able to cancel the event
    (handler as any).capture = false;
    (handler as any).passive = true;

    // This works, but no documentation means it's hard to tell if I'm doing it right
    return directive((part: EventPart) => {
        part.setValue(handler);
        part.commit(); // this adds the listener, but will it get cleaned up?
    });
}
```

Then I could do `<input value=${this.foo} @change=${bind(this, 'foo')} />`, which feels a bit cleaner. I don't like having two statements for each binding-way, but it does allow different properties/events as needed (e.g. `<input type="checkbox" ?checked=${this.foo} @input=${bind(this, 'foo', 'checked')} />`)

- Does this overlap with any directives already planned? It seems like a core action and a reference implementation for an `EventPart` would be a useful resource.
- Should this also bind the value? In the `directive` I could add `part.element[source] = obj[prop];`, but in this context that's also a side effect that may be unwelcome.
- Is this the 'right' way to configure an `EventPart` `directive`?
- Does this make more sense as a new combined type of part? We could add something like `<input value@change=${bind(this, 'foo')} />`, which does both but seems even messier?
- If it is going to stay one-way would it be more commonly understandable to call it `update`?

This has been discussed before (in #181), but at that point it was suggested that it belonged in the (now deprecated) lit-extended and ended with the suggestion that `EventPart` should be used. Well, this is an attempt to use `EventPart` right.

**Comment by mariusGundersen** [comment]
I'm not sure I understand why you want to do this. Note that `value=${this.foo}` on an input sets the *attribute*, not the *property*, and you probably don't need to do that. The `value` property already has the current value of the input (and checkbox), so there isn't really any need for javascript to set it manually.

**Comment by KeithHenry** [comment]
@mariusGundersen In my simplified examples I'm using `<input>` where `value` _is_ an attribute - I have plenty of things like `<custom-control .value=${...` where it is a property.

> The value property already has the current value of the input (and checkbox), so there isn't really any need for javascript to set it manually.

How? If I didn't set it the `<input>` would start blank. How would I get the current/previous value to be the input otherwise?

In any case that bit works fine and isn't what I'm trying to fix here - `attr=${whatever}` and `.prop=${whatever}` all good, but also one way. My problem is that when the input changes I need to update `whatever`, which is easy enough each time, but I have to do it a _lot_.

I want to make it easy to have lots (I have hundreds) of inputs (custom and native) that when the user changes the value (on `@change`, `@input`, `@keyUp` or whatever) it updates the underlying object too.

**Comment by cyper8** [comment]
LitHtml is just a templating tool and does its job. For data flow boilerplate you must choose a framework or write your own solution. Since you use litHtml i may suggest [Polymer](https://polymer-project.org) or even [LitElement](https://github.com/Polymer/lit-element) though the last one is beta.

**Comment by KeithHenry** [comment]
@cyper8 `PolymerElement` has 2-way bindings with `{{...}}` but it's also deprecated - it's an upgrade path at best. `LitElement` uses `lit-html` for bindings and templates - this would be a `lit-html` `directive` (like `repeat` or `guard`). `LitElement` does already have `@eventOptions()` decorators, but that doesn't solve _this_ problem - I still have 50 inputs with 50 almost identical `@eventOptions()` functions to update 50 properties.

**Comment by cyper8** [comment]
@KeithHenry you gave event more up to date state of things on data binding in Polymer Project, thank you - I didn't know that two way data binding support is discontinued. That is sad, I must say... though you always can extend `HTMLInputElement`, or wrap `<input>` in `LitElement`-child-class-element with all needed boilerplate implemented in any convenient way.
What I wanted to point out is just that it is hardly a template-engine issue. Maybe it is better to ask in litElement repo?
And I'm just a humble user - my words are none of the _official response_ - just a private thought on the alternative a developer faces in a situation like you have described.

**Comment by KeithHenry** [comment]
@cyper8 It is a template-engine issue to everything else - React, Angular, Vue, original Polymer all included 2-way bindings in their template engines. I can totally extend lit-html to support one too, but that feels like reinventing the wheel. As you can see from my reference implementation above this is a `directive` - a direct extension of lit-html that works entirely independently of `LitElement` (which does have `@eventOptions` decorators to avoid the `e => ...(e)` noise around each handler)

I've just used `<input>` for my examples, in practice I also have map components, date pickers, various bespoke quick-find controls and the like, often nested (so that an entity with maybe 100 properties to edit is split up across sub-components and managable screens in an SPA) all currently using Polymer's two way binding and notify pattern. The plan, long term, is to move to `LitElement` for everything, and webcomponents let us do that one component at a time.

I think my solution above _might_ be a way to avoid lots of copy-paste code in scenarios where you want lots of 2-way bindings, but I'm not sure it isn't abusing the  `EventPart` or reinventing something in the roadmap.

**Comment by mariusGundersen** [comment]
> React, Angular, Vue, original Polymer all included 2-way bindings in their template engines

Sorry, I might be misunderstanding something, but how would you do two-way binding in react?

**Comment by KeithHenry** [comment]
@mariusGundersen I thought they had a mixin that did it, but my React is very rusty. Happy to redact as it's not really relevant.

**Comment by mariusGundersen** [comment]
So I guess the answer then is that, just like in React, it's not part of lit-html because it's not deemed as a thing that should be done by the core library. It is possible to create wrapper libraries that do it, as has been shown in this thread. But there are also several ways to write applications that don't require two-way bindings, which is why it's not integrated into the core of lit-html (or React).

**Comment by mkay581** [comment]
Yes, two-way binding is just one way to dynamically respond to state changes throughout an app. But there are other ways to deal with state management. So doesnt make sense to add this to core. 

> In particular we end up with either explicit updates (so `@change=${e => this.foo = e.target.value})` or an update method for each input (so lots of boilerplate code, and I have hundreds of inputs to bind).

To help with the boilerplate issue specifically, you could loop through all of the inputs and attach the `@change` handler. You'd want to loop if you're dealing with hundreds of inputs that have similar logic anyway.

**Comment by KeithHenry** [comment]
@mariusGundersen OK, well that would answer one of my questions: it's not planned, fair enough. I still think it's a good candidate for a reference implementation of an `EventPart`, once the documentation gets there.
@mkay581 I could, but in this new functional world I thought we were supposed to avoid that sort of thing? In any case I'm looking for a consistent solution a team can apply again and again, not a single specific massive form. I think auto-hookup is an interesting idea, but it's also sounds like a bug factory to me.

**Comment by mkay581** [comment]
> I could, but in this new functional world I thought we were supposed to avoid that sort of thing?

Haha functional programming is nice but not sure how doing what I proposed requires a non-functional programming paradigm.  But interesting enough, based on your earlier comments, it seems like you prefer not to use class-based logic like LitElement based on this new functional world you like. Is that why you opened this PR against lit-html instead of lit-element? :wink:

**Comment by mariusGundersen** [comment]
Instead of doing two-way binding, where it becomes difficult to track the changes to a variable as it can change at any time, it's better to handle the event and then react to that event. This is the way it's done in react for example.

In my own projects I use RxJS together with lit-html and use Observables to react to changes. So instead of having a variable that can be changed at any time by something that has a reference to it and no way to know when it has changed or by who, I use Observables. So an event pushes a new value into an observable and this value is piped through a chain that ends up updating something in lit-html. It looks something like this:

```js
const [action, observable] = createEvent(x => x);

const total = observable.scan((total, delta) => total+delta, 0);

render(html`
  <div>
    <button @click=${action(-1)}>-</button>
    ${$replace(total)}
    <button @click=${action(+1)}>+</button>
  </div>
`, elm);
```

**Comment by KeithHenry** [comment]
@mkay581 Without at least 1-way binding it's just static HTML. Lit has binding contexts for attributes, properties and events, and various custom parts (like `ifDefined`) that do specific things to make those bindings easier. This is an extension of the `EventPart` created by `@event` bindings, so it's part of what lit-html is doing.

@mariusGundersen That's really interesting and something I want to look in to, but maybe a bit too much of a shift for the current project :-)

**Comment by justinfagnani** [comment]
Hi all,

Let me clarify a few things. lit-html doesn't have two-way data-binding mainly because it only receives _values_, not expressions, and thus has no idea where to set values that change. Also, because it's just a templating library, and tries to be relatively un-opinionated, it's doesn't have a way to associate a attribute or property name with an event name. Polymer invented a convention for this, but we want to avoid that here.

Hopefully it's somewhat obvious, not just to those in this thread, that you could make a directive to implement something like 2-way binding, with whatever conventions for associating names and events you want. We won't be providing such a directiv here because of the number of options in this space.

Even if we did, it wouldn't save that many characters due to the fact that we're trying very hard to avoid metaprogramming in lit-html and LitElement. Rather than reference the bound property by name, we'd want to do it with a JS reference so that type-checkers and compilers have full visibility in to the references. A directive would look something like this:

```js
html`<input value=${bind(this.foo, (v) => this.foo = v)}>`
```

The only thing this does is add the `change` event listener for you and grab a value for `event.target.value` It's really not _that_ much savings over:

```js
html`<input value=${this.foo} @change=${(e) => this.foo = event.target.value}>`
```

Especially if you need to configure the event name, or support Polymer-style `*-changed` properties, since those events carry the value directly.

Note that the reason why we're trying to limit metaprogramming even though property binding is already using metaprogramming, is that in this one case we're planning to explore building a tsc plug-in for type-checking, and precompiler for use with Closure. If we keep the metaprogramming to property bindings, this is tractable. If not, it'll be hard to cover all the cases.

**Comment by noelmace** [comment]
FYI for people stumbling upon this issue in 2021: go check the [`live` directive](https://lit-html.polymer-project.org/guide/template-reference#cache) (for the one-way/`value` attribute part).

**Comment by nikitalpopov** [comment]
@noelmace I'm trying to add 'cancel' button which will reset value of some input to initial. Your solution works perfectly if I want to handle case like this:
```javascript
<input type="text" value="${this.value}" />
```
I just need to add `live()`:
```javascript
<input type="text" value="${live(this.value)}" />
```

But what to do in case like this:
```javascript
<input type="checkbox" checked="${this.value === someConditionVar}" />
```
? I can't pass `this.value === someConditionVar` to `live()`

I was trying something like that:
```javascript
render() {
    const checked = this.value === someConditionVar;
    return html`
        <input type="checkbox" checked="${live(checked)}" />
    `;
}
```
But it also failed

**Comment by noelmace** [comment]
@nikitalpopov I believe Justin's [answer](https://github.com/Polymer/lit-html/issues/626#issuecomment-440077976) is still valid for more complicated use cases like yours. You may use `@change` to store the checkbox boolean value in a variable, and use it in your test.

> IMO, I don't think a Github issue is a good place to discuss this kind of stuff. Go check the [Community](https://lit-html.polymer-project.org/guide/community) page related to this project, and ask your question on [Slack](https://www.polymer-project.org/slack-invite) or [Stackoverflow](https://stackoverflow.com/tags/lit-element).

**Comment by aigan** [comment]
Here is a way to react on changes from used components. Example used here is a component `my-box` that uses polymer to notify parent when the `opened` attribute changes.

```js
// Example: <my-box ?opened=${this.bind('box_opened')} />
this.bind = directive( prop => {
	const el = this;
	if( !el._bind ) el._bind = {};
	if( !el._bind[prop] ) el._bind[prop] = {};
	const binds = el._bind[prop];
	return (part) => {
		if( !binds[part.name] ){
			binds[part.name] = ev =>{
				//log("got changed event", prop, part.name, ev.detail.value );
				el[prop] = ev.detail.value;
			}
			part.element.addEventListener( part.name + "-changed", binds[part.name]);
		}
		part.setValue( el[prop] );
	}
});
```

**Comment by aigan** [comment]
> Any recommendations on how to handle properties with a nested structure?

Something like...?

```html
 <input .control=${c} @change=${this.onChange} type="text" class="form-control" id = "${c.id}" placeholder="${c.fn_param_name}" value="${c.value}">
```
```js
onChange(ev){ ev.target.control.value = ev.target.value }
```

**Comment by msingh00** [comment]
In my case, just doing that didn't work given that the nested properties were also iterables.  So requires an extra step after setting the target value..one of two solutions:

1. call requestUpdate()
2. clone the object and re-assign to the property to trigger the update to propagate.

both solution shown below in case it helps others, w/ the 2nd commented out..
```

        updateModel(e){
            e.target.ref_obj.value = e.target.value;
            this.requestUpdate();
            // let idx = this.target.getAttribute(idx)
            // let clone = structuredClone(this.panel_data);
            // clone[idx].value = e.target.value;
            // this.panel_data = clone
        }
```

**Comment by msingh00** [comment]
> > Any recommendations on how to handle properties with a nested structure?
> 
> Something like...?
> 
> ```
>  <input .control=${c} @change=${this.onChange} type="text" class="form-control" id = "${c.id}" placeholder="${c.fn_param_name}" value="${c.value}">
> ```
> 
> ```js
> onChange(ev){ ev.target.control.value = ev.target.value }
> ```

In my case, just doing that didn't work given that the nested properties were also iterables.  So requires an extra step after setting the target value..one of two solutions:

1. call requestUpdate()
2. clone the object and re-assign to the property to trigger the update to propagate.

both solution shown below in case it helps others, w/ the 2nd commented out..
```

        updateModel(e){
            e.target.ref_obj.value = e.target.value;
            this.requestUpdate();
            // let idx = this.target.getAttribute(idx)
            // let clone = structuredClone(this.panel_data);
            // clone[idx].value = e.target.value;
            // this.panel_data = clone
        }
```
