### ISSUE TITLE
[suggestion] A way to be intercept/delay node removal - `unmount` hook

### ISSUE THREAD

**Issue by prasannavl** [Polymer/lit-html#635]
I've been using `lit-html` for a while, it manages to solve most uses cases with the well designed and thoughtful use of `directives` which are quite fantastic since you don't have resort to building abstractions on top to solve things, that are better solved in the lower layers (like what `react-transition-group` does because of the lack of the ability to do it in lower layers).

But doing so, one of the most common need that I found, that couldn't be quite easily addressed without writing a good amount of abstraction, was for doing something just before node removal, and scheduling node removal right after. 

For instance, `repeat` directive lets you easily manage lists. You can do an onappear effects/animations easily by abstracting them into their own component and handling it in the lower components. But currently, there's no way to detect an onremove, since lit-html just removes the nodes right away (and all that a DOM gives you would be a diconnected hook, which happens after the fact, and not before), there's nothing more you can do and you're force to handle a full fledged view models in the top layers. 

It would be great, if there was a way to detect nodes just before removal, especially while handling lists with `repeat` and the likes -- even better if it can do so with optional promise resolutions. I think having that will help solve a large class of problems a lot more elegantly.

I suspect the ideal approach would be a directive that can work in combination with repeat, providing a hook into remove, but I also think that might be difficult looking at the way `repeat` is implemented -- so perhaps an independent directive with a removal hook.

**Comment by ruphin** [comment]
This same issue is also discussed in #527

**Comment by prasannavl** [comment]
Ah, somehow I seem to have missed the dupes. Sorry about that. Closing this.
Also, related: https://github.com/Polymer/lit-html/issues/283
