### ISSUE TITLE
Swap keyFn and Template on Repeat directive?

### ISSUE THREAD

**Issue by stramel** [Polymer/lit-html#643]
The `keyFn` in the `repeat` directive is optional but comes before the `template` param. This results in requiring code to handle it being optional.

Wouldn't it make sense to swap the `template` and `keyFn` param to remove the extra code?

https://github.com/Polymer/lit-html/blob/881c25a2ead3fce155d115999202905fc66ac6dd/src/directives/repeat.ts#L90-L99

could become,

```ts
export const repeat = directive( 
     <T>(items: Iterable<T>, 
         template: ItemTemplate<T>, 
         keyFn?: KeyFn<T>): DirectiveFn => {
```

**Comment by justinfagnani** [comment]
Personally, I think it's easier to read if the data and options are up front, and the template - which might be long - comes last. In plain HTML the equivalent would be all configuration in attributes of a `<template>` element.

**Comment by stramel** [comment]
hmmm you have a good point there. Up to you guys, was just seeing if we could clean that up a bit before the API lands stable but either way is fine.
