### ISSUE TITLE
Missing event lifecycle docs?

### ISSUE THREAD

**Issue by kokujin** [Polymer/lit-html#659]
Can someone point me to the docs on lifecycle events? Thanks

**Comment by justinfagnani** [comment]
What lifecycle events are your referring to?

**Comment by kokujin** [comment]
Things like, isMounted, unmount e.t.c

**Comment by mkay581** [comment]
Web Components have lifecycle events like `connectedCallback`, `disconnectedCallback`, etc when they are appended or removed from the DOM. [Here is more documentation on it](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions). Is this what you mean?

 If you are rendering Web Components inside of lit-html's parser, those lifecycle events will be called on each web component. But those lifecycle events have nothing to do with lit-html. In fact, they can be used even without lit-html.

**Comment by csvn** [comment]
`lit-html` does not have any preference for how lifecycle/structure is handled. `lit-html` is only concerned with updating the DOM (via e.g. ``render(html`...`, document.body)``. That said, most cases I've seen are using a base-class that you extend to get a consistent behavior for creating components.

[`lit-element`](https://github.com/Polymer/lit-element) is a lib by the Polymer team, that is an example of such a base-class. It has plenty of hooks for pre/post-render etc. In our project we are using a custom base-class that is similar to `lit-element`, with decorators for attributes (`@attr()`) and properties (`@prop()`) to invalidate the view on changes, and schedule a new render.

So what lifecycle hooks you have depend entirely on what your implementation looks like.

**Comment by kokujin** [comment]
Thanks for the info @mkay581 and @csvn. 

I would take a closer look at [lit-element](https://github.com/Polymer/lit-element#api-documentation)
