### ISSUE TITLE
@invalid doesn't listen to form element invalid events

### ISSUE THREAD

**Issue by mattlohkamp** [Polymer/lit-html#660]
normally when you `addEventListener` to the parent form it will fire on the 'invalid' event from each form element that invalidates, but I can't get that to work through lit-elements.

adding an @invalid event listener attribute to each form element is a workaround:

```
<form @invalid="${this.does_not_work}">
   <input type="text" required @invalid="${this.does_work}" />
   <input type="submit" />
</form>
```

**Comment by justinfagnani** [comment]
I can't think of anything in lit-html that would affect only the `invalid` event.

MDN says the `invalid` event doesn't bubble: https://developer.mozilla.org/en-US/docs/Web/Events/invalid It you query for the `<form>` element and manually add an event listener does it work?

**Comment by mattlohkamp** [comment]
oh, duh - the code I was testing for that had useCapture=true

demo here: https://codepen.io/mattlohkamp/pen/vQzeVZ

so to refocus slightly - if I were going to use useCapture in an event listener, I'd probably just want to do it outside of the @event syntax in lit-html?

**Comment by justinfagnani** [comment]
This should work:

```js
html`
  <form @invalid="${{handleEvent: () => this.does_work(), capture: true}}">
    <input type="text" required>
    <input type="submit">
  </form>
`
```

Or, if you're using LitElement with decorators:

```js
class MyElement {
  render() {
    return html`
      <form @invalid="${this.does_work}">
        <input type="text" required>
        <input type="submit">
      </form>
    `;
  }

  @eventOptions({capture: true})
  does_work(e) { ... }
}
```

Without decorators:
```js
MyElement.prototype.does_work.capture = true;
```

**Comment by mattlohkamp** [comment]
gotcha. thanks!
