### ISSUE TITLE
Component abstraction

### ISSUE THREAD

**Issue by askbeka** [Polymer/lit-html#661]
Very interesting project, that takes a totally different approach at solving declarative UI rendering than projects like React. And my compliments for API design, clean and simple.

In this issue I will address couple of problems, application developers may face when using lit-html: 
- handling side effects
- scaling

I am not sure about future plans for this project, but it seems to have non obvious coupling with webcomponents, namely LitElement which is webcomponents library.

Webcomponents are great, but not quite necessary. For reusable components, the leaf nodes it totally makes sense since you need to encapsulate styles, limit the boundaries of events and layout children from lightDOM in a specific way.

But for creating reusable parts of templates that might not need any of that, or there are different ways to accomplish similar things, webcomponents introduce limitations that might require extra configuration and workarrounds.

We could use simple functions that return templates, but we need to manage the internal state, which brings us to directives where we can accomplish that, then we might need to manage the life cycle, then default solution is to go with webcomponents since directives do not provide a way to do so yet (I saw couple issues here to handle that).

And I imagine developers will have this often using lit-html, they first declare a pure function the they realize that they need to keep the state and go convert it to LitElement.

And this is a problem for other projects too, like React. React team proposed a very interesting solution recently [React Hooks API](https://reactjs.org/docs/hooks-intro.html), and there is an attempt to make it work with webcomponents in [haunted](https://github.com/matthewp/haunted).
You can see that transition from pure function to full blown component or even webcomponent in case of `haunted` is simple. Aside from providing cleaner API that scales very nicely, it has other benefits, like better minification and AOC benefits.

**So** my proposal is to create component building block, that is a function that can use similar approach as React Hooks to handle internal state and side effects, but so that it makes sense for lit-html.
For example components can be absolute primitives for providing values to Parts using directives.
Meaning that return value of component functions can be any other primitive value in context of lit-html,
like javascript primitive or TemplateResult, since properties and attributes need values too and you might want to update them based on side effects, and clean them up.
So this makes component a single, scalable way to build any abstraction on top of lit-html, and it is in spirit of lit-html since docs have section about `Thinking functionally` and that `lit-html helps to express f(data) => UI`
I do not mean one to one copy of Reacts Hooks API, but would be nice addition to be able to reuse hooks from React community and contribute. and have this way to share not only UI primitives with webcomponents but also other parts of applications across frameworks.

I understand that this proposal is quite opinionated and name `component` is questionable too, but I wanted to know what is your opinion on this, especially  since I am very interested in exploring this idea, and may be to get to know if you have something intersecting planned

**Comment by justinfagnani** [comment]
The web has a component model already, and that's Web Components. We have really no interested in making yet another component model to compete with both the native component model, and the million other proprietary component models that exist only because the web didn't have a native one for so long. In my opinion, adding one would only harm the wider web development ecosystem.

As you point out, directives have some features of components, and we do want to make that API easier to use, especially around managing state, but we won't ever promote it as a full-blown component model. They're powerful enough to be used that way if someone wishes (Haunted does), but we're going to encourage that directives are for enhancing template capabilities and components should be Web Components - _which will be usable outside of lit-html_. We've no interest in creating another component silo.

**Comment by mariusGundersen** [comment]
Having used lit-html for a project without any web-components, I agree that the component handling needs to be improved. I think it's important, before we start discussing code and features, to define what a component is and what it should be able to do. IMO it is different from a memoized pure function, which lit-html already supports quite well, in that it has both *state* and *lifecycle events*. I've been hacking away at some ways to implement this, for example in #591, and based on that a way to define a component could be like this:

```js

// This is the simplest possible implementation, 
// it could be made more advanced
const component = func => createDirective(
  part => func(
    value => part.commitValue(value)
  )
);

// Define a reusable component
// It works by creating a closure where 
// state can be stored.
// @param commit is a function that can
// be called to update the current content
// of the DOM
const Counter = component(commit => {
  // Here is the state for the component
  let previousInitialCount = undefined;
  let count = 0;

  // Some helper functions
  // Note that in this very simple example
  // we need to manually rerender the DOM
  // after updating state
  function decrement(){
    count--;
    commit(render());
  }

  function increment(){
    count++;
    commit(render());
  }

  // Another function, this one rendering the
  // component. The result is passed to the 
  // commit function
  const render = () => html`
    <button @click=${decrement}>-</button>
    <strong>${count}</strong>
    <button @click=${increment}>+</button>
  `;

  // Here we return a function that will be called
  // every time the lit-html tree is rendered.
  // Instead of returning a function we could return
  // an object with several methods, including
  // various lifecycle events
  return (initialCount=0) => {
    // Handle both the initial and subsequent
    // renders. If the parameter changes reset 
    // the counter
    if(initialCount !== previousInitialCount){
      previousInitialCount = initialCount;
      count = initialCount;

      // Render the component when changed
      commit(render());
    }
  }
});

// How to use component in an app
const app = () => html`
  <div>
    <h1>A counter example</h1>
    ${Counter(0)}
  </div>
`;
```

This example does not rely on any global state, unlike react hooks, and can therefore be easily tested and mocked. It is also easy to compose to handle different scenarios. For example, the code that checks if the `initialCount` is different from the `previousInitialCount` could be removed by wrapping the returned function in `memo()`, defined like this:

```js
const memo = update => {
  let params = undefined;

  return (...next) => {
    if(params
      && params.length === next.length
      && next.every((x, i) => x === params[i])){
      return;
    }

    params = next;
    update(...next);
  };
}

// ... inside the component
  return memo((initialCount=0) => {
    // This is now only called when initialCount changes
    // Handle both the initial and subsequent renders. 
    count = initialCount;

    // Render the component
    commit(render());
  });
```

So other small functions can be introduced to handle for example re-rendering automatically when state changes, etc. 

I guess the most important lifecycle hook is when the component is detached, but this requires a lot of work in lit-html. I think work is being done on this, but it's not very visible here on github.

**Comment by web-padawan** [comment]
> So the difference is in class definition(lit-element) vs function definition(haunted)

The LitElement class definition is a sugar on top of the native Custom Elements spec.
React community is moving away from classes, but that's a separate topic.

**Comment by askbeka** [comment]
@web-padawan

> The LitElement class definition is a sugar on top of the native Custom Elements spec.

Yes, but I would say more like a extension of base webcomponents spec, since it adds features like props and etc.
So relation `LitElement->WebComponents` is similar to `TypeScript -> Javascript`, rather than `(Elm, ClojureScript, ReasonML) -> JavasScript`

Moving away from classes is a positive move for React since it helps,  with best practices they are advocating, like composition over inheritance. Webcompoents could learn from their experience, since it is following very similar path right now. For example React had mixins too,, which is very popular in WebComponents applications, and [moved away from them](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750).

I don't have intentions starting a holy war, here. Just stating what happened:)

**Comment by mkay581** [comment]
> For example React had mixins too,, which is very popular in WebComponents applications

You sure about this? I have quite a few of applications built using no framework and just web components and have never need to use a mixin. I personally think mixins can be confusing. I doubt anyone is advocating for this here.

> Moving away from classes is a positive move for React since it helps, with best practices they are advocating, like composition over inheritance. 

True but I do think when Classes are used (and inherited correctly), it has its advantages.

**Comment by askbeka** [comment]
@mkay581 
> You sure about this?

I am quite sure, being heavily involved building applications using WebComponents.
How would you implement reusable behaviors otherwise in Wecomponents world?

> True but I do think when Classes are used (and inherited correctly), they can be advantageous.

JavaScript has prototypal inheritance, Correct use of classes in JavaScript,  in my experience was not using much of their features.

**Comment by askbeka** [comment]
@justinfagnani 
> Just to be clear, React had problems with their particular formulation of mixins. JavaScript class mixins do not have those problems.

Partially true, they had their own mixins implementation and were considering to move to JavaScript class mixins, and still have decided not too. And motivations are stated in that article.

I do recognize all of the problems they have mentioned, in JS class mixins

**Comment by askbeka** [comment]
Let me give an outline how compositioncould look like using function definition:

```javascript
const MyChildFn = props => (html`<div>${props.name}</div>`)

const AppFn = (props) => {
  const [state, setState] = useState(initialState);
  
  return html`
     <main>
        ${MyChildFn({ name: 'askbeka' })}
        <--! OR -->
        <my-child .name=${'askbeka'}></my-child>
     </main>
  `;
}
```

**Comment by askbeka** [comment]
Previous is what `haunted` already provides:
If we go further with the idea of Components they can be applied to other parts as I have stated above:

```javascript

const transactionsFn = ({ order, filter }) => {
  const [state, setState] = useState([]);
  
  useEffect(() => {

    transactionsBus.subscribe();

    transactionsBus.on('update', (data) => {
       setState(data);
    });

    return () => transactionsBus.unsubscribe();

  }, [order, filter]); 

 return state;
}

const transactions = virtual(transactionsFn);

html`
  <main>
      <x-grid .data=${transactionDataProvider({ order: 'ascending', filter: '24h' })}></x-grid>
  </main>
`
```

**Comment by askbeka** [comment]
As you can see there are issues with when to use what, and documentation and more intuitive API design could help, but there is a big win in uniform way to describe data transformations into UI
