### ISSUE TITLE
EventPart use of EventListener interface assumption that interface contains eventListener options causes side affects

### ISSUE THREAD

**Issue by purtuga** [Polymer/lit-html#669]
The current implementation of `EventPart` assumes that if we use an Object that exposes the `EventListener` interface, that it also (may) contain options for `addEventListener()`. This behavior restricts and limits the use of `EventListener` interface - which only requires the `handleEvent()` method to be defined. This in turn means that (in some cases) we can not longer apply that interface to non-simple objects that might have members that conflict in naming with those option supported by `addEventListener()` options.

Example: I have a CE base class that exposes an `EventEmitter` like interface for event handling ---  something like this:

```javascript
class HelloWorld extends HTMLElement {
    handleEvent() {}

    render() {
        return html`<button @click=${ this }">Click me</button>`;
    }
    
    // EventEmitter type of interface applied to class
    on(){}
    once(){}
    off(){}
    emit(){}
}
```

In the above, the click event will be emitted only once - this is the side affect that was caused by the fact that `once()` was picked up as the option value for `addEventListener()`. 

My Questions: :grimacing:
- Should this be the default behavior for `EventPart`?
- If so, could we have a mechanism to turn it off? and possibly have a more explicit way to define the options object from our template - perhaps something like what was suggested [here](https://github.com/Polymer/lit-html/issues/662#issuecomment-443219165) ?

Appreciate your time on this item.

/paul

_____
(FYI: this in away is also related to the topics [here](https://github.com/Polymer/lit-html/issues/662) around supporting event name Modifiers :smiley:  )

**Comment by justinfagnani** [comment]
This is indeed a small hazzard here, but it can be turned off by using a function or object to wrap the other object. Event bindings are a specific API that has its own requirements, I think it's ok for it to vary slightly from addEventListener.
