### ISSUE TITLE
regression 0.13 -> 0.14: Source code string rendered into dom, expected element to be inserted.

### ISSUE THREAD

**Issue by xxgreg** [Polymer/lit-html#687]
After upgrading from lit-element 0.6.3 -> 0.6.4, and from lit-html 0.13 -> 0.14, I now see:

<img width="1565" alt="screen shot 2018-12-11 at 9 51 48 am" src="https://user-images.githubusercontent.com/704/49760982-a1372680-fd2a-11e8-9eb7-d82a111f5fac.png">

It appears that the places in my source code where I insert an element into a lit template are rendering the toString of a lit-html library function, rather than inserting the element as previously.

This happens in both Chrome and Safari.

I am not using the web components polyfill.

I can't share the source code publicly. I'll see if I can find some time to make a minimal reproduction, and share that.

**Comment by Westbrook** [comment]
If you run `yarn list lit-html` or `yarn list @polymer/lit-element` are you seeing multiple version in your `node_modules`? You need to only have one install of each, and this often occurs when version mismatches are perceived as you wanting more than one copy in your dependency tree.

**Comment by xxgreg** [comment]
Should I remove the direct lit-html dependency from my package.json?

package.json
```
  "dependencies": {
    "@polymer/lit-element": "^0.6.4",
    "lit-html": "^0.14.0",
    "pwa-helpers": "^0.9.0",
    "rxjs": "^6.3.3"
  }
```

npm ls
```
job-editor-proto@0.0.1
├─┬ @polymer/lit-element@0.6.4
│ └── lit-html@0.14.0 deduped
├── lit-html@0.14.0
├── pwa-helpers@0.9.0
└─┬ rxjs@6.3.3
  └── tslib@1.9.3
```

**Comment by xxgreg** [comment]
Thank you. Removing the explicit lit-html dependency from package.json fixed this.

I'll close this issue.
