### ISSUE TITLE
(Some?) directives don't work in 1.0

### ISSUE THREAD

**Issue by tpluscode** [Polymer/lit-html#705]
## Description

At least `until` and `repeat` don't work in 1.0 RC. Instead of the expected output they print a chunk of JS code. This, actually: https://github.com/Polymer/lit-html/blob/bcc87cf6488fa414e5361a9d46d992f01c11517a/src/lib/directive.ts#L42-L47

## Current behavior

https://stackblitz.com/edit/js-rnkbrw?file=index.js

## Expected behavior

As it was with 0.14: https://stackblitz.com/edit/js-qgfwzd

**Comment by tpluscode** [comment]
Oh, I'm sorry, apparently it has to be `import {} from lit-html/directives/*` in both cases. Don't know where I got `lit-html/lib/until`.

However, why does this actually build? Also webstorm complains about `lit-html/lib/if-defined` but not about `lit-html/lib/until` 🤔

**Comment by ruphin** [comment]
It's unreliable because you use node-style imports. If you don't specify an absolute path, Nodejs will try to import anything that could match that path. If an older version of lit-html exists anywhere in your node_modules folder, you can end up importing from there.

**Comment by rapodaca** [comment]
In 1.0.0 running from unpkg.com, the import for repeat needs to be:

```javascript
import { repeat } from 'https://unpkg.com/lit-html@1.0.0/directives/repeat.js';
```

Importing from `lib/repeat.js` caused the error, in which a chunk of JS is inserted into the DOM.
