### ISSUE TITLE
[docs] Change npm installation instructions to reduce chance of package duplication

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#706]
The default version range that `npm i` writes to pakcage.json is `^{current_version}`, ie `npm i lit-html` when the current version of lit-html is 1.0.3 will use a version constraint of `^1.0.3`. This constraint is usually unnecessarily high, as the package can probably work with version 1.0.0, and can lead to unnecessary package duplication in some cases.

We'd encourage better version constraint hygiene if we change installation instructions to use `npm i lit-html@^1.0.0` (once we release 1.0).

**Comment by arthurevans** [comment]
I assume we should add this on lit-element as well?

**Comment by justinfagnani** [comment]
Yep!
