### ISSUE TITLE
"node is null" in `reparentNodes`

### ISSUE THREAD

**Issue by jhpratt** [Polymer/lit-html#709]
Currently getting the error which my source map traces back to [src/lib/dom.ts:38](https://github.com/Polymer/lit-html/blob/c1b3bfd0d4fb5d2db2a897c487a28f6737168734/src/lib/dom.ts#L38).

I'm getting this when I'm setting a property that's used as the innerHTML of an element. Not entirely sure why `reparentNodes` is even being run.

I can try to create a minimal example, but this only seems to occur when I'm receiving the data via a WebSocket connection (which obviously shouldn't matter).

**Comment by justinfagnani** [comment]
This is old and we'd need a reproduction anyway. We'll see if new reports occur with 2.0.
