### ISSUE TITLE
Make the attribute/prop difference between lit-html and lit-extended clearer

### ISSUE THREAD

**Issue by kenchris** [Polymer/lit-html#71]
Docs say that lit-extended uses properties by default, but it doesn't point out that lit-html uses attributes, so maybe that could be made a bit more clear?

I at least had to look through the code to figure out why things wasn't working with lit-extended

**Comment by Hotell** [comment]
I guess it's mentioned right here -> https://github.com/PolymerLabs/lit-html#template-rendering

ofc for beginner is very confusing 

> lit-html includes two type of parts by default: NodePart and AttributePart, which let you set text content and attribute values respectively. 

and then for lit-extended

> Rendering can be customized by providing alternate render() implementations which create different kinds of TemplateInstances and Parts, like PropertyPart and EventPart included in lib/lit-extended.ts

but I totally agree it should be stated more explicit and user friendly in the docs 👍

**Comment by justinfagnani** [comment]
Going to close this as a little old and hopefully addressed in the new doc site here: https://polymer.github.io/lit-html/guide/writing-templates.html#lit-html-or-lit-extended
