### ISSUE TITLE
Docs: Menu is transparent and shows what is below

### ISSUE THREAD

**Issue by kenchris** [Polymer/lit-html#716]
![screenshot_20181219-203419](https://user-images.githubusercontent.com/1101339/50254682-cdf3d980-03cd-11e9-9f93-bc72b1140692.png)

**Comment by kenchris** [comment]
Seems to only affect the top content

**Comment by justinfagnani** [comment]
I think this is fixed now.

**Comment by justinfagnani** [comment]
@kenchris can you verify on the device you saw this on?

**Comment by kenchris** [comment]
Yes works now
