### ISSUE TITLE
Add current section indicator to docs

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#723]
"Guide" or "API" could use a highlight, underline or something.

cc @yuinchien for guidance

**Comment by brettdewoody** [comment]
Same for the sections on the left-sidebar, they would benefit from an active style:
* Introduction
* Getting Started
* Writing templates
* Template syntax reference
* Concepts

**Comment by brettdewoody** [comment]
Preference on the 2 options below:

1. <img width="199" alt="screenshot 2019-01-04 at 22 55 36" src="https://user-images.githubusercontent.com/409070/50715177-f0dfe800-1073-11e9-88d2-a0196958adbd.png">
2. <img width="202" alt="screenshot 2019-01-04 at 22 48 59" src="https://user-images.githubusercontent.com/409070/50715178-f0dfe800-1073-11e9-80cf-5c75c0fe132c.png">

Option 1 uses a bottom border. Option 2 uses a text-underline.

**Comment by brettdewoody** [comment]
Option 1 has my vote.

**Comment by hyperpress** [comment]
Option 1. Provides a better menu styled presentation, IMHO.

**Comment by kenchris** [comment]
1. definitely

**Comment by yuinchien** [comment]
![20190104 tab](https://user-images.githubusercontent.com/406636/50716670-8315cb00-1037-11e9-8970-48ce81566578.png)

Hello, according to the Material tab design pattern, the highlighter should be anchored at the bottom of the topbar.

**Comment by brettdewoody** [comment]
@yuinchien while i like Material design, imo that doesn't provide a clear indication of the active tab.

**Comment by hyperpress** [comment]
Yes, the Material Design would need a contrasting text and border color.
Doesn't work with the same white background.

**Comment by hyperpress** [comment]
If you add 2px contrasting border-bottom to the navbar, you can achieve
that, like so:

**Comment by hyperpress** [comment]
Something like adding a bottom border with a contrasting color, like this, works:
![screenshot_20190104-181446](https://user-images.githubusercontent.com/25212653/50717520-63899d00-104d-11e9-8bff-8f88d6ff613b.png)

**Comment by brettdewoody** [comment]
That works well when the background of the nav and primary background are close in color, but on lit-html we already have a contrasting nav and main background. 

Going with a different direction...

<img width="217" alt="screenshot 2019-01-05 at 10 40 47" src="https://user-images.githubusercontent.com/409070/50723491-6a102700-10d6-11e9-9470-7a560992db13.png">

**Comment by hyperpress** [comment]
I like that.

**Comment by eeayor** [comment]
很好

**Comment by eeayor** [comment]
Very good!

**Comment by brettdewoody** [comment]
@yuinchien is this too far from Material UI guidelines to use?

**Comment by yuinchien** [comment]
@brettdewoody i think it looks like buttons instead of tabs. I'd suggest using the standard underline pattern, visually it's clean and quite common people are used to it's purpose/behavior. If the concern is that the white underline needs more contrast, we can make the topbar shadow more prominent, and add transparency(70%) to unselected tab labels.

<img width="682" alt="screen shot 2019-01-31 at 1 10 13 pm" src="https://user-images.githubusercontent.com/406636/52085534-92fecd00-2559-11e9-8ace-75300e5bd09b.png">
