### ISSUE TITLE
repeat not working

### ISSUE THREAD

**Issue by kambeena** [Polymer/lit-html#725]
render() {
        return html`<ul>${repeat(this.itemsList, (todo) => todo.id, (todo) => html`\<li>${todo.item}\</li>`</ul>`;
    }
(note : backticks are removed by formating)
returns 
(...args) => { const d = f(...args); directives.set(d, true); return d; } not the html list.

My itemsList is:
[{"id":1545488867446,"item":"kam todo","done":false},{"id":1545488871284,"item":"hello","done":false},{"id":1545488877314,"item":"new hello","done":false}]

**Comment by CaptainCodeman** [comment]
if by "returns" you mean "renders onto the page" then check if you have multiple copies of lit-html being used (e.g. more than one copy in your node_modules tree)

**Comment by kambeena** [comment]
Thanks Captain, Yes its renders on the page. I will check for duplicate lit-html.

**Comment by justinfagnani** [comment]
This is likely caused by multiple version of lit-html. Run `npm dedupe` and then check your package-lock.

**Comment by kambeena** [comment]
Thanks.

**Comment by govis** [comment]
same here, get <code>(...args) => {  const d = f(...args);  directives.set(d, true);  return d; }</code> stamped instead of html with lit-html 1.0.0 (no other versions seem present)

**Comment by pnewell** [comment]
Reopening because I am seeing this same issue. Using lit-html and lit-element together. This simple component causes the same issue ((...args) => { const d = f(...args); directives.set(d, true); return d; } is printed on the page):

```
  render() {
    var test = ["apple","orange","banana"];
    return html`
      <div>
        ${repeat(test, (test) => html`<h3>${test}</h3>`)}
      </div>
    `
  }
```

**Comment by BedrucktesPapier** [comment]
Have the same problem in a lit-element and desperately looking for a fast way to bind large arrays

**Comment by LarsDenBakker** [comment]
Did you read justin's answer to this issue?

**Comment by hyperpress** [comment]
Try `npm dedupe` or delete `*package-lock.json* and node_modules` and
reinstall.
