### ISSUE TITLE
select rendering bug

### ISSUE THREAD

**Issue by robhicks** [Polymer/lit-html#735]
# Description
lit-html does not render selected option of select element upon switching data values and re-rendering

# Steps to Reproduce
1. Clone this [repo](https://github.com/robhicks/lit-html-select-issue)
2. npm install with node 10
3. run npx rollup -cw
4. browse to localhost:5011 using Chrome, Safari and Firefox. Note no polyfills have been loaded. You'll notice the problem in Chrome and Firefox.
5. select either A or B and then select an option in the select element. Now switch to the opposite button (A or B). Look at the console. You'll see the underlying model changed. Use your developer tools and notice the select attribute is on the right option but that option is not render as selected. 

## Expected Results
I would expect the select to display the option with the select attribute. It works correctly in Safari.

## Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by justinfagnani** [comment]
We've addressed this with the `live()` directive, which dirty-checks against the live DOM value, rather than the previously bound value.
