### ISSUE TITLE
shady-render requires existence of `ShadowRoot`

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#742]
This effectively requires either native Shadow DOM or the polyfill to be loaded.

The issue is at https://github.com/Polymer/lit-html/blob/master/src/lib/shady-render.ts#L247 and could be easily avoided with a `window.ShadowRoot` check.

**Comment by quetzalsly** [comment]
Is there any progress on this? I am trying to convert some old project that uses bootstrap to use lit-element but I don't plan to use shadow dom, would be nice to avoid loading the polyfils for shadow dom if they are not needed?

**Comment by justinfagnani** [comment]
@bicknellr could you take a look at this, since you're roughly in the CSS/render area?

**Comment by bicknellr** [comment]
It looks like this has already been fixed by https://github.com/Polymer/lit-html/pull/824. However, I don't think we are testing shady-render in an explicitly non-polyfilled case. I'll work on setting up tests for that situation.

**Comment by bicknellr** [comment]
Oh, now I'm seeing the issue, `options` is effectively non-optional with shady-render.

**Comment by bicknellr** [comment]
Talked with @justinfagnani, sounds like it's expected that `options` with `scopeName` is required, but should throw a better error.

**Comment by bicknellr** [comment]
@quetzalsly, is there a particular reason you're planning to use shady-render (as opposed to the regular render function) even though you're not using Shadow DOM?

**Comment by quetzalsly** [comment]
@bicknellr I am using lit-element which I assume uses shady-render? lit-element source has `import {render} from 'lit-html/lib/shady-render.js';` unless there's some other way to configure lit-element? I am still learning how to use this framework.

**Comment by bicknellr** [comment]
Oh, I didn't realize lit-element used it by default. That case should also be OK without a polyfill as of #824 because [lit-element always passes `scopeName`](https://github.com/Polymer/lit-element/blob/508af0ee635549d1f2a87feccff4eb97b82c51ba/src/lit-element.ts#L216-L220). Also, I think that lit-element reads `render` from [this static property](https://github.com/Polymer/lit-element/blob/508af0ee635549d1f2a87feccff4eb97b82c51ba/src/lit-element.ts#L68-L76) so that you can override it (with the non-shady `render` function, for example) if you want a particular class that extends `LitElement` to render differently - but that shouldn't be necessary. If you find otherwise, please post a bug!

**Comment by quetzalsly** [comment]
@bicknellr Thanks for the explanation, I am still a bit confused though, right now I use this html + js:

```
<script>window.process={env:{NODE_ENV:'production'}};window.WebComponents=window.WebComponents||{};window.WebComponents.root='node_modules/@webcomponents/webcomponentsjs/';if('serviceWorker' in window.navigator){window.addEventListener('load',function(){window.navigator.serviceWorker.register('service-worker.js',{scope:'/'})})}</script>
```

```
import "regenerator-runtime/runtime";
import "@webcomponents/webcomponentsjs/webcomponents-bundle.js";
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js';
import './components/my-app.js';
```

I am transpiling to es5 using babel, so the ce adapter is needed I guess. Not sure if I should be using webcomponents-bundle or loader? I don't want to use shadow dom at all in this project and it's a bit confusing how to include only the minimal polyfils. Should I be like writing my own webcomponents-loader to not include the shady stuff?
