### ISSUE TITLE
Form element setting/updating

### ISSUE THREAD

**Issue by robhicks** [Polymer/lit-html#743]
# Description
Either I don't understand how to use lit-html or it has some serious bugs in form processing. 

This is related to https://github.com/Polymer/lit-html/issues/735. 

In lit-html 1.0.0-rc.2, I have the following template, which does not work as expected.
```Javascript
import { html } from './node_modules/lit-html/lit-html.js';
import css from './css.js';

export default function template(c) {
  console.log('props', c.text, c.selected, c.checkbox, c.radioButton);
  const changeText = c.changeText.bind(c);
  return html`
    ${css()}
    <form>
      <div>input cannot be updated programatically</div>
      <input type="text" value="${c.text}" @input="${changeText}"/>

      <div>select cannot be set/changed programatically</div>
      <select @change="${ev => {c.selected = ev.currentTarget.value; console.log('value set to', ev.currentTarget.value)}}">
        <option value="" ?selected="${c.selcted === ''}">Select</option>
        <option value="1" ?selected="${c.selcted === '1'}">1</option>
        <option value="2" ?selected="${c.selcted === '2'}">2</option>
        <option value="3" ?selected="${c.selcted === '3'}">3</option>
        <option value="4" ?selected="${c.selcted === '4'}">4</option>
      </select>
      <div>checkbox cannot be updated programatically</div>
      <input
        type="checkbox"
        @change="${(ev) => {c.checkbox = ev.currentTarget.value; console.log('checkbox value:', ev.currentTarget.value)}}"
        ?checked="${c.checkbox === 'on'}"
      />
      <div>radio buttons cannot be updated programatically</div>
      <input
        name="radio"
        type="radio"
        value="1"
        @change="${ev => {c.radioButton = '1'; console.log('radio button value: ', ev.currentTarget.value)}}"
        ?checked="${c.radioButton === '1'}"/>
      <label>1</label>
      <input
        name="radio"
        type="radio"
        value="2"
        @change="${ev => {c.radioButton = '2'; console.log('radio button value: ', ev.currentTarget.value)}}"
        ?checked="${c.radioButton === '2'}"/>
      <label>2</label>
      <input
        name="radio"
        type="radio"
        value="3"
        @change="${ev => {c.radioButton = '3'; console.log('radio button value: ', ev.currentTarget.value)}}"
        ?checked="${c.radioButton === '3'}"/>
      <label>3</label>
    </form>
  `;
}
```
It is populated/controlled by the following native web component:

```Javascript
import { render } from './node_modules/lit-html/lit-html.js';
import template from './template.js';

class MyForm extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({mode: 'open'});
    this.text = 'foo';
    this.selected = '2';
    this.checkbox = 'on';
    this.radioButton = '1';
  }

  attributeChangedCallback(name, oVal, nVal) {

  }

  connectedCallback() {
    this.render();
    setInterval(() => {
      this.text = 'foobar';
      this.selected = '3';
      this.checkbox = 'off';
      this.radioButton = '2';
      this.render();
    }, 2000);
  }

  disconnectedCallback() {

  }

  changeText(ev) {
    const { value } = ev.currentTarget;
    this.text = value;
    this.render();
  }

  render() {
    render(template(this), this.shadowRoot);
  }

  static get observedAttributes() {
    return ['']
  }
}
customElements.get('my-form') || customElements.define('my-form', MyForm);

export { MyForm }
```
Note the web component attempts to set the value of various inputs on first render. Thereafter, it attempts to set them again using setInterval. setInterval is used solely to show how the web component is attempting to update the template. 

In the case of the select, an option cannot be set programatically. And in the case of each of the other input elements, once selected in the UI cannot be updated programatically. 

I have created a [small repo](https://github.com/robhicks/lit-html-issues) that hooks all of this up. 

# Steps to Reproduce
1. clone [the repo](https://github.com/robhicks/lit-html-issues)
2. follow the instructions in the readme

## Expected Results

I would expect each of the input elements to be set on first render. Then, after a user selects a value and blurs the field, I would expect the web component to reset each of the values.
## Actual Results

The select cannot be set or updated programatically. 
Once changed by a user, the other input elements cannot be set programatically. 
## Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge - NOT TESTED 
- [x] Safari 12
- [ ] Safari 11 - NOT TESTED
- [ ] Safari 10 - NOT TESTED
- [ ] IE 11 - NOT TESTED

**Comment by Westbrook** [comment]
Take a look at this typeo: `c.selcted` as opposed to `c.selected`. With that changed it seems your repo works as expected. Let me know if I misunderstood something.

**Comment by Westbrook** [comment]
On thing of side note:

When using `<input type="text" value="${c.text}" @input="${changeText}"/>` you are setting the attribute of `value` not the property, so this won't overwrite any user input for that element. This is due to the way that (unlike most property/attribute pairs) the `value` property and attribute are not attached to each other in an `input` element.

Might not be important for what you're working on, but my brain fell into the trap of seeing that as the source of your troubles as I was developing my understanding of this issue here.

**Comment by robhicks** [comment]
@Westbrook Thanks for responding! It's always great when someone responds. 

I have updated the repo and the select can now be set initially.

Based upon your comment about attributes and properties, I'm still baffled about how lit-html is supposed to work. 

I understand non-standard attributes do not set properties. And I understand that the value attribute is one way, setting the attribute updates the property but setting the property does not update the attribute.

However, in the repo and text input example, the web component sets the value of this.text, render is then called, and the value attribute of the input should get changed by lit, which should change not only the attribute in the DOM but also the property. 

Anyway, since what I'm doing is apparently not the right way to make changes in lit, can you point me to the right way?

**Comment by Westbrook** [comment]
It is important to know that lit-html works the way HTML works in all cases that the functionality that it is delivering is already available to you. This is why the interaction with `input` is so specific, lit-html isn't doing anything that the HTML specification doesn't already enforce for this element. However, it seems that you have a pretty solid understanding of the overall technique across the rest of your template. I'd keep on eye on the evolving documentation site and make sure to join the Slack channel to have someone to kick the tires of your ideas, but other than that keep on putting in the time!

When you use `<input type="text" value="${c.text}" @input="${changeText}"/>` you are setting the attribute. This will also set the property _ONLY_ when the property hasn't been set by actual input. That is to say, in you demo, if you type really quickly (before you setTimeout) then the attribute changing will not override the new property that the user has set. _IF_ you want the data that you are using to be the master UI (meaning you want to override what the user sets) then you need to use `<input type="text" .value="${c.text}" @input="${changeText}"/>` which will always set the property of `value` and as such change the actual visual content of the input.

**Comment by justinfagnani** [comment]
@Westbrook it correct here.

To reiterate for clarification. lit-html does special-case any elements or attributes. WYSISYG in terms of the bindings: `attr=${}` is always an attribute binding, `.prop=${}` is always a property binding, etc. `<input>` is arguably weird because it ignores `value` attribute updates after parsing, but that's on `<input>`.

I did file an issue on eslint-plugin-lit to warn on this case: https://github.com/43081j/eslint-plugin-lit/issues/20
