### ISSUE TITLE
Tooling docs

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#744]
We should have a tooling section in the docs that shows how to get up-and-running with modules, integrate modules into common build setups like Rollup and WebPack, and recommends tools to make DX better.

- Dev server: `polymer serve`
- Testing: `polymer test` and/or link to a Karma setup
- VS Code plugin: https://marketplace.visualstudio.com/items?itemName=bierner.lit-html
- ESLint plugin: https://github.com/43081j/eslint-plugin-lit
- Template minification: https://github.com/asyncLiz/minify-html-literals
- Mention `npm dedupe`, Yarn, etc.

**Comment by justinfagnani** [comment]
See https://github.com/web-padawan/awesome-lit-html for a nice list of tools and other libraries.

**Comment by LarsDenBakker** [comment]
We have a setup for karma with web components: https://open-wc.org/guide/testing.html#setup

**Comment by stramel** [comment]
It would be nice to have some pre-made sandbox templates built for developers to play with `lit-html` and use for reproductions in issues (maybe include in ISSUE_TEMPLATE?)

**Comment by arthurevans** [comment]
Trying to figure out what the MVP (MVD?) for this doc is. 

It seems like the bare minimum would be how to work with modules (polymer serve/build steps). It doesn't look like either awesome-lit-html or openwc mention this.

open-wc.org has a lot of great resources, but they're all set up for a web component, mostly LitElement, and as a user I don't necessarily know how to adapt those to a project that's not a WC, for example.

From Justin's original list, is this the minimum set we need:

- Dev server: polymer serve (any other dev servers that do this?)
- Testing: polymer test and/or link to a Karma setup (maybe add a karma setup for vanilla lit-html based on one of the open-wc ones?)
- IDE plugins: awesome-lit-html has a more comprehensive list of plugins (for multiple IDEs/editors).
    - VS Code plugin: https://marketplace.visualstudio.com/items?itemName=bierner.lit-html
     - ESLint plugin: https://github.com/43081j/eslint-plugin-lit
- Template minification: awesome-lit-html has a list for multiple build tools.
    https://github.com/asyncLiz/minify-html-literals
- Mention npm dedupe, Yarn, etc.
   Haven't the faintest idea what we'd say about these.

**Comment by arthurevans** [comment]
Is there something useful we can say about build (webpack config, polymer build)... Seems like the relevant points for lit-html itself are handling ES modules and template minification.

**Comment by daKmoR** [comment]
🎉  We just released a bunch of tools and docs for developing web components 🎉 
- [Simple web server](https://open-wc.org/developing/owc-dev-server.html)  
  - only changes bare modules
  - so by fare not as powerful as polymer serve 
  - if you only develop in chrome it's good enough
- [Webpack configuration](https://open-wc.org/building/building-webpack.html)
  - also with config for webpack dev server => for when you need to debug in something other then chrome
  - it has Template minification
  - and creating 2 bundles for with and without es modules support
- [Modern WC polyfills loader](https://open-wc.org/building/polyfills-loader.html)
  - was needed for the webpack config to have no conflict with babel and to allow for the smallest bundle size

I hope some of the stuff is usefull for you guys 🤗 

> Mention npm dedupe, Yarn, etc.

I think that is still the biggest pain point especially if you are new... however no clue howto best prevent or explain this 🙈
