### ISSUE TITLE
NodePart private functions

### ISSUE THREAD

**Issue by kaaninel** [Polymer/lit-html#747]
# Description
I'm trying to extend NodePart and change template processor with mine but _commitIterable is private not protected so when I'm extending it I can't override _commitIterable function to create my extended nodepart class. 

# Steps to Reproduce
1. Open IDE
2. Create a ".ts" file
3. Define a class extends NodePart
4. Try to define _commitIterable inside it.

## Expected Results
No Typescript Error 

## Actual Results
Class 'LinkNodePart' incorrectly extends base class 'NodePart'.
  Types have separate declarations of a private property '_commitIterable'. [2415]

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] IE 11
- [x] Safari 10

**Comment by kaaninel** [comment]
Also its really painful to define your own processor when you try to override NodePart. I think TemplateProcessor needs a rework about typescript types.

**Comment by justinfagnani** [comment]
_commitIterable is private because it's too low level to commit to not breaking. It used to be part of commit(). What are you trying to do?

**Comment by kaaninel** [comment]
I imlemented something like directives that i call "block". Basically a class for managing parts. 
```typescript
class LinkNodePart extends NodePart {
  commit(){
    const V = this._pendingValue;
    if(V instanceof Block) {
      //@ts-ignore
      V.$Assign(this);
      this._pendingValue = noChange;
    }
    super.commit();
  }
  //_commitIterable here
}
```
I just wanna use this class instead of NodePart everywhere. I think lit needs something like this with a better implementation but for experiment I'm trying out in my lib before creating an issue about it. 

```typescript

class Profile extends Block {
  
  _Id: number;

  get Id(){
    return this._Id;
  }

  set Id(Value: number){
    if(this._Id !== Value) {
      this._Id = Value;
      this.Load();
    }
  }

  constructor(Id?: number){
    super();
    if(Id) this.Id = Id;
  }

  async Load(){
    const Req = await fetch(`https://swapi.co/api/people/${this.Id}`);
    const JSON = await Req.json();
    this.Template = html`
      Name: ${JSON.name}
      Gender: ${JSON.gender}
    `;
  }

}
```
An example block and usage would be 
```typescript
const ProfileBlock = new Profile(1);

render(html`${ProfileBlock}${ProfileBlock}`, container);

setInterval(() => { ProfileBlock.Id++; }, 10000);
```
as you can guess this helps that block to be rendered without a dom node attachment so wont break my styles and I can manage similar blocks. This way i can refresh all the info of small components on my page without triggering my elements lifecycle. 

Also i got pretty promising results during tests. With this Block thing i added 10k text node that's refreshing every second and it only consumed 57mb of ram + 10% cpu of i7 notebook. With 40k text node 95mb of ram and 45% cpu and it still had idle time a lot. Of course  this test is a bit optimized for scenario but for most uses i can see it can benefit from this performance gains. Also I know its pushed to post 1.0.0 but a disconnect callback for parts would be amazing so i can clear things.

Sorry for long entry, I just wanted to justify my reason so you can help me about this situation.
