### ISSUE TITLE
Exception when using an empty style tag

### ISSUE THREAD

**Issue by Artur-** [Polymer/lit-html#760]
# Description
If you add an empty style tag to your template, rendering fails

# Steps to Reproduce

```
class MyElement extends LitElement {
  render() {
    return html`
    <style></style>
     Hello
    `;
  }
}
```
## Expected Results
"Hello" is rendered

## Actual Results
```
Uncaught (in promise) TypeError: Cannot read property 'cloneNode' of null
    at prepareTemplateStyles (shady-render.ts:169)
    at Function.exports.render (shady-render.ts:281)
    at HTMLElement.LitElement.update (lit-element.ts:53)
    at HTMLElement.UpdatingElement.performUpdate (updating-element.ts:216)
    at HTMLElement.eval (updating-element.ts:687)
```

https://3xvfkz.stackblitz.io
## Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari 11
- [X] Safari 10
- [X] IE 11

**Comment by leofavre** [comment]
The same happened to me with an `@import` statement followed by a semicolon.

```
<style>
  @import url("/some-css.css");
</style>
```

But removing the semicolon solved the issue.

```
<style>
  @import url("/some-css.css")
</style>
```
