### ISSUE TITLE
Feature request: Ability to pass information to directive functions from the render call

### ISSUE THREAD

**Issue by tec27** [Polymer/lit-html#762]
I'm using `lit-html` as part of a JS-only component structure in which only one render call is used to render the complete application (this differs from e.g. `lit-element`'s setup where components have individual render calls for their sub-tree). Component instances are written to return `TemplateResult`s. 

I've encountered a number of cases where it would be useful to have access to some piece of state from a higher part of the component tree in components at the leaves, but not have to pass that state through all the intermediate components.

For example:
```
Root -> Content -> ... -> TodoList -> [Todo, Todo, Todo, ...]
```

If `Todo` needs access to some state from `Root` (say, visual theming), it would often be nice to not have to pass this through many intermediate components which don't have a particular need for it. The use case here is very similar to [`Context` in React](https://reactjs.org/docs/context.html), although in my particular cases I only really care about having one context key per render tree; I don't need to set additional contexts in sub-trees of the application.

I have a sort-of-hacky way of accomplishing this now, which is to set an additional key on the `RenderOptions` passed to render(). Since this object is [destructured and passed through](https://github.com/Polymer/lit-html/blob/master/src/lib/render.ts#L51), I can then access that key in any `NodePart` directives I write. I create a new object for each Root, register that in a WeakMap specific to the data I want to store, and then look it up in the relevant directive.

For example, if I wanted to implement this for theming I could do:
```typescript
interface ThemeContext {
  readonly theme: Theme;
}

const themeContexts = new WeakMap<{}, ThemeContext>();
function registerThemeContext(contextKey: {}, themeContext: ThemeContext>) {
  themeContexts.set(contextKey, themeContext);
}

function themeAwareDirective(directiveFn: (part: NodePart, theme: Theme) => void) {
  return (part: NodePart) => {
    const theme = themeContexts.get(part.options.contextKey)!.theme;
    directiveFn(part, theme);
  };
}

const renderWithTheme = directive((render: (theme: Theme) => TemplateResult) => {
  return themeAwareDirective((part, theme) => {
    part.setValue(render(theme));
  });
});
```

```typescript
function myThemedComponent() {
  const renderFn = (theme: Theme) => {
    const style = `color: "${theme.textColor}";`
    return html`<p style=${style}>content!</p>`;
  };

  return renderWithTheme(renderFn);
}
```

```typescript
class Root implements ThemeContext {
  private contextKey = Object.create(null);
  constructor(readonly container: HTMLElement, readonly theme: Theme) {
    registerThemeContext(this.contextKey, this);
  }

  renderApplication() {
    render(html`<div>${myThemedComponent()}</div>`, 
        this.container, { contextKey: this.contextKey });
  }
}
```

That setup works for me currently, but it'd be nice to have some guarantee that it will continue working across code changes (namely, that all `RenderOptions` including ones unknown to `lit` will continue to be passed through to created `Part`s). There's also almost certainly a cleaner API that could be designed around that if desired, but I'm not sure how common this problem actually is :)

**Comment by justinfagnani** [comment]
In 2.0, RenderOptions are available to directives via Parts. While we still don't intend directives to be a component system, this does seem to close out this issue.
