### ISSUE TITLE
Open editors in new tab 

### ISSUE THREAD

**Issue by arthurevans** [Polymer/lit-html#774]
On GS page: https://lit-html.polymer-project.org/guide/getting-started

**Comment by fernandopasik** [comment]
does this one qualify as "good first issue"? :)

**Comment by justinfagnani** [comment]
@fernandopasik sure!

**Comment by arthurevans** [comment]
Also: 
  -- mention npm init if you're not doing this in an existing project.
  -- mention "in your project folder" before npm init/npm i

**Comment by fernandopasik** [comment]
@arthurevans would that be mentioned in the **npm** section before or after `npm install` ?
