### ISSUE TITLE
Directives aren't fully described, just built-in directives

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#775]
We don't describe how to write a directive, or any of the best-practices with using directives.

We used to have a section that showed a simple directive implementation, and then listed the built-ins.

**Comment by e111077** [comment]
Also would like to recommend a simple live environment that exemplifies their uses

**Comment by e111077** [comment]
maybe include stackblitz examples.

Also a bit unrelated, argument types would be very helpful and argument documentation.

e.g. `repeat(items, keyfn, template)` is really confusing when it comes to `keyfn` as I knew it was a function but I didn't really know the types or what `items` was in the example
