### ISSUE TITLE
Links in code font should show in link color

### ISSUE THREAD

**Issue by arthurevans** [Polymer/lit-html#778]
For example, `classMap` and `styleMap` in the bullet list on the first page of content here: https://styling-updates-dot-polymer-lit-html.appspot.com/guide/styling-templates

Also, seems like we don't need the background color on inline code—I think that should only be on code blocks. WDYT @yuinchien @keanulee ?

**Comment by arthurevans** [comment]
Related style q: seems like code blocks have extra padding above and below, so the background is extra tall, which looks like we have extra blank lines at the start and end of the sample code. Wonder if this should just be margin, instead?

**Comment by keanulee** [comment]
Fixed by #779
