### ISSUE TITLE
lit-html not thread safe

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/lit-html#783]
Going to cut allot of corners here sorry, still assuming you are able to understand what is going on :p 

basically when you render a light dom inside a root dom who is rendering at the same time you get `Uncaught TypeError: Cannot read property 'nextSibling' of null`

```js
        const startLocation = (response) => {
            class StartLocation extends HTMLElement {
              constructor() {
                super()
                let l = 0
                // sleep(2000).then(()=> {
                //   console.log("wtf")
                  render(html`${response.map((i) => html`<input type="radio" id="sl${l}" name="start-location" value="${i}" @click=${(e) => this.value=e.target.value}/><label for="sl${l++}">${i}</label><br>`)}`, this)
                // })
              }
            }
            customElements.define('start-location', StartLocation)
          }
```

```
         const myapp = (response) => {
            class MyApp extends HTMLElement {
              constructor() {
                super()
                const root = this.attachShadow({mode: 'open'});
                render(html`...<start-location><start-location>...`, root)
            }
            customElements.define('my-app', MyApp)
          }
```

Uncaught TypeError: Cannot read property 'nextSibling' of null

![image](https://user-images.githubusercontent.com/863731/52173917-105e5380-278d-11e9-9a96-4bc5cc654739.png)

uncommenting sleep prevent this from crashing.

PS feel free to edit the title :P

**Comment by web-padawan** [comment]
I think you generally should defer rendering until `connectedCallback`.

**Comment by gertcuykens** [comment]
Yep that seem to fix it, can this be documented somewhere maybe?
