### ISSUE TITLE
lit-html-server (part 2)

### ISSUE THREAD

**Issue by popeindustries** [Polymer/lit-html#786]
Since it looks like server-side rendering may soon become an area of focus, I thought I should post an update on the current status of [@popeindustries/lit-html-server](https://github.com/popeindustries/lit-html-server), which has recently undergone a major refactor/redesign since #461.

Inspired by one of @justinfagnani's [comments](https://github.com/Polymer/lit-html/issues/733#issuecomment-450918697), the design now more closely resembles that of lit-html proper:

- calls to `html` return instances of a `TemplateResult`
- `TemplateResult`s store references to cached `Template` instances and an array of unresolved `values`
- `Template` instances store the parsed static template strings and dynamic `Part` instances (generated by a `DefaultTemplateProcessor` factory)
- `Template` instances (and `Parts`) are created only once, and are cached with the `strings` array passed to `html` as key (tagged template literals always reference a single, frozen array storing the static strings)
- `TemplateResult`s are resolved and rendered lazily when passed to one of the template renderer functions (`renderToStream`, `renderToString`, or `renderToBuffer`)

Although I don't (yet?) see the benefit of sharing the same `html` function across client/server environments, this new design benefits greatly from the pre-processing and caching of `Template` instances. There are, however, several (potentially irreconcilable) differences:

- in order to be able to conditionally render attribute names based on their dynamic values, the static `strings` passed to `html` are parsed and modified when stored in `Template` (`AttributePart`s "own" the attribute name and surrounding quotes, as well as any static strings when there are multiple values)
- all strings are stored as Node.js `Buffer` instances to improve performance when concatenating strings and rendering to stream
- `Part` instances exist as properties of `Template`, and are therefore cached instead of generated for each `TemplateResult` to limit the total number of temporary objects created
- `TemplateResult` instances are single use and destroyed once rendered before being returned to an object pool, again to limit the total number of temporary objects created
- directives must set a `part` value synchronously, and `part.commit()` is a no-op
- Promises/AsyncIterators are valid types and may be used without directives

In general, these differences boil down to performance: pre-process and cache as much as possible, handle strings in the same format they are output as, and limit the total number of intermediate (temporary) objects created.

## Performance

Performance testing has been done against a production appplication, currently written in React, that renders a single page comprising ~2000 DOM elements. The lit-html-ified version generates ~1000 calls to `html` per request without fragment caching (using a fragment cache directive that caches rendered fragments as Buffers reduces the total to ~200). All tests were run with [autocannon](https://github.com/mcollina/autocannon) with the following command:

```text
autocannon --connections 200 --duration 10
```

| version                          | info                                                                   | avg. req/sec      |
| -------------------------------- | ---------------------------------------------------------------------- | ----------------- |
| baseline React app               | 2 instance `cluster`                                                   | ~53 (per instance) |
| baseline lit-html app            | no fragment cache                                                      | 110               |
| optimized lit-html app           | with fragment cache                                                    | 442               |
| baseline lit-html renderer       | no fragment cache, template render only                                | 152               |
| optimized lit-html renderer      | with fragment cache, template render only                              | 728               |
| semi-optimized lit-html renderer | no `TemplateResult` pooling, with fragment cache, template render only | 667               |

I'm happy with the results so far, but there is still work to be done to profile memory useage. I aslo hope to port our production application in a more generalized form in order to track performance improvements/regressions more accurately. This would likely aslo serve as a good "advanced" example on how to use lit-html on the server.

## Next Step

Rehydration (where the server-rendered HTML is used to initialise lit-html instances on the client) is obviously the next step. From `lit-html-server`'s point of view, there probably aren't that many opportunities to encode metadata to make this step easier/more efficient on the client. Two exceptions are of course the handling of event and property attributes, which are currently ignored by `lit-html-server` when rendering:

- property attributes (`<div .stuff=${data}>`): `JSON.stringify(data)` and inline to be parsed and set when the element is created (rendered as `<div data-lit-prop-stuff="{\"some\": \"json\"}">`)
- event attributes (`<div @click=${this.onClick}>`): bind `onClick` to element when created (rendered as `<div data-lit-event-click="this.onClick">`)

Both of these probably make more sense when used with Custom Elements (`<my-element>`), and in theory could be configured with `options` passed to `renderTo*(templateResult, options)`.

Unfortunately, I don't know the `lit-html` internals well enough to be able to judge how big a challenge rehydration will be, but I do look forward to avoiding the flash of re-rendered markup (FORRM) that occurs currently 😜

**Comment by justinfagnani** [comment]
Thanks for your work in this area @popeindustries! We now have the `@lit-labs/ssr` package that we are developing for full lit-html SSR and hydration.
