### ISSUE TITLE
Mention file size on lit-html home page

### ISSUE THREAD

**Issue by dorivaught** [Polymer/lit-html#795]
Just over 3kB bundled, minified and gzipped (3.14kB currently)

**Comment by motss** [comment]
Single `bundlephobia` badge seems to do the trick: https://flat.badgen.net/bundlephobia/minzip/lit-html

**Comment by justinfagnani** [comment]
We haven't mentioned specific file size because it can change over time. The 2.0 site does mention a rough number for now.
