### ISSUE TITLE
Slot not working when lit-html used as webcomponent template

### ISSUE THREAD

**Issue by BrianDGLS** [Polymer/lit-html#798]
I am using lit-html to generate the templates and render web components.
A webcomponent in my set up look like the following.

```javascript
class MyList extends CustomElement(HTMLElement) {
  static selector = 'my-list';
  get template() {
    return html`<ul><slot></slot></ul>`
  }
}
```

This is working fine, untill it comes to using `slot`s. So for example the above component could be used as follows.

```html
<my-list>
      <li>test</li>
      <li>test</li>
      <li>test</li>
</my-list>
```

However there is nothing being output in the slot, as I would expect. Let me know if I am making and error or if this can be resolved.

For more context I have added the repo below. The `examples/main.ts` holds the web component definition.
https://github.com/BrianDGLS/web-component-playground

**Comment by jsilvermist** [comment]
Correct me if I'm wrong but it seems like you're not using shadow dom which is a requirement for being able to use `slot` with custom elements.

**Comment by BrianDGLS** [comment]
Thanks @jsilvermist , i'll enable it and check.

**Comment by BrianDGLS** [comment]
Thanks @jsilvermist , that was the issue.
