### ISSUE TITLE
nodeMarker comments make CSS selector :empty impossible

### ISSUE THREAD

**Issue by klebba** [Polymer/lit-html#799]
Example:

```
const root = document.createElement('div');
const foo = '';
const tmpl = html`<div>${foo}</div>`;
render(tmpl, root);
console.log(root.innerHTML);
// <!----><div><!----><!----></div><!---->
```

As a result CSS selectors like this will not work:
```
div:empty {
  display: none;
}
```

The markup would need to be `<div></div>`. Early versions of `lit-html` did not fill bindings with this comment `nodeMarker` content. Is there a way to disable the comment bindings?

Thanks in advance!

**Comment by ruphin** [comment]
I cannot reproduce the issue: https://codepen.io/ruphin/pen/exVydQ?editors=0110
Can you create a reproduction that shows the behaviour as you mentioned?

The comment markers are currently necessary for the internal implementation of lit-html, and cannot be disabled.

**Comment by justinfagnani** [comment]
Comment nodes should not affect `:empty`: https://developer.mozilla.org/en-US/docs/Web/CSS/:empty

**Comment by justinfagnani** [comment]
Since we don't have a reproduction and we should be ok according to the spec, I'm going to close. If you can make a reproduction, ping us. Thanks!

**Comment by klebba** [comment]
@ruphin thanks for putting together a test; I will need to take another look at my code. Perhaps it's a newline causing the problem, but clearly it's not the comments.

**Comment by klebba** [comment]
Just closing the loop here, my issue was unrelated to the nodeMarkers. Thanks for the prompt reply!

**Comment by gormonn** [comment]
I faced the same problem, due to the spaces the prettier leaves when formatting.
<! - prettier-ignore -> saved the day
