### ISSUE TITLE
docs: classMap section wrongly states that must be the entire value of class attribute

### ISSUE THREAD

**Issue by blikblum** [Polymer/lit-html#804]
# Description
The [classMap documentation](https://lit-html.polymer-project.org/guide/template-reference#classmap) states that "you can only use classMap in an attribute binding for the class attribute, and it must be the entire value of the attribute." And gives an example that supposedly should not work  

The implementation and the tests supports static parts in class attribute just like the "forbidden" example

# Steps to Reproduce

Not applicable

## Expected Results
The classMap docs should cite support for static parts

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by ernsheong** [comment]
So it works, and the documentation just needs an update?

**Comment by blikblum** [comment]
> So it works, and the documentation just needs an update?

Yes, it works and its [tested](https://github.com/Polymer/lit-html/blob/master/src/test/directives/class-map_test.ts#L72). Seems like a unofficial / unsupported feature.
