### ISSUE TITLE
Trouble setting a numeric attribute - weird case

### ISSUE THREAD

**Issue by pshihn** [Polymer/lit-html#807]
# Description

I'm having trouble setting a numeric attribute using lit-html

The trouble is that on the page there's some 3rd party code that adds an iterator to numbers which returns values from 0 to x, where x is the number.

`AttributeCommitter` does not have a special case for dealing with numbers. It does for strings, arrays. Rest gets translated to string using iterator using https://github.com/Polymer/lit-html/blob/79f4e5764355a87b7faf2992748f34af3523ac80/src/lib/parts.ts#L78

So if I set the attribute to `5`, the attribute gets set to `01234` because of this third party iterator logic. 

I was wondering if lit-html should be able to deal with number and booleans directly rather than falling back to iterators

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
😱

**Comment by justinfagnani** [comment]
This is crazy, and no one should be monkey-patching Number, but I think it'll be a simple workaround.

**Comment by pshihn** [comment]
Yes it's quite crazy. Unfortunately I'm in the business of writing widgets for other sites so very little control :/
Out of curiosity what's an example of the use case where iterator -> string is the way to set an attribute?
