### ISSUE TITLE
WebComponent polyfills can't be loaded lazily

### ISSUE THREAD

**Issue by csvn** [Polymer/lit-html#810]
# Description
Major browsers support Web Components natively (Edge is the current holdout). In an effort to save size, it would be great to load polyfills for web components dynamically when they are needed. lit-html checks for `ShadyCSS` eagerly instead of when required, which means the polyfills for ShadyCSS will not have an effect in browsers that require it.

Both using `@webcomponents/webcomponentsjs/webcomponents-loader.js` with `defer`, or loading polyfills manually will have the same problem. The check for compatible `ShadyCSS` version [is done here](https://github.com/Polymer/lit-html/blob/master/src/lib/shady-render.ts#L42-L52), and it is done as soon as lit-html is loaded.

# Steps to Reproduce

1. A manual approach to loading polyfills can be done like the below code. Note: Will require a build step to actually test the browsers that this will fail in.

```javascript
// webcomponents-polyfills.js
import '@webcomponents/shadydom/shadydom.min.js';
import '@webcomponents/shadycss/scoping-shim.min.js';
// ....

// index.js
import { html } from 'lit-html';
import { render } from 'lit-html/lib/shady-render';

(async() => {
  if (!('attachShadow' in document.body)) {
    await import('./webcomponents-polyfills');
  }
  const container = document.querySelector('#app').attachShadow({ mode: 'open' });
  render(html`<style>:host { display: block; height: 300px; background: red; }`, container, { scopeName: 'my-app' });
})();
```
<small>A similar approach can be used with `webcomponents-loader` and `defer`.</small>

2. When checking the result, no style scoping will be done

## Live Reproduction Link
Sorry, I could not get `import()` to work for a live reproduction. I made a small repo that shows the issue.

- https://github.com/csvn/dynamic-polyfills-lit-html-reproduction (`master`), shows custom loading of polyfills
- https://github.com/csvn/dynamic-polyfills-lit-html-reproduction/tree/%40webcomponents-loader (`@webcomponents-loader`) shows the issue by using the webcomponents loader and `defer`

## Expected Results
Loading but not executing `render()` from shady render before loading ShadyCSS polyfill will correctly scope styling when executing `render()` after ShadyCSS polyfill has loaded.

## Actual Results
Loading but not executing `render()` from shady render before loading ShadyCSS polyfill will disable style scoping.

## Browsers Affected

Browsers without native Web Component support, e.g.:

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari 11
- [ ] Safari 10
- [X] IE 11

**Comment by justinfagnani** [comment]
You can't import the polyfills, they're not modules.

**Comment by csvn** [comment]
Just thought I'd mention the reason we don't/can't use `https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs´. We are building a set of components that should be easy to integrate, which is why we handle loading of the polyfills if they are required. Our customers only add a single `script` tag. We don't want them to have to do a lot of extra steps to ensure all required polyfills exist, so our script loads them if needed.

The issue mentioned above was solved by lazy loading the main part of the library (e.g. components). Providing `eager` to Webpack let's the code remain in the same bundle, but still executes lazily.

```
// index.js
async function main() {
  await import('./polyfills'); // required @webcomponents polyfills
  await import(/* webpackMode: "eager" */ './components/index');
}
main();
```

> You can't import the polyfills, they're not modules.

As far as I know, any JS file can be a module, as long as window is not referred to as `this`, and strict-mode does not result in errors. 🤔  
Webpack seems to handle inlining them just fine if they're imported in the correct order (`webcomponents-platform`, `template`, `shadydom`, `custom-elements`, `scoping-shim`).

Anyway, just thought I'd mention this in case someone runs into a similar issue and finds their way here.
