### ISSUE TITLE
lit import must be identical everywhere

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/lit-html#817]
Only `done2` works but when printing for chrome they are identical
```js
import {svg} from 'https://unpkg.com/lit-html@latest'

export const done = svg`<g><path fill="none" d="M0 0h24v24H0z"/><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></g>`
```

```js
      import {svg, html, render} from 'https://unpkg.com/lit-html'

      import {done} from './svg-icon.js'
      console.log(done)

      const done2 = svg`<g><path fill="none" d="M0 0h24v24H0z"/><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></g>`
      console.log(done2)

      class HelloWorld extends HTMLElement {
        constructor() {
          super()
        }
        connectedCallback() {
          const root = this.attachShadow({mode: 'open'});
          render(html`
            WTF
            <svg id="save" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24">${done}</svg>
          `, root)

        }
      }
      customElements.define('hello-world', HelloWorld)
```
![image](https://user-images.githubusercontent.com/863731/52916854-c5902000-32e4-11e9-8f96-bdea4c62991d.png)

I get this when using the import one

![image](https://user-images.githubusercontent.com/863731/52916955-e442e680-32e5-11e9-92f4-4fb5401a7627.png)

**Comment by Westbrook** [comment]
My first read of this point to `'https://unpkg.com/lit-html@latest'` and `'https://unpkg.com/lit-html'` not technically resolving to the _same_ `lit-html` as your issue. Even though these will likely import the same `lit-html` version, being the URLs are not exactly the same the ES Module resolution will cause two copies of that same version to be downloaded. Can you check to see if this works with those two URLs matched? Either/or should be fine, but with them even a character off you'll trigger multiple copies.

**Comment by gertcuykens** [comment]
thx for response, tried removing @latest to make them identical but get same result.

**Comment by gertcuykens** [comment]
Also when trying this I get to see the correct escape quoted string so don't think it has to do with my module itself
```
export const done = `<g><path fill="none" d="M0 0h24v24H0z"/><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></g>`
```

![image](https://user-images.githubusercontent.com/863731/52917356-b90ec600-32ea-11e9-9f5b-0e4c41976380.png)

**Comment by justinfagnani** [comment]
Strings are always escaped. You need to tag the fragment with the `svg` template tag.

For external HTML/SVG you'll need to use `innerHTML` yourself on a DOM node that lit-html isn't controlling the contents of, or use the `unsafeHTML` directive.

**Comment by gertcuykens** [comment]
Wait, your right! forgot to at `?module` had to make sure I used `from 'https://unpkg.com/lit-html?module'` everywhere or I get does shenanigans. Hmm this wil bite somebody else sooner or later i guess also

**Comment by justinfagnani** [comment]
I think we can close this...
