### ISSUE TITLE
Exec lastAttributeNameRegex only once per template string

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#833]
Right now we have two places that we exec `lastAttributeNameRegex`:
- https://github.com/Polymer/lit-html/blob/6db24ced84fe33bd83a8716507a27c5d15a1ae97/src/lib/template-result.ts#L59
- https://github.com/Polymer/lit-html/blob/6db24ced84fe33bd83a8716507a27c5d15a1ae97/src/lib/template.ts#L87

We should try to store the result from the first call in `TemplateResult#getHTML` to reuse in the `Template` constructor. This will obviously eliminate the cost of the second regex exec, but also, the template strings array, because it's frozen, is much slower to access than a normal array of strings. We don't yet know the full additional cost of re-accessing the strings, but this would eliminate the second access.

**Comment by jridgewell** [comment]
> the template strings array, because it's frozen, is much slower to access than a normal array of strings. We don't yet know the full additional cost of re-accessing the strings, but this would eliminate the second access.

2-3x slower to access: https://jsbench.github.io/#a9465213400973207316d7af71fa0110

**Comment by justinfagnani** [comment]
It could be much worse for optimised code, at least until v8 handled this better: https://docs.google.com/document/d/1X6zO5F_Zojizn2dmo_ftaOWsY8NltPHUhudBbUzMxnc/edit?usp=drivesdk

What we don't have great insight into is how much this effects overall perf for us, especially at what point typical application code will cause these paths in lit-html to be optimised.

**Comment by ruphin** [comment]
The parser/template instantiation system I'm working on fixes this issue. It annotates the bound attributes during initial template creation, as suggested here.

**Comment by lazystring** [comment]
A simple solution would be to store a lookup array as part of the TemplateResult. That way, we could re-use the parsed attributes later on:

```
// Look up attribute corresponding to a template string, possibly returning undefined.
const name = result.getAttribute(partIndex);
```

How does that sound? I can send out a PR if nobody is working on this already.

**Comment by justinfagnani** [comment]
2.0 doesn't use the same regex and the regexes it has are executed only once during string scanning. Also V8 has improved access to frozen objects: https://bugs.chromium.org/p/v8/issues/detail?id=6831
