### ISSUE TITLE
Memory leak: Async directives hold onto full DOM trees

### ISSUE THREAD

**Issue by jridgewell** [Polymer/lit-html#841]
# Description

A few of the first-class Promise directives hold onto their parts (and the part's nodes). I didn't think this was too serious at first, until I thought about the DOM trees they're holding onto.

Eg:
```js
// Let's call this the Page 1 UI.
render(html`<div>
  ${until(promise1, 'foo')}
</div>`, container);
```

Here, we know there'll be a `<div><!--lit-->foo<!--lit--></div>` rendered inside the container. But we've chained off of `promise1`, and that chain holds the part's `startNode` and `endNode`. Those nodes hold _every other_ node in the tree, either directly or indirectly. Imagine this `until` directive was somewhere **deeply** nested under `container`.

Now image we change to a different template on the same container:

```js
render(page2Ui, container);
```

Here we've completely wiped away that other templates DOM tree. But actually, no, we haven't. `until` is still holding on to _everything_ rendered under that container until `promise1` resolves.

Ideally, we'd use the [disconnect](https://github.com/Polymer/lit-html/issues/283) API clean up. We could have these Promise awaiting directives use a `Promise.race`:

```js
Promise.race([disconnect, userValue]).then((resolvedValue) => {
  part.setValue(resolvedValue);
  part.commit();
}, () => {
  // disconnected
});
```

Now, when the part is disconnected (either because a parent node disconnected, or because the part updated do a different value), we can reject the `disconnect` promises. When the chain settles, the reference to the part will be cleaned up.

# Test Case

```ts
test('holds DOM tree after disconnect', async () => {
  let resolve1: (v: any) => void;
  const promise1 = new Promise((res, _) => {
    resolve1 = res;
  });
  render(html`<div>${until(promise1, 'foo')}</div>`, container);
  assert.equal(stripExpressionMarkers(container.innerHTML), '<div>foo</div>');
  const text = container.firstElementChild!.firstChild!.nextSibling as Text;
  assert.equal(text.data, 'foo');

  // Render a different template over container, so everything is "freed".
  render(html``, container);
  assert.equal(stripExpressionMarkers(container.innerHTML), '');

  resolve1!('bar');
  await promise1;

  // Do not allow commits after a disconnect
  assert.equal(text.data, 'foo');
});
```

## Expected Results

First class directives should make it easy to avoid memory leaks.

## Actual Results

Memory leaks are easy.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
We have a directive disconnect API in lit-html 2.0
