### ISSUE TITLE
Allow conditional creation of attributes

### ISSUE THREAD

**Issue by zhaoz** [Polymer/lit-html#86]
lit currently doesn't allow you to conditionally create an attribute.

For example, if you would like to toggle 'checked' state on an input.

<input type="checkbox" checked>

There is no way to conditionally toggle the 'checked' attribute.

This may be related to https://github.com/PolymerLabs/lit-html/issues/56 but that seems to expect undefined to not serialize, but does not mention removing attributes.

**Comment by LarsDenBakker** [comment]
Running into the sane issue.

**Comment by kyuwoo-choi** [comment]
same here. so what's the best for now?
I just recreate the element on a condition.

```js
checkbox = checkToggleAll
    ? html`<input class="toggle-all" type="checkbox" checked>`
    : html`<input class="toggle-all" type="checkbox">`
```

**Comment by shutdown256** [comment]
PRs #197 and #204 both solve this

**Comment by justinfagnani** [comment]
Deduping all boolean/conditional attribute issues to #56
