### ISSUE TITLE
Can't bind div property scrollTop

### ISSUE THREAD

**Issue by nikolafon** [Polymer/lit-html#862]
# Description
I'm trying to keep the scroll position when I navigate away from the articles page to the article page.

Property scrollTop binding of div element when rendering template is not reflected.
# Steps to Reproduce

Consider this template:

```
<div id="articlesContainer" .scrollTop=${state.scrollTop} class="articles-container animated fadeIn">
          ${state.articles.map(
            article =>
              html`
                <div class="article-item-container">
                  <span class="article-category">${article.category}</span>
                  <div class="article-item" @click=${() => this.gotToArticle(article, this.shadowRoot.getElementById("articlesContainer").scrollTop)}>
                    <h2 class="article-title">${article.title}</h2>
                    <img class="article-image" src="${article.smallImageUrl}" />
                  </div>
                </div>
              `
          )}
        </div>
```
When I go to an article page I set the current scrollTop of the scrollable div element.
The state is updated properly when I navigate to an article page and when I navigate back and this peace of template is rendered
the property binding .scrollTop=${state.scrollTop}  doesn't work, meaning the scroll position of div element is 0.

## Browsers Affected

- [x ] Chrome

**Comment by justinfagnani** [comment]
The problem here is that the last value set by lit-html hasn't changed, and so it doesn't know it needs to set the value.

I opened up a more generic issue to track this: #877
