### ISSUE TITLE
how render <input pattern="${pattern}">

### ISSUE THREAD

**Issue by mantou132** [Polymer/lit-html#866]
# Description
When the attribute value is falsy, I want to delete the attribute. When the attribute value is truthy, I want to render the attribute.
 
# Steps to Reproduce

1. Write this code

```ts
import {html, render} from 'lit-html';

render(html`<input pattern="${''}">`, document.body);
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-sduo8q

## Expected Results

&lt;input&gt;

## Actual Results

&lt;input pattern&gt;

**Comment by T-Knott-Mesh** [comment]
https://lit-element.polymer-project.org/guide/properties

<input ?pattern=${pattern}>

**Comment by ruphin** [comment]
You may want to look at the `ifDefined` directive: https://lit-html.polymer-project.org/guide/template-reference#ifdefined

The `ifDefined` directive will render the attribute if the value passed in is not `undefined`. However, it will not work for falsy values. 

If you want conditional rendering based on truthyness, you can make your own directive that does this:

```js
import {AttributePart, directive, Part} from '../lit-html.js';

const ifTruthy = directive(value => part => {
  if (value && part instanceof AttributePart) {
    if (value !== part.value) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else {
    part.setValue(value);
  }
});

render(html`<input pattern="${ ifTruthy('') }">`, document.body);
// renders: <input>

render(html`<input pattern="${ ifTruthy('something') }">`, document.body);
// renders: <input pattern="something">
```

**Comment by justinfagnani** [comment]
You can also leverage `ifDefined` directly:

```js
const ifTruthy = (value) => ifDefined(!value ? undefined : value);
```
