### ISSUE TITLE
Make `shady-render` smaller by by moving functionality into ShadyCSS

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#871]
We could move some of the code that fixes up styling and templates directly into ShadyCSS.

**Comment by ruphin** [comment]
What is the benefit of moving the complexity elsewhere? Won't that just bloat ShadyCSS for all non-lit-html users? Or is there a significant amount of duplicate code that can be eliminated by merging the codebases?

**Comment by justinfagnani** [comment]
This is just an idea for exploration, to see how much weight we could save.

The benefit of moving the code around would be that on modern browsers app would not have to pay as much for Shady CSS integration. Right now LitElement, to support Shady CSS, imports shady-render.js and pays the cost on all browsers.

**Comment by justinfagnani** [comment]
This is probably obsoleted by the new platform-support.js approach in 2.0.
