### ISSUE TITLE
Script tag in lit html not working

### ISSUE THREAD

**Issue by msteller-connyun** [Polymer/lit-html#883]
# Description
The script tag in lit html is not executed

# Steps to Reproduce

1. Write this code

```
html`<script type="text/javascript">alert('Foo')</script>`;
html`${unsafeHTML`<script type="text/javascript">alert('Foo')</script>`}`;
```

2. See this output...

## Expected Results
An an alert box with „Foo“ should be pop up.

## Actual Results
Nothing happens

It looks like that script tags are not executed when they are added via innerHTML (I saw the usage of innerHTML serveral times in the lit source).
https://stackoverflow.com/questions/51101473/script-inside-shadow-dom-not-working
Maybe that’s the reason?

**Comment by motss** [comment]
But why would you want to do this instead of dynamically loading scripts for execution?

**Comment by justinfagnani** [comment]
This is working as intended. Cloned scripts are not evaluated by the browser, and this is critical to our security story.

**Comment by msteller-connyun** [comment]
I want to do a webcomponent for Google Analytics.
The idea was to create with LIT the script tag to load the GA JS file.

**Comment by Westbrook** [comment]
Not sure how this rates against the security story, but you can use `script` nodes directly in `lit-html`, a la: https://stackblitz.com/edit/mytohf-frfwbd?file=my-element.js

**Comment by msteller-connyun** [comment]
Well, creating the script-tag in lit would be nice... but I’m using plan b, now

```
  updated(changedProperties) {
    if (['_id', '_accepted'].some(key => changedProperties.has(key)) && this._id && this._accepted === true) {
      this._initTrackingScript();
    }
  }
  _initTrackingScript() {
    if (!document.querySelector('#cy-ga-script')) {
      const scriptFileEl = document.createElement('script');
      scriptFileEl.setAttribute('async', '');
      scriptFileEl.setAttribute('id', 'cy-ga-script');
      scriptFileEl.setAttribute('src', `https://www.googletagmanager.com/gtag/js?id=${this._id}`);
      document.head.appendChild(scriptFileEl);
      _gtag('js', new Date());
      _gtag('config', this._id);
    }
  }
```

Would be nice if I could add the script tag with lit, after I want do the banner which asks for the tracking permission also with lit. But the way I do it now works great. It’s just a little bit inelegantly ;)
