### ISSUE TITLE
directive not getting object identical part

### ISSUE THREAD

**Issue by yorrd** [Polymer/lit-html#886]
I was under the impression that directives should be passed the same part upon each rerender. Now I've got this code:

```
    <div style="margin-top: -50vh; height: 50vh; pointer-events: none;">
      ${whenSeen(() => {
        // increase limit of the pagination
      })}
    </div>
```

in which I want to use the `whenSeen` directive to do pagination. So far so good.

Now, I want to throttle the pagination calls and therefore, in `whenSeen` recognize if it is called from the same place twice. I tried implementing it using a `WeakMap` with the `NodePart` I get as the key, but that `Part` is different every time. 

```
export const whenSeen = directive((cb: () => void, throttle: number = 300) => (part: NodePart) => {
  if (!subjectCache.get(part)) {
    subjectCache.set(part, new Subject<Function>());
...
```

Am I going at this the wrong way?

**Comment by blikblum** [comment]
> Am I going at this the wrong way?

Most times the part instance does not change with rerender with a [few catches](https://github.com/Polymer/lit-html/pull/874#discussion_r269361175)

A working example would help to evaluate the behavior

**Comment by yorrd** [comment]
@blikblum so youre saying this happens because Im removing and re-attaching the part? Did I understand that correctly? If so, I need to have a look at the outer scope of my code.

**Comment by blikblum** [comment]
> @blikblum so youre saying this happens because Im removing and re-attaching the part?

It's a possibility. Needs a working example to evaluate. 

In lit-html, nested templates is a first class feature so is natural to think that a nested template will behave the same as other portions of the main template.  But, at least regarding the directive `part` instance is not true.

Example:

```javascript
html`
  <div>Directive in main template ${myDirective()}</div>
  ${html`<div>Directive in nested template ${myDirective()}</div>`}
`
```

The `part` instance passed to myDirective will be the same in the main template at each re-render but inside the nested template will be different at each re-render

**Comment by yorrd** [comment]
Okay got it. Thank you for your example, very helpful! Now it'd be helpful to know if this is going to be fixed at some point or if this is "by design". Because if it is, I can't do a whole lot of stuff that I thought I could :smile:

**Comment by jridgewell** [comment]
>  Now it'd be helpful to know if this is going to be fixed at some point or if this is "by design".

This is by design. We throw away old inner-template's parts when rendering a new inner-template.

However, you can use the [`cache` directive](https://github.com/Polymer/lit-html/blob/master/src/directives/cache.ts) to reuse the same parts for each inner-template swap. See https://codepen.io/anon/pen/xePagN?editors=1000
