### ISSUE TITLE
Template with = in text causes malformed TemplateResult

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#893]
# Description
When a template contains a text node with a `=` symbol and an expression on the same line the template gets malformed. I think it is evaluated as an attribute binding.

# Steps to Reproduce

1. Write this code

```ts
import { html, render } from 'lit-html';

render( html`
  foo=${'bar'}
`, document.body);
```
2. See this output...

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-gvfbz7?file=src%2Findex.js

## Expected Results
`foo=bar`

## Actual Results
`foo$lit$=bar`

## Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by ruphin** [comment]
There are currently several proposals to parser changes that solve this problem, but we are waiting with changes to the parser system until the benchmarking solution is in place so we can account for performance impact.

**Comment by justinfagnani** [comment]
This is fixed on master. Test here: https://github.com/Polymer/lit-html/blob/master/src/test/lib/render_test.ts#L123

**Comment by justinfagnani** [comment]
The fix will go out in the next release.
