### ISSUE TITLE
Fast way to create (non-dynamic) "render roots"

### ISSUE THREAD

**Issue by micahjon** [Polymer/lit-html#914]
First off, thanks for maintaining this excellent library. 

In our application's component model, we often generate a single "root" HTML element and render lit-html template within it, e.g.
```js
const root = document.createElement('div').addClass('navbar');

const template = () => html`
  <div class="navbar-item">Item 1</div>
  <div class="navbar-item">Item 2</div>
`;
render(template(), root);
```

It would be nice if we could generate this "root" element easily with lit-html, e.g.
```js
const root = elem`<div class="navbar"></div>`;
```

I wrote a little "elem" helper that creates a new element, renders within it, and returns the first child. The problem it it's too slow, the `render()` step taking 3-10x longer than calling `createElement()` & adding attributes. 
```js
export const elem = (...args) => {
    const container = document.createElement('div');
    render(html(...args), container);
    return container.firstElementChild;
};
```

Is there was a better way to achieve the desired effect: a quick first render?

**Comment by jridgewell** [comment]
How are you testing the perf? If there's any nested children inside of you root node, I don't think there'll be any real perf hit. But if you're using it to generate the root node _only_ (no children), then it'll be much slower.

**Comment by pranksinatra** [comment]
Yeah, in these cases I'm only generating the root node since the internals are a separate lit-html template. 

As far as testing perf, I'm just using `console.time`, e.g. 
```js
console.time('five lit');
const fiveElementsLit = [
    elem`<div class="navbar-item"></div>`,
    elem`<div class="navbar-item"></div>`,
    elem`<div class="navbar-item"></div>`,
    elem`<div class="navbar-item"></div>`,
    elem`<div class="navbar-item"></div>`,
];
console.timeEnd('five lit');

console.time('five vanilla');
const fiveElementsVanilla = [
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
];
console.timeEnd('five vanilla');
```

You're right, when adding a child element the difference is reduced (to 2-3x slower, which feels like a reasonable cost of abstraction).

**Comment by jridgewell** [comment]
In your test, you're paying the cost of internal lit-html template creation _5 times_. This isn't the way lit is supposed to be used, you want to reuse a single tagged template literal multiple times to create nodes:

```js
const navbar = () => elem`<div class="navbar-item"></div>`;
console.time('five lit');
const fiveElementsLit = [
    navbar(),
    navbar(),
    navbar(),
    navbar(),
    navbar(),
];
console.timeEnd('five lit');

console.time('five vanilla');
const fiveElementsVanilla = [
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
    document.createElement('div').addClass('navbar-item'),
];
console.timeEnd('five vanilla');
```

This should reduce it to a much more reasonable difference.

**Comment by pranksinatra** [comment]
Yep, I understand that this is a silly example. My actual use case is creating root elements for a variety of different components, each with their own template (so template re-use isn't possible), e.g.

```js
const rootA = elem`<div class="navbar"></div>`;
const rootB = elem`<div class="account-menu"></div>`;
const rootC = elem`<div class="settings-modal"></div>`;
// etc...
```

So the bottleneck of rendering a new TemplateResult in a new (or cloned) element remains.

**Comment by pranksinatra** [comment]
Also, in my tests, `TemplateResult` creation time is negligible. Rendering the `TemplateResult` in an Element for the first time actually takes time, so this is what I'm trying to optimize for.

**Comment by jridgewell** [comment]
Ok. Unfortunately, it's a extra expensive to render a template for the first time. We could try to optimize this when we know there are no interpolations necessary, in which case there'll be a `<template>` created, a `template.innerHTML = 'html'`, and a `template.content.cloneNode()`. (Right now, we also instantiate a `TreeWalker`, which is very expensive to create)

So it'll still be slower than a simple `document.createElement()`, but it'll be a bit faster than it is now.

**Comment by pranksinatra** [comment]
Hey, really appreciate the detailed explanation. 

Of course, I'd love if there was a way to force a fast one-time render, but I'm guessing this is a nonstandard use case and isn't worth making your API more complex. For now, I'll just make sure I only use this `elem` helper in contexts where performance isn't critical.

**Comment by justinfagnani** [comment]
I think this is a pretty limited audience feature, so we probably don't want to add it to core.

Regarding perf, the key to speeding this up is to cache the container so that it triggers lit-html's update code path:

```ts
const fragments = new WeakMap();
export const elem = (strings, ...values) => {
  let fragment = fragments.get(strings);
  if (fragment === undefined) {
    fragment = document.createDocumentFragment();
    fragments.set(strings, fragment);
  }
  render(html(strings, ...values), fragment);
  return fragment;
};
``` 

Note I'm returning the entire fragment so that `elem` can contain text and multiple nodes. The name might not fit anymore.
