### ISSUE TITLE
Accessing element in template when added to dom

### ISSUE THREAD

**Issue by marlun** [Polymer/lit-html#915]
I'm having a hard time explaining this but I'm using another library which you give a <video> element when initializing it. I want to render a lit-html "component' which includes a <video> element and when it's added to the DOM run the initialization and send in the video element.

I couldn't find any similar issue.

**Comment by Westbrook** [comment]
What library are you using, even a non-lit example of its usage could be helpful.

However, in the interim, you might find success via the idea that you can use created elements in a template:
```
const myEl = document.createElement('video');
const myTemplate = () => html`${myEl}`;
render(myTemplate(), document.body);
magicLibrary.init(myEl);
```
Hard to say if a version of this is helpful without more information, but happy to try and point you in a good direction when you've shared a little more of your context!

**Comment by justinfagnani** [comment]
@marlun 

In addition to providing the element to the template, like @Westbrook showed, you can also query the container to get to an element rendered by lit-html:

```js
const myTemplate = () => html`<div id="my-el"></div>`;
render(myTemplate(), document.body);
const myEl = document.body.querySelector('#my-el');
magicLibrary.init(myEl);
```

I'll close this in the hopes that one of the two answers works. Please ping me to reopen if this didn't help!

**Comment by marlun** [comment]
Thanks, I did solve it with the fact that I can create the element outside of the template, set up a listener for when it's added to the DOM and then add it to the template. Thanks both of you!

**Comment by Samantha-uk** [comment]
> Thanks, I did solve it with the fact that I can create the element outside of the template, set up a listener for when it's added to the DOM and then add it to the template. Thanks both of you!

I'm having this exact problem trying to use lit-html and vis.js ... off to see if this approach works for me too!
