### ISSUE TITLE
Comment nodes are rendered as text nodes

### ISSUE THREAD

**Issue by Zhang-Wei-666** [Polymer/lit-html#926]
# Description
Comment nodes are rendered as text nodes

# Steps to Reproduce

1. Write this code

```js
import { render, html } from 'lit-html';

render(
  html`<!--${ 123 }-->`,
  app
);
```

2. See this output...

## Live Reproduction Link

https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/Polymer/lit-html/3.html

## Expected Results
Render a comment node

## Actual Results
Render a text nodes

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
What version of lit-html are you using?

**Comment by Zhang-Wei-666** [comment]
1.1.0

**Comment by Zhang-Wei-666** [comment]
1.1.0 @justinfagnani

**Comment by jridgewell** [comment]
[Confirmed](https://jsbin.com/sonedon/edit?html,output) Putting any char around the `${}` expression will fix this. Likely a bug where we see a comment marker and think it's a text marker.

**Comment by cacophobe** [comment]
Confirmed, using version:
lit-element@2.1.0
lit-html@1.1.0
