### ISSUE TITLE
spread syntax proposals

### ISSUE THREAD

**Issue by chase-moskal** [Polymer/lit-html#934]
hello! in #923 there is an ongoing discussion about whether or not spread is a desirable feature -- this is not a continuation of that discussion

related to that discussion, i have seen three proposals about possible lit-html syntax for a spread feature

i just wanted to ask you folks: if spread was implemented, which syntax would you prefer, and why?

**spread syntax A**

```html
<my-video ...${attrs}>
<my-video *...${props}>
<my-video ?...${bools}>
<my-video @...${events}>
```

- downside: we need to choose a sigil for properties that is not ".", because it's too tricky to distinguish three dots for attributes from four dots for properties
  - i chose "*" in this example, but maybe we can think of a better candidate
- upside is that this syntax is succinct, and is similar to the lit-html symbology

**spread syntax B**

```html
<my-video ...${attrs}>
<my-video ...${spreadProperties(props)}>
<my-video ...${spreadBooleans(bools)}>
<my-video ...${spreadEvents(events)}>
```

- downside is verbosity and the hassle to import these helpers
- upside is that it's clear and easy to understand

**spread syntax C**

```html
<my-video ...${{
  coolattr: "myattr",
  ".coolprop": myprop,
  "?coolbool": true,
  "@coolevent": myhandler
}}>
```

- upside: very terse, uses familiar lit-html symbology exactly
- we should also then include the helpers of syntax B
- downside: ergonomic concern over using string literals (hurts ide refactor functionality)
- this is the current implementation by @straversi in #923, but with the equal sign either omitted or made optional

my thoughts: i'm fond of all three possibilites, while i like A the most, i wonder if the asterisk problem is unforgivable, in which case i do like C

i think syntax C implies syntax B comes along for the ride, which is kind of complex, so maybe B-only is simpler -- in which case i still prefer A because it's terse and isn't complex since it doesn't involve helper functions

can anybody think of any alternatives we could consider?

edit for credits: as far as i can tell, these possibilities were first discussed by @straversi, @westbrook, and @justinfagnani in #923

cheers folks :wave:

**Comment by chase-moskal** [comment]
sidenote

i just wanted to share my enthusiasm for a simple syntactic pleasure i've long enjoyed about spread generally

```html
<my-video title=${title} description=${description}>
```

can be shortened to simply

```html
<my-video ...${{title, description}}>
```

no need to repeat ourselves, i love it

this trick has been used in jsx-like templating languages for many years -- sometimes beauty can be found in the little things :)

**Comment by justinfagnani** [comment]
I'd rather not split this conversation over multiple issues. Also, we need to stick to the valid HTML attribute syntax of `name=value` unless we want a much more invasive scanning phase for template preparation. The problem with that is it would lock us into that custom parsing, as opposed to possibly being about to seamlessly use template instantion's syntax if and when that arrives.
