### ISSUE TITLE
Should directives like unsafeHTML parse HTML in the context of the NodePart?

### ISSUE THREAD

**Issue by rictic** [Polymer/lit-html#936]
As an example:

```javascript
html`
  <table>
    ${unsafeHTML('<tr></tr>')}
  </table>
`;
```

Should this render as `<table><tbody><tr></tr></tbody></table>` or as `<table><tr></tr></table>`?

Currently unsafeHTML does an innerHTML on an empty `<template>` tag, and so we'll render the second output. It might be more correct for us to look up the parent element, create an instance in the `<template>` tag, and innerHTML into _that_ in order to better emulate the context into which the content will be written.

**Comment by rictic** [comment]
I'm leaning towards no here, because it adds implementation complexity, and I don't know of any cases where preserving the context is valuable really.

**Comment by rictic** [comment]
Another example, where parse context matters from Mike Samuel:

> There are situations where it's more significant.  Foreign content comes to mind.
>
> In SVG, where the innerHTML uses CDATA sections like
>
```html
<svg>
  <style><![[CDATA[
    .foo:before { content: "&lt;" }
  ]]></style>
</svg>
```

**Comment by justinfagnani** [comment]
Someone could write a similar directive that takes some context, and removes the nodes from that to insert into a part. I lean towards no here too, until we get a user-report on it.
