### ISSUE TITLE
Conditional switching between tags in lithtml

### ISSUE THREAD

**Issue by mukuljp** [Polymer/lit-html#942]
I want to conditionaly switch between tags .
${true?html`<p>`:html`div`} inner content  ${true?html`</p>`:html`</div>`

i tried the above code but its not working.

**Comment by motss** [comment]
Does your code look something like this?

```ts
...
  render() {
    const content = someCondition ?
      html`<div>Hello, World!</div>` :
      html`<p>Hello, World!</p>`;
    return html`${content}`;
  }
...
```

**Comment by mukuljp** [comment]
yes, that solved it. Thank you
