### ISSUE TITLE
Update api.md for changes to `render`

### ISSUE THREAD

**Issue by bicknellr** [Polymer/lit-html#953]
#904 / #910 allow `render` to accept any type, not just a `TemplateResult` - api.md should reflect these changes.

**Comment by arthurevans** [comment]
@justinfagnani do we want to keep maintaining this markdown file? We have more comprehensive  generated API docs as part of the web site:

https://lit-html.polymer-project.org/api/modules/lit_html.html#render

We could keep the file in place, just replace the text with a link to the generated docs, maybe?

**Comment by justinfagnani** [comment]
No, let's remove this file now.
