### ISSUE TITLE
Cannot control the textarea?

### ISSUE THREAD

**Issue by lake2** [Polymer/lit-html#960]
# Description
Cannot implements two-way bind like react.

# Steps to Reproduce
1、click the set botton
2、change the text in the textarea
3、click the set button
4、value in textarea not reset

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-yjqqdb?file=src/index.js

## Browsers Affected

- [ 1] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by blikblum** [comment]
Try to bind to .value: https://stackblitz.com/edit/lit-html-2vcmot?file=src/index.js

**Comment by lake2** [comment]
It seems that it will temporarily be blank  when I click the set button, is there a way to fix it ?

**Comment by Westbrook** [comment]
There’s a small typeo in the code. Note the `e.target.value` in the correct version:
```
<textarea @change=${(e) => onChange(e.target.value)} .value=${value || null}></textarea>
```
instead of 
```
<textarea @change=${(e) => onChange(e.value)} .value=${value || null}></textarea>
```
Will make sure that on blur you aren’t accidentally setting the value to `undefined`.

**Comment by lake2** [comment]
thanks. It helps me a lot.
