### ISSUE TITLE
events based on option

### ISSUE THREAD

**Issue by vegarringdal** [Polymer/lit-html#962]
How can I make a event based on a option ?

```html
<input @${option.eventype}=${update}>
```
Tried to look in the docs and issues but did not see anything, maybe Im just blind ? 😂

**Comment by vegarringdal** [comment]
Tried to use directive for this.
Anyone that can tell me if Im doing something I should not do ?

```ts
const eventHandler = ()=>{console.log('triggered')}
html`<div @custom=${ListenForEvent('mouseover', eventHandler)}>
              some text
        </div>`
```

```ts
const weakmap = new WeakMap();
const ListenForEvent = directive((event, call) => (part) => {

    const EventHandler = class {
        private part: any;
        private event: string;
        private caller: Function;
        private handlerBinded: EventListenerOrEventListenerObject;

        constructor(part, event, call) {
            if (!(part instanceof EventPart) || part.eventName !== 'custom') {
                throw new Error('myListDirective can only be used on "@custom" eventName');
            } else {
                this.part = part;
                this.event = event;
                this.caller = call;
                this.handlerBinded = this.handler.bind(this);
                part.element.addEventListener(event, this.handlerBinded)
            }
        }

        handler(e) {
            this.caller(e);
        }

        update(event, call) {
            this.part = part;
            this.caller = call;
            if (this.event !== event) {
                this.part.element.removeEventLister(this.event, this.handlerBinded);
                this.event = event;
                this.part.element.addEventListener(event, this.handlerBinded);
            }
        }
    }

    let handler = weakmap.get(part);
    if (handler === undefined) {
        let eventHandler = new EventHandler(part, event, call);
        weakmap.set(part, eventHandler);
    } else {
        handler.update(event, call)
    }
});
```

**Comment by PaulHMason** [comment]
I'm pretty sure what you're trying to do isn't possible with lit-html. It can only bind to text content and attribute values - you can't dynamically create tag or attribute names in binding expressions. You can achieve the same result by returning different TemplateResults based on your `option.eventtype` from a function.

**Comment by vegarringdal** [comment]
@PaulHMason 
Hi
Atm Im using directive Im using posted in 16 hours ago in mye "free-grid" project, [simple demo](https://vegarringdal.github.io/test/) here.

Atm it looks like its working very nicely, will make a few changes to it and add a boolean argument option, so it only adds event if that is true or not.
Returning different template results based on if/else etc gets messy very quickly if you have many options.

Btw, do you have issues with html template literals in vscode ? Atm Im really strugling with code formating not working at all/failing quickly in very simple template literals

**Comment by jridgewell** [comment]
Try something like https://jsbin.com/xucugof/3/edit?html,output. You can check out the `PartEvent` class in this repo for ideas on how to expand the directive.

**Comment by vegarringdal** [comment]
@jridgewell 
Thanks for responding.
Unsure what the link was for ?
In post 2 I did a directive on how I could do it, was that wrong ? Any bad parts. ?
Just been using lit.html so any good suggestions is welcome :-)
