### ISSUE TITLE
classMap doesnt support mutation

### ISSUE THREAD

**Issue by Maiquu** [Polymer/lit-html#972]
# Description
classMap doesnt update class attributes when same object reference is used to render after first time.
# Steps to Reproduce

```js
const classes = { disabled : false, checked: true };
const template = () => html`<div class=${classMap(classes)}></div>`;

render(template(),document.body);
//outputHTML = <div class="checked"></div>

classes.disabled = true;

render(template(),document.body);
//outputHTML = <div class="checked"></div>

```
## Expected Output
```<div class="checked disabled"></div>```

**Comment by azakus** [comment]
@Maiquu just hit this myself in nearly the same way, so I'm going to revive this issue :)

**Comment by azakus** [comment]
A workaround for this is to clone the object before each render:

```js
const template = () => html`<div class=${classMap({...classes})}></div>`;
```

**Comment by justinfagnani** [comment]
Given that lit-html renders deep changes to objects in other contexts already, I consider this a bug.

**Comment by jridgewell** [comment]
This applies to `styleMap` and `classMap`.

**Comment by ruphin** [comment]
I will work on a PR that fixes this
