### ISSUE TITLE
render behaviour varies with window focus

### ISSUE THREAD

**Issue by moonlitknight** [Polymer/lit-html#973]
# Brief Description
lit-html appears to behave differently with and without the Chrome devconsole open and in the foreground/background. 
See https://ibb.co/4M75sPQ for an animated gif of the problem.

## Long Description
My app has a hide/reveal icon bar triggered by a scrollEvent. With the devconsole loaded in the foreground window, the icon bar is correctly hidden/revealed. By bringing the app window to the foreground, the hide/reveal no longer works, even though in the JS console, I can see the same events firing, the same Redux state update and the same render() method being called. What I do see differently, is that when the effect is working, I see an exception being thrown in lit-html. When the effect is not working, I see no exception.

lit-element is at v2.1.0, lit-element 1.0.0

![devconsole](https://user-images.githubusercontent.com/24694139/62390274-c8609380-b559-11e9-8667-7ab2954a206b.gif)

**Comment by moonlitknight** [comment]
I've updated to l-e 2.2.1, l-h 1.1.1 and the problem seems to have been resolved.

**Comment by moonlitknight** [comment]
On further testing, it seems that it isn't devconsole that is the influencing factor, it is the fact that my app is in a background window. 

So, to restate the issue, if my app is running in a foreground window, the effect does not display. If I overlay any other window, thus removing focus from my app window, the effect works. Nothing in my app attempts to detect foreground/background windows, and to repeat, the scrollEvent through to the lit-element render, is identical for both the good and bad test case.

**Comment by justinfagnani** [comment]
@moonlitknight what's the exception? Can you post a minimal reproduction to Stackblitz?

**Comment by justinfagnani** [comment]
We would need more information to follow up on this. Please open a new issue if this is still a problem.
