### ISSUE TITLE
Clarify when to use directives versus pure functions

### ISSUE THREAD

**Issue by arthurevans** [Polymer/lit-html#975]
The distinction can be confusing for users. It might be nice to add a paragraph or small, freestanding section on when to use a directive versus a function. Related discussion here:

https://polymer.slack.com/archives/C03PF4L4L/p1565116175349600?thread_ts=1565046667.297000&cid=C03PF4L4L

**Comment by justinfagnani** [comment]
I think the upcoming directives docs cover this pretty well.
