### ISSUE TITLE
Non primitive properties always being set, even when not updated

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/lit-html#982]
# Description
Setters for any non-primitive properties are called any time any other property on an element is updated.

# Steps to Reproduce
Click the Update Test 3 button while viewing the console:

## Live Reproduction Link
https://stackblitz.com/edit/pe7vkr-qhvm3l?file=my-element.js

(thanks to @Westbrook for the example)

## Expected Results
I would expect that the child element wouldn't have the setters called for properties that had not changed. In a situation where updates are immutable (e.g. using Redux), the references will be unchanged and calling the setters may result in unnecessary work.

## Actual Results
Updating the simple string property (third option) causes other setters to be called (see console):
```
test1: {test: 1}
test2: {test: 2}
test3: world
```

## Browsers Affected
Only tested in Chrome
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by CaptainCodeman** [comment]
If anyone comes across this, it is the expected behavior - the trick is to use the `guard` directive to avoid the properties updating:

https://stackblitz.com/edit/pe7vkr-sztrr9?file=my-element.js

**Comment by danielvanmil** [comment]
I also ran into the issue and are struggling with how to use the mechanism as it looks a but inconsistent between atomic and complex values. Now it looks like we should use the _live_ or the _guard_ directive depending on the use case/desired behavior, but when you want consistent behavior between your components in for example a form view you should at least use one of them on all field components? (depending on whether it involves complex or atomic properties)

Is it possible to provide a bit more documentation/examples how or when to use the directives with a combination of atomic/complex properties in for example a form or other use cases?
