### ISSUE TITLE
Rollup with Babel - Doesn't transpile into ES5 

### ISSUE THREAD

**Issue by zaynzafar** [Polymer/lit-html#983]
I've been trying to get my application to transpile lit-html to ES5 but have had no luck with this. There doesn't seem to be any documentation to resolve this issue either despite having seen a few support tickets open regarding this issue.

I am using the following plugins with roll up:

- rollup-plugin-node-resolve
- rollup-plugin-babel
- rollup-plugin-commonjs 

The commonjs plugin (which converts commonjs modules into es6 modules) already ignores ES6 modules according to their documentation so this should be ruled out.

This is a relevant snippet of my rollup.config.js:

``` sourcemap: 'inline',
    format: 'iife',
    plugins: [
      babel({
        exclude: './node_modules/**'
      }),
      nodeResolve({browser: true }),
      commonJS({
        include: './node_modules/**'
      }),
    ]
```

This is my .babelrc file:

```
{
    "presets": [
        ["@babel/preset-env"]
    ]
}
```

For some reason, the compiled file still contains lit-html ES6 code in it and this shouldn't be the case. Everything else is converted into ES5 code and this is breaking support for internet explorer 11 for which I must include support for. 

Does anyone have any ideas of how to resolve this? Maybe webpack users have had a similar problem too?

**Comment by LarsDenBakker** [comment]
It's literally there in the config you're showing, you're excluding node modules from babel compilation.

**Comment by zaynzafar** [comment]
@LarsDenBakker Sorry, i should've included the fact that even if I remove this line from the babel config, it still doesn't compile: 

`exclude: './node_modules/**'`

**Comment by yankooknay** [comment]
@zaynzafar did it work for you with the @LarsDenBakker suggestion?
