### ISSUE TITLE
Why classMap blocked multiple parts?

### ISSUE THREAD

**Issue by TroyTae** [Polymer/lit-html#984]
# Description
I want to use like this:
```
<button class="${className1} ${className2}"></button>
```
But classMap blocked multiple parts (https://github.com/Polymer/lit-html/blob/master/src/directives/class-map.ts#L41-L43).
Can you tell me what is the reason?

# Steps to Reproduce

1. Write this code

```ts
import {html, render} from 'lit-html';

const className1 = 'class1';
const className2 = 'class2';

render(html`<button class="${className1} ${className2}"></button>`, document.body);
```

**Comment by csvn** [comment]
`classMap` is actually a directive, you have to use it like this:

```js
import {classMap} from 'lit-html/directives/class-map.js';

let classes = { highlight: true, enabled: true, hidden: false };

html`<div class=${classMap(classes)}>Classy text</div>`;
// renders as <div class="highlight enabled">Classy text</div>
```

See: https://lit-html.polymer-project.org/guide/template-reference#classmap

**Comment by TroyTae** [comment]
@csvn 
Thank you for reply :)
I also use classMap like this:
```
const staticClassName = 'root-element';
const classes = { highlight: isHighlight, enabled: isEnabled, hidden: isHidden};

html`<div class="${staticClassName} ${classMap(classes)}">text</div>`;
```
My point I want to use classMap, only dynamic className.

**Comment by csvn** [comment]
@TroyTae Aha, I see. The only way I see is by adding the dynamic classname to the object:

```js
const staticClassName = 'root-element';
const classes = {
  [staticClassName]: true,
  highlight: isHighlight,
  enabled: isEnabled,
  hidden: isHidden
};
html`<div class="${classMap(classes)}">text</div>`;
```

Other than that approach, I don't know 🙂

**Comment by TroyTae** [comment]
@csvn 
Yes you're right 😢 
So I write like this: https://github.com/material-components/material-components-web-components/pull/385/commits/7dede390da148fbe7be18dceaa7c1c9bfc03cf44
And I create this because I want to know why polymer team design like this.
Or they have some plan to improve this code.

**Comment by Westbrook** [comment]
The `classMap` directive keys into the `classList` API on a DOM element: https://github.com/Polymer/lit-html/blob/master/src/directives/class-map.ts#L54 to enable fast add/remove of class names on your element. Standard attribute binding sets attributes directly https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L96. When mixed, the standard binding overwrites the `classMap` binding. Rather than vend complicated logic and increase the size of the library, `lit-html` simply disallows the use of both in a single `class=${}` and suggests the `[staticClassName]: true,` syntax above, which gives you the same functionality at a lower cost.

**Comment by TroyTae** [comment]
@Westbrook 
Thank you for your reply :)
But I want to know design intent.

@justinfagnani 
Can you tell me about this??

**Comment by justinfagnani** [comment]
The problem with allowing multiple expressions with `classMap` is exactly as @Westbrook says: that `classMap` manages the class list directly while attribute bindings use `setAttribute()`. `classMap` _could_ try to take over the whole attribute including receiving the values of expressions, splitting them, and adding them to the set of classes under management. That would be more complicated for sure. Instead you can do this yourself:

```ts
const classes = {
  one: isOne,
  two: isTwo,
};
otherClasses.forEach((c) => classes[c] = true);
return html`<div class=${classMap(classes)}></div>`;
```

**Comment by TroyTae** [comment]
@Westbrook @justinfagnani 
Oh I misread @Westbrook 's comment.
Thank you both 😄

**Comment by TroyTae** [comment]
And... I don't know polymer team has plan about this, but I'll try to think how can we allow several syntax and maintain size/performance!
