### ISSUE TITLE
unexpected use of `this` in async-replace.js es module

### ISSUE THREAD

**Issue by askbeka** [Polymer/lit-html#986]
# Description
js output of [directives/async-replace](https://unpkg.com/lit-html@1.1.2/directives/async-replace.js) contains following:

```js
var __asyncValues = (this && this.__asyncValues) || function (o) {
    if (!Symbol.asyncIterator) throw new TypeError("Symbol.asyncIterator is not defined.");
    var m = o[Symbol.asyncIterator], i;
    return m ? m.call(o) : (o = typeof __values === "function" ? __values(o) : o[Symbol.iterator](), i = {}, verb("next"), verb("throw"), verb("return"), i[Symbol.asyncIterator] = function () { return this; }, i);
    function verb(n) { i[n] = o[n] && function (v) { return new Promise(function (resolve, reject) { v = o[n](v), settle(resolve, reject, v.done, v.value); }); }; }
    function settle(resolve, reject, d, v) { Promise.resolve(v).then(function(v) { resolve({ value: v, done: d }); }, reject); }
};
import { directive, NodePart } from '../lit-html.js';
```
Which results in warning in [Rollup](https://rollupjs.org/guide/en/#error-this-is-undefined):
```bash
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
../../../node_modules/lit-html/directives/async-append.js
14:  * http://polymer.github.io/PATENTS.txt
15:  */
16: var __asyncValues = this && this.__asyncValues || function (o) {
                        ^
17:   if (!Symbol.asyncIterator) throw new TypeError("Symbol.asyncIterator is not defined.");
18:   var m = o[Symbol.asyncIterator],
```

It is not that bad, but one of the workarounds, that people will find to get rid of the warning, is to provide a [context like window](https://rollupjs.org/guide/en/#danger-zone). Which is **bad**

# Steps to Reproduce

run `rollup`

## Expected Results
No warnings

## Actual Results
Warning replacing this to undefined;

## Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 11
- [ x] Safari 10
- [ x] IE 11

**Comment by jridgewell** [comment]
This is from TypeScript's output, not actual code we've written in lit-html.

Rollup performing badly here, and shouldn't be throwing an error (warning is ok, but an error is just wrong). Try setting `context` or `moduleContext` like https://rollupjs.org/guide/en/#error-this-is-undefined says.

**Comment by askbeka** [comment]
@jridgewell Thanks,
I am aware that it is a build output of typescript.
It is not an error but a warning in rollup!
I like rollup showing this message, because I was able to locate this sort of use cases,

But I imagine many developers will not and just try to switch it off, which should not be an advise!

Maybe uglifying for unreachable code can be performed to remove this code, since `this` is always will be `undefined`

**Comment by jridgewell** [comment]
We could complain to TS, since it shouldn't be using a top-level this if it's compiling to a module.

**Comment by csvn** [comment]
If there is focus on creating small bundles, I would instead recommend to build `lit-html` from source with `"importHelpers": true`. The issue above is not an problem if all helpers are imported from the `tslib` package. Multiple instances of helpers (e.g. `__asyncValues`= for TS _and_ babel for dependencies and source code can inflate bundle size a lot.

(We also compile our TS-code with `"target": "esnext"`, and use babel to transpile our code to correct targets. Babel can selectively transform only the required features, so can do more granular transpiling than TS's `es5`/`es2015` targets.)

**Comment by askbeka** [comment]
@jridgewell I think it should be fixed on TS side. I can go complain:)

@csvn we are building lit-html and lit-element libraries centrally and consuming from shared location like CDN, so that is not much of an overhead. But thanks for the hint.

**Comment by abdonrd** [comment]
Related with this: https://github.com/open-wc/open-wc/issues/640#issuecomment-515092531

**Comment by justinfagnani** [comment]
The top-level `this` reference doesn't cause an error when replaced with `undefined`, so aside from the warning, there's nothing really wrong here. As noted this is a TypeScript issue. We can remove the helper when we update browser support, or import the helpers. It's currently nice to not have any dependencies though.
