### ISSUE TITLE
input minlength and maxlength not validating correctly

### ISSUE THREAD

**Issue by Cuttsy27** [Polymer/lit-html#988]
When using an input's checkValidity() method with a  `minlength` and `maxlength` set, the input is not invalid and does not have a validationMessage. This only occurs (minimal testing) when binding to `.value`. `required` and `pattern` validate as expected. Custom constraints (via setCustomValidity) validate as expected. I've not tested any other constraints.

Tested in Chrome and Firefox.

To recreate:

1. Create an input element and set minlength and maxlength attributes. 
2. Bind to `.value` ie. `.value=${this.firstName}`.

Notice the input will not validate/become invalid. Binding to `value` instead, the input validates as expected. The input validates as expected when no value is bound, also.

**Comment by jridgewell** [comment]
Please create a stackblitz demonstrating the issue. You can fork https://stackblitz.com/edit/lit-html to get started.

**Comment by Cuttsy27** [comment]
I was unable to recreate the issue in Stackblitz. I'll do some further testing and ensure it isn't my environment only.

**Comment by justinfagnani** [comment]
Feel free to reopen if this is still an issue and we can make a reproduction.
