### ISSUE TITLE
Does it fit the use case of full re-rendering?

### ISSUE THREAD

**Issue by dakom** [Polymer/lit-html#993]
I'm thinking of using lit-html in a pipeline that resembles something more like a game loop than a stateful component tree.

In other words - I have a bunch of data that gets updated via some outside mechanism, and then I re-render the entire dom whenever any of that data changes (or even if it doesn't, every tick). The dom renderer should be blissfully unaware of any state, it should just render the entire page the way a game might re-render the entire screen each tick.

Is lit-html the library I'm looking for, to do that efficiently?

**Comment by ruphin** [comment]
Yes

**Comment by dakom** [comment]
thanks will close the issue now :)
