### ISSUE TITLE
refs and context?

### ISSUE THREAD

**Issue by dakom** [Polymer/lit-html#995]
what is the recommended approach for working with canvas/context?

Example - let's say there's a page that has menus and other UI elements which render in a regular tree.

But then somewhere in there, is a canvas, that should be updated when props change.

By "updated" I mean, needs to getContext, and then issue a bunch of imperative calls on it (fill, drawImage, etc.)

I'm sorta thinking something a bit heretical - to consider that this is a side effect and maybe store an id and good ol' document.getElementById() then have an outside function do the drawing... but wondering if there's a way that's more in line with the declarative lit-html API

**Comment by justinfagnani** [comment]
We don't have refs in lit-html. The easiest thing to do is just querySelector against the container after the render.

**Comment by dakom** [comment]
Good :) thanks!

**Comment by majo44** [comment]
Hi 
What do you think about such implementation: 
Do you think is some anti-pattern ? Or there can be some problem ?

```javascript

/**
 * @param {Node} element
 * @returns {boolean}
 */
export default function isDetached(element) {
    if (!element) return true;
    if (!(element instanceof HTMLElement) || element.nodeType === Node.DOCUMENT_NODE) {
        return false;
    }
    return isDetached(element.parentNode);
}

const cache = new WeakMap();

export const ref = directive(
    (refHandle) =>
        /**
         * @param {import('lit-html').PropertyPart} part
         */
        (part) => {
            const element = part.committer.element;
            if (!cache.has(element)) {
                const observer = new MutationObserver(() => {
                    if (isDetached(element)) {
                        refHandle(null);
                        observer.disconnect();
                        cache.delete(element);
                    }
                });
                observer.observe(element.ownerDocument, {
                    childList: true,
                    subtree: true,
                });
                cache.set(element, observer);
                refHandle(element);
            }
        },
);
```
and usage:
```html
<input type="text" ref=${ref(e => console.log('REF', e))}">
```
or even
```html
<input type="text" .=${ref(e => console.log('REF', e))}">
```
