### ISSUE TITLE
classMap can not be used on a slot tag

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-html#999]
```js
const computedClass = CSSMap({foo: true})

render(){
  return html`<slot class=${computedClass}></slot>`
}
```

and then I got: 

> The `classMap` directive must be used in the `class` attribute and must be the only part in the attribute.

**Comment by justinfagnani** [comment]
Do you have a reproduction? I can't think of why this wouldn't work with native shadow DOM, but I can see that it definitely wouldn't work with Shady DOM.

**Comment by justinfagnani** [comment]
Closing since this is so old. Please one a new issue if it's still a problem and we have a reproduction.
